import type { BarterItem } from "./barter-types";

/**
 * Barter & Trade Value Estimator — Item Database
 *
 * Values derived from historical collapse economies:
 * - Venezuela 2017-2020 (hyperinflation barter markets)
 * - Argentina 2001-2002 (trueque clubs, barter networks)
 * - Yugoslavia 1992-1995 (Selco Begovic survivor accounts)
 * - Post-Katrina 2005 (Gulf Coast trading)
 * - Lebanon 2020-2022 (currency collapse)
 * - Prison economies (documented trade ratios)
 *
 * Scale: 1 = nearly worthless in trade, 10 = highest possible trade value
 */

// ─── GOODS ──────────────────────────────────────────────────────────────────────

export const GOODS: BarterItem[] = [
  // ── Water & Purification ──────────────────────────────────────────────────
  {
    id: "g-water-jug-5gal",
    name: "Water (5-gallon jug)",
    category: "Water & Purification",
    type: "good",
    description: "Clean drinking water in sealed container",
    valueDay7: 3,
    valueDay30: 8,
    valueDay90: 9,
    consumable: true,
    unit: "jug",
    tradesFor: "1 jug = 2-3 days of food for one person",
    notes: "In Venezuela, bottled water sold for more than gasoline. Katrina survivors paid $20+ per gallon.",
    retailPrice: 8,
  },
  {
    id: "g-water-filter-gravity",
    name: "Gravity Water Filter",
    category: "Water & Purification",
    type: "good",
    description: "Gravity-fed water filtration system (ProOne, Berkey-style)",
    valueDay7: 3,
    valueDay30: 9,
    valueDay90: 10,
    consumable: false,
    unit: "each",
    tradesFor: "1 filter = weeks of food or a firearm",
    notes: "A working filter is a renewable water source. In prolonged collapse, this becomes one of the most valuable items you can own.",
    retailPrice: 250,
    asin: "B0BXMQ1KGY",
  },
  {
    id: "g-water-filter-squeeze",
    name: "Portable Water Filter (Sawyer/LifeStraw)",
    category: "Water & Purification",
    type: "good",
    description: "Squeeze or straw-style personal water filter",
    valueDay7: 2,
    valueDay30: 7,
    valueDay90: 8,
    consumable: false,
    unit: "each",
    tradesFor: "1 filter = 3-5 days of food",
    notes: "Sawyer Squeeze filters 100,000 gallons. Lightweight, backpackable, nearly indestructible.",
    retailPrice: 35,
    asin: "B00FA2RLX2",
  },
  {
    id: "g-purification-tabs",
    name: "Water Purification Tablets",
    category: "Water & Purification",
    type: "good",
    description: "Iodine or chlorine dioxide tablets (50-pack)",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 7,
    consumable: true,
    unit: "pack",
    tradesFor: "1 pack = 2 days of food",
    notes: "Lightweight, long shelf life. Aquamira tablets or Potable Aqua. Easy to trade in small quantities.",
    retailPrice: 12,
    asin: "B0078SA5SE",
  },
  {
    id: "g-bleach-unscented",
    name: "Unscented Bleach (gallon)",
    category: "Water & Purification",
    type: "good",
    description: "Regular unscented household bleach for water purification and sanitation",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 6,
    consumable: true,
    unit: "gallon",
    tradesFor: "1 gallon = 1-2 days of food",
    notes: "8 drops per gallon of water. Also critical for sanitation. Cheap to stockpile now.",
    retailPrice: 4,
  },
  {
    id: "g-water-bob",
    name: "WaterBOB Bathtub Bladder",
    category: "Water & Purification",
    type: "good",
    description: "65-gallon bathtub water storage bladder",
    valueDay7: 4,
    valueDay30: 3,
    valueDay90: 2,
    consumable: false,
    unit: "each",
    tradesFor: "Pre-event: high value. Post-event: moderate (needs water source to fill)",
    notes: "Only valuable if filled BEFORE the water stops. After that it is a plastic bag. Fill it the moment you hear bad news.",
    retailPrice: 35,
    asin: "B001AXLUX2",
  },

  // ── Food & Nutrition ──────────────────────────────────────────────────────
  {
    id: "g-canned-goods",
    name: "Canned Goods (assorted)",
    category: "Food & Nutrition",
    type: "good",
    description: "Canned vegetables, fruits, soups, meats",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 7,
    consumable: true,
    unit: "can",
    tradesFor: "3 cans = 1 day of labor",
    notes: "In Argentina 2001, canned food became the de facto currency at trueque fairs.",
    retailPrice: 2,
  },
  {
    id: "g-rice-bulk",
    name: "Rice (25 lb bag)",
    category: "Food & Nutrition",
    type: "good",
    description: "White rice in sealed bag or bucket",
    valueDay7: 2,
    valueDay30: 7,
    valueDay90: 8,
    consumable: true,
    unit: "bag",
    tradesFor: "1 bag = 1 week of labor or 5 gallons of fuel",
    notes: "20+ year shelf life if stored properly. Calorie-dense. Universal acceptance in every collapse economy.",
    retailPrice: 15,
  },
  {
    id: "g-beans-dried",
    name: "Dried Beans (25 lb bag)",
    category: "Food & Nutrition",
    type: "good",
    description: "Pinto, black, or mixed dried beans",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 8,
    consumable: true,
    unit: "bag",
    tradesFor: "1 bag = 1 week of labor",
    notes: "Rice and beans together form a complete protein. Cheap to stockpile, massive trade value later.",
    retailPrice: 18,
  },
  {
    id: "g-freeze-dried",
    name: "Freeze-Dried Meals",
    category: "Food & Nutrition",
    type: "good",
    description: "Mountain House or similar, just-add-water meals",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 6,
    consumable: true,
    unit: "pouch",
    tradesFor: "2 pouches = 1 day of labor",
    notes: "25-year shelf life. Require water and heat. Lighter than canned but less familiar to most people.",
    retailPrice: 10,
  },
  {
    id: "g-protein-bars",
    name: "Protein/Energy Bars",
    category: "Food & Nutrition",
    type: "good",
    description: "Clif, Kind, or similar calorie-dense bars",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 5,
    consumable: true,
    unit: "bar",
    tradesFor: "3-5 bars = 1 small tool or service",
    notes: "Short shelf life compared to other foods. Good for quick trades. Kids love them.",
    retailPrice: 1.5,
  },
  {
    id: "g-salt",
    name: "Salt (iodized, 26 oz)",
    category: "Food & Nutrition",
    type: "good",
    description: "Table salt or sea salt",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 8,
    consumable: true,
    unit: "container",
    tradesFor: "1 container = 2-3 days of food",
    notes: "Historically one of the most traded commodities in human history. Essential for food preservation, electrolytes, and flavor. Yugoslavia survivors noted salt was worth more than sugar.",
    retailPrice: 1,
  },
  {
    id: "g-sugar",
    name: "Sugar (5 lb bag)",
    category: "Food & Nutrition",
    type: "good",
    description: "Granulated white sugar",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 6,
    consumable: true,
    unit: "bag",
    tradesFor: "1 bag = 1-2 days of food",
    notes: "Never spoils if kept dry. Good for morale, preserving fruit, making alcohol.",
    retailPrice: 4,
  },
  {
    id: "g-cooking-oil",
    name: "Cooking Oil (48 oz)",
    category: "Food & Nutrition",
    type: "good",
    description: "Vegetable, olive, or coconut oil",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 7,
    consumable: true,
    unit: "bottle",
    tradesFor: "1 bottle = 2-3 days of food",
    notes: "Calorie-dense (120 cal/tbsp), essential for cooking, lamp fuel in a pinch. In Venezuela, cooking oil was one of the first things to disappear.",
    retailPrice: 6,
  },
  {
    id: "g-coffee",
    name: "Coffee (ground, 12 oz)",
    category: "Food & Nutrition",
    type: "good",
    description: "Ground coffee or instant coffee",
    valueDay7: 2,
    valueDay30: 7,
    valueDay90: 9,
    consumable: true,
    unit: "bag",
    tradesFor: "1 bag = 1-2 days of labor",
    notes: "Morale item. In every documented collapse, coffee and tobacco become premium trade goods. Yugoslavia survivors rated coffee as a top-5 barter item.",
    retailPrice: 8,
  },
  {
    id: "g-alcohol-liquor",
    name: "Liquor (750ml bottle)",
    category: "Food & Nutrition",
    type: "good",
    description: "Vodka, whiskey, or other hard liquor",
    valueDay7: 3,
    valueDay30: 8,
    valueDay90: 9,
    consumable: true,
    unit: "bottle",
    tradesFor: "1 bottle = 3-5 days of food or medical supplies",
    notes: "Triple use: morale, antiseptic, trade. In Yugoslavia, a bottle of Jack Daniels could buy a week of food. Vodka works as wound cleaner. Never expires.",
    retailPrice: 20,
  },
  {
    id: "g-alcohol-mini",
    name: "Mini Liquor Bottles (50ml)",
    category: "Food & Nutrition",
    type: "good",
    description: "Airline-style mini bottles, various spirits",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 5,
    consumable: true,
    unit: "bottle",
    tradesFor: "2-3 minis = 1 meal or small service",
    notes: "Perfect barter denomination. You do not trade a full bottle when a mini will do. Stock up during sales.",
    retailPrice: 2,
  },
  {
    id: "g-honey",
    name: "Honey (2 lb jar)",
    category: "Food & Nutrition",
    type: "good",
    description: "Raw or pasteurized honey",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 7,
    consumable: true,
    unit: "jar",
    tradesFor: "1 jar = 2-3 days of food",
    notes: "Never spoils. Antibacterial properties for wound care. Calorie-dense. Natural sweetener when sugar runs out.",
    retailPrice: 12,
  },
  {
    id: "g-peanut-butter",
    name: "Peanut Butter (16 oz)",
    category: "Food & Nutrition",
    type: "good",
    description: "Peanut butter, any brand",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 6,
    consumable: true,
    unit: "jar",
    tradesFor: "1 jar = 1-2 days of food",
    notes: "Calorie-dense, protein-rich, no cooking needed. Kids eat it without complaint. 2-year shelf life.",
    retailPrice: 4,
  },
  {
    id: "g-spices",
    name: "Spices & Seasoning (assorted)",
    category: "Food & Nutrition",
    type: "good",
    description: "Garlic powder, chili flakes, cumin, pepper, bouillon cubes",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 5,
    consumable: true,
    unit: "set",
    tradesFor: "Seasoning set = 1-2 meals",
    notes: "Underrated. When people eat rice and beans for 30 days straight, flavor becomes a morale lifesaver.",
    retailPrice: 10,
  },
  {
    id: "g-powdered-milk",
    name: "Powdered Milk (64 oz)",
    category: "Food & Nutrition",
    type: "good",
    description: "Nonfat dry milk powder",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 6,
    consumable: true,
    unit: "container",
    tradesFor: "1 container = 2-3 days of food",
    notes: "Essential for families with children. 20+ year shelf life sealed. Calcium source when dairy is gone.",
    retailPrice: 14,
  },
  {
    id: "g-tobacco",
    name: "Tobacco / Cigarettes",
    category: "Food & Nutrition",
    type: "good",
    description: "Carton of cigarettes or rolling tobacco",
    valueDay7: 2,
    valueDay30: 8,
    valueDay90: 9,
    consumable: true,
    unit: "carton",
    tradesFor: "1 carton = 3-5 days of food or skilled labor",
    notes: "Prison currency. Yugoslavia currency. Venezuela currency. Every collapse economy proves tobacco is gold. You do not need to smoke to stockpile it.",
    retailPrice: 60,
  },

  // ── Medical & Hygiene ─────────────────────────────────────────────────────
  {
    id: "g-antibiotics",
    name: "Antibiotics (fish/bird, amoxicillin 500mg)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Broad-spectrum antibiotics (veterinary-grade, same compound as human)",
    valueDay7: 3,
    valueDay30: 9,
    valueDay90: 10,
    consumable: true,
    unit: "bottle",
    tradesFor: "1 bottle = a firearm or weeks of food",
    notes: "The single most valuable consumable in a collapse. A minor cut becomes life-threatening without antibiotics. In Venezuela, a course of antibiotics cost a month's salary.",
    retailPrice: 30,
    asin: "B0C1HPJKWL",
  },
  {
    id: "g-painkillers-otc",
    name: "OTC Painkillers (ibuprofen, acetaminophen)",
    category: "Medical & Hygiene",
    type: "good",
    description: "200-count bottles of ibuprofen or acetaminophen",
    valueDay7: 1,
    valueDay30: 6,
    valueDay90: 8,
    consumable: true,
    unit: "bottle",
    tradesFor: "1 bottle = 2-3 days of food",
    notes: "Dental pain, headaches, fever reduction, inflammation. When pharmacies are closed, a bottle of Advil is priceless.",
    retailPrice: 8,
    asin: "B005GCOJPQ",
  },
  {
    id: "g-first-aid-kit",
    name: "First Aid Kit (comprehensive)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Complete kit with bandages, gauze, tape, antiseptic, tourniquet",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 7,
    consumable: true,
    unit: "kit",
    tradesFor: "1 kit = several days of food or fuel",
    notes: "Consumable items run out fast when treating real injuries. Stock multiples.",
    retailPrice: 40,
    asin: "B08DLMP6HK",
  },
  {
    id: "g-suture-kit",
    name: "Suture Kit (surgical)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Sterile suture kit with needles, thread, forceps, scissors",
    valueDay7: 1,
    valueDay30: 7,
    valueDay90: 9,
    consumable: true,
    unit: "kit",
    tradesFor: "1 kit + someone who knows how to use it = extremely high value",
    notes: "Worthless without skill. Combined with wound care training, this is one of the highest-value items you can carry.",
    retailPrice: 15,
    asin: "B08GY581G1",
  },
  {
    id: "g-prescription-meds",
    name: "Prescription Medications (90-day supply)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Blood pressure, insulin, thyroid, heart, psychiatric medications",
    valueDay7: 5,
    valueDay30: 10,
    valueDay90: 10,
    consumable: true,
    unit: "supply",
    tradesFor: "Person-dependent — someone's blood pressure meds are worth everything to them",
    notes: "Not tradeable in the usual sense — but the person who runs out will trade anything they own for a refill. Stock extras if your doctor allows.",
    retailPrice: 50,
  },
  {
    id: "g-soap",
    name: "Bar Soap (multi-pack)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Unscented bar soap, 10-pack",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 6,
    consumable: true,
    unit: "bar",
    tradesFor: "2-3 bars = 1 day of food",
    notes: "Hygiene prevents disease. When sanitation breaks down, soap prevents infections that kill. In Yugoslavia, soap was a top barter item.",
    retailPrice: 8,
  },
  {
    id: "g-toothpaste",
    name: "Toothpaste (6 oz tube)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Fluoride toothpaste",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 5,
    consumable: true,
    unit: "tube",
    tradesFor: "1 tube = 1 meal",
    notes: "Dental infections without treatment can become fatal. Prevention matters.",
    retailPrice: 3,
  },
  {
    id: "g-feminine-products",
    name: "Feminine Hygiene Products (multi-pack)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Tampons, pads, or menstrual cups",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 7,
    consumable: true,
    unit: "pack",
    tradesFor: "1 pack = 1-2 days of food",
    notes: "Chronically overlooked in prepper stockpiles. Half the population needs them monthly. High demand, low supply in collapse.",
    retailPrice: 8,
  },
  {
    id: "g-toilet-paper",
    name: "Toilet Paper (4-pack)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Standard toilet paper rolls",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 5,
    consumable: true,
    unit: "pack",
    tradesFor: "1 pack = 1 meal",
    notes: "Remember 2020? People fought over this. In a real collapse it is a genuine comfort item with steady demand.",
    retailPrice: 4,
  },
  {
    id: "g-bleach-disinfectant",
    name: "Disinfectant Wipes/Spray",
    category: "Medical & Hygiene",
    type: "good",
    description: "Lysol wipes or spray disinfectant",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 5,
    consumable: true,
    unit: "container",
    tradesFor: "1 container = 1 meal",
    notes: "When sanitation systems fail, disinfection becomes critical. Gastro outbreaks kill in grid-down.",
    retailPrice: 5,
  },
  {
    id: "g-hand-sanitizer",
    name: "Hand Sanitizer (8 oz)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Alcohol-based hand sanitizer",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 4,
    consumable: true,
    unit: "bottle",
    tradesFor: "1 bottle = 1 meal",
    notes: "Also works as fire starter and wound cleaner in a pinch.",
    retailPrice: 3,
  },
  {
    id: "g-diapers",
    name: "Diapers (box)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Disposable diapers, various sizes",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 6,
    consumable: true,
    unit: "box",
    tradesFor: "1 box = 2-3 days of food for parents with infants",
    notes: "Parents with babies will trade almost anything. Even if you do not have kids, stock a box for trade.",
    retailPrice: 30,
  },
  {
    id: "g-dental-kit",
    name: "Emergency Dental Kit",
    category: "Medical & Hygiene",
    type: "good",
    description: "Temporary filling material, dental wax, clove oil",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 7,
    consumable: true,
    unit: "kit",
    tradesFor: "Kit + dental knowledge = very high value",
    notes: "Dental emergencies are one of the most common medical issues in prolonged collapse. Clove oil is a natural analgesic.",
    retailPrice: 15,
  },
  {
    id: "g-vitamins-multi",
    name: "Multivitamins (200-count)",
    category: "Medical & Hygiene",
    type: "good",
    description: "Daily multivitamin supplement",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 5,
    consumable: true,
    unit: "bottle",
    tradesFor: "1 bottle = 1-2 days of food",
    notes: "Nutritional deficiencies start showing by day 30 on a limited diet. Vitamin C prevents scurvy. Long shelf life.",
    retailPrice: 10,
  },

  // ── Power & Fuel ──────────────────────────────────────────────────────────
  {
    id: "g-gasoline",
    name: "Gasoline (5 gallons, stabilized)",
    category: "Power & Fuel",
    type: "good",
    description: "Stabilized gasoline in approved container",
    valueDay7: 4,
    valueDay30: 8,
    valueDay90: 7,
    consumable: true,
    unit: "can",
    tradesFor: "5 gal = 1 week of food or major service",
    notes: "Post-Katrina gas was $10+/gallon when you could find it. Stabilize with STA-BIL for 24-month shelf life. Value drops at day 90 because vehicles become less useful.",
    retailPrice: 25,
  },
  {
    id: "g-diesel",
    name: "Diesel Fuel (5 gallons)",
    category: "Power & Fuel",
    type: "good",
    description: "Diesel fuel in approved container",
    valueDay7: 4,
    valueDay30: 8,
    valueDay90: 7,
    consumable: true,
    unit: "can",
    tradesFor: "5 gal = generator runtime or vehicle fuel",
    notes: "Diesel stores longer than gasoline naturally. Generators, trucks, and heavy equipment all run diesel.",
    retailPrice: 25,
  },
  {
    id: "g-propane-1lb",
    name: "Propane Canisters (1 lb, 4-pack)",
    category: "Power & Fuel",
    type: "good",
    description: "Coleman-style 1 lb propane canisters",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 5,
    consumable: true,
    unit: "pack",
    tradesFor: "1 canister = 1-2 meals of cooking fuel",
    notes: "Universal fuel for camp stoves, heaters, lanterns. Unlimited shelf life. Easy to store and trade.",
    retailPrice: 16,
  },
  {
    id: "g-propane-20lb",
    name: "Propane Tank (20 lb)",
    category: "Power & Fuel",
    type: "good",
    description: "Standard BBQ-size propane tank, full",
    valueDay7: 3,
    valueDay30: 7,
    valueDay90: 6,
    consumable: true,
    unit: "tank",
    tradesFor: "1 tank = 1-2 weeks of cooking or several days of heating",
    notes: "20 lb tank provides roughly 20 hours of cooking on a standard grill. Indefinite shelf life.",
    retailPrice: 40,
  },
  {
    id: "g-batteries-aa",
    name: "Batteries AA (24-pack)",
    category: "Power & Fuel",
    type: "good",
    description: "Alkaline AA batteries",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 5,
    consumable: true,
    unit: "pack",
    tradesFor: "4 AA = 1 meal",
    notes: "Flashlights, radios, clocks, kids toys (morale). In Yugoslavia, batteries were top-10 barter items.",
    retailPrice: 12,
  },
  {
    id: "g-batteries-rechargeable",
    name: "Rechargeable Batteries + Charger",
    category: "Power & Fuel",
    type: "good",
    description: "Eneloop or similar NiMH rechargeable batteries with solar-compatible charger",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 7,
    consumable: false,
    unit: "set",
    tradesFor: "Set = several days of food (renewable value)",
    notes: "Paired with solar, this is a renewable battery source. Value increases over time as disposable batteries run out.",
    retailPrice: 30,
  },
  {
    id: "g-solar-panel-portable",
    name: "Portable Solar Panel (100-200W)",
    category: "Power & Fuel",
    type: "good",
    description: "Foldable solar panel for charging devices and power stations",
    valueDay7: 2,
    valueDay30: 7,
    valueDay90: 9,
    consumable: false,
    unit: "each",
    tradesFor: "1 panel = major trade item — weeks of food or firearms",
    notes: "Renewable power source. At day 90 when fuel is gone, solar is king. The person with solar panels can charge devices for the whole neighborhood.",
    retailPrice: 200,
    asin: "B09PDLT12H",
  },
  {
    id: "g-power-station",
    name: "Portable Power Station (1-2kWh)",
    category: "Power & Fuel",
    type: "good",
    description: "EcoFlow, Jackery, or Bluetti portable battery",
    valueDay7: 3,
    valueDay30: 6,
    valueDay90: 8,
    consumable: false,
    unit: "each",
    tradesFor: "Power station + solar = community-level trade asset",
    notes: "Only valuable if you can recharge it (solar). Without solar, it is a paperweight after the battery drains.",
    retailPrice: 800,
  },
  {
    id: "g-generator-portable",
    name: "Portable Generator (3500W)",
    category: "Power & Fuel",
    type: "good",
    description: "Gas or dual-fuel portable generator",
    valueDay7: 5,
    valueDay30: 7,
    valueDay90: 5,
    consumable: false,
    unit: "each",
    tradesFor: "Generator = high-value but declines as fuel runs out",
    notes: "High initial value but fuel-dependent. Gets LOUD — security risk. Value drops sharply when fuel is gone.",
    retailPrice: 600,
  },
  {
    id: "g-candles",
    name: "Candles (emergency, 12-pack)",
    category: "Power & Fuel",
    type: "good",
    description: "Long-burn emergency candles (100+ hours each)",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 5,
    consumable: true,
    unit: "pack",
    tradesFor: "2-3 candles = 1 meal",
    notes: "When the lights are off and it gets dark at 5pm, candles become essential. Also provide small amounts of heat.",
    retailPrice: 15,
  },
  {
    id: "g-lighters",
    name: "BIC Lighters (multi-pack)",
    category: "Power & Fuel",
    type: "good",
    description: "Disposable butane lighters, 10-pack",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 7,
    consumable: true,
    unit: "lighter",
    tradesFor: "1 BIC lighter = 1-2 meals at day 90",
    notes: "THE classic collapse barter item. Yugoslavia survivors said a BIC lighter was worth more than a gold ring. Cheap, small, universally needed. Buy them by the 50-pack.",
    retailPrice: 1,
  },
  {
    id: "g-matches-stormproof",
    name: "Stormproof Matches (box)",
    category: "Power & Fuel",
    type: "good",
    description: "UCO or similar waterproof/stormproof matches",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 5,
    consumable: true,
    unit: "box",
    tradesFor: "1 box = 1 meal",
    notes: "Backup to lighters. Work in wind and rain. Small and easy to trade.",
    retailPrice: 6,
  },
  {
    id: "g-firewood",
    name: "Firewood (cord or partial)",
    category: "Power & Fuel",
    type: "good",
    description: "Seasoned split firewood",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 6,
    consumable: true,
    unit: "bundle",
    tradesFor: "1 bundle = 1 meal (more in cold weather)",
    notes: "Heating, cooking, water purification, morale. Value skyrockets in winter. Renewable if you have trees and an axe.",
    retailPrice: 8,
  },
  {
    id: "g-kerosene",
    name: "Kerosene (1 gallon)",
    category: "Power & Fuel",
    type: "good",
    description: "Kerosene for lamps and heaters",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 5,
    consumable: true,
    unit: "gallon",
    tradesFor: "1 gallon = 1-2 days of food",
    notes: "Kerosene heaters and lamps run forever on small amounts. Stores well.",
    retailPrice: 10,
  },

  // ── Tools & Hardware ──────────────────────────────────────────────────────
  {
    id: "g-hand-tools-set",
    name: "Hand Tool Set (hammer, pliers, screwdrivers)",
    category: "Tools & Hardware",
    type: "good",
    description: "Basic hand tool set — no power required",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 7,
    consumable: false,
    unit: "set",
    tradesFor: "Tool set = ongoing labor value",
    notes: "When power tools are dead weight, hand tools are everything. A good set enables repairs, construction, and barter labor.",
    retailPrice: 40,
    asin: "B09ZKCHQCR",
  },
  {
    id: "g-nails-screws",
    name: "Nails & Screws (assorted box)",
    category: "Tools & Hardware",
    type: "good",
    description: "Mixed box of common nails and wood screws",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 6,
    consumable: true,
    unit: "box",
    tradesFor: "Handful of nails = 1 meal",
    notes: "You cannot rebuild or fortify without fasteners. Easy to store, easy to trade in small quantities.",
    retailPrice: 15,
  },
  {
    id: "g-duct-tape",
    name: "Duct Tape (roll)",
    category: "Tools & Hardware",
    type: "good",
    description: "Gorilla or similar heavy-duty duct tape",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 6,
    consumable: true,
    unit: "roll",
    tradesFor: "1 roll = 1-2 days of food",
    notes: "Repairs tarps, seals leaks, splints, patching, 1000 uses. The most versatile item in any collapse.",
    retailPrice: 7,
  },
  {
    id: "g-tarps",
    name: "Heavy-Duty Tarp (8x10 or larger)",
    category: "Tools & Hardware",
    type: "good",
    description: "UV-resistant poly tarp with grommets",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 6,
    consumable: false,
    unit: "each",
    tradesFor: "1 tarp = 2-3 days of food",
    notes: "Shelter, rain collection, ground cover, privacy screen. After Katrina, tarps were in massive demand for roof repair.",
    retailPrice: 15,
  },
  {
    id: "g-rope-paracord",
    name: "Paracord 550 (100 ft)",
    category: "Tools & Hardware",
    type: "good",
    description: "Mil-spec 550 paracord",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 5,
    consumable: true,
    unit: "hank",
    tradesFor: "50 ft = 1 meal",
    notes: "Shelter building, lashing, snares, clotheslines, splints. Inner strands work as fishing line or sewing thread.",
    retailPrice: 8,
  },
  {
    id: "g-knife-fixed",
    name: "Fixed-Blade Knife",
    category: "Tools & Hardware",
    type: "good",
    description: "Full-tang fixed blade, 4-5 inch (Mora, ESEE, etc.)",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 6,
    consumable: false,
    unit: "each",
    tradesFor: "1 quality knife = several days of food",
    notes: "The most fundamental survival tool. Batoning, processing game, carving, self-defense. A Mora Companion costs $17 and works forever.",
    retailPrice: 17,
    asin: "B00BMFYMDI",
  },
  {
    id: "g-axe-hatchet",
    name: "Axe / Hatchet",
    category: "Tools & Hardware",
    type: "good",
    description: "Full-size axe or camp hatchet",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 7,
    consumable: false,
    unit: "each",
    tradesFor: "1 axe = several days of food or ongoing labor",
    notes: "Firewood processing, construction, clearing. A durable axe is a renewable tool — it makes fuel. Value increases as firewood demand rises.",
    retailPrice: 35,
  },
  {
    id: "g-sewing-kit",
    name: "Sewing Kit (heavy-duty)",
    category: "Tools & Hardware",
    type: "good",
    description: "Needles, thread, buttons, patches, leather needle",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 5,
    consumable: true,
    unit: "kit",
    tradesFor: "Repair service = ongoing trade value",
    notes: "Clothing repair becomes essential when you cannot buy new clothes. Also wound suturing in emergencies.",
    retailPrice: 10,
  },
  {
    id: "g-zip-ties",
    name: "Zip Ties (assorted, 200-pack)",
    category: "Tools & Hardware",
    type: "good",
    description: "Various sizes of nylon cable ties",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 4,
    consumable: true,
    unit: "pack",
    tradesFor: "Handful = 1 small trade",
    notes: "Fast repairs, bundling, temporary fixes, restraints. Cheap to stockpile, useful for everything.",
    retailPrice: 8,
  },
  {
    id: "g-sharpening-stone",
    name: "Sharpening Stone / Whetstone",
    category: "Tools & Hardware",
    type: "good",
    description: "Dual-grit sharpening stone for knives, axes, and tools",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 6,
    consumable: false,
    unit: "each",
    tradesFor: "Sharpening service = ongoing trade",
    notes: "Every blade gets dull. The person who can sharpen tools provides an ongoing service. Renewable trade value.",
    retailPrice: 12,
  },
  {
    id: "g-wire-assorted",
    name: "Wire (assorted gauge, spools)",
    category: "Tools & Hardware",
    type: "good",
    description: "Copper, galvanized, and baling wire",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 5,
    consumable: true,
    unit: "spool",
    tradesFor: "Wire = repair and construction material",
    notes: "Electrical repairs, snares, fencing, binding. Multiple gauges serve different purposes.",
    retailPrice: 10,
  },
  {
    id: "g-glue-epoxy",
    name: "Epoxy / Super Glue (multi-pack)",
    category: "Tools & Hardware",
    type: "good",
    description: "JB Weld, Gorilla Glue, and super glue assortment",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 4,
    consumable: true,
    unit: "pack",
    tradesFor: "Adhesive = small trade item",
    notes: "Repairs plastic, metal, wood. Super glue also works for wound closure in emergencies.",
    retailPrice: 12,
  },

  // ── Defense & Comms ───────────────────────────────────────────────────────
  {
    id: "g-ammo-9mm",
    name: "Ammunition — 9mm (50 rounds)",
    category: "Defense & Comms",
    type: "good",
    description: "9mm FMJ or JHP ammunition",
    valueDay7: 4,
    valueDay30: 8,
    valueDay90: 9,
    consumable: true,
    unit: "box",
    tradesFor: "1 box 9mm = 3-5 days of food",
    notes: "Most common handgun caliber in the US. Universal demand. In Yugoslavia, ammo was currency. Individual rounds traded for meals.",
    retailPrice: 15,
  },
  {
    id: "g-ammo-22lr",
    name: "Ammunition — .22 LR (100 rounds)",
    category: "Defense & Comms",
    type: "good",
    description: ".22 Long Rifle rimfire ammunition",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 7,
    consumable: true,
    unit: "box",
    tradesFor: "1 box .22 = 2-3 days of food",
    notes: "Small game hunting. Cheap to stockpile. Lightweight. Everyone with a .22 rifle needs it, and .22s are the most common firearm in America.",
    retailPrice: 8,
  },
  {
    id: "g-ammo-12ga",
    name: "Ammunition — 12 Gauge (25 shells)",
    category: "Defense & Comms",
    type: "good",
    description: "12 gauge shotgun shells, birdshot/buckshot/slug mix",
    valueDay7: 3,
    valueDay30: 7,
    valueDay90: 8,
    consumable: true,
    unit: "box",
    tradesFor: "1 box = 3-4 days of food",
    notes: "Versatile: bird hunting with birdshot, deer with slugs, defense with buckshot. One platform, multiple uses.",
    retailPrice: 12,
  },
  {
    id: "g-ammo-556",
    name: "Ammunition — 5.56/.223 (20 rounds)",
    category: "Defense & Comms",
    type: "good",
    description: "5.56 NATO or .223 Remington rifle ammunition",
    valueDay7: 3,
    valueDay30: 7,
    valueDay90: 8,
    consumable: true,
    unit: "box",
    tradesFor: "1 box = 3-5 days of food",
    notes: "AR-15 platform is the most popular rifle in America. High demand caliber.",
    retailPrice: 12,
  },
  {
    id: "g-two-way-radio",
    name: "Two-Way Radios (GMRS/FRS pair)",
    category: "Defense & Comms",
    type: "good",
    description: "Midland, Motorola, or similar GMRS/FRS handheld radios",
    valueDay7: 3,
    valueDay30: 6,
    valueDay90: 7,
    consumable: false,
    unit: "pair",
    tradesFor: "Radio pair = several days of food or services",
    notes: "When cell towers die, radios are the only way to communicate beyond shouting distance. GMRS has better range than FRS.",
    retailPrice: 70,
    asin: "B09GKP83WZ",
  },
  {
    id: "g-am-fm-radio",
    name: "AM/FM Crank Radio",
    category: "Defense & Comms",
    type: "good",
    description: "Hand-crank emergency radio with NOAA weather band",
    valueDay7: 3,
    valueDay30: 5,
    valueDay90: 4,
    consumable: false,
    unit: "each",
    tradesFor: "Information = power. The person with news has leverage.",
    notes: "No batteries needed. Information is the most underrated currency in collapse. Knowing what is happening gives you a massive advantage.",
    retailPrice: 30,
  },
  {
    id: "g-binoculars",
    name: "Binoculars (8x42 or 10x42)",
    category: "Defense & Comms",
    type: "good",
    description: "Quality binoculars for observation and security",
    valueDay7: 2,
    valueDay30: 4,
    valueDay90: 5,
    consumable: false,
    unit: "each",
    tradesFor: "1 pair = 2-3 days of food",
    notes: "Early warning. Seeing who is coming from a distance is a security multiplier.",
    retailPrice: 50,
  },
  {
    id: "g-pepper-spray",
    name: "Pepper Spray (3-pack)",
    category: "Defense & Comms",
    type: "good",
    description: "OC spray for personal defense",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 4,
    consumable: true,
    unit: "can",
    tradesFor: "1 can = 1-2 meals",
    notes: "Non-lethal defense option. Good for people who are not comfortable with firearms.",
    retailPrice: 10,
  },
  {
    id: "g-ham-radio-handheld",
    name: "HAM Radio Handheld (Baofeng UV-5R)",
    category: "Defense & Comms",
    type: "good",
    description: "Dual-band amateur radio transceiver",
    valueDay7: 3,
    valueDay30: 6,
    valueDay90: 7,
    consumable: false,
    unit: "each",
    tradesFor: "HAM radio + knowledge = community-level communication",
    notes: "Requires license to transmit legally, but in a real SHTF nobody is checking. Can reach repeaters for regional communication.",
    retailPrice: 25,
  },

  // ── Seeds & Agriculture ───────────────────────────────────────────────────
  {
    id: "g-seed-vault",
    name: "Heirloom Seed Vault (35+ varieties)",
    category: "Seeds & Agriculture",
    type: "good",
    description: "Non-GMO heirloom vegetable seed vault, 10,000+ seeds",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 10,
    consumable: false,
    unit: "vault",
    tradesFor: "Seed vault = major trade item at day 90. Equivalent to firearms.",
    notes: "Heirloom seeds produce plants that make MORE seeds. This is renewable food production. At day 90, when stockpiles are running out, seeds are the future.",
    retailPrice: 40,
    asin: "B01BSEYRJE",
  },
  {
    id: "g-seeds-individual",
    name: "Seed Packets (individual varieties)",
    category: "Seeds & Agriculture",
    type: "good",
    description: "Individual packets of common vegetables (tomato, bean, squash, etc.)",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 7,
    consumable: false,
    unit: "packet",
    tradesFor: "1 packet = 1-2 meals at day 90",
    notes: "Small denomination trade items. Easy to barter one packet at a time.",
    retailPrice: 3,
  },
  {
    id: "g-fertilizer",
    name: "Fertilizer (general purpose, 10 lb)",
    category: "Seeds & Agriculture",
    type: "good",
    description: "10-10-10 or similar balanced fertilizer",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 6,
    consumable: true,
    unit: "bag",
    tradesFor: "1 bag = 2-3 days of food at day 90",
    notes: "Most collapse-grown gardens will struggle with depleted soil. Fertilizer multiplies food production.",
    retailPrice: 12,
  },
  {
    id: "g-garden-tools",
    name: "Gardening Tools (shovel, rake, hoe)",
    category: "Seeds & Agriculture",
    type: "good",
    description: "Basic hand gardening tools",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 6,
    consumable: false,
    unit: "set",
    tradesFor: "Tool set = ongoing labor value",
    notes: "You cannot garden with your hands. Basic tools enable food production for everyone around you.",
    retailPrice: 35,
  },
  {
    id: "g-fishing-gear",
    name: "Fishing Kit (rod, reel, tackle)",
    category: "Seeds & Agriculture",
    type: "good",
    description: "Complete fishing setup with lures, hooks, line, and sinkers",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 7,
    consumable: false,
    unit: "kit",
    tradesFor: "Fishing gear = renewable food source value",
    notes: "Renewable protein source. Near any body of water, fishing gear becomes a food factory. Extra hooks and line are great small-denomination trades.",
    retailPrice: 50,
  },
  {
    id: "g-fishing-hooks-line",
    name: "Fishing Hooks & Line (spare)",
    category: "Seeds & Agriculture",
    type: "good",
    description: "Extra hooks (assorted sizes) and monofilament line",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 5,
    consumable: true,
    unit: "pack",
    tradesFor: "10 hooks = 1 meal",
    notes: "Small, lightweight, easy to trade. Everyone near water needs them. Also used for snares.",
    retailPrice: 8,
  },
  {
    id: "g-traps-snares",
    name: "Traps & Snare Wire",
    category: "Seeds & Agriculture",
    type: "good",
    description: "Small game snares and trap components",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 6,
    consumable: true,
    unit: "set",
    tradesFor: "Snare set = 2-3 days of food",
    notes: "Passive food acquisition. Set it and move on. Works while you do other things. Requires knowledge to be effective.",
    retailPrice: 15,
  },
  {
    id: "g-chicken-feed",
    name: "Chicken Feed (50 lb bag)",
    category: "Seeds & Agriculture",
    type: "good",
    description: "Layer feed for egg-producing chickens",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 7,
    consumable: true,
    unit: "bag",
    tradesFor: "1 bag = ongoing egg production for weeks",
    notes: "If anyone in your area has chickens, feed becomes premium. Eggs are one of the few renewable protein sources.",
    retailPrice: 18,
  },
  {
    id: "g-canning-supplies",
    name: "Canning Supplies (lids, jars, pectin)",
    category: "Seeds & Agriculture",
    type: "good",
    description: "Mason jars, two-piece lids, and pectin for food preservation",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 7,
    consumable: true,
    unit: "set",
    tradesFor: "Canning supplies = food preservation ability",
    notes: "When gardens start producing, preserving the harvest becomes critical. Lids are the consumable bottleneck.",
    retailPrice: 20,
  },
];

// ─── SKILLS ─────────────────────────────────────────────────────────────────────

export const SKILLS: BarterItem[] = [
  // ── Medical ───────────────────────────────────────────────────────────────
  {
    id: "s-first-aid",
    name: "First Aid / Wound Care",
    category: "Medical",
    type: "skill",
    description: "Stop bleeding, clean wounds, apply bandages, recognize shock",
    valueDay7: 3,
    valueDay30: 8,
    valueDay90: 9,
    dependencies: ["first aid supplies", "bandages", "antiseptic"],
    tradesFor: "Treatment = food for a day or more",
    notes: "The most immediately needed medical skill. A minor wound untreated becomes sepsis in days.",
  },
  {
    id: "s-wound-closure",
    name: "Wound Closure / Suturing",
    category: "Medical",
    type: "skill",
    description: "Close wounds with sutures, staples, or butterfly strips",
    valueDay7: 2,
    valueDay30: 8,
    valueDay90: 10,
    dependencies: ["suture kit", "antiseptic", "gloves"],
    tradesFor: "Major wound closure = days of food or valuable goods",
    notes: "The person who can stitch a wound eats for free. Period. Take a course now.",
  },
  {
    id: "s-dental-emergency",
    name: "Emergency Dental Care",
    category: "Medical",
    type: "skill",
    description: "Temporary fillings, tooth extraction, abscess drainage, pain management",
    valueDay7: 2,
    valueDay30: 8,
    valueDay90: 10,
    dependencies: ["dental kit", "clove oil", "painkillers"],
    tradesFor: "Dental work = premium trade. People will give almost anything for pain relief.",
    notes: "Dental emergencies are one of the top medical issues in prolonged collapse. Abscesses can become life-threatening.",
  },
  {
    id: "s-midwifery",
    name: "Midwifery / Birth Assistance",
    category: "Medical",
    type: "skill",
    description: "Prenatal care, labor and delivery assistance, postpartum care",
    valueDay7: 2,
    valueDay30: 7,
    valueDay90: 9,
    dependencies: ["clean linens", "sterile equipment", "clean water"],
    tradesFor: "Delivery assistance = long-term alliance with family",
    notes: "Babies do not wait for the grid to come back. This skill creates community bonds that go beyond simple barter.",
  },
  {
    id: "s-mental-health",
    name: "Mental Health / Counseling",
    category: "Medical",
    type: "skill",
    description: "Crisis counseling, trauma support, conflict mediation",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 7,
    dependencies: [],
    tradesFor: "Counseling = community stability value (harder to quantify in trades)",
    notes: "Undervalued early but critical by day 90. PTSD, depression, and interpersonal conflict destroy communities from within.",
  },
  {
    id: "s-herbal-medicine",
    name: "Herbal Medicine / Foraging for Medicinals",
    category: "Medical",
    type: "skill",
    description: "Identify and prepare medicinal plants for common ailments",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 8,
    dependencies: ["plant identification knowledge", "preparation tools"],
    tradesFor: "Remedies = 1-2 meals per treatment",
    notes: "When pharmaceuticals run out, traditional medicine fills the gap. Willow bark (aspirin), plantain (wound care), elderberry (immune support).",
  },

  // ── Mechanical ────────────────────────────────────────────────────────────
  {
    id: "s-engine-repair",
    name: "Engine Repair (vehicle)",
    category: "Mechanical",
    type: "skill",
    description: "Diagnose and repair gasoline and diesel engines",
    valueDay7: 3,
    valueDay30: 6,
    valueDay90: 5,
    dependencies: ["hand tools", "parts/fluids"],
    tradesFor: "Engine repair = days of food or fuel",
    notes: "High value early when vehicles still matter. Drops as fuel runs out. Shifts to generator repair value.",
  },
  {
    id: "s-generator-maintenance",
    name: "Generator Maintenance & Repair",
    category: "Mechanical",
    type: "skill",
    description: "Service, troubleshoot, and repair portable generators",
    valueDay7: 4,
    valueDay30: 7,
    valueDay90: 5,
    dependencies: ["hand tools", "oil", "spark plugs"],
    tradesFor: "Generator fix = days of food or fuel share",
    notes: "Everyone with a generator needs someone who can keep it running. Carb cleaning, oil changes, fuel system issues.",
  },
  {
    id: "s-small-engine",
    name: "Small Engine Repair",
    category: "Mechanical",
    type: "skill",
    description: "Chainsaw, lawn mower, tiller, pump engine repair",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 6,
    dependencies: ["hand tools", "parts"],
    tradesFor: "Keeping a chainsaw running = ongoing trade relationship",
    notes: "Chainsaws and tillers become community assets. Keeping them running makes you essential.",
  },
  {
    id: "s-bicycle-repair",
    name: "Bicycle Repair",
    category: "Mechanical",
    type: "skill",
    description: "Fix flats, repair chains, adjust brakes, rebuild wheels",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 6,
    dependencies: ["bike tools", "tubes", "patches"],
    tradesFor: "Bike repair = 1-2 days of food",
    notes: "When fuel runs out, bicycles become primary transportation. The bike mechanic becomes the town mechanic.",
  },
  {
    id: "s-welding",
    name: "Welding (stick/MIG)",
    category: "Mechanical",
    type: "skill",
    description: "Join and repair metal structures and equipment",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 6,
    dependencies: ["welder", "power source", "welding rod/wire", "safety gear"],
    tradesFor: "Welding repair = days of food or goods",
    notes: "Requires power, so value depends on having generator or solar. Can repair things nothing else can fix.",
  },

  // ── Electrical ────────────────────────────────────────────────────────────
  {
    id: "s-wiring",
    name: "Electrical Wiring & Repair",
    category: "Electrical",
    type: "skill",
    description: "Wire buildings, repair electrical systems, install circuits",
    valueDay7: 3,
    valueDay30: 7,
    valueDay90: 8,
    dependencies: ["wire", "connectors", "tools", "power source"],
    tradesFor: "Wiring work = days of food or ongoing community role",
    notes: "When you need to wire a generator into a panel, or set up a 12V system, the electrician is the most popular person in town.",
  },
  {
    id: "s-solar-install",
    name: "Solar Panel Installation & Wiring",
    category: "Electrical",
    type: "skill",
    description: "Size, install, and wire solar panel systems with charge controllers and batteries",
    valueDay7: 2,
    valueDay30: 7,
    valueDay90: 10,
    dependencies: ["solar panels", "charge controller", "batteries", "wire"],
    tradesFor: "Solar installation = premium community asset. Weeks of food or permanent role.",
    notes: "At day 90, the person who can build solar power systems is building the new infrastructure. This skill peaks in value when fuel is gone.",
  },
  {
    id: "s-battery-systems",
    name: "Battery Bank Design & Maintenance",
    category: "Electrical",
    type: "skill",
    description: "Build, wire, and maintain battery storage systems (12V, 24V, 48V)",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 9,
    dependencies: ["batteries", "wire", "fuses", "tools"],
    tradesFor: "Battery system build = days of food or ongoing maintenance role",
    notes: "Pairs with solar. Understanding series/parallel, charge profiles, and safety is critical.",
  },
  {
    id: "s-radio-repair",
    name: "Radio Repair & Modification",
    category: "Electrical",
    type: "skill",
    description: "Diagnose, repair, and modify communication radios",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 7,
    dependencies: ["soldering iron", "multimeter", "spare components"],
    tradesFor: "Working radio = communication = security",
    notes: "Keeping radios operational maintains community communication networks.",
  },

  // ── Construction ──────────────────────────────────────────────────────────
  {
    id: "s-carpentry",
    name: "Carpentry & Woodworking",
    category: "Construction",
    type: "skill",
    description: "Build and repair wooden structures, furniture, and fortifications",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 7,
    dependencies: ["hand tools", "fasteners", "lumber/materials"],
    tradesFor: "Construction work = food for the duration of the job",
    notes: "Building shelters, repairing damage, constructing raised beds, fortifying positions. Always in demand.",
  },
  {
    id: "s-plumbing",
    name: "Plumbing & Water Systems",
    category: "Construction",
    type: "skill",
    description: "Repair pipes, build gravity-fed water systems, install rain catchment",
    valueDay7: 3,
    valueDay30: 7,
    valueDay90: 8,
    dependencies: ["pipe fittings", "sealant", "tools"],
    tradesFor: "Water system work = premium trade",
    notes: "Water infrastructure is critical. Building rain catchment, gravity filtration, and waste water systems.",
  },
  {
    id: "s-roofing",
    name: "Roofing & Weatherproofing",
    category: "Construction",
    type: "skill",
    description: "Repair and install roofing, seal leaks, waterproof structures",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 6,
    dependencies: ["tarps", "fasteners", "sealant", "tools"],
    tradesFor: "Roof repair = days of food",
    notes: "Post-Katrina, roofers named their price. A leaking roof makes a house uninhabitable.",
  },
  {
    id: "s-masonry",
    name: "Masonry & Concrete Work",
    category: "Construction",
    type: "skill",
    description: "Build with stone, brick, and concrete. Construct ovens, fireplaces, foundations.",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 6,
    dependencies: ["masonry tools", "mortar/cement", "materials"],
    tradesFor: "Building a community oven or fireplace = ongoing food/labor trades",
    notes: "Building rocket stoves, outdoor ovens, and foundations from local materials.",
  },
  {
    id: "s-fortification",
    name: "Fortification & Defensive Construction",
    category: "Construction",
    type: "skill",
    description: "Reinforce doors, windows, and perimeters. Build barriers and observation positions.",
    valueDay7: 3,
    valueDay30: 6,
    valueDay90: 5,
    dependencies: ["lumber", "fasteners", "tools"],
    tradesFor: "Fortification work = community protection role",
    notes: "Most needed in the first month when security situations are evolving. Boarding windows, reinforcing entry points, building barricades.",
  },

  // ── Food Production ───────────────────────────────────────────────────────
  {
    id: "s-gardening",
    name: "Vegetable Gardening",
    category: "Food Production",
    type: "skill",
    description: "Plan, plant, maintain, and harvest food gardens",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 10,
    dependencies: ["seeds", "tools", "water source"],
    tradesFor: "Produce = ongoing food source for community",
    notes: "THE most valuable skill at day 90. When stockpiles run out, the gardener feeds the neighborhood. Learn this NOW — it takes seasons to get good at it.",
  },
  {
    id: "s-animal-husbandry",
    name: "Animal Husbandry (chickens, goats, rabbits)",
    category: "Food Production",
    type: "skill",
    description: "Raise, breed, and care for small livestock",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 9,
    dependencies: ["animals", "feed", "shelter", "fencing"],
    tradesFor: "Eggs, milk, meat = daily trade value",
    notes: "Renewable protein. Chickens are the gateway animal — eggs daily, meat when needed, manure for gardens.",
  },
  {
    id: "s-hunting",
    name: "Hunting & Trapping",
    category: "Food Production",
    type: "skill",
    description: "Track, hunt, and trap wild game",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 8,
    dependencies: ["firearm or bow", "ammunition", "traps", "knife"],
    tradesFor: "Fresh meat = 2-3 days of food per successful hunt",
    notes: "Game will be overhunted quickly near population centers. Trapping is more sustainable than hunting long-term.",
  },
  {
    id: "s-fishing",
    name: "Fishing (rod, net, trotline)",
    category: "Food Production",
    type: "skill",
    description: "Catch fish using various methods including passive techniques",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 8,
    dependencies: ["fishing gear", "water access"],
    tradesFor: "Fish = daily protein source",
    notes: "Trotlines and gill nets are force multipliers — passive fishing while you do other work. Learn knots.",
  },
  {
    id: "s-butchering",
    name: "Butchering & Meat Processing",
    category: "Food Production",
    type: "skill",
    description: "Field dress, skin, butcher, and process game and livestock",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 8,
    dependencies: ["sharp knives", "clean workspace", "salt for preservation"],
    tradesFor: "Butchering service = share of the meat",
    notes: "Most people cannot process an animal. The person who can turns a deer into a week of food for multiple families.",
  },
  {
    id: "s-canning-preserving",
    name: "Canning & Food Preservation",
    category: "Food Production",
    type: "skill",
    description: "Water bath and pressure canning, dehydrating, smoking, salt-curing",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 9,
    dependencies: ["canning supplies", "heat source", "salt", "food to preserve"],
    tradesFor: "Preservation service = share of preserved food",
    notes: "When gardens produce more than you can eat, preservation prevents waste. Summer abundance feeds winter scarcity.",
  },
  {
    id: "s-brewing",
    name: "Brewing & Distilling",
    category: "Food Production",
    type: "skill",
    description: "Brew beer, wine, or mead. Basic distillation for spirits or water purification.",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 7,
    dependencies: ["yeast", "sugar source", "containers", "heat"],
    tradesFor: "Alcohol = premium trade good",
    notes: "Alcohol is medicine, morale, and currency. The person who can produce it has a renewable income stream.",
  },
  {
    id: "s-foraging",
    name: "Wild Plant Foraging & Identification",
    category: "Food Production",
    type: "skill",
    description: "Identify, harvest, and prepare wild edible plants, mushrooms, and nuts",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 7,
    dependencies: ["field guide or knowledge", "basket/container"],
    tradesFor: "Wild food = supplement to diet",
    notes: "Supplements garden and hunting. Dandelion, cattail, acorns, berries, mushrooms — free calories if you know what you are looking at.",
  },

  // ── Security ──────────────────────────────────────────────────────────────
  {
    id: "s-perimeter-setup",
    name: "Perimeter Security Setup",
    category: "Security",
    type: "skill",
    description: "Design and install early warning systems, observation points, and barriers",
    valueDay7: 3,
    valueDay30: 7,
    valueDay90: 6,
    dependencies: ["wire", "alarms/noisemakers", "tools"],
    tradesFor: "Security setup = community protection role + food/housing",
    notes: "Trip wires, motion lights (solar), observation schedules, dead zones. The guy who sets this up becomes essential.",
  },
  {
    id: "s-watch-organization",
    name: "Watch Organization & Scheduling",
    category: "Security",
    type: "skill",
    description: "Organize rotating watch schedules, communication protocols, and response procedures",
    valueDay7: 2,
    valueDay30: 6,
    valueDay90: 5,
    dependencies: ["radios", "timepieces"],
    tradesFor: "Leadership role = food and community standing",
    notes: "Military vets and law enforcement often fill this role naturally. Someone has to organize it.",
  },
  {
    id: "s-conflict-resolution",
    name: "Conflict Resolution & Mediation",
    category: "Security",
    type: "skill",
    description: "De-escalate tensions, mediate disputes, negotiate between parties",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 7,
    dependencies: [],
    tradesFor: "Stability = community survival",
    notes: "Most collapse deaths are not from violence by strangers — they are from internal community breakdown. The mediator prevents this.",
  },
  {
    id: "s-self-defense-training",
    name: "Self-Defense & Firearms Training",
    category: "Security",
    type: "skill",
    description: "Teach basic self-defense, firearms safety, and marksmanship",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 4,
    dependencies: ["training area", "ammunition for training"],
    tradesFor: "Training = food per session",
    notes: "People who never touched a gun will want to learn. The person who can teach safely has an ongoing trade.",
  },

  // ── Communications ────────────────────────────────────────────────────────
  {
    id: "s-ham-radio",
    name: "HAM Radio Operation",
    category: "Communications",
    type: "skill",
    description: "Operate amateur radio equipment, make contacts, relay information",
    valueDay7: 3,
    valueDay30: 7,
    valueDay90: 8,
    dependencies: ["HAM radio", "antenna", "power source"],
    tradesFor: "Information relay = community intelligence role",
    notes: "The HAM operator becomes the community's link to the outside world. Knowing what is happening beyond your area is power.",
  },
  {
    id: "s-antenna-building",
    name: "Antenna Building & Optimization",
    category: "Communications",
    type: "skill",
    description: "Build, repair, and tune antennas for maximum range",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 7,
    dependencies: ["wire", "coax cable", "connectors", "basic tools"],
    tradesFor: "Better antenna = better communication for entire community",
    notes: "A good antenna matters more than a good radio. Can be built from scrap wire and basic materials.",
  },
  {
    id: "s-morse-code",
    name: "Morse Code",
    category: "Communications",
    type: "skill",
    description: "Send and receive Morse code via radio, light, or sound",
    valueDay7: 1,
    valueDay30: 3,
    valueDay90: 5,
    dependencies: ["signal device"],
    tradesFor: "Encoded communication = security advantage",
    notes: "Low-tech, low-power communication that works when voice does not. Can communicate via flashlight or mirror.",
  },
  {
    id: "s-signal-intelligence",
    name: "Signal Intelligence (monitoring & analysis)",
    category: "Communications",
    type: "skill",
    description: "Monitor radio frequencies, identify threats, analyze communication patterns",
    valueDay7: 2,
    valueDay30: 5,
    valueDay90: 6,
    dependencies: ["scanner or radio", "antenna", "power"],
    tradesFor: "Intelligence = security",
    notes: "Knowing what others are saying and planning provides early warning. Scanner + knowledge = eyes and ears for your community.",
  },

  // ── Teaching ──────────────────────────────────────────────────────────────
  {
    id: "s-teaching-general",
    name: "Teaching (any skill to others)",
    category: "Teaching",
    type: "skill",
    description: "Ability to clearly teach survival, medical, technical, or practical skills to others",
    valueDay7: 1,
    valueDay30: 5,
    valueDay90: 8,
    dependencies: [],
    tradesFor: "Teaching multiplies community capability. Ongoing food/role.",
    notes: "One person who can suture is valuable. That person teaching 5 others to suture is a force multiplier. The teacher creates redundancy.",
  },
  {
    id: "s-teaching-children",
    name: "Child Education & Activities",
    category: "Teaching",
    type: "skill",
    description: "Keep children learning, occupied, and psychologically stable",
    valueDay7: 1,
    valueDay30: 4,
    valueDay90: 6,
    dependencies: ["basic supplies"],
    tradesFor: "Childcare = parents can do other work",
    notes: "Parents cannot stand watch, garden, and repair things if their kids are unattended. The person who handles kids frees up labor.",
  },
];

/** Combined list for lookups */
export const ALL_ITEMS: BarterItem[] = [...GOODS, ...SKILLS];

/** Lookup map for fast access by ID */
export const ITEM_MAP = new Map<string, BarterItem>(
  ALL_ITEMS.map((item) => [item.id, item])
);
