import type { TripPreset } from "./fuel-types";

export const tripPresets: TripPreset[] = [
  {
    id: "mojave-road",
    name: "Mojave Road",
    region: "California",
    description: "130-mile historic east-west route across the Mojave Desert. Mostly maintained dirt with sandy washes and rocky sections.",
    totalMiles: 130,
    segments: [
      { name: "I-40 to Mojave Road Start", distanceMiles: 15, terrain: "highway", elevationGainFt: 0, speedMph: 65, isFuelStop: false },
      { name: "Mojave Road \u2014 East Section", distanceMiles: 35, terrain: "gravel", elevationGainFt: 800, speedMph: 25, isFuelStop: false },
      { name: "Sandy Wash Crossing", distanceMiles: 12, terrain: "sand", elevationGainFt: 0, speedMph: 10, isFuelStop: false },
      { name: "Mojave Road \u2014 Central", distanceMiles: 40, terrain: "dirt", elevationGainFt: 1200, speedMph: 20, isFuelStop: false },
      { name: "Rock Springs \u2014 Rocky Section", distanceMiles: 8, terrain: "rock-crawl", elevationGainFt: 600, speedMph: 5, isFuelStop: false },
      { name: "Mojave Road \u2014 West to I-15", distanceMiles: 20, terrain: "gravel", elevationGainFt: 400, speedMph: 30, isFuelStop: false },
    ],
  },
  {
    id: "rubicon-trail",
    name: "Rubicon Trail",
    region: "California",
    description: "22-mile iconic rock-crawling trail from Loon Lake to Lake Tahoe. One of America's most famous off-road routes.",
    totalMiles: 82,
    segments: [
      { name: "Highway to Loon Lake", distanceMiles: 30, terrain: "highway", elevationGainFt: 2000, speedMph: 45, isFuelStop: false },
      { name: "Loon Lake to Rubicon Springs", distanceMiles: 7, terrain: "rock-crawl", elevationGainFt: 800, speedMph: 3, isFuelStop: false },
      { name: "Rubicon Springs to Big Sluice", distanceMiles: 5, terrain: "rock-crawl", elevationGainFt: 1200, speedMph: 2, isFuelStop: false },
      { name: "Big Sluice to Wentworth Springs", distanceMiles: 10, terrain: "rock-crawl", elevationGainFt: 600, speedMph: 4, isFuelStop: false },
      { name: "Wentworth Springs to Georgetown", distanceMiles: 30, terrain: "gravel", elevationGainFt: 500, speedMph: 30, isFuelStop: false },
    ],
  },
  {
    id: "trans-america-co",
    name: "Trans-America Trail \u2014 Colorado Section",
    region: "Colorado",
    description: "250-mile section through the Rockies. Mix of mountain passes, dirt roads, and small-town fuel stops.",
    totalMiles: 250,
    segments: [
      { name: "Denver to Kenosha Pass", distanceMiles: 65, terrain: "highway", elevationGainFt: 3000, speedMph: 55, isFuelStop: false },
      { name: "Kenosha Pass to Buena Vista", distanceMiles: 45, terrain: "gravel", elevationGainFt: 1500, speedMph: 25, isFuelStop: false },
      { name: "Buena Vista (fuel stop)", distanceMiles: 5, terrain: "city", elevationGainFt: 0, speedMph: 25, isFuelStop: true },
      { name: "Cottonwood Pass", distanceMiles: 20, terrain: "dirt", elevationGainFt: 3500, speedMph: 15, isFuelStop: false },
      { name: "Taylor Park to Tin Cup", distanceMiles: 30, terrain: "dirt", elevationGainFt: 1200, speedMph: 20, isFuelStop: false },
      { name: "Cumberland Pass", distanceMiles: 15, terrain: "dirt", elevationGainFt: 2800, speedMph: 15, isFuelStop: false },
      { name: "Pitkin to Ohio Creek", distanceMiles: 35, terrain: "gravel", elevationGainFt: 800, speedMph: 30, isFuelStop: false },
      { name: "Gunnison (fuel stop)", distanceMiles: 10, terrain: "city", elevationGainFt: 0, speedMph: 30, isFuelStop: true },
      { name: "Lake City Road", distanceMiles: 25, terrain: "gravel", elevationGainFt: 1500, speedMph: 25, isFuelStop: false },
    ],
  },
  {
    id: "death-valley-loop",
    name: "Death Valley Explorer",
    region: "California / Nevada",
    description: "200-mile loop through Death Valley NP. Extreme heat, sandy washes, and long stretches without services.",
    totalMiles: 200,
    segments: [
      { name: "Pahrump to DV West Entrance", distanceMiles: 45, terrain: "highway", elevationGainFt: 1500, speedMph: 60, isFuelStop: false },
      { name: "Stovepipe Wells to Titus Canyon", distanceMiles: 15, terrain: "gravel", elevationGainFt: 2500, speedMph: 20, isFuelStop: false },
      { name: "Titus Canyon (one-way)", distanceMiles: 27, terrain: "dirt", elevationGainFt: 1800, speedMph: 15, isFuelStop: false },
      { name: "Scotty\u2019s Castle Road to Ubehebe", distanceMiles: 30, terrain: "highway", elevationGainFt: 500, speedMph: 50, isFuelStop: false },
      { name: "Racetrack Road", distanceMiles: 28, terrain: "gravel", elevationGainFt: 800, speedMph: 15, isFuelStop: false },
      { name: "Return to Stovepipe Wells", distanceMiles: 55, terrain: "highway", elevationGainFt: 1000, speedMph: 55, isFuelStop: false },
    ],
  },
  {
    id: "ouray-imogene",
    name: "Ouray \u2014 Imogene Pass Loop",
    region: "Colorado",
    description: "High-altitude loop over Imogene Pass (13,114 ft). Tight switchbacks, rocky ledges, and stunning views.",
    totalMiles: 55,
    segments: [
      { name: "Ouray to Camp Bird Mine", distanceMiles: 8, terrain: "gravel", elevationGainFt: 1500, speedMph: 20, isFuelStop: false },
      { name: "Camp Bird to Imogene Summit", distanceMiles: 7, terrain: "rock-crawl", elevationGainFt: 3500, speedMph: 5, isFuelStop: false },
      { name: "Imogene Summit to Telluride", distanceMiles: 10, terrain: "dirt", elevationGainFt: 0, speedMph: 15, isFuelStop: false },
      { name: "Telluride to Ridgway (Hwy 62)", distanceMiles: 25, terrain: "highway", elevationGainFt: 500, speedMph: 55, isFuelStop: false },
      { name: "Ridgway to Ouray", distanceMiles: 5, terrain: "highway", elevationGainFt: 0, speedMph: 45, isFuelStop: false },
    ],
  },
  {
    id: "baja-mike-sky",
    name: "Baja \u2014 Mike\u2019s Sky Ranch",
    region: "Baja California, Mexico",
    description: "Popular Baja day trip from Ensenada through coastal highway, then inland on dirt to Mike\u2019s Sky Ranch.",
    totalMiles: 140,
    segments: [
      { name: "Ensenada to Hwy 3 Junction", distanceMiles: 25, terrain: "highway", elevationGainFt: 500, speedMph: 55, isFuelStop: false },
      { name: "Hwy 3 East (Valle de Trinidad)", distanceMiles: 40, terrain: "highway", elevationGainFt: 2000, speedMph: 50, isFuelStop: false },
      { name: "Dirt Road to Mike\u2019s Sky Ranch", distanceMiles: 22, terrain: "dirt", elevationGainFt: 1500, speedMph: 15, isFuelStop: false },
      { name: "Mike\u2019s to Hwy 3 (return)", distanceMiles: 22, terrain: "dirt", elevationGainFt: 500, speedMph: 15, isFuelStop: false },
      { name: "Hwy 3 West to Ensenada", distanceMiles: 31, terrain: "highway", elevationGainFt: 0, speedMph: 55, isFuelStop: false },
    ],
  },
  {
    id: "white-rim-trail",
    name: "White Rim Trail",
    region: "Utah",
    description: "100-mile loop below the mesa tops in Canyonlands NP. Permit required. Usually done over 2\u20133 days.",
    totalMiles: 125,
    segments: [
      { name: "Moab to Island in the Sky Entrance", distanceMiles: 25, terrain: "highway", elevationGainFt: 1500, speedMph: 55, isFuelStop: false },
      { name: "Shafer Trail Descent", distanceMiles: 5, terrain: "rock-crawl", elevationGainFt: 0, speedMph: 5, isFuelStop: false },
      { name: "White Rim Road \u2014 South", distanceMiles: 30, terrain: "dirt", elevationGainFt: 400, speedMph: 15, isFuelStop: false },
      { name: "Murphy Hogback Section", distanceMiles: 8, terrain: "rock-crawl", elevationGainFt: 800, speedMph: 5, isFuelStop: false },
      { name: "White Rim Road \u2014 West", distanceMiles: 25, terrain: "dirt", elevationGainFt: 300, speedMph: 15, isFuelStop: false },
      { name: "Mineral Bottom Climb", distanceMiles: 7, terrain: "gravel", elevationGainFt: 1400, speedMph: 15, isFuelStop: false },
      { name: "Mineral Bottom Road to Hwy 313", distanceMiles: 15, terrain: "gravel", elevationGainFt: 500, speedMph: 30, isFuelStop: false },
      { name: "Hwy 313 to Moab", distanceMiles: 10, terrain: "highway", elevationGainFt: 0, speedMph: 55, isFuelStop: false },
    ],
  },
  {
    id: "alpine-loop-ut",
    name: "Alpine Loop \u2014 Ouray to Lake City",
    region: "Colorado",
    description: "65-mile scenic backcountry loop through Engineer Pass and Cinnamon Pass above 12,000 ft.",
    totalMiles: 65,
    segments: [
      { name: "Ouray to Engineer Pass", distanceMiles: 12, terrain: "rock-crawl", elevationGainFt: 4000, speedMph: 5, isFuelStop: false },
      { name: "Engineer Summit to Animas Forks", distanceMiles: 5, terrain: "dirt", elevationGainFt: 0, speedMph: 10, isFuelStop: false },
      { name: "Animas Forks to Cinnamon Pass", distanceMiles: 8, terrain: "dirt", elevationGainFt: 2000, speedMph: 10, isFuelStop: false },
      { name: "Cinnamon Pass to Lake City", distanceMiles: 20, terrain: "gravel", elevationGainFt: 0, speedMph: 25, isFuelStop: false },
      { name: "Lake City to Ouray (Hwy 149/550)", distanceMiles: 20, terrain: "highway", elevationGainFt: 500, speedMph: 50, isFuelStop: false },
    ],
  },
];
