// ─── Virtual Go-Bag — Gear Database ──────────────────────────────────────────
import type { GoBagItem, GoBagCategory, GoBagCategoryMeta } from "./go-bag-types";

export const categoryMeta: GoBagCategoryMeta[] = [
  { id: "water",      label: "Water",       icon: "Droplets" },
  { id: "fire",       label: "Fire / Food", icon: "Flame" },
  { id: "power",      label: "Power",       icon: "Zap" },
  { id: "recovery",   label: "Recovery",    icon: "Truck" },
  { id: "shelter",    label: "Shelter",     icon: "Tent" },
  { id: "comms",      label: "Comms",       icon: "Radio" },
  { id: "medical",    label: "Medical",     icon: "HeartPulse" },
  { id: "navigation", label: "Navigation",  icon: "Compass" },
  { id: "tools",      label: "Tools / EDC", icon: "Wrench" },
];

export const gearDatabase: GoBagItem[] = [

  // ── WATER — all pack ───────────────────────────────────────────────────────
  {
    id: "sawyer_sqz",
    name: "Squeeze Filter",
    brand: "Sawyer",
    category: "water",
    context: "pack",
    weight_lbs: 0.2,
    description: "Hollow fiber squeeze filter. 0.1 micron. Includes backflush syringe.",
    asin: "B00FA2RLX2",
    hasDiagnostic: true,
  },
  {
    id: "sawyer_mini",
    name: "Mini Filter",
    brand: "Sawyer",
    category: "water",
    context: "pack",
    weight_lbs: 0.1,
    description: "Ultra-compact hollow fiber inline filter. 100,000 gallon rated.",
    asin: "B00FHRADQ2",
    hasDiagnostic: true,
  },
  {
    id: "grayl_geo",
    name: "GeoPress 24oz",
    brand: "Grayl",
    category: "water",
    context: "pack",
    weight_lbs: 1.0,
    description: "Press-to-filter purifier. Removes viruses, bacteria, protozoa, and particulates.",
    asin: "B07NQ6W2M4",
    hasDiagnostic: true,
  },
  {
    id: "grayl_ultra",
    name: "UltraPress 16.9oz",
    brand: "Grayl",
    category: "water",
    context: "pack",
    weight_lbs: 0.87,
    description: "Compact press purifier. 250-press cartridge.",
    asin: "B082WB6RLQ",
    hasDiagnostic: true,
  },
  {
    id: "katadyn_befree",
    name: "BeFree 1L",
    brand: "Katadyn",
    category: "water",
    context: "pack",
    weight_lbs: 0.06,
    description: "EZ-clean hollow fiber filter integrated into a soft flask.",
    asin: "B07BMBQNSQ",
    hasDiagnostic: true,
  },
  {
    id: "msr_miniworks",
    name: "MiniWorks EX",
    brand: "MSR",
    category: "water",
    context: "pack",
    weight_lbs: 0.84,
    description: "Field-maintainable ceramic pump filter. Filters and purifies with iodine resin.",
    asin: "B000BBF2RY",
    hasDiagnostic: true,
  },
  {
    id: "platypus_grav",
    name: "GravityWorks 4L",
    brand: "Platypus",
    category: "water",
    context: "pack",
    weight_lbs: 0.7,
    description: "Hands-free gravity filter. 4L capacity. Great for basecamp and group use.",
    asin: "B0050FFESU",
    hasDiagnostic: true,
  },
  {
    id: "msr_autoflow",
    name: "AutoFlow XL 4L",
    brand: "MSR",
    category: "water",
    context: "pack",
    weight_lbs: 0.65,
    description: "Gravity-fed hollow fiber filter. Field-maintainable.",
    asin: "B00B4H9HOU",
    hasDiagnostic: true,
  },
  {
    id: "lifestraw_personal",
    name: "LifeStraw Personal",
    brand: "LifeStraw",
    category: "water",
    context: "pack",
    weight_lbs: 0.1,
    description: "Ultralight personal straw filter. 1000L rated. Bag, belt, or pocket.",
    asin: "B006QF3TW4",
    hasDiagnostic: false,
  },
  {
    id: "aquatabs",
    name: "Aquatabs 50-pack",
    brand: "Aquatabs",
    category: "water",
    context: "pack",
    weight_lbs: 0.03,
    description: "Chemical water purification tablets. 1 tab per 1L. Works when filters freeze or fail.",
    asin: "B002AQRSXO",
    hasDiagnostic: false,
  },
  {
    id: "nalgene_32",
    name: "Wide Mouth 32oz",
    brand: "Nalgene",
    category: "water",
    context: "pack",
    weight_lbs: 0.31,
    description: "BPA-free hard bottle. Boil-safe. Fits most filters.",
    asin: "B001NCDE48",
    hasDiagnostic: false,
  },
  {
    id: "hydrapak_seeker",
    name: "Seeker 3L",
    brand: "HydraPak",
    category: "water",
    context: "pack",
    weight_lbs: 0.14,
    description: "Collapsible soft flask. Pairs with inline filters. Easy dirty-water source bag.",
    asin: "B07CLLZ9SX",
    hasDiagnostic: false,
  },

  // ── FIRE / FOOD — pack stoves ──────────────────────────────────────────────
  {
    id: "msr_pocket",
    name: "PocketRocket 2",
    brand: "MSR",
    category: "fire",
    context: "pack",
    weight_lbs: 0.18,
    description: "Ultra-compact canister stove. Folds to pocket-size. Rated for 3-season use.",
    asin: "B01N5LGKV4",
    hasDiagnostic: true,
  },
  {
    id: "whisperlite",
    name: "WhisperLite Universal",
    brand: "MSR",
    category: "fire",
    context: "pack",
    weight_lbs: 0.87,
    description: "Multi-fuel stove. Runs on white gas, kerosene, unleaded. Field-maintainable.",
    asin: "B009RIOER6",
    hasDiagnostic: true,
  },
  {
    id: "jetboil_flash",
    name: "Flash Cooking System",
    brand: "Jetboil",
    category: "fire",
    context: "pack",
    weight_lbs: 0.92,
    description: "Integrated canister system. 100 second boil time for 0.5L. Push-button igniter.",
    asin: "B002RAVNWO",
    hasDiagnostic: true,
  },
  {
    id: "snowpeak_gigapower",
    name: "GigaPower Auto",
    brand: "Snow Peak",
    category: "fire",
    context: "pack",
    weight_lbs: 0.09,
    description: "Titanium canister stove with auto-igniter. Extremely compact.",
    asin: "B000AR45BE",
    hasDiagnostic: true,
  },
  {
    id: "biolite_camp",
    name: "CampStove 2+",
    brand: "BioLite",
    category: "fire",
    context: "pack",
    weight_lbs: 2.06,
    description: "Wood-burning stove that generates electricity to charge USB devices. No fuel to carry.",
    asin: "B07B4K5T78",
    hasDiagnostic: false,
  },
  {
    id: "bic_lighter",
    name: "BIC Lighter 3-pack",
    brand: "BIC",
    category: "fire",
    context: "pack",
    weight_lbs: 0.15,
    description: "The most reliable ignition backup on earth. Always carry multiples.",
    asin: "B00004TZK2",
    hasDiagnostic: false,
  },
  {
    id: "ferro_rod",
    name: "Scout 2-pack",
    brand: "Light My Fire",
    category: "fire",
    context: "pack",
    weight_lbs: 0.15,
    description: "Ferrocerium striker. 3000+ strikes. Works wet. Backup for any igniter failure.",
    asin: "B004IH0Z1M",
    hasDiagnostic: false,
  },
  {
    id: "stormproof_matches",
    name: "Stormproof Matches 25ct",
    brand: "UCO",
    category: "fire",
    context: "pack",
    weight_lbs: 0.1,
    description: "Burns 15 seconds in rain and wind. Waterproof case included.",
    asin: "B000P2HBL2",
    hasDiagnostic: false,
  },
  {
    id: "esbit_tabs",
    name: "Solid Fuel Tablets 12-pack",
    brand: "Esbit",
    category: "fire",
    context: "pack",
    weight_lbs: 0.2,
    description: "No-mess hexamine tablets. Last 12 min each. Silent and odorless.",
    asin: "B000G1EJ2C",
    hasDiagnostic: false,
  },

  // ── FIRE / FOOD — vehicle camp cooking & generators ────────────────────────
  {
    id: "jetboil_genesis",
    name: "Genesis Base Camp",
    brand: "Jetboil",
    category: "fire",
    context: "vehicle",
    weight_lbs: 4.0,
    description: "Two-burner camp system. Freestand or vehicle-mounted. Simmer control.",
    asin: "B07ZVQKXQV",
    hasDiagnostic: true,
  },
  {
    id: "honda_eu2200",
    name: "EU2200i Generator",
    brand: "Honda",
    category: "fire",
    context: "vehicle",
    weight_lbs: 46.5,
    description: "2200W inverter generator. 3–8 hour runtime on 0.95 gal. Parallel capable.",
    asin: "B07FBNMK37",
    hasDiagnostic: true,
  },
  {
    id: "champion_3500",
    name: "3500W Dual Fuel Generator",
    brand: "Champion",
    category: "fire",
    context: "vehicle",
    weight_lbs: 119.0,
    description: "Gas or propane. 3500W running / 4000W surge. Electric start.",
    asin: "B01LZ9KLCO",
    hasDiagnostic: true,
  },

  // ── POWER — pack (portable banks only) ────────────────────────────────────
  {
    id: "anker_powerbank_26800",
    name: "PowerCore 26800",
    brand: "Anker",
    category: "power",
    context: "pack",
    weight_lbs: 1.28,
    description: "26800mAh portable battery bank. Dual input charging. 3 USB-A.",
    asin: "B01JIWQPMW",
    hasDiagnostic: false,
  },

  // ── POWER — vehicle (stations, panels, chargers) ──────────────────────────
  {
    id: "ecoflow_delta3",
    name: "DELTA 3 Ultra",
    brand: "EcoFlow",
    category: "power",
    context: "vehicle",
    weight_lbs: 30.9,
    description: "1500Wh LiFePO4. 1500W solar input. 1800W AC output. App control.",
    asin: "B0CXQHX48K",
    hasDiagnostic: true,
  },
  {
    id: "jackery_1000",
    name: "Explorer 1000 v2",
    brand: "Jackery",
    category: "power",
    context: "vehicle",
    weight_lbs: 23.1,
    description: "1070Wh. 1500W AC. 400W solar input. Dual USB-C 100W.",
    asin: "B0CFW1LTX2",
    hasDiagnostic: true,
  },
  {
    id: "goalzero_yeti1000",
    name: "Yeti 1000 Core",
    brand: "Goal Zero",
    category: "power",
    context: "vehicle",
    weight_lbs: 22.0,
    description: "983Wh. 1500W AC surge. 600W solar input. Tank-style build.",
    asin: "B097D3HZ8X",
    hasDiagnostic: false,
  },
  {
    id: "bluetti_ac180",
    name: "AC180",
    brand: "Bluetti",
    category: "power",
    context: "vehicle",
    weight_lbs: 35.3,
    description: "1152Wh LiFePO4. 1800W AC. 500W solar. MC4 direct input.",
    asin: "B0BV3GGCVJ",
    hasDiagnostic: false,
  },
  {
    id: "renogy_200w",
    name: "200W Mono Rigid Panel",
    brand: "Renogy",
    category: "power",
    context: "vehicle",
    weight_lbs: 28.2,
    description: "200W monocrystalline. MC4 connector. Roof or ground mount.",
    asin: "B08CRJYJ22",
    hasDiagnostic: true,
  },
  {
    id: "bougerv_200w",
    name: "200W Flexible Panel",
    brand: "BougeRV",
    category: "power",
    context: "vehicle",
    weight_lbs: 6.8,
    description: "200W flexible mono. RTT and vehicle roof rated. MC4 connector.",
    asin: "B0BW4YTY67",
    hasDiagnostic: true,
  },
  {
    id: "jackery_solarsaga200",
    name: "SolarSaga 200W",
    brand: "Jackery",
    category: "power",
    context: "vehicle",
    weight_lbs: 13.9,
    description: "Portable foldable panel. DC8020 output. Kickstand included.",
    asin: "B09CRPNL8J",
    hasDiagnostic: false,
  },
  {
    id: "renogy_dcc30s",
    name: "DCC30S DC-DC Charger",
    brand: "Renogy",
    category: "power",
    context: "vehicle",
    weight_lbs: 2.4,
    description: "30A dual-input DC-DC charger. Alternator + solar simultaneously.",
    asin: "B093BB3PCV",
    hasDiagnostic: false,
  },

  // ── RECOVERY — all vehicle ─────────────────────────────────────────────────
  {
    id: "warn_zeon",
    name: "Zeon 10-S Winch",
    brand: "Warn",
    category: "recovery",
    context: "vehicle",
    weight_lbs: 56.0,
    description: "10,000 lb synthetic rope winch. Series-wound motor. Industry standard.",
    asin: "B00B7HXOGY",
    hasDiagnostic: true,
  },
  {
    id: "smittybilt_x20",
    name: "X2O 10K Winch",
    brand: "Smittybilt",
    category: "recovery",
    context: "vehicle",
    weight_lbs: 54.0,
    description: "10,000 lb waterproof winch. Synthetic rope. Wireless remote.",
    asin: "B00W78XADG",
    hasDiagnostic: true,
  },
  {
    id: "arb_hilift",
    name: "Hi-Lift Jack 60\"",
    brand: "ARB",
    category: "recovery",
    context: "vehicle",
    weight_lbs: 16.7,
    description: "Cast iron climbing jack. 7,000 lb rating. Also works as a hand winch.",
    asin: "B00004YL1G",
    hasDiagnostic: true,
  },
  {
    id: "maxtrax_mk2",
    name: "MKII Recovery Boards (pair)",
    brand: "Maxtrax",
    category: "recovery",
    context: "vehicle",
    weight_lbs: 10.0,
    description: "High-strength nylon traction boards. Sand, mud, snow. Stackable.",
    asin: "B07FDHBHWL",
    hasDiagnostic: false,
  },
  {
    id: "viair_400c",
    name: "400C Automatic Compressor",
    brand: "VIAIR",
    category: "recovery",
    context: "vehicle",
    weight_lbs: 9.0,
    description: "150 PSI max. 33% duty cycle. Tires up to 35\". Direct battery clamps.",
    asin: "B000MG40YS",
    hasDiagnostic: true,
  },
  {
    id: "recovery_strap",
    name: "20ft Kinetic Recovery Rope",
    brand: "ARB",
    category: "recovery",
    context: "vehicle",
    weight_lbs: 6.0,
    description: "17,600 lb MBS kinetic rope. Stretch absorbs snatch impact.",
    asin: "B001D2WTV0",
    hasDiagnostic: false,
  },
  {
    id: "d_ring_shackles",
    name: "3/4\" D-Ring Shackles (pair)",
    brand: "Bubba Rope",
    category: "recovery",
    context: "vehicle",
    weight_lbs: 2.0,
    description: "4.75-ton WLL screw-pin shackles. Required for most recovery setups.",
    asin: "B008QSXKXY",
    hasDiagnostic: false,
  },

  // ── SHELTER — pack tents/bags ──────────────────────────────────────────────
  {
    id: "msr_hubba",
    name: "Hubba Hubba NX 2P",
    brand: "MSR",
    category: "shelter",
    context: "pack",
    weight_lbs: 3.66,
    description: "3-season 2-person backpacking tent. Freestanding. Full-coverage fly.",
    asin: "B000V9BY0G",
    hasDiagnostic: true,
  },
  {
    id: "kelty_cosmic",
    name: "Cosmic 20°F Down Bag",
    brand: "Kelty",
    category: "shelter",
    context: "pack",
    weight_lbs: 3.0,
    description: "700-fill down sleeping bag. 20°F rated. Zippered footbox.",
    asin: "B07XVT6HB3",
    hasDiagnostic: true,
  },
  {
    id: "thermarest_neoair",
    name: "NeoAir XLite NXT",
    brand: "Therm-a-Rest",
    category: "shelter",
    context: "pack",
    weight_lbs: 0.88,
    description: "Inflatable sleeping pad. R-value 4.5. Ultralight. Includes patch kit.",
    asin: "B093WJKJ99",
    hasDiagnostic: true,
  },
  {
    id: "emergency_bivvy",
    name: "SOL Escape Bivvy",
    brand: "Adventure Medical",
    category: "shelter",
    context: "pack",
    weight_lbs: 0.45,
    description: "Breathable emergency bivy. Reflects 70% body heat. Reusable.",
    asin: "B002B4SQTW",
    hasDiagnostic: false,
  },
  {
    id: "tarp_silnylon",
    name: "SilPoly Tarp 10x10",
    brand: "Aqua Quest",
    category: "shelter",
    context: "pack",
    weight_lbs: 1.7,
    description: "Waterproof silpoly tarp. 15 tie-out points. 3000mm HH.",
    asin: "B01LZCCUWB",
    hasDiagnostic: false,
  },

  // ── SHELTER — vehicle RTTs ─────────────────────────────────────────────────
  {
    id: "ovs_bushveld",
    name: "HD Bushveld II RTT",
    brand: "OVS",
    category: "shelter",
    context: "vehicle",
    weight_lbs: 132.0,
    description: "Hard-shell fold-out RTT. 2-person. All-aluminum frame. Mounts any rack.",
    asin: "",
    hasDiagnostic: false,
  },
  {
    id: "bighorn_rtv",
    name: "3.0 Hardshell RTT",
    brand: "Big Horn",
    category: "shelter",
    context: "vehicle",
    weight_lbs: 165.0,
    description: "Hardshell clamshell RTT. Cross-platform mount. Integrated LED strips.",
    asin: "B09MJCN7MZ",
    hasDiagnostic: true,
  },
  {
    id: "ikamper_skycamp",
    name: "Skycamp 3.0",
    brand: "iKamper",
    category: "shelter",
    context: "vehicle",
    weight_lbs: 132.0,
    description: "4-person hardshell RTT. Opens 180°. 2\" foam mattress.",
    asin: "B09FKPDNF2",
    hasDiagnostic: false,
  },

  // ── COMMS — pack handhelds ─────────────────────────────────────────────────
  {
    id: "baofeng_uv5r",
    name: "UV-5R Dual Band",
    brand: "Baofeng",
    category: "comms",
    context: "pack",
    weight_lbs: 0.33,
    description: "VHF/UHF handheld transceiver. HAM license required for TX. 4W output.",
    asin: "B007H4VT7A",
    hasDiagnostic: false,
  },
  {
    id: "garmin_inreach_mini2",
    name: "inReach Mini 2",
    brand: "Garmin",
    category: "comms",
    context: "pack",
    weight_lbs: 0.22,
    description: "2-way satellite communicator. SOS, tracking, messaging. No cell needed.",
    asin: "B09FKJGZSF",
    hasDiagnostic: false,
  },
  {
    id: "zoleo",
    name: "Zoleo Satellite Communicator",
    brand: "Zoleo",
    category: "comms",
    context: "pack",
    weight_lbs: 0.22,
    description: "2-way satellite + Bluetooth. SOS button. App-connected. $20/mo plan.",
    asin: "B08DWQMKQJ",
    hasDiagnostic: false,
  },
  {
    id: "uniden_bcd325p2",
    name: "BCD325P2 Handheld Scanner",
    brand: "Uniden",
    category: "comms",
    context: "pack",
    weight_lbs: 0.66,
    description: "Digital/analog P25 phase 1+2 scanner. Listen to EMS, fire, local government.",
    asin: "B00IU4B1RG",
    hasDiagnostic: false,
  },
  {
    id: "noaa_weather_radio",
    name: "Emergency Weather Radio",
    brand: "Midland",
    category: "comms",
    context: "pack",
    weight_lbs: 0.7,
    description: "NOAA weather alerts. Hand crank + solar + battery. AM/FM/NOAA.",
    asin: "B0742L3S2J",
    hasDiagnostic: false,
  },

  // ── COMMS — vehicle mounted ────────────────────────────────────────────────
  {
    id: "midland_mxt275",
    name: "MXT275 MicroMobile GMRS",
    brand: "Midland",
    category: "comms",
    context: "vehicle",
    weight_lbs: 1.0,
    description: "15W GMRS mobile radio. No HAM license. 8 repeater channels. Dash-mount.",
    asin: "B01N5MFRKM",
    hasDiagnostic: false,
  },

  // ── MEDICAL — all pack ─────────────────────────────────────────────────────
  {
    id: "cat_tourniquet",
    name: "CAT Gen 7 Tourniquet",
    brand: "North American Rescue",
    category: "medical",
    context: "pack",
    weight_lbs: 0.25,
    description: "Combat Application Tourniquet. #1 used by US military. One-handed application.",
    asin: "B00D9GGQCU",
    hasDiagnostic: false,
  },
  {
    id: "israeli_bandage",
    name: "Emergency Bandage 6\"",
    brand: "Persys Medical",
    category: "medical",
    context: "pack",
    weight_lbs: 0.35,
    description: "Compression bandage. One-handed self-application. Pressure bar design.",
    asin: "B002MTUVY4",
    hasDiagnostic: false,
  },
  {
    id: "quikclot_gauze",
    name: "Combat Gauze 3\"×4yd",
    brand: "QuikClot",
    category: "medical",
    context: "pack",
    weight_lbs: 0.25,
    description: "Hemostatic gauze. Kaolin-treated. Stops life-threatening bleeding.",
    asin: "B07XQN6GD5",
    hasDiagnostic: false,
  },
  {
    id: "sam_splint",
    name: "SAM Splint 36\"",
    brand: "SAM Medical",
    category: "medical",
    context: "pack",
    weight_lbs: 0.25,
    description: "Padded aluminum splint. Molds to any fracture. Reusable.",
    asin: "B000EVWJPK",
    hasDiagnostic: false,
  },
  {
    id: "wilderness_fa_kit",
    name: "Weekender First Aid Kit",
    brand: "Adventure Medical",
    category: "medical",
    context: "pack",
    weight_lbs: 1.0,
    description: "48-piece kit. Wound care, blister, meds, irrigation. Waterproof case.",
    asin: "B00CEXD59O",
    hasDiagnostic: false,
  },
  {
    id: "nasopharyngeal",
    name: "NPA Kit 28FR",
    brand: "Bound Tree",
    category: "medical",
    context: "pack",
    weight_lbs: 0.1,
    description: "Nasopharyngeal airway. Maintains airway in unconscious patient.",
    asin: "B07P3VVFML",
    hasDiagnostic: false,
  },
  {
    id: "chest_seal",
    name: "Hyfin Chest Seal Twin Pack",
    brand: "North American Rescue",
    category: "medical",
    context: "pack",
    weight_lbs: 0.15,
    description: "Vented chest seal. One-way valve. Prevents tension pneumothorax.",
    asin: "B00GDMAPX6",
    hasDiagnostic: false,
  },

  // ── NAVIGATION — all pack ──────────────────────────────────────────────────
  {
    id: "garmin_gpsmap67",
    name: "GPSMAP 67",
    brand: "Garmin",
    category: "navigation",
    context: "pack",
    weight_lbs: 0.37,
    description: "Multi-band GPS/GLONASS/Galileo. TopoActive maps. 36-hr battery. IPX7.",
    asin: "B09Z31CCWM",
    hasDiagnostic: false,
  },
  {
    id: "suunto_a10",
    name: "A-10 Baseplate Compass",
    brand: "Suunto",
    category: "navigation",
    context: "pack",
    weight_lbs: 0.06,
    description: "Classic baseplate compass. Declination adjustment. Works without batteries.",
    asin: "B000FIE4UY",
    hasDiagnostic: false,
  },
  {
    id: "gaia_offline",
    name: "Gaia GPS Pro (offline maps)",
    brand: "Gaia",
    category: "navigation",
    context: "pack",
    weight_lbs: 0.0,
    description: "App subscription. Download topo maps offline. National forests, BLM, USGS.",
    asin: "",
    hasDiagnostic: false,
  },
  {
    id: "delorme_atlas",
    name: "DeLorme Atlas (state)",
    brand: "DeLorme",
    category: "navigation",
    context: "pack",
    weight_lbs: 1.5,
    description: "Spiral-bound state topo atlas. Detailed backroads, trails, and terrain.",
    asin: "",
    hasDiagnostic: false,
  },
  {
    id: "glowring",
    name: "GlowRing Tritium Compass",
    brand: "TruArc",
    category: "navigation",
    context: "pack",
    weight_lbs: 0.3,
    description: "Luminous compass ring. No batteries. Always-on tritium illumination.",
    asin: "B075WT3MXW",
    hasDiagnostic: false,
  },

  // ── TOOLS / EDC — all pack ─────────────────────────────────────────────────
  {
    id: "leatherman_wave",
    name: "Wave+ Multi-tool",
    brand: "Leatherman",
    category: "tools",
    context: "pack",
    weight_lbs: 0.53,
    description: "18 tools. Locking blades. Needlenose pliers. Bit driver. 25yr warranty.",
    asin: "B0BMHPB5W9",
    hasDiagnostic: false,
  },
  {
    id: "gerber_mp600",
    name: "MP600 Multi-Plier",
    brand: "Gerber",
    category: "tools",
    context: "pack",
    weight_lbs: 0.47,
    description: "Butterfly opening pliers. One-hand tool deployment. Military-spec build.",
    asin: "B00004YTHB",
    hasDiagnostic: false,
  },
  {
    id: "mora_companion",
    name: "Companion Fixed Blade",
    brand: "Mora",
    category: "tools",
    context: "pack",
    weight_lbs: 0.19,
    description: "4.1\" stainless blade. Scandinavian grind. Best budget fixed blade on earth.",
    asin: "B001IDVMKM",
    hasDiagnostic: false,
  },
  {
    id: "esee_4",
    name: "ESEE-4 Fixed Blade",
    brand: "ESEE",
    category: "tools",
    context: "pack",
    weight_lbs: 0.44,
    description: "1095 carbon steel. Full tang. Lifetime guarantee. Built for serious field use.",
    asin: "B001TLUR98",
    hasDiagnostic: false,
  },
  {
    id: "gorilla_tape",
    name: "Gorilla Tape 1.88\"×35yd",
    brand: "Gorilla",
    category: "tools",
    context: "pack",
    weight_lbs: 0.88,
    description: "Double-thick adhesive. Works on rough and uneven surfaces. Waterproof.",
    asin: "B001IPGMQ4",
    hasDiagnostic: false,
  },
  {
    id: "paracord_100",
    name: "550 Paracord 100ft",
    brand: "Atwood",
    category: "tools",
    context: "pack",
    weight_lbs: 0.5,
    description: "Type III 550 paracord. 7-strand inner core. MIL-C-5040H spec.",
    asin: "B008STIJWA",
    hasDiagnostic: false,
  },
  {
    id: "zipties_50",
    name: "Cable Ties 50-pack",
    brand: "Gardner Bender",
    category: "tools",
    context: "pack",
    weight_lbs: 0.2,
    description: "Heavy-duty 11\" zip ties. UV resistant. Reusable with a knife.",
    asin: "B0000AW1EJ",
    hasDiagnostic: false,
  },
  {
    id: "headlamp_black_diamond",
    name: "Spot 400 Headlamp",
    brand: "Black Diamond",
    category: "tools",
    context: "pack",
    weight_lbs: 0.2,
    description: "400 lumen max. Red night vision mode. IPX8 waterproof. AAA batteries.",
    asin: "B08GF5XG4L",
    hasDiagnostic: false,
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

export function getItemsByCategory(category: GoBagCategory): GoBagItem[] {
  return gearDatabase.filter((i) => i.category === category);
}

export function getItemsByContext(context: "pack" | "vehicle"): GoBagItem[] {
  return gearDatabase.filter((i) => i.context === context);
}

export function getItemById(id: string): GoBagItem | undefined {
  return gearDatabase.find((i) => i.id === id);
}

export function getTotalWeight(itemIds: string[]): number {
  return itemIds.reduce((sum, id) => {
    const item = getItemById(id);
    return sum + (item?.weight_lbs ?? 0);
  }, 0);
}
