// ─── Overland Load Balancer — Gear Database ──────────────────────────────────
// Pre-built library of overlanding gear items with real-world weights and
// sensible default placement zones.
// Sources: manufacturer specs, Amazon listings — March 2026
// ─────────────────────────────────────────────────────────────────────────────

import type { GearItem } from "./load-balancer-compute";

export const GEAR_LIBRARY: GearItem[] = [

  // ── SHELTER ────────────────────────────────────────────────────────────────

  {
    id: "ikamper-skycamp-3",
    name: "iKamper Skycamp 3.0 (2–3P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 154,
    unit: "item",
    asin: "B0CB6RX4RT",
    notes: "Hard-shell RTT, 1-min setup",
  },
  {
    id: "roofnest-falcon-2",
    name: "Roofnest Falcon 2 (2P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 138,
    unit: "item",
    asin: "B0CJCWY2DN",
  },
  {
    id: "arb-simpson-iii",
    name: "ARB Simpson III (2P Soft Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 110,
    unit: "item",
    asin: "B001RDLGG6",
  },
  {
    id: "smittybilt-overlander",
    name: "Smittybilt Overlander Soft Shell RTT",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 126,
    unit: "item",
    notes: "Budget soft-shell RTT",
  },
  {
    id: "ground-tent-2p",
    name: "2-Person Ground Tent",
    category: "shelter",
    defaultZone: "bed-rear",
    weightPerUnit: 5.5,
    unit: "item",
  },
  {
    id: "ground-tent-4p",
    name: "4-Person Family Tent",
    category: "shelter",
    defaultZone: "bed-rear",
    weightPerUnit: 12,
    unit: "item",
  },
  {
    id: "sleeping-bag",
    name: "Sleeping Bag (3-season, each)",
    category: "shelter",
    defaultZone: "cab",
    weightPerUnit: 2.5,
    unit: "item",
  },
  {
    id: "sleeping-pad",
    name: "Sleeping Pad (self-inflating, each)",
    category: "shelter",
    defaultZone: "cab",
    weightPerUnit: 2,
    unit: "item",
  },
  {
    id: "arb-awning-270",
    name: "ARB 270° Awning (full enclosure kit)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 55,
    unit: "item",
    notes: "Attaches to rack side rail; includes walls",
  },
  {
    id: "side-awning",
    name: "Side Awning 8×6.5 ft",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 18,
    unit: "item",
  },

  // ── RECOVERY ───────────────────────────────────────────────────────────────

  {
    id: "hi-lift-48",
    name: "Hi-Lift 48\" Jack (HL484)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 17.5,
    unit: "item",
    asin: "B00005RBAT",
  },
  {
    id: "hi-lift-60",
    name: "Hi-Lift 60\" Jack (HL606)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 27.5,
    unit: "item",
    asin: "B0053GNQUA",
  },
  {
    id: "maxtrax-mkii",
    name: "MaxTrax MKII Traction Boards (pair)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 14.3,
    unit: "item",
    asin: "B07BNLKQZW",
  },
  {
    id: "traction-boards-generic",
    name: "Generic Traction Boards / Sand Ladders (pair)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 17,
    unit: "item",
    notes: "45\" HDPE boards",
  },
  {
    id: "warn-vr-evo-10s",
    name: "WARN VR EVO 10-S Winch (10,000 lb)",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 57,
    unit: "item",
    notes: "Front bumper-mounted; weight shifts to front axle",
  },
  {
    id: "kinetic-rope-30",
    name: "Kinetic Recovery Rope 7/8\" × 30 ft",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 4.5,
    unit: "item",
  },
  {
    id: "tow-strap",
    name: "Recovery Tow Strap 3\" × 20 ft",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 3.5,
    unit: "item",
  },
  {
    id: "snatch-block",
    name: "Snatch Block 8-ton",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 4.2,
    unit: "item",
  },
  {
    id: "d-ring-shackles",
    name: "D-Ring Shackles 3/4\" (pair)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "tree-saver-strap",
    name: "Tree Saver Strap 3\" × 8 ft",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 2,
    unit: "item",
  },
  {
    id: "arb-compressor",
    name: "ARB Twin Compressor CKMTA12",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 4.6,
    unit: "item",
    asin: "B01LYQYXBP",
    notes: "Portable; often under-hood or cab-mounted",
  },
  {
    id: "viair-400p",
    name: "Viair 400P Portable Compressor",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 6.5,
    unit: "item",
  },
  {
    id: "shovel-folding",
    name: "Folding Shovel (e-tool)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "shovel-long",
    name: "Full-Size Recovery Shovel",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 3.5,
    unit: "item",
  },
  {
    id: "fire-extinguisher",
    name: "Fire Extinguisher 2.5 lb ABC",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 4,
    unit: "item",
    notes: "Required on many trail systems",
  },

  // ── WATER & FUEL ───────────────────────────────────────────────────────────

  {
    id: "nato-jerry-water-5gal",
    name: "NATO Jerry Can 5-gal — Water (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 46,
    unit: "item",
    notes: "Steel can (~4.5 lb) + 5 gal × 8.34 lb/gal",
  },
  {
    id: "nato-jerry-fuel-5gal",
    name: "NATO Jerry Can 5-gal — Fuel (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 39,
    unit: "item",
    notes: "Steel can (~8 lb) + 5 gal × 6.1 lb/gal",
  },
  {
    id: "rotopax-2gal-water",
    name: "Rotopax 2-gal Water Pack (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 20,
    unit: "item",
    notes: "Stackable; mounts to rack or trail door",
  },
  {
    id: "rotopax-2gal-fuel",
    name: "Rotopax 2-gal Fuel Pack (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 15.5,
    unit: "item",
  },
  {
    id: "scepter-5gal-fuel",
    name: "Scepter 5-gal Military Fuel Can (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 39,
    unit: "item",
  },
  {
    id: "aquatainer-7gal",
    name: "Reliance Aqua-Tainer 7-gal (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 60,
    unit: "item",
  },
  {
    id: "water-bladder-4gal",
    name: "4-gal Collapsible Water Bladder (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 34,
    unit: "item",
  },

  // ── POWER ──────────────────────────────────────────────────────────────────

  {
    id: "jackery-1000-plus",
    name: "Jackery Explorer 1000 Plus (1264Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 25.4,
    unit: "item",
    asin: "B0CFVBGWBT",
  },
  {
    id: "goal-zero-yeti-1000-core",
    name: "Goal Zero Yeti 1000 Core (983Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 22,
    unit: "item",
    asin: "B08FX3S5LF",
  },
  {
    id: "bluetti-ac200max",
    name: "Bluetti AC200MAX (2048Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 61.7,
    unit: "item",
    asin: "B09GKCH4CW",
  },
  {
    id: "ecoflow-delta-3-ultra",
    name: "EcoFlow DELTA 3 Ultra (4096Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 79,
    unit: "item",
    asin: "B0FT32MCM9",
  },
  {
    id: "battle-born-100ah",
    name: "Battle Born 100Ah LiFePO4 Battery",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 31,
    unit: "item",
    notes: "Auxiliary house battery",
  },
  {
    id: "renogy-200w-solar-portable",
    name: "Renogy 200W Portable Solar Panel (folding)",
    category: "power",
    defaultZone: "bed-rear",
    weightPerUnit: 10.6,
    unit: "item",
    asin: "B0CNPHD4VY",
  },
  {
    id: "solar-panel-rigid-100w",
    name: "Rigid Roof Solar Panel 100W",
    category: "power",
    defaultZone: "roof",
    weightPerUnit: 14.5,
    unit: "item",
    notes: "Mounted to roof rack; typical 100W monocrystalline",
  },

  // ── KITCHEN ────────────────────────────────────────────────────────────────

  {
    id: "dometic-cfx3-55im",
    name: "Dometic CFX3 55IM Fridge/Freezer",
    category: "kitchen",
    defaultZone: "bed-front",
    weightPerUnit: 40,
    unit: "item",
    asin: "B085MM9B2D",
  },
  {
    id: "arb-fridge-50qt",
    name: "ARB Classic Series II Fridge 50qt",
    category: "kitchen",
    defaultZone: "bed-front",
    weightPerUnit: 59,
    unit: "item",
    asin: "B07Q75PB68",
  },
  {
    id: "yeti-tundra-65",
    name: "YETI Tundra 65 Hard Cooler (empty)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 29,
    unit: "item",
    notes: "Add ice/food weight separately",
  },
  {
    id: "coleman-cooler-54qt",
    name: "Coleman 54-qt Cooler (empty)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 15,
    unit: "item",
  },
  {
    id: "ice-per-bag",
    name: "Bagged Ice (10-lb bag)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 10,
    unit: "item",
  },
  {
    id: "camp-chef-explorer-2x",
    name: "Camp Chef Explorer 2X Two-Burner Stove",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 22,
    unit: "item",
    asin: "B0006VORDY",
  },
  {
    id: "biolite-campstove-2",
    name: "BioLite CampStove 2+",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 2.1,
    unit: "item",
    asin: "B0C31B18Y2",
  },
  {
    id: "propane-1lb",
    name: "1-lb Propane Canister",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 1.65,
    unit: "item",
  },
  {
    id: "propane-20lb",
    name: "20-lb Propane Tank (full)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 37.5,
    unit: "item",
    notes: "~17 lb gas + ~20 lb tare",
  },
  {
    id: "cast-iron-skillet",
    name: "Cast Iron Skillet 10\"",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 5.2,
    unit: "item",
  },
  {
    id: "camp-cookset",
    name: "Camp Cookset (4-person)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 3.5,
    unit: "item",
  },
  {
    id: "solo-stove-ranger",
    name: "Solo Stove Ranger 2.0 Fire Pit",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 15,
    unit: "item",
    asin: "B0B7BG9YPW",
  },
  {
    id: "folding-camp-table",
    name: "Folding Camp Table",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 9,
    unit: "item",
  },
  {
    id: "camp-chair",
    name: "Camp Chair (each)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 5,
    unit: "item",
  },

  // ── MEDICAL ────────────────────────────────────────────────────────────────

  {
    id: "ifak",
    name: "IFAK (Individual First Aid Kit)",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "trauma-kit",
    name: "Trauma / Bleeding Control Kit",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 2.5,
    unit: "item",
  },
  {
    id: "first-aid-kit-large",
    name: "Large Group First Aid Kit",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 4,
    unit: "item",
  },
  {
    id: "medications",
    name: "Medications & Prescriptions (30-day supply)",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 1,
    unit: "item",
  },
  {
    id: "snake-bite-kit",
    name: "Snakebite / Venom Extractor Kit",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 0.3,
    unit: "item",
  },

  // ── COMMS ──────────────────────────────────────────────────────────────────

  {
    id: "garmin-inreach-mini",
    name: "Garmin inReach Mini 3 Plus",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 0.24,
    unit: "item",
    asin: "B0G4RST8LV",
  },
  {
    id: "midland-gmrs-pair",
    name: "Midland GXT1000VP4 GMRS Radio (pair)",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 0.9,
    unit: "item",
    asin: "B001WMFYH4",
  },
  {
    id: "baofeng-uv5r",
    name: "Baofeng UV-5R Handheld Radio",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 0.29,
    unit: "item",
    asin: "B074XPB313",
  },
  {
    id: "cb-radio",
    name: "CB Radio (dash-mounted, incl. mount/antenna)",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 1.5,
    unit: "item",
    notes: "40-channel; common for convoy use",
  },

  // ── NAVIGATION ─────────────────────────────────────────────────────────────

  {
    id: "garmin-gpsmap-67",
    name: "Garmin GPSMAP 67 Handheld GPS",
    category: "navigation",
    defaultZone: "cab",
    weightPerUnit: 0.37,
    unit: "item",
  },
  {
    id: "paper-atlas",
    name: "Paper Maps / Road Atlas",
    category: "navigation",
    defaultZone: "cab",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "tablet-nav",
    name: "Tablet with Nav App (iPad / Android + case)",
    category: "navigation",
    defaultZone: "cab",
    weightPerUnit: 1.2,
    unit: "item",
    notes: "OnX Offroad, Gaia GPS, etc.",
  },

  // ── CLOTHING ───────────────────────────────────────────────────────────────

  {
    id: "clothing-duffel",
    name: "Clothing Duffel (per person, 5-day trip)",
    category: "clothing",
    defaultZone: "cab",
    weightPerUnit: 15,
    unit: "item",
  },
  {
    id: "clothing-cold-weather",
    name: "Cold-Weather Gear Bag (per person)",
    category: "clothing",
    defaultZone: "cab",
    weightPerUnit: 8,
    unit: "item",
    notes: "Insulated jacket, heavy layers, boots",
  },
  {
    id: "waders-hip",
    name: "Hip Waders / Chest Waders",
    category: "clothing",
    defaultZone: "bed-rear",
    weightPerUnit: 4,
    unit: "item",
  },

  // ── TOOLS ──────────────────────────────────────────────────────────────────

  {
    id: "chainsaw-battery",
    name: "Battery Chainsaw 12\" Bar",
    category: "tools",
    defaultZone: "bed-rear",
    weightPerUnit: 7,
    unit: "item",
    notes: "Trail clearing; e.g. STIHL MSA 220C",
  },
  {
    id: "axe-full",
    name: "Full-Size Axe / Splitting Maul",
    category: "tools",
    defaultZone: "bed-rear",
    weightPerUnit: 3.8,
    unit: "item",
  },
  {
    id: "hatchet",
    name: "Camp Hatchet",
    category: "tools",
    defaultZone: "cab",
    weightPerUnit: 1.75,
    unit: "item",
  },
  {
    id: "tool-roll",
    name: "Vehicle Tool Roll (sockets, wrenches, pliers)",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 8,
    unit: "item",
  },
  {
    id: "floor-jack-3t",
    name: "3-Ton Aluminum Floor Jack",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 42,
    unit: "item",
    notes: "Base camp; most leave at home for remote trips",
  },
  {
    id: "jumper-cables",
    name: "Jumper Cables 20 ft 4-gauge",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 4.5,
    unit: "item",
  },
  {
    id: "socket-set",
    name: "Socket & Ratchet Set (3/8\" + 1/2\")",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 6,
    unit: "item",
  },
  {
    id: "multitool",
    name: "Multi-Tool (Leatherman Wave+)",
    category: "tools",
    defaultZone: "cab",
    weightPerUnit: 0.52,
    unit: "item",
  },

  // ── OTHER ──────────────────────────────────────────────────────────────────

  {
    id: "roof-rack-platform",
    name: "Roof Rack / Platform Rack (steel)",
    category: "other",
    defaultZone: "roof",
    weightPerUnit: 55,
    unit: "item",
    notes: "Aluminum racks ~28–35 lbs; steel ~50–70 lbs",
  },
  {
    id: "bed-drawer-system",
    name: "Truck Bed Drawer System",
    category: "other",
    defaultZone: "bed-front",
    weightPerUnit: 90,
    unit: "item",
    notes: "E.g. ARB Roller Drawer; aluminum ~65 lbs",
  },
  {
    id: "roof-basket",
    name: "Roof Cargo Basket",
    category: "other",
    defaultZone: "roof",
    weightPerUnit: 38,
    unit: "item",
  },
  {
    id: "hitch-cargo-carrier",
    name: "Receiver Hitch Cargo Carrier 2\"",
    category: "other",
    defaultZone: "hitch",
    weightPerUnit: 35,
    unit: "item",
    notes: "Adds tongue weight; rate carrier + cargo separately",
  },
  {
    id: "spare-tire-35",
    name: "Full-Size Spare Tire 35\" (e.g. BFG KO2)",
    category: "other",
    defaultZone: "bed-rear",
    weightPerUnit: 65,
    unit: "item",
    notes: "Bed/bumper-mounted; stock under-bed spare ≈ 35–45 lbs",
  },
  {
    id: "rear-bumper-tire-carrier",
    name: "Steel Rear Bumper w/ Swing Tire Carrier",
    category: "other",
    defaultZone: "hitch",
    weightPerUnit: 125,
    unit: "item",
    notes: "Adds significant tongue/rear weight; shifts CG rearward",
  },
  {
    id: "skid-plate-set",
    name: "Full Skid Plate Set (engine, transfer, fuel)",
    category: "other",
    defaultZone: "cab",
    weightPerUnit: 55,
    unit: "item",
    notes: "Under-vehicle; treated as cab zone for axle math",
  },
  {
    id: "dog-large",
    name: "Dog — Large Breed (update to actual weight)",
    category: "other",
    defaultZone: "cab",
    weightPerUnit: 80,
    unit: "item",
    notes: "Rear seat; default 80 lb — adjust to your dog",
  },
  {
    id: "dog-medium",
    name: "Dog — Medium Breed (update to actual weight)",
    category: "other",
    defaultZone: "cab",
    weightPerUnit: 42,
    unit: "item",
  },
];

/** Alias export — matches the import name used in LoadBalancer.tsx */
export const gearItems = GEAR_LIBRARY;
