// ─── Overland Load Balancer — Gear Database ──────────────────────────────────
// Pre-built library of overlanding gear items with real-world weights and
// sensible default placement zones.
// Sources: manufacturer specs, Amazon listings — March 2026
// ─────────────────────────────────────────────────────────────────────────────

import type { GearItem } from "./load-balancer-compute";

export const GEAR_LIBRARY: GearItem[] = [

  // ── SHELTER — Hard Shell RTTs ──────────────────────────────────────────────

  {
    id: "ovs-hd-bushveld",
    name: "OVS HD Bushveld Hard Shell RTT (2P)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 155,
    unit: "item",
    notes: "Hard-shell aluminum RTT; OVS flagship",
  },
  {
    id: "ikamper-skycamp-3",
    name: "iKamper Skycamp 3.0 (2–3P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 154,
    unit: "item",
    asin: "B0CB6RX4RT",
    notes: "Hard-shell RTT, 1-min setup",
  },
  {
    id: "ikamper-skycamp-mini",
    name: "iKamper Skycamp Mini 02 (1–2P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 115,
    unit: "item",
    notes: "Compact hard-shell; fits trucks and smaller rigs",
  },
  {
    id: "roofnest-falcon-2",
    name: "Roofnest Falcon 2 (2P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 138,
    unit: "item",
    asin: "B0CJCWY2DN",
  },
  {
    id: "roofnest-sparrow-eye",
    name: "Roofnest Sparrow Eye (2P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 120,
    unit: "item",
    notes: "Mid-size hard-shell; popular truck/SUV option",
  },
  {
    id: "roofnest-condor",
    name: "Roofnest Condor (3–4P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 175,
    unit: "item",
    notes: "Family-size hard-shell RTT",
  },
  {
    id: "23zero-armadillo-x2",
    name: "23Zero Armadillo X2 (2P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 139,
    unit: "item",
    notes: "Aluminum hard-shell; Australian brand",
  },
  {
    id: "freespirit-high-country",
    name: "Freespirit Recreation High Country Edition RTT",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 132,
    unit: "item",
    notes: "Budget-friendly hard-shell option",
  },
  {
    id: "james-baroud-evasion",
    name: "James Baroud Evasion (2P Hard Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 145,
    unit: "item",
    notes: "French hard-shell; premium build quality",
  },

  // ── SHELTER — Soft Shell RTTs ──────────────────────────────────────────────

  {
    id: "ovs-bushveld-soft",
    name: "OVS Bushveld Soft Shell RTT (2P)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 126,
    unit: "item",
    notes: "OVS soft-shell; lower profile than HD",
  },
  {
    id: "arb-simpson-iii",
    name: "ARB Simpson III (2P Soft Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 110,
    unit: "item",
    asin: "B001RDLGG6",
  },
  {
    id: "smittybilt-overlander",
    name: "Smittybilt Overlander Soft Shell RTT",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 126,
    unit: "item",
    notes: "Budget soft-shell RTT",
  },
  {
    id: "ikamper-x-cover",
    name: "iKamper X-Cover 2.0 (2P Soft Shell RTT)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 110,
    unit: "item",
    notes: "Soft-shell with integrated annex system",
  },
  {
    id: "tepui-autana-3",
    name: "Tepui Autana 3 Soft Shell RTT (3P)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 145,
    unit: "item",
    notes: "Family-size soft-shell; Thule brand",
  },
  {
    id: "tepui-kukenam-3",
    name: "Tepui Explorer Kukenam 3 Soft Shell RTT",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 154,
    unit: "item",
    notes: "3P soft-shell; aluminum base",
  },
  {
    id: "yakima-skyrise-hd-m",
    name: "Yakima SkyRise HD Medium Soft Shell RTT (2P)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 85,
    unit: "item",
    notes: "Lighter soft-shell; good budget option",
  },
  {
    id: "cvt-mt-mckinley",
    name: "CVT Mt. McKinley 1800 Soft Shell RTT (2P)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 116,
    unit: "item",
    notes: "Lifetime warranty; US brand",
  },
  {
    id: "tuff-stuff-alpha-ii",
    name: "Tuff Stuff Alpha II Overland RTT (2P)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 110,
    unit: "item",
    notes: "Budget soft-shell with annex included",
  },
  {
    id: "23zero-latitude-soft",
    name: "23Zero Latitude 83 Soft Shell RTT (2P)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 104,
    unit: "item",
  },

  // ── SHELTER — Awnings & Annexes ────────────────────────────────────────────

  {
    id: "arb-awning-270",
    name: "ARB 270° Awning (base unit)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 35,
    unit: "item",
    notes: "Driver or passenger side; add walls separately",
  },
  {
    id: "270-awning-walls",
    name: "270° Awning Walls / Enclosure Kit",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 22,
    unit: "item",
    notes: "Side walls for 270° awning; brands vary",
  },
  {
    id: "side-awning",
    name: "Side Awning 8×6.5 ft",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 18,
    unit: "item",
  },
  {
    id: "front-runner-awning",
    name: "Front Runner 2m Awning",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 22,
    unit: "item",
    notes: "Side-mount rack awning with LED strip option",
  },
  {
    id: "rtt-annex-room",
    name: "RTT Annex Room / Vestibule (generic)",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 18,
    unit: "item",
    notes: "Ground-level annex attaches below RTT ladder",
  },
  {
    id: "ovs-annex-room",
    name: "OVS Annex Room",
    category: "shelter",
    defaultZone: "roof",
    weightPerUnit: 22,
    unit: "item",
    notes: "OVS-specific annex; privacy room + changing area",
  },
  {
    id: "shower-privacy-tent",
    name: "Portable Shower / Privacy Tent",
    category: "shelter",
    defaultZone: "bed-rear",
    weightPerUnit: 3.5,
    unit: "item",
    notes: "Pop-up enclosure for camp shower or changing",
  },

  // ── SHELTER — Ground & Sleep ───────────────────────────────────────────────

  {
    id: "ground-tent-2p",
    name: "2-Person Ground Tent",
    category: "shelter",
    defaultZone: "bed-rear",
    weightPerUnit: 5.5,
    unit: "item",
  },
  {
    id: "ground-tent-4p",
    name: "4-Person Family Tent",
    category: "shelter",
    defaultZone: "bed-rear",
    weightPerUnit: 12,
    unit: "item",
  },
  {
    id: "sleeping-bag",
    name: "Sleeping Bag (3-season, each)",
    category: "shelter",
    defaultZone: "cab",
    weightPerUnit: 2.5,
    unit: "item",
  },
  {
    id: "sleeping-bag-winter",
    name: "Sleeping Bag (Winter / -20°F, each)",
    category: "shelter",
    defaultZone: "cab",
    weightPerUnit: 5,
    unit: "item",
    notes: "Cold weather rated; significantly heavier than 3-season",
  },
  {
    id: "sleeping-pad",
    name: "Sleeping Pad (self-inflating, each)",
    category: "shelter",
    defaultZone: "cab",
    weightPerUnit: 2,
    unit: "item",
  },
  {
    id: "hammock",
    name: "Hammock (ENO DoubleNest or similar, each)",
    category: "shelter",
    defaultZone: "cab",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "overland-ground-mat",
    name: "Overland Ground Mat / Outdoor Rug",
    category: "shelter",
    defaultZone: "bed-rear",
    weightPerUnit: 5,
    unit: "item",
    notes: "Camp mat under awning; keeps dirt/mud out of rig",
  },

  // ── RECOVERY ───────────────────────────────────────────────────────────────

  {
    id: "hi-lift-48",
    name: "Hi-Lift 48\" Jack (HL484)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 17.5,
    unit: "item",
    asin: "B00005RBAT",
  },
  {
    id: "hi-lift-60",
    name: "Hi-Lift 60\" Jack (HL606)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 27.5,
    unit: "item",
    asin: "B0053GNQUA",
  },
  {
    id: "maxtrax-mkii",
    name: "MaxTrax MKII Traction Boards (pair)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 14.3,
    unit: "item",
    asin: "B07BNLKQZW",
  },
  {
    id: "traction-boards-generic",
    name: "Generic Traction Boards / Sand Ladders (pair)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 17,
    unit: "item",
    notes: "45\" HDPE boards",
  },
  {
    id: "warn-vr-evo-10s",
    name: "WARN VR EVO 10-S Winch (10,000 lb)",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 57,
    unit: "item",
    notes: "Front bumper-mounted; weight shifts to front axle",
  },
  {
    id: "kinetic-rope-30",
    name: "Kinetic Recovery Rope 7/8\" × 30 ft",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 4.5,
    unit: "item",
  },
  {
    id: "tow-strap",
    name: "Recovery Tow Strap 3\" × 20 ft",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 3.5,
    unit: "item",
  },
  {
    id: "snatch-block",
    name: "Snatch Block 8-ton",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 4.2,
    unit: "item",
  },
  {
    id: "d-ring-shackles",
    name: "D-Ring Shackles 3/4\" (pair)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "tree-saver-strap",
    name: "Tree Saver Strap 3\" × 8 ft",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 2,
    unit: "item",
  },
  {
    id: "arb-compressor",
    name: "ARB Twin Compressor CKMTA12",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 4.6,
    unit: "item",
    asin: "B01LYQYXBP",
    notes: "Portable; often under-hood or cab-mounted",
  },
  {
    id: "viair-400p",
    name: "Viair 400P Portable Compressor",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 6.5,
    unit: "item",
  },
  {
    id: "shovel-folding",
    name: "Folding Shovel (e-tool)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "shovel-long",
    name: "Full-Size Recovery Shovel",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 3.5,
    unit: "item",
  },
  {
    id: "fire-extinguisher",
    name: "Fire Extinguisher 2.5 lb ABC",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 4,
    unit: "item",
    notes: "Required on many trail systems",
  },
  {
    id: "warn-zeon-10s",
    name: "WARN Zeon 10-S Winch (10,000 lb)",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 57,
    unit: "item",
    notes: "Premium steel-cable winch; front bumper-mounted",
  },
  {
    id: "smittybilt-x2o-10k",
    name: "Smittybilt X2O 10,000 lb Winch",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 54,
    unit: "item",
    notes: "Waterproof-rated; popular budget winch",
  },
  {
    id: "deadman-anchor",
    name: "Deadman / Mantis Ground Anchor",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 8,
    unit: "item",
    notes: "For winching in sandless terrain without a tree",
  },
  {
    id: "pull-pal",
    name: "Pull-Pal Land Anchor (sand/mud)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 25,
    unit: "item",
    notes: "Self-deploying anchor for sand, mud, snow",
  },
  {
    id: "staun-deflators",
    name: "Staun Tire Deflators (set of 4)",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 0.5,
    unit: "item",
    notes: "Preset to target PSI; faster than gauge deflation",
  },
  {
    id: "noco-gb70",
    name: "NOCO Boost HD GB70 Jump Starter",
    category: "recovery",
    defaultZone: "cab",
    weightPerUnit: 3,
    unit: "item",
    asin: "B07VBXHZWN",
    notes: "2000A; starts diesels up to 8L",
  },
  {
    id: "recovery-gear-bag",
    name: "Recovery Gear Bag (organized kit)",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 25,
    unit: "item",
    notes: "All-in-one bag: straps, shackles, gloves, block",
  },
  {
    id: "traction-board-bag",
    name: "Traction Board Storage Bag",
    category: "recovery",
    defaultZone: "bed-rear",
    weightPerUnit: 2,
    unit: "item",
    notes: "Keeps MaxTrax / traction boards clean and contained",
  },

  // ── WATER & FUEL ───────────────────────────────────────────────────────────

  {
    id: "nato-jerry-water-5gal",
    name: "NATO Jerry Can 5-gal — Water (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 46,
    unit: "item",
    notes: "Steel can (~4.5 lb) + 5 gal × 8.34 lb/gal",
  },
  {
    id: "nato-jerry-fuel-5gal",
    name: "NATO Jerry Can 5-gal — Fuel (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 39,
    unit: "item",
    notes: "Steel can (~8 lb) + 5 gal × 6.1 lb/gal",
  },
  {
    id: "rotopax-2gal-water",
    name: "Rotopax 2-gal Water Pack (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 20,
    unit: "item",
    notes: "Stackable; mounts to rack or trail door",
  },
  {
    id: "rotopax-2gal-fuel",
    name: "Rotopax 2-gal Fuel Pack (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 15.5,
    unit: "item",
  },
  {
    id: "scepter-5gal-fuel",
    name: "Scepter 5-gal Military Fuel Can (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 39,
    unit: "item",
  },
  {
    id: "aquatainer-7gal",
    name: "Reliance Aqua-Tainer 7-gal (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 60,
    unit: "item",
  },
  {
    id: "water-bladder-4gal",
    name: "4-gal Collapsible Water Bladder (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 34,
    unit: "item",
  },
  {
    id: "water-bladder-60gal-empty",
    name: "60-gal Rugged Water Bladder (empty)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 12,
    unit: "item",
    notes: "Fill at camp or before leaving; full = ~510 lbs — add water weight separately",
  },
  {
    id: "water-bladder-60gal-full",
    name: "60-gal Rugged Water Bladder (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 512,
    unit: "item",
    notes: "WARNING: 510 lbs of water alone — verify payload before loading",
  },
  {
    id: "water-tank-30gal-full",
    name: "30-gal Underbody / Bed Water Tank (full)",
    category: "water-fuel",
    defaultZone: "bed-front",
    weightPerUnit: 257,
    unit: "item",
    notes: "Mounted tank; 30 gal × 8.34 lb + ~7 lb tank",
  },
  {
    id: "gravity-shower-5gal",
    name: "5-gal Sun Shower / Gravity Bag (full)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 42.5,
    unit: "item",
    notes: "Solar-heated camp shower bag",
  },
  {
    id: "camp-shower-propane",
    name: "Portable Propane Camp Shower (unit only)",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 5,
    unit: "item",
    notes: "Pump + heater unit; pair with water bladder",
  },
  {
    id: "on-demand-water-heater",
    name: "On-Demand Propane Water Heater",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 7.5,
    unit: "item",
    notes: "Instant hot water for camp shower; e.g. Eccotemp L5/L10",
  },
  {
    id: "12v-water-pump",
    name: "12V Electric Water Transfer Pump",
    category: "water-fuel",
    defaultZone: "bed-front",
    weightPerUnit: 2,
    unit: "item",
    notes: "Transfers water from bladder/tank to shower or sink",
  },
  {
    id: "sawyer-squeeze",
    name: "Sawyer Squeeze Water Filter",
    category: "water-fuel",
    defaultZone: "cab",
    weightPerUnit: 0.1,
    unit: "item",
    asin: "B00B1OSU4W",
    notes: "0.1 micron filter; ultralight trail option",
  },
  {
    id: "berkey-travel",
    name: "Travel Berkey Water Filter (1.5 gal)",
    category: "water-fuel",
    defaultZone: "bed-front",
    weightPerUnit: 7,
    unit: "item",
    notes: "Gravity filter; great for base camp use",
  },
  {
    id: "fuel-transfer-pump",
    name: "12V Fuel Transfer Pump",
    category: "water-fuel",
    defaultZone: "bed-rear",
    weightPerUnit: 2.5,
    unit: "item",
    notes: "Transfers diesel/gas from jerry cans to tank",
  },

  // ── POWER ──────────────────────────────────────────────────────────────────

  {
    id: "jackery-1000-plus",
    name: "Jackery Explorer 1000 Plus (1264Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 25.4,
    unit: "item",
    asin: "B0CFVBGWBT",
  },
  {
    id: "goal-zero-yeti-1000-core",
    name: "Goal Zero Yeti 1000 Core (983Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 22,
    unit: "item",
    asin: "B08FX3S5LF",
  },
  {
    id: "bluetti-ac200max",
    name: "Bluetti AC200MAX (2048Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 61.7,
    unit: "item",
    asin: "B09GKCH4CW",
  },
  {
    id: "ecoflow-delta-3-ultra",
    name: "EcoFlow DELTA 3 Ultra (4096Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 79,
    unit: "item",
    asin: "B0FT32MCM9",
  },
  {
    id: "battle-born-100ah",
    name: "Battle Born 100Ah LiFePO4 Battery",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 31,
    unit: "item",
    notes: "Auxiliary house battery",
  },
  {
    id: "renogy-200w-solar-portable",
    name: "Renogy 200W Portable Solar Panel (folding)",
    category: "power",
    defaultZone: "bed-rear",
    weightPerUnit: 10.6,
    unit: "item",
    asin: "B0CNPHD4VY",
  },
  {
    id: "solar-panel-rigid-100w",
    name: "Rigid Roof Solar Panel 100W",
    category: "power",
    defaultZone: "roof",
    weightPerUnit: 14.5,
    unit: "item",
    notes: "Mounted to roof rack; typical 100W monocrystalline",
  },
  {
    id: "ecoflow-wave-3",
    name: "EcoFlow WAVE 3 Portable AC/Heat",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 28.4,
    unit: "item",
    notes: "Portable AC + heater; pairs with EcoFlow power stations",
  },
  {
    id: "ecoflow-delta-3-plus",
    name: "EcoFlow DELTA 3 Plus (1024Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 27.7,
    unit: "item",
    notes: "Expandable with smart extra batteries",
  },
  {
    id: "jackery-1000-v2",
    name: "Jackery Explorer 1000 v2 (1070Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 22.3,
    unit: "item",
    asin: "B0CFYVB43L",
  },
  {
    id: "goal-zero-yeti-3000x",
    name: "Goal Zero Yeti 3000X (2982Wh)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 69.6,
    unit: "item",
    notes: "Heavy but high capacity; typically base camp use",
  },
  {
    id: "renogy-220w-portable",
    name: "Renogy 220W Portable Suitcase Solar Panel",
    category: "power",
    defaultZone: "bed-rear",
    weightPerUnit: 13,
    unit: "item",
    notes: "Foldable briefcase style; Renogy 220W kit",
  },
  {
    id: "rigid-solar-200w",
    name: "Rigid Roof Solar Panel 200W",
    category: "power",
    defaultZone: "roof",
    weightPerUnit: 26,
    unit: "item",
    notes: "Roof rack-mounted 200W monocrystalline",
  },
  {
    id: "mppt-charge-controller",
    name: "MPPT Solar Charge Controller (30–40A)",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 2,
    unit: "item",
    notes: "Needed for roof/portable panels charging aux battery",
  },
  {
    id: "aux-battery-200ah",
    name: "200Ah LiFePO4 Auxiliary Battery",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 52,
    unit: "item",
    notes: "House battery; e.g. Renogy, Battle Born, LiTime",
  },
  {
    id: "inverter-2000w",
    name: "2000W Pure Sine Inverter",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 12,
    unit: "item",
    notes: "Converts 12V to 120V AC for cabin-style power",
  },
  {
    id: "anderson-plug-kit",
    name: "Anderson Plug / Power Distribution Kit",
    category: "power",
    defaultZone: "bed-front",
    weightPerUnit: 2,
    unit: "item",
    notes: "SB50 connectors + bus bar; clean power routing",
  },
  {
    id: "starlink-standard",
    name: "Starlink Home Standard (dish + router)",
    category: "power",
    defaultZone: "roof",
    weightPerUnit: 12,
    unit: "item",
    notes: "Portable mode; ~9.5 lb dish + tripod/mount",
  },

  // ── KITCHEN ────────────────────────────────────────────────────────────────

  {
    id: "dometic-cfx3-55im",
    name: "Dometic CFX3 55IM Fridge/Freezer",
    category: "kitchen",
    defaultZone: "bed-front",
    weightPerUnit: 40,
    unit: "item",
    asin: "B0F9LFBJHF",
    notes: "55L with ice maker",
  },
  {
    id: "arb-fridge-50qt",
    name: "ARB Classic Series II Fridge 50qt",
    category: "kitchen",
    defaultZone: "bed-front",
    weightPerUnit: 59,
    unit: "item",
    asin: "B07Q75PB68",
  },
  {
    id: "yeti-tundra-65",
    name: "YETI Tundra 65 Hard Cooler (empty)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 29,
    unit: "item",
    notes: "Add ice/food weight separately",
  },
  {
    id: "coleman-cooler-54qt",
    name: "Coleman 54-qt Cooler (empty)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 15,
    unit: "item",
  },
  {
    id: "ice-per-bag",
    name: "Bagged Ice (10-lb bag)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 10,
    unit: "item",
  },
  {
    id: "camp-chef-explorer-2x",
    name: "Camp Chef Explorer 2X Two-Burner Stove",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 22,
    unit: "item",
    asin: "B0006VORDY",
  },
  {
    id: "biolite-campstove-2",
    name: "BioLite CampStove 2+",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 2.1,
    unit: "item",
    asin: "B0C31B18Y2",
  },
  {
    id: "propane-1lb",
    name: "1-lb Propane Canister",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 1.65,
    unit: "item",
  },
  {
    id: "propane-20lb",
    name: "20-lb Propane Tank (full)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 37.5,
    unit: "item",
    notes: "~17 lb gas + ~20 lb tare",
  },
  {
    id: "cast-iron-skillet",
    name: "Cast Iron Skillet 10\"",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 5.2,
    unit: "item",
  },
  {
    id: "camp-cookset",
    name: "Camp Cookset (4-person)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 3.5,
    unit: "item",
  },
  {
    id: "solo-stove-ranger",
    name: "Solo Stove Ranger 2.0 Fire Pit",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 15,
    unit: "item",
    asin: "B0B7BG9YPW",
  },
  {
    id: "folding-camp-table",
    name: "Folding Camp Table",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 9,
    unit: "item",
  },
  {
    id: "camp-chair",
    name: "Camp Chair (each)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 5,
    unit: "item",
  },
  {
    id: "jetboil-genesis",
    name: "JetBoil Genesis Base Camp 2-Burner Stove",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 3.5,
    unit: "item",
    notes: "Compact integrated 2-burner; runs on canister or auto-ignite",
  },
  {
    id: "jetboil-flash",
    name: "JetBoil Flash Cooking System",
    category: "kitchen",
    defaultZone: "cab",
    weightPerUnit: 0.91,
    unit: "item",
    asin: "B0BHWFBK2Z",
    notes: "Solo fast-boil system; 1L cup + burner",
  },
  {
    id: "msr-windburner",
    name: "MSR WindBurner Stove System (1P)",
    category: "kitchen",
    defaultZone: "cab",
    weightPerUnit: 1.1,
    unit: "item",
    notes: "Integrated pot + stove; wind-resistant",
  },
  {
    id: "camp-chef-denali-3x",
    name: "Camp Chef Denali 3X Three-Burner Stove",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 39,
    unit: "item",
    notes: "30,000 BTU per burner; group cooking workhorse",
  },
  {
    id: "gci-chef-station",
    name: "GCI Outdoor Chef Station",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 11,
    unit: "item",
    notes: "Folding camp kitchen station; hooks, storage, prep surface",
  },
  {
    id: "engel-mr040",
    name: "Engel MR040 Fridge/Freezer 40qt",
    category: "kitchen",
    defaultZone: "bed-front",
    weightPerUnit: 40,
    unit: "item",
    notes: "Single-zone; known for reliability in extreme heat",
  },
  {
    id: "dometic-cfx3-35",
    name: "Dometic CFX3 35 Fridge/Freezer 36qt",
    category: "kitchen",
    defaultZone: "bed-front",
    weightPerUnit: 26,
    unit: "item",
    notes: "Compact dual-zone option",
  },
  {
    id: "pelican-50qt",
    name: "Pelican Elite 50qt Cooler (empty)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 28,
    unit: "item",
    notes: "Rotomolded; 10-day ice retention",
  },
  {
    id: "yeti-roadie-24",
    name: "YETI Roadie 24 Hard Cooler (empty)",
    category: "kitchen",
    defaultZone: "cab",
    weightPerUnit: 7.4,
    unit: "item",
    notes: "Day-use cooler for cab access",
  },
  {
    id: "ice-bag-40lb",
    name: "Ice (40-lb bag)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 40,
    unit: "item",
    notes: "Add one bag per hard cooler; weight melts away over trip",
  },
  {
    id: "lodge-dutch-oven-5qt",
    name: "Lodge 5-qt Cast Iron Dutch Oven",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 12.3,
    unit: "item",
    notes: "Camp cooking staple; heavy but bulletproof",
  },
  {
    id: "coffee-percolator",
    name: "Camp Coffee Percolator 9-cup",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "food-provisions-day",
    name: "Food & Provisions (per person per day)",
    category: "kitchen",
    defaultZone: "bed-rear",
    weightPerUnit: 3,
    unit: "item",
    notes: "Approximate; 3 lbs/person/day covers full meals + snacks",
  },

  // ── MEDICAL ────────────────────────────────────────────────────────────────

  {
    id: "ifak",
    name: "IFAK (Individual First Aid Kit)",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "trauma-kit",
    name: "Trauma / Bleeding Control Kit",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 2.5,
    unit: "item",
  },
  {
    id: "first-aid-kit-large",
    name: "Large Group First Aid Kit",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 4,
    unit: "item",
  },
  {
    id: "medications",
    name: "Medications & Prescriptions (30-day supply)",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 1,
    unit: "item",
  },
  {
    id: "snake-bite-kit",
    name: "Snakebite / Venom Extractor Kit",
    category: "medical",
    defaultZone: "cab",
    weightPerUnit: 0.3,
    unit: "item",
  },

  // ── COMMS ──────────────────────────────────────────────────────────────────

  {
    id: "garmin-inreach-mini",
    name: "Garmin inReach Mini 3 Plus",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 0.24,
    unit: "item",
    asin: "B0G4RST8LV",
  },
  {
    id: "midland-gmrs-pair",
    name: "Midland GXT1000VP4 GMRS Radio (pair)",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 0.9,
    unit: "item",
    asin: "B001WMFYH4",
  },
  {
    id: "baofeng-uv5r",
    name: "Baofeng UV-5R Handheld Radio",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 0.29,
    unit: "item",
    asin: "B074XPB313",
  },
  {
    id: "cb-radio",
    name: "CB Radio (dash-mounted, incl. mount/antenna)",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 1.5,
    unit: "item",
    notes: "40-channel; common for convoy use",
  },
  {
    id: "starlink-mini",
    name: "Starlink Mini (vehicle use)",
    category: "comms",
    defaultZone: "roof",
    weightPerUnit: 2.4,
    unit: "item",
    notes: "Compact portable dish; great for vehicle/overlanding",
  },
  {
    id: "garmin-inreach-messenger",
    name: "Garmin inReach Messenger Plus",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 0.26,
    unit: "item",
    notes: "2-way satellite messaging; subscription required",
  },
  {
    id: "spot-x",
    name: "SPOT X Satellite Messenger",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 0.4,
    unit: "item",
    notes: "2-way messaging + GPS tracking",
  },
  {
    id: "gmrs-mobile-radio",
    name: "GMRS Mobile Radio (vehicle-mounted)",
    category: "comms",
    defaultZone: "cab",
    weightPerUnit: 1.8,
    unit: "item",
    notes: "Higher power than handhelds; e.g. Midland MXT575",
  },

  // ── NAVIGATION ─────────────────────────────────────────────────────────────

  {
    id: "garmin-gpsmap-67",
    name: "Garmin GPSMAP 67 Handheld GPS",
    category: "navigation",
    defaultZone: "cab",
    weightPerUnit: 0.37,
    unit: "item",
  },
  {
    id: "paper-atlas",
    name: "Paper Maps / Road Atlas",
    category: "navigation",
    defaultZone: "cab",
    weightPerUnit: 1.5,
    unit: "item",
  },
  {
    id: "tablet-nav",
    name: "Tablet with Nav App (iPad / Android + case)",
    category: "navigation",
    defaultZone: "cab",
    weightPerUnit: 1.2,
    unit: "item",
    notes: "OnX Offroad, Gaia GPS, etc.",
  },
  {
    id: "garmin-overlander",
    name: "Garmin Overlander GPS (with mount)",
    category: "navigation",
    defaultZone: "cab",
    weightPerUnit: 0.55,
    unit: "item",
    notes: "Built-in BirdsEye Satellite Imagery; preloaded topo",
  },
  {
    id: "ram-dash-mount",
    name: "RAM Mount / Cradle (phone or tablet)",
    category: "navigation",
    defaultZone: "cab",
    weightPerUnit: 0.5,
    unit: "item",
    notes: "X-Grip or cradle style; adds minor weight to cab",
  },

  // ── CLOTHING ───────────────────────────────────────────────────────────────

  {
    id: "clothing-duffel",
    name: "Clothing Duffel (per person, 5-day trip)",
    category: "clothing",
    defaultZone: "cab",
    weightPerUnit: 15,
    unit: "item",
  },
  {
    id: "clothing-cold-weather",
    name: "Cold-Weather Gear Bag (per person)",
    category: "clothing",
    defaultZone: "cab",
    weightPerUnit: 8,
    unit: "item",
    notes: "Insulated jacket, heavy layers, boots",
  },
  {
    id: "waders-hip",
    name: "Hip Waders / Chest Waders",
    category: "clothing",
    defaultZone: "bed-rear",
    weightPerUnit: 4,
    unit: "item",
  },

  // ── TOOLS ──────────────────────────────────────────────────────────────────

  {
    id: "chainsaw-battery",
    name: "Battery Chainsaw 12\" Bar",
    category: "tools",
    defaultZone: "bed-rear",
    weightPerUnit: 7,
    unit: "item",
    notes: "Trail clearing; e.g. STIHL MSA 220C",
  },
  {
    id: "axe-full",
    name: "Full-Size Axe / Splitting Maul",
    category: "tools",
    defaultZone: "bed-rear",
    weightPerUnit: 3.8,
    unit: "item",
  },
  {
    id: "hatchet",
    name: "Camp Hatchet",
    category: "tools",
    defaultZone: "cab",
    weightPerUnit: 1.75,
    unit: "item",
  },
  {
    id: "tool-roll",
    name: "Vehicle Tool Roll (sockets, wrenches, pliers)",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 8,
    unit: "item",
  },
  {
    id: "floor-jack-3t",
    name: "3-Ton Aluminum Floor Jack",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 42,
    unit: "item",
    notes: "Base camp; most leave at home for remote trips",
  },
  {
    id: "jumper-cables",
    name: "Jumper Cables 20 ft 4-gauge",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 4.5,
    unit: "item",
  },
  {
    id: "socket-set",
    name: "Socket & Ratchet Set (3/8\" + 1/2\")",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 6,
    unit: "item",
  },
  {
    id: "multitool",
    name: "Multi-Tool (Leatherman Wave+)",
    category: "tools",
    defaultZone: "cab",
    weightPerUnit: 0.52,
    unit: "item",
  },
  {
    id: "tire-plug-kit",
    name: "Tire Plug / Repair Kit (mushroom plugs + irons)",
    category: "tools",
    defaultZone: "cab",
    weightPerUnit: 1,
    unit: "item",
    notes: "Trail fix for punctures; always in cab",
  },
  {
    id: "portable-work-light",
    name: "Portable LED Flood / Work Light",
    category: "tools",
    defaultZone: "bed-rear",
    weightPerUnit: 2,
    unit: "item",
    notes: "Camp lighting or under-hood repairs at night",
  },
  {
    id: "air-tank-5gal",
    name: "Portable Air Tank 5-gal",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 14,
    unit: "item",
    notes: "Pre-filled for trail tire airing up without a compressor running",
  },
  {
    id: "hi-lift-base-plate",
    name: "Hi-Lift Off-Road Base Plate",
    category: "tools",
    defaultZone: "bed-rear",
    weightPerUnit: 4.5,
    unit: "item",
    notes: "Prevents Hi-Lift from sinking in mud/sand",
  },
  {
    id: "torque-wrench",
    name: "Torque Wrench 1/2\" Drive",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 3,
    unit: "item",
    notes: "For wheel re-install after tire repair",
  },
  {
    id: "noco-genius-10",
    name: "NOCO Genius 10 Battery Charger/Maintainer",
    category: "tools",
    defaultZone: "bed-front",
    weightPerUnit: 1.2,
    unit: "item",
    asin: "B07WPQT5BZ",
    notes: "Keeps aux battery healthy at base camp; 10A",
  },
  {
    id: "zip-tie-electrical-kit",
    name: "Zip Tie & Electrical Tape Emergency Kit",
    category: "tools",
    defaultZone: "cab",
    weightPerUnit: 0.5,
    unit: "item",
    notes: "Assorted zip ties, electrical tape, wire connectors",
  },

  // ── OTHER ──────────────────────────────────────────────────────────────────

  {
    id: "roof-rack-platform",
    name: "Roof Rack / Platform Rack (steel)",
    category: "other",
    defaultZone: "roof",
    weightPerUnit: 55,
    unit: "item",
    notes: "Aluminum racks ~28–35 lbs; steel ~50–70 lbs",
  },
  {
    id: "bed-drawer-system",
    name: "Truck Bed Drawer System",
    category: "other",
    defaultZone: "bed-front",
    weightPerUnit: 90,
    unit: "item",
    notes: "E.g. ARB Roller Drawer; aluminum ~65 lbs",
  },
  {
    id: "roof-basket",
    name: "Roof Cargo Basket",
    category: "other",
    defaultZone: "roof",
    weightPerUnit: 38,
    unit: "item",
  },
  {
    id: "hitch-cargo-carrier",
    name: "Receiver Hitch Cargo Carrier 2\"",
    category: "other",
    defaultZone: "hitch",
    weightPerUnit: 35,
    unit: "item",
    notes: "Adds tongue weight; rate carrier + cargo separately",
  },
  {
    id: "spare-tire-35",
    name: "Full-Size Spare Tire 35\" (e.g. BFG KO2)",
    category: "other",
    defaultZone: "bed-rear",
    weightPerUnit: 65,
    unit: "item",
    notes: "Bed/bumper-mounted; stock under-bed spare ≈ 35–45 lbs",
  },
  {
    id: "rear-bumper-tire-carrier",
    name: "Steel Rear Bumper w/ Swing Tire Carrier",
    category: "other",
    defaultZone: "hitch",
    weightPerUnit: 125,
    unit: "item",
    notes: "Adds significant tongue/rear weight; shifts CG rearward",
  },
  {
    id: "skid-plate-set",
    name: "Full Skid Plate Set (engine, transfer, fuel)",
    category: "other",
    defaultZone: "cab",
    weightPerUnit: 55,
    unit: "item",
    notes: "Under-vehicle; treated as cab zone for axle math",
  },
  {
    id: "dog-large",
    name: "Dog — Large Breed (update to actual weight)",
    category: "other",
    defaultZone: "cab",
    weightPerUnit: 80,
    unit: "item",
    notes: "Rear seat; default 80 lb — adjust to your dog",
  },
  {
    id: "dog-medium",
    name: "Dog — Medium Breed (update to actual weight)",
    category: "other",
    defaultZone: "cab",
    weightPerUnit: 42,
    unit: "item",
  },
  {
    id: "bed-rack-steel",
    name: "Overland Bed Rack (steel)",
    category: "other",
    defaultZone: "bed-front",
    weightPerUnit: 85,
    unit: "item",
    notes: "Truck bed rack for RTT or cargo; steel ~75–100 lbs",
  },
  {
    id: "bed-rack-aluminum",
    name: "Overland Bed Rack (aluminum)",
    category: "other",
    defaultZone: "bed-front",
    weightPerUnit: 55,
    unit: "item",
    notes: "Aluminum bed rack; ~45–65 lbs depending on brand",
  },
  {
    id: "roof-rack-aluminum",
    name: "Roof Rack / Platform Rack (aluminum)",
    category: "other",
    defaultZone: "roof",
    weightPerUnit: 32,
    unit: "item",
    notes: "Lighter than steel; e.g. Prinsu, Front Runner Slimline II",
  },
  {
    id: "roof-cargo-box",
    name: "Rooftop Cargo Box (Thule Force XT L or similar)",
    category: "other",
    defaultZone: "roof",
    weightPerUnit: 38,
    unit: "item",
    notes: "Hard-sided rooftop cargo box; ~22–38 lbs empty",
  },
  {
    id: "truck-topper",
    name: "Aluminum Truck Canopy / Topper",
    category: "other",
    defaultZone: "bed-front",
    weightPerUnit: 200,
    unit: "item",
    notes: "Full bed enclosure; significant weight over rear axle",
  },
  {
    id: "rock-sliders",
    name: "Rock Sliders / Side Steps (pair)",
    category: "other",
    defaultZone: "cab",
    weightPerUnit: 60,
    unit: "item",
    notes: "Under-cab protection; weight distributed along frame",
  },
  {
    id: "front-bumper-steel",
    name: "Steel Front Bumper (full-width)",
    category: "other",
    defaultZone: "cab",
    weightPerUnit: 85,
    unit: "item",
    notes: "Replaces factory bumper; shifts ~50–60 lbs to front axle",
  },
  {
    id: "rear-bumper-plain",
    name: "Steel Rear Bumper (no swing arm)",
    category: "other",
    defaultZone: "hitch",
    weightPerUnit: 60,
    unit: "item",
    notes: "Adds rear weight without swing-out tire carrier",
  },
  {
    id: "jerry-can-mount-2",
    name: "Jerry Can Rack / Mount (2-can, rack rail)",
    category: "other",
    defaultZone: "roof",
    weightPerUnit: 8,
    unit: "item",
    notes: "Mounts to roof rack side rail; add jerry can weights separately",
  },
  {
    id: "molle-panel-set",
    name: "MOLLE Panel Set (bed or cab walls)",
    category: "other",
    defaultZone: "bed-front",
    weightPerUnit: 12,
    unit: "item",
    notes: "Organizes smaller gear; lightweight aluminum panels",
  },
  {
    id: "kayak-canoe",
    name: "Kayak / Canoe (single)",
    category: "other",
    defaultZone: "roof",
    weightPerUnit: 55,
    unit: "item",
    notes: "Average kayak 40–65 lbs; use actual weight",
  },
  {
    id: "spare-tire-37",
    name: "Full-Size Spare Tire 37\" (e.g. BFG KO2)",
    category: "other",
    defaultZone: "bed-rear",
    weightPerUnit: 75,
    unit: "item",
    notes: "37\" tire significantly heavier than 35\" — use actual weight",
  },
];

/** Alias export — matches the import name used in LoadBalancer.tsx */
export const gearItems = GEAR_LIBRARY;
