// ---------------------------------------------------------------------------
// RigRated UTV Machine Database
// ~26 machines across 6 manufacturers (2024-2025 model year specs)
// ---------------------------------------------------------------------------

export type UTVBodyType =
  | "2-seat-sport"
  | "4-seat-sport"
  | "2-seat-utility"
  | "4-seat-utility"
  | "crew-cab-utility";

export interface UTVMachine {
  id: string;
  make: string;
  model: string;
  trim: string;
  year: number;
  bodyType: UTVBodyType;
  seatingCapacity: 2 | 4 | 6;
  dryWeightLbs: number;
  gvwrLbs: number;
  payloadCapacityLbs: number;
  towingCapacityLbs: number;
  bedLengthIn: number;
  bedWidthIn: number;
  bedDepthIn: number;
  groundClearanceIn: number;
  wheelbaseIn: number;
  trackWidthFrontIn: number;
  trackWidthRearIn: number;
  overallWidthIn: number;
  overallHeightIn: number;
  turningRadiusFt: number;
  horsePower: number;
  torqueFtLbs: number;
  fuelCapacityGal: number;
  tireSize: string;
  engineType: "gas" | "turbo-gas";
  notes?: string;
}

// ---------------------------------------------------------------------------
// Machine entries
// ---------------------------------------------------------------------------

export const machines: UTVMachine[] = [
  // =========================================================================
  // POLARIS (8)
  // =========================================================================
  {
    id: "polaris-rzr-xp-1000",
    make: "Polaris",
    model: "RZR XP 1000",
    trim: "Premium",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1482,
    gvwrLbs: 1982,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 30,
    bedWidthIn: 40,
    bedDepthIn: 8,
    groundClearanceIn: 14.5,
    wheelbaseIn: 90,
    trackWidthFrontIn: 64,
    trackWidthRearIn: 64,
    overallWidthIn: 64,
    overallHeightIn: 73.5,
    turningRadiusFt: 17.5,
    horsePower: 110,
    torqueFtLbs: 68,
    fuelCapacityGal: 9.5,
    tireSize: "30x10R14",
    engineType: "gas",
    notes: "Proven trail-ripper with FOX 2.0 Podium shocks.",
  },
  {
    id: "polaris-rzr-xp-turbo-r",
    make: "Polaris",
    model: "RZR XP Turbo R",
    trim: "Ultimate",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1850,
    gvwrLbs: 2350,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 30,
    bedWidthIn: 40,
    bedDepthIn: 8,
    groundClearanceIn: 16,
    wheelbaseIn: 93,
    trackWidthFrontIn: 72,
    trackWidthRearIn: 72,
    overallWidthIn: 72,
    overallHeightIn: 75,
    turningRadiusFt: 18,
    horsePower: 181,
    torqueFtLbs: 120,
    fuelCapacityGal: 9.5,
    tireSize: "32x10R15",
    engineType: "turbo-gas",
    notes: "74-inch chassis with 181hp ProStar turbo. Desert weapon.",
  },
  {
    id: "polaris-rzr-pro-xp",
    make: "Polaris",
    model: "RZR Pro XP",
    trim: "Sport",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1767,
    gvwrLbs: 2267,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 30,
    bedWidthIn: 42,
    bedDepthIn: 8,
    groundClearanceIn: 15,
    wheelbaseIn: 93,
    trackWidthFrontIn: 64,
    trackWidthRearIn: 64,
    overallWidthIn: 64,
    overallHeightIn: 74,
    turningRadiusFt: 18,
    horsePower: 181,
    torqueFtLbs: 120,
    fuelCapacityGal: 9.5,
    tireSize: "30x10R14",
    engineType: "turbo-gas",
    notes: "181hp turbo in a 64-inch chassis for tight trails.",
  },
  {
    id: "polaris-rzr-pro-r",
    make: "Polaris",
    model: "RZR Pro R",
    trim: "Ultimate",
    year: 2025,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1950,
    gvwrLbs: 2450,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 30,
    bedWidthIn: 42,
    bedDepthIn: 8,
    groundClearanceIn: 16.5,
    wheelbaseIn: 96,
    trackWidthFrontIn: 74,
    trackWidthRearIn: 74,
    overallWidthIn: 74,
    overallHeightIn: 76,
    turningRadiusFt: 19,
    horsePower: 225,
    torqueFtLbs: 145,
    fuelCapacityGal: 9.5,
    tireSize: "32x10R15",
    engineType: "gas",
    notes: "2.0L NA four-cylinder. Top of the RZR food chain.",
  },
  {
    id: "polaris-ranger-xp-1000",
    make: "Polaris",
    model: "Ranger XP 1000",
    trim: "Premium",
    year: 2024,
    bodyType: "2-seat-utility",
    seatingCapacity: 2,
    dryWeightLbs: 1655,
    gvwrLbs: 2505,
    payloadCapacityLbs: 850,
    towingCapacityLbs: 2500,
    bedLengthIn: 36,
    bedWidthIn: 54,
    bedDepthIn: 11,
    groundClearanceIn: 13,
    wheelbaseIn: 81,
    trackWidthFrontIn: 58,
    trackWidthRearIn: 58,
    overallWidthIn: 62,
    overallHeightIn: 76,
    turningRadiusFt: 15,
    horsePower: 82,
    torqueFtLbs: 55,
    fuelCapacityGal: 9,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "Work-horse Ranger. Lock & Ride cargo system, full dump bed.",
  },
  {
    id: "polaris-ranger-crew-xp-1000",
    make: "Polaris",
    model: "Ranger Crew XP 1000",
    trim: "Premium",
    year: 2024,
    bodyType: "crew-cab-utility",
    seatingCapacity: 6,
    dryWeightLbs: 1850,
    gvwrLbs: 2940,
    payloadCapacityLbs: 1090,
    towingCapacityLbs: 2500,
    bedLengthIn: 36,
    bedWidthIn: 54,
    bedDepthIn: 11,
    groundClearanceIn: 12,
    wheelbaseIn: 113,
    trackWidthFrontIn: 58,
    trackWidthRearIn: 58,
    overallWidthIn: 62,
    overallHeightIn: 77,
    turningRadiusFt: 20,
    horsePower: 82,
    torqueFtLbs: 55,
    fuelCapacityGal: 9,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "6-seat crew cab. Full dump bed with 1,000-lb box capacity.",
  },
  {
    id: "polaris-general-xp-1000",
    make: "Polaris",
    model: "General XP 1000",
    trim: "Deluxe",
    year: 2024,
    bodyType: "2-seat-utility",
    seatingCapacity: 2,
    dryWeightLbs: 1580,
    gvwrLbs: 2255,
    payloadCapacityLbs: 675,
    towingCapacityLbs: 1500,
    bedLengthIn: 24,
    bedWidthIn: 42,
    bedDepthIn: 9.5,
    groundClearanceIn: 12,
    wheelbaseIn: 83,
    trackWidthFrontIn: 60,
    trackWidthRearIn: 60,
    overallWidthIn: 62,
    overallHeightIn: 75,
    turningRadiusFt: 16,
    horsePower: 100,
    torqueFtLbs: 65,
    fuelCapacityGal: 9.5,
    tireSize: "29x9R14",
    engineType: "gas",
    notes: "The crossover: sport chassis with a real dump bed.",
  },
  {
    id: "polaris-general-xp-4-1000",
    make: "Polaris",
    model: "General XP 4 1000",
    trim: "Deluxe",
    year: 2024,
    bodyType: "4-seat-utility",
    seatingCapacity: 4,
    dryWeightLbs: 1790,
    gvwrLbs: 2540,
    payloadCapacityLbs: 750,
    towingCapacityLbs: 1500,
    bedLengthIn: 24,
    bedWidthIn: 42,
    bedDepthIn: 9.5,
    groundClearanceIn: 12,
    wheelbaseIn: 117,
    trackWidthFrontIn: 60,
    trackWidthRearIn: 60,
    overallWidthIn: 62,
    overallHeightIn: 75,
    turningRadiusFt: 20,
    horsePower: 100,
    torqueFtLbs: 65,
    fuelCapacityGal: 9.5,
    tireSize: "29x9R14",
    engineType: "gas",
    notes: "4-seat General with extended wheelbase. Family trail hauler.",
  },

  // =========================================================================
  // CAN-AM (5)
  // =========================================================================
  {
    id: "canam-maverick-x3-xrs-turbo-rr",
    make: "Can-Am",
    model: "Maverick X3 X RS Turbo RR",
    trim: "Turbo RR",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1726,
    gvwrLbs: 2226,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 26,
    bedWidthIn: 40,
    bedDepthIn: 7,
    groundClearanceIn: 15,
    wheelbaseIn: 102,
    trackWidthFrontIn: 72,
    trackWidthRearIn: 72,
    overallWidthIn: 72,
    overallHeightIn: 72,
    turningRadiusFt: 18.5,
    horsePower: 200,
    torqueFtLbs: 131,
    fuelCapacityGal: 10,
    tireSize: "32x10R15",
    engineType: "turbo-gas",
    notes: "Triple-crown desert racer. 200hp Rotax ACE turbo, 24-inch travel.",
  },
  {
    id: "canam-maverick-r",
    make: "Can-Am",
    model: "Maverick R",
    trim: "X RS",
    year: 2025,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1990,
    gvwrLbs: 2490,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 28,
    bedWidthIn: 42,
    bedDepthIn: 7,
    groundClearanceIn: 16,
    wheelbaseIn: 105,
    trackWidthFrontIn: 74,
    trackWidthRearIn: 74,
    overallWidthIn: 74,
    overallHeightIn: 73,
    turningRadiusFt: 19,
    horsePower: 240,
    torqueFtLbs: 170,
    fuelCapacityGal: 10,
    tireSize: "33x10R15",
    engineType: "turbo-gas",
    notes: "999cc twin turbo. Can-Am flagship. 25 inches of suspension travel.",
  },
  {
    id: "canam-defender-hd9",
    make: "Can-Am",
    model: "Defender HD9",
    trim: "DPS",
    year: 2024,
    bodyType: "2-seat-utility",
    seatingCapacity: 2,
    dryWeightLbs: 1460,
    gvwrLbs: 2310,
    payloadCapacityLbs: 850,
    towingCapacityLbs: 2000,
    bedLengthIn: 36,
    bedWidthIn: 48,
    bedDepthIn: 10.5,
    groundClearanceIn: 11,
    wheelbaseIn: 83,
    trackWidthFrontIn: 58,
    trackWidthRearIn: 58,
    overallWidthIn: 62,
    overallHeightIn: 75,
    turningRadiusFt: 15.5,
    horsePower: 65,
    torqueFtLbs: 50,
    fuelCapacityGal: 10,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "Rotax 799cc V-twin. Budget-friendly workhorse.",
  },
  {
    id: "canam-defender-hd10",
    make: "Can-Am",
    model: "Defender HD10",
    trim: "XT",
    year: 2024,
    bodyType: "2-seat-utility",
    seatingCapacity: 2,
    dryWeightLbs: 1520,
    gvwrLbs: 2420,
    payloadCapacityLbs: 900,
    towingCapacityLbs: 2500,
    bedLengthIn: 36,
    bedWidthIn: 48,
    bedDepthIn: 10.5,
    groundClearanceIn: 11,
    wheelbaseIn: 83,
    trackWidthFrontIn: 60,
    trackWidthRearIn: 60,
    overallWidthIn: 63,
    overallHeightIn: 76,
    turningRadiusFt: 15.5,
    horsePower: 82,
    torqueFtLbs: 56,
    fuelCapacityGal: 10,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "976cc Rotax V-twin, VERSA-TEC rear cargo system.",
  },
  {
    id: "canam-defender-max-hd10",
    make: "Can-Am",
    model: "Defender MAX HD10",
    trim: "XT",
    year: 2024,
    bodyType: "4-seat-utility",
    seatingCapacity: 4,
    dryWeightLbs: 1690,
    gvwrLbs: 2690,
    payloadCapacityLbs: 1000,
    towingCapacityLbs: 2500,
    bedLengthIn: 36,
    bedWidthIn: 48,
    bedDepthIn: 10.5,
    groundClearanceIn: 11,
    wheelbaseIn: 116,
    trackWidthFrontIn: 60,
    trackWidthRearIn: 60,
    overallWidthIn: 63,
    overallHeightIn: 76,
    turningRadiusFt: 20,
    horsePower: 82,
    torqueFtLbs: 56,
    fuelCapacityGal: 10,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "4-seat Defender with full bed. Best-in-class utility capacity.",
  },

  // =========================================================================
  // HONDA (4)
  // =========================================================================
  {
    id: "honda-pioneer-1000",
    make: "Honda",
    model: "Pioneer 1000",
    trim: "EPS",
    year: 2024,
    bodyType: "2-seat-utility",
    seatingCapacity: 2,
    dryWeightLbs: 1504,
    gvwrLbs: 2415,
    payloadCapacityLbs: 911,
    towingCapacityLbs: 2000,
    bedLengthIn: 36,
    bedWidthIn: 48,
    bedDepthIn: 10,
    groundClearanceIn: 12.3,
    wheelbaseIn: 79.5,
    trackWidthFrontIn: 58,
    trackWidthRearIn: 58,
    overallWidthIn: 62,
    overallHeightIn: 77,
    turningRadiusFt: 15.5,
    horsePower: 69,
    torqueFtLbs: 55,
    fuelCapacityGal: 7.9,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "Honda reliability. 999cc unicam twin, automatic DCT.",
  },
  {
    id: "honda-pioneer-1000-5",
    make: "Honda",
    model: "Pioneer 1000-5",
    trim: "Deluxe",
    year: 2024,
    bodyType: "4-seat-utility",
    seatingCapacity: 4,
    dryWeightLbs: 1616,
    gvwrLbs: 2596,
    payloadCapacityLbs: 980,
    towingCapacityLbs: 2000,
    bedLengthIn: 33,
    bedWidthIn: 48,
    bedDepthIn: 10,
    groundClearanceIn: 12,
    wheelbaseIn: 113.5,
    trackWidthFrontIn: 58.2,
    trackWidthRearIn: 58.2,
    overallWidthIn: 63,
    overallHeightIn: 77,
    turningRadiusFt: 19.5,
    horsePower: 69,
    torqueFtLbs: 55,
    fuelCapacityGal: 7.9,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "QuickFlip rear seat converts to flat cargo. Most versatile Honda UTV.",
  },
  {
    id: "honda-talon-1000r",
    make: "Honda",
    model: "Talon 1000R",
    trim: "FOX Live Valve",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1483,
    gvwrLbs: 1933,
    payloadCapacityLbs: 450,
    towingCapacityLbs: 1500,
    bedLengthIn: 27,
    bedWidthIn: 38,
    bedDepthIn: 7.5,
    groundClearanceIn: 14.6,
    wheelbaseIn: 93.3,
    trackWidthFrontIn: 66,
    trackWidthRearIn: 68,
    overallWidthIn: 68,
    overallHeightIn: 72,
    turningRadiusFt: 17.5,
    horsePower: 99,
    torqueFtLbs: 68,
    fuelCapacityGal: 7.7,
    tireSize: "30x10R14",
    engineType: "gas",
    notes: "Live Valve suspension auto-adjusts in real time. 999cc twin.",
  },
  {
    id: "honda-talon-1000x",
    make: "Honda",
    model: "Talon 1000X",
    trim: "FOX Live Valve",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1461,
    gvwrLbs: 1911,
    payloadCapacityLbs: 450,
    towingCapacityLbs: 1500,
    bedLengthIn: 27,
    bedWidthIn: 38,
    bedDepthIn: 7.5,
    groundClearanceIn: 13.7,
    wheelbaseIn: 87.6,
    trackWidthFrontIn: 59.4,
    trackWidthRearIn: 59.8,
    overallWidthIn: 64,
    overallHeightIn: 72.5,
    turningRadiusFt: 16.5,
    horsePower: 99,
    torqueFtLbs: 68,
    fuelCapacityGal: 7.7,
    tireSize: "28x10R14",
    engineType: "gas",
    notes: "Shorter wheelbase X model for tight single-track. 50-inch width.",
  },

  // =========================================================================
  // KAWASAKI (3)
  // =========================================================================
  {
    id: "kawasaki-teryx-krx-1000",
    make: "Kawasaki",
    model: "Teryx KRX 1000",
    trim: "eS",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1715,
    gvwrLbs: 2215,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 28,
    bedWidthIn: 40,
    bedDepthIn: 8,
    groundClearanceIn: 14.3,
    wheelbaseIn: 92.3,
    trackWidthFrontIn: 68,
    trackWidthRearIn: 68,
    overallWidthIn: 68.5,
    overallHeightIn: 74.8,
    turningRadiusFt: 18,
    horsePower: 99,
    torqueFtLbs: 72,
    fuelCapacityGal: 9.5,
    tireSize: "31x10R15",
    engineType: "gas",
    notes: "999cc parallel twin. Fox 2.5 Podium LSC shocks. Built for rock crawling.",
  },
  {
    id: "kawasaki-teryx-krx4-1000",
    make: "Kawasaki",
    model: "Teryx KRX4 1000",
    trim: "eS",
    year: 2024,
    bodyType: "4-seat-sport",
    seatingCapacity: 4,
    dryWeightLbs: 1890,
    gvwrLbs: 2490,
    payloadCapacityLbs: 600,
    towingCapacityLbs: 1500,
    bedLengthIn: 28,
    bedWidthIn: 40,
    bedDepthIn: 8,
    groundClearanceIn: 13.8,
    wheelbaseIn: 117.5,
    trackWidthFrontIn: 68,
    trackWidthRearIn: 68,
    overallWidthIn: 68.5,
    overallHeightIn: 75,
    turningRadiusFt: 21,
    horsePower: 99,
    torqueFtLbs: 72,
    fuelCapacityGal: 9.5,
    tireSize: "31x10R15",
    engineType: "gas",
    notes: "4-seat KRX with extended cage. Family-size rock crawler.",
  },
  {
    id: "kawasaki-mule-pro-fxt",
    make: "Kawasaki",
    model: "Mule PRO-FXT",
    trim: "EPS LE",
    year: 2024,
    bodyType: "crew-cab-utility",
    seatingCapacity: 6,
    dryWeightLbs: 1686,
    gvwrLbs: 2886,
    payloadCapacityLbs: 1200,
    towingCapacityLbs: 2000,
    bedLengthIn: 33,
    bedWidthIn: 48,
    bedDepthIn: 10.5,
    groundClearanceIn: 10.4,
    wheelbaseIn: 92.3,
    trackWidthFrontIn: 56.1,
    trackWidthRearIn: 56.1,
    overallWidthIn: 63,
    overallHeightIn: 78.1,
    turningRadiusFt: 17,
    horsePower: 48,
    torqueFtLbs: 38,
    fuelCapacityGal: 7.9,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "812cc triple. Trans Cab converts 6-seat to cargo. Ultimate work mule.",
  },

  // =========================================================================
  // YAMAHA (3)
  // =========================================================================
  {
    id: "yamaha-yxz1000r",
    make: "Yamaha",
    model: "YXZ1000R",
    trim: "SS SE",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1326,
    gvwrLbs: 1826,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 24,
    bedWidthIn: 38,
    bedDepthIn: 7,
    groundClearanceIn: 13.2,
    wheelbaseIn: 90.6,
    trackWidthFrontIn: 64,
    trackWidthRearIn: 64,
    overallWidthIn: 64,
    overallHeightIn: 71.7,
    turningRadiusFt: 17,
    horsePower: 108,
    torqueFtLbs: 69,
    fuelCapacityGal: 7.9,
    tireSize: "29x9R14",
    engineType: "gas",
    notes: "Only UTV with a true manual gearbox. 998cc triple, paddle shift.",
  },
  {
    id: "yamaha-wolverine-rmax-1000",
    make: "Yamaha",
    model: "Wolverine RMAX 1000",
    trim: "XT-R",
    year: 2024,
    bodyType: "2-seat-utility",
    seatingCapacity: 2,
    dryWeightLbs: 1530,
    gvwrLbs: 2205,
    payloadCapacityLbs: 675,
    towingCapacityLbs: 2000,
    bedLengthIn: 32.6,
    bedWidthIn: 46.5,
    bedDepthIn: 10,
    groundClearanceIn: 13.8,
    wheelbaseIn: 86.7,
    trackWidthFrontIn: 62,
    trackWidthRearIn: 62,
    overallWidthIn: 64,
    overallHeightIn: 76.4,
    turningRadiusFt: 16,
    horsePower: 99,
    torqueFtLbs: 65,
    fuelCapacityGal: 9.2,
    tireSize: "30x10R14",
    engineType: "gas",
    notes: "Adventure-ready with real cargo capacity. D-Mode throttle mapping.",
  },
  {
    id: "yamaha-wolverine-rmax4-1000",
    make: "Yamaha",
    model: "Wolverine RMAX4 1000",
    trim: "XT-R",
    year: 2024,
    bodyType: "4-seat-utility",
    seatingCapacity: 4,
    dryWeightLbs: 1700,
    gvwrLbs: 2475,
    payloadCapacityLbs: 775,
    towingCapacityLbs: 2000,
    bedLengthIn: 32.6,
    bedWidthIn: 46.5,
    bedDepthIn: 10,
    groundClearanceIn: 13.4,
    wheelbaseIn: 116.1,
    trackWidthFrontIn: 62,
    trackWidthRearIn: 62,
    overallWidthIn: 64,
    overallHeightIn: 76.8,
    turningRadiusFt: 21,
    horsePower: 99,
    torqueFtLbs: 65,
    fuelCapacityGal: 9.2,
    tireSize: "30x10R14",
    engineType: "gas",
    notes: "4-seat RMAX. Extended cage, same powertrain as 2-seater.",
  },

  // =========================================================================
  // CFMOTO (3)
  // =========================================================================
  {
    id: "cfmoto-zforce-950",
    make: "CFMoto",
    model: "ZForce 950",
    trim: "Sport",
    year: 2024,
    bodyType: "2-seat-sport",
    seatingCapacity: 2,
    dryWeightLbs: 1280,
    gvwrLbs: 1780,
    payloadCapacityLbs: 500,
    towingCapacityLbs: 1500,
    bedLengthIn: 26,
    bedWidthIn: 38,
    bedDepthIn: 7,
    groundClearanceIn: 13.4,
    wheelbaseIn: 90.6,
    trackWidthFrontIn: 64,
    trackWidthRearIn: 64,
    overallWidthIn: 64,
    overallHeightIn: 72,
    turningRadiusFt: 17,
    horsePower: 79,
    torqueFtLbs: 55,
    fuelCapacityGal: 7.9,
    tireSize: "28x10R14",
    engineType: "gas",
    notes: "963cc V-twin. Best bang-for-buck sport UTV on the market.",
  },
  {
    id: "cfmoto-uforce-1000",
    make: "CFMoto",
    model: "UForce 1000",
    trim: "EPS",
    year: 2024,
    bodyType: "2-seat-utility",
    seatingCapacity: 2,
    dryWeightLbs: 1425,
    gvwrLbs: 2125,
    payloadCapacityLbs: 700,
    towingCapacityLbs: 2000,
    bedLengthIn: 36,
    bedWidthIn: 48,
    bedDepthIn: 10,
    groundClearanceIn: 11.8,
    wheelbaseIn: 81,
    trackWidthFrontIn: 58,
    trackWidthRearIn: 58,
    overallWidthIn: 62,
    overallHeightIn: 76,
    turningRadiusFt: 15.5,
    horsePower: 79,
    torqueFtLbs: 57,
    fuelCapacityGal: 9,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "963cc V-twin utility. Tilt dump bed, factory winch ready.",
  },
  {
    id: "cfmoto-uforce-1000-xl",
    make: "CFMoto",
    model: "UForce 1000 XL",
    trim: "EPS",
    year: 2024,
    bodyType: "4-seat-utility",
    seatingCapacity: 4,
    dryWeightLbs: 1575,
    gvwrLbs: 2375,
    payloadCapacityLbs: 800,
    towingCapacityLbs: 2000,
    bedLengthIn: 33,
    bedWidthIn: 48,
    bedDepthIn: 10,
    groundClearanceIn: 11.5,
    wheelbaseIn: 113,
    trackWidthFrontIn: 58,
    trackWidthRearIn: 58,
    overallWidthIn: 62,
    overallHeightIn: 77,
    turningRadiusFt: 20,
    horsePower: 79,
    torqueFtLbs: 57,
    fuelCapacityGal: 9,
    tireSize: "27x9R14",
    engineType: "gas",
    notes: "4-seat UForce with extended cab. Incredible value for a crew UTV.",
  },
];

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

export function getUniqueMakes(): string[] {
  return Array.from(new Set(machines.map((m) => m.make))).sort();
}

export function getModelsForMake(make: string): string[] {
  return Array.from(new Set(machines.filter((m) => m.make === make).map((m) => m.model))).sort();
}

export function getTrimsForModel(make: string, model: string): string[] {
  return machines
    .filter((m) => m.make === make && m.model === model)
    .map((m) => `${m.year} ${m.trim}`)
    .sort();
}

export function findMachine(
  make: string,
  model: string,
  yearTrim: string,
): UTVMachine | undefined {
  return machines.find(
    (m) => m.make === make && m.model === model && `${m.year} ${m.trim}` === yearTrim,
  );
}
