// RigRated UTV Accessories Database
// ~160+ accessories across 35+ categories with realistic weights and brands

export type AccessoryCategory =
  | "windshield" | "doors" | "roof" | "bumper-front" | "bumper-rear"
  | "winch" | "skid-plate" | "rock-slider" | "roof-rack" | "cargo-rack"
  | "light-bar" | "light-pod" | "sound-system" | "mirrors" | "fridge-mount" | "dual-battery"
  | "solar-panel" | "rtt-mount" | "spare-tire-carrier" | "fuel-can-rack"
  | "fuel-cell"
  | "led-whip" | "underglow" | "sound-bar"
  | "harness" | "storage" | "switch-panel" | "camera"
  | "fender-flare" | "brace-kit" | "interior" | "recovery"
  | "cooling" | "exhaust" | "axle" | "heater";

export type AccessoryMountPosition = "front" | "rear" | "roof" | "bed" | "sides" | "distributed";

export interface UTVAccessory {
  id: string;
  brand: string;
  model: string;
  category: AccessoryCategory;
  weightLbs: number;
  mountPosition: AccessoryMountPosition;
  isCosmetic: boolean;
  affiliateUrl: string;
  compatibleMachines: string[] | "all";
  fuelCapacityGal?: number; // For fuel cells — dry weight in weightLbs, full = weightLbs + (fuelCapacityGal * 6.3)
  notes?: string;
}

export const accessories: UTVAccessory[] = [
  // ── Windshields (6) ──────────────────────────────────────────────────
  {
    id: "superatv-full-windshield-glass",
    brand: "SuperATV",
    model: "Full Windshield (Glass)",
    category: "windshield",
    weightLbs: 25,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B08J7L52QT?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Laminated safety glass, scratch-resistant",
  },
  {
    id: "superatv-half-windshield",
    brand: "SuperATV",
    model: "Half Windshield",
    category: "windshield",
    weightLbs: 12,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07HBDGYP9?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Polycarbonate, good airflow compromise",
  },
  {
    id: "seizmik-vented-windshield",
    brand: "Seizmik",
    model: "Vented Windshield",
    category: "windshield",
    weightLbs: 18,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01JSG1JRO?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Adjustable vents for airflow control",
  },
  {
    id: "kolpin-half-fold-windshield",
    brand: "Kolpin",
    model: "Half-Fold Windshield",
    category: "windshield",
    weightLbs: 14,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00DQ6SIGI?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Folds down for open-air riding",
  },
  {
    id: "cfmoto-oem-full-windshield",
    brand: "CFMOTO",
    model: "OEM Full Windshield",
    category: "windshield",
    weightLbs: 20,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["cfmoto-zforce-950", "cfmoto-zforce-800", "cfmoto-uforce-1000"],
    notes: "CFMOTO factory fitment only",
  },
  {
    id: "polaris-poly-full-windshield",
    brand: "Polaris",
    model: "Poly Full Windshield",
    category: "windshield",
    weightLbs: 15,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp", "polaris-rzr-200"],
    notes: "Polaris Lock & Ride compatible",
  },

  // ── Doors (5) ────────────────────────────────────────────────────────
  {
    id: "superatv-half-doors",
    brand: "SuperATV",
    model: "Half Doors (Pair)",
    category: "doors",
    weightLbs: 35,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07M6V6VST?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Aluminum frame, keeps debris out of cab",
  },
  {
    id: "pro-armor-suicide-doors",
    brand: "Pro Armor",
    model: "Suicide Doors (Pair)",
    category: "doors",
    weightLbs: 40,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B005G05F36?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Rear-hinged for easy entry/exit",
  },
  {
    id: "seizmik-full-doors",
    brand: "Seizmik",
    model: "Full Doors (Pair)",
    category: "doors",
    weightLbs: 55,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B009XIWOEA?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Full enclosure with upper window cutout",
  },
  {
    id: "polaris-lock-ride-pro-fit-doors",
    brand: "Polaris",
    model: "Lock & Ride Pro-Fit Doors",
    category: "doors",
    weightLbs: 50,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp"],
    notes: "Polaris OEM tool-less install",
  },
  {
    id: "dragonfire-hiboy-doors",
    brand: "Dragonfire",
    model: "HiBoy Doors (Pair)",
    category: "doors",
    weightLbs: 30,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00UI00PYI?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Lightweight aluminum, lower profile",
  },

  // ── Roof (5) ─────────────────────────────────────────────────────────
  {
    id: "superatv-aluminum-roof",
    brand: "SuperATV",
    model: "Aluminum Roof",
    category: "roof",
    weightLbs: 28,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07QSWKV6P?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Powder-coated aluminum, rattle-free",
  },
  {
    id: "polaris-poly-sport-roof",
    brand: "Polaris",
    model: "Poly Sport Roof",
    category: "roof",
    weightLbs: 20,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp", "polaris-rzr-200"],
    notes: "Polaris OEM poly roof",
  },
  {
    id: "pro-armor-aluminum-sport-roof",
    brand: "Pro Armor",
    model: "Aluminum Sport Roof",
    category: "roof",
    weightLbs: 25,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B071XWFX7F?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "razorback-soft-top",
    brand: "Razorback",
    model: "Soft Top",
    category: "roof",
    weightLbs: 8,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Lightweight fabric, easy on/off",
  },
  {
    id: "dragonfire-aluminum-roof",
    brand: "Dragonfire",
    model: "Aluminum Roof",
    category: "roof",
    weightLbs: 24,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07HF682GQ?tag=prepperevo-20",
    compatibleMachines: "all",
  },

  // ── Front Bumper (5) ─────────────────────────────────────────────────
  {
    id: "superatv-front-bumper",
    brand: "SuperATV",
    model: "Front Bumper",
    category: "bumper-front",
    weightLbs: 35,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0821QR74V?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Heavy-duty steel with winch mount",
  },
  {
    id: "hmf-front-bumper",
    brand: "HMF",
    model: "Front Bumper",
    category: "bumper-front",
    weightLbs: 40,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07QYBNZ3T?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Steel tube construction",
  },
  {
    id: "assault-industries-apache-front-bumper",
    brand: "Assault Industries",
    model: "Apache Front Bumper",
    category: "bumper-front",
    weightLbs: 45,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07NF4NN9F?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Integrated winch plate and D-ring mounts",
  },
  {
    id: "pro-armor-front-bumper",
    brand: "Pro Armor",
    model: "Front Bumper",
    category: "bumper-front",
    weightLbs: 38,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07PGQDK8F?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "can-am-oem-front-bumper",
    brand: "Can-Am",
    model: "OEM Front Bumper",
    category: "bumper-front",
    weightLbs: 30,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["can-am-maverick-x3", "can-am-maverick-sport", "can-am-defender"],
    notes: "Can-Am factory accessory",
  },

  // ── Rear Bumper (5) ──────────────────────────────────────────────────
  {
    id: "superatv-rear-bumper",
    brand: "SuperATV",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 30,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07PVZMW17?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "hmf-rear-bumper",
    brand: "HMF",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 35,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01MXTPQDO?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "assault-industries-rear-bumper",
    brand: "Assault Industries",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 40,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B072KGKKWJ?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "pro-armor-rear-bumper",
    brand: "Pro Armor",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 32,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00NPUZCH8?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "tusk-rear-bumper",
    brand: "Tusk",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 28,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00I48HZ3K?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Budget-friendly steel construction",
  },

  // ── Winch (5) ────────────────────────────────────────────────────────
  {
    id: "warn-vrx-45s",
    brand: "WARN",
    model: "VRX 45-S",
    category: "winch",
    weightLbs: 25,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B091XX4TZP?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, synthetic rope",
  },
  {
    id: "superatv-4500-black-ops",
    brand: "SuperATV",
    model: "4500 lb Black Ops Winch",
    category: "winch",
    weightLbs: 22,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07TNLH72L?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, synthetic rope",
  },
  {
    id: "kfi-se45-r2",
    brand: "KFI",
    model: "SE45-R2",
    category: "winch",
    weightLbs: 20,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01N6VN6I0?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, stealth series",
  },
  {
    id: "warn-provantage-4500s",
    brand: "WARN",
    model: "ProVantage 4500-S",
    category: "winch",
    weightLbs: 27,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B008BYQBUA?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, corrosion-resistant",
  },
  {
    id: "kolpin-4500-winch",
    brand: "Kolpin",
    model: "4500 lb Winch",
    category: "winch",
    weightLbs: 23,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B075FSBP38?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, steel cable",
  },

  // ── Skid Plates (5) ──────────────────────────────────────────────────
  {
    id: "superatv-full-skid-plate-kit",
    brand: "SuperATV",
    model: "Full Skid Plate Kit",
    category: "skid-plate",
    weightLbs: 45,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01MZ2LDKX?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "HDPE, covers front to rear",
  },
  {
    id: "factory-utv-uhmw-skid-plate",
    brand: "Factory UTV",
    model: "UHMW Skid Plate",
    category: "skid-plate",
    weightLbs: 35,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01CXOUCP8?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "3/8-inch UHMW polyethylene, self-healing",
  },
  {
    id: "sss-off-road-skid-plates",
    brand: "SSS Off Road",
    model: "Skid Plates",
    category: "skid-plate",
    weightLbs: 50,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00M94UJ1A?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Aluminum, full coverage belly pan",
  },
  {
    id: "trail-armor-skid-plate-set",
    brand: "Trail Armor",
    model: "Skid Plate Set",
    category: "skid-plate",
    weightLbs: 40,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
  },
  {
    id: "polaris-oem-skid-plate",
    brand: "Polaris",
    model: "OEM Skid Plate",
    category: "skid-plate",
    weightLbs: 30,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp"],
    notes: "Polaris factory skid plate kit",
  },

  // ── Rock Sliders (4) ─────────────────────────────────────────────────
  {
    id: "superatv-rock-sliders",
    brand: "SuperATV",
    model: "Rock Sliders",
    category: "rock-slider",
    weightLbs: 35,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07KMLDR2J?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Heavy-duty steel tree kickers",
  },
  {
    id: "s3-power-sports-rock-sliders",
    brand: "S3 Power Sports",
    model: "Rock Sliders",
    category: "rock-slider",
    weightLbs: 40,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07JJ5VKV3?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "pro-armor-rock-sliders",
    brand: "Pro Armor",
    model: "Rock Sliders",
    category: "rock-slider",
    weightLbs: 38,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0CBS91DR8?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "tusk-nerf-bars",
    brand: "Tusk",
    model: "Nerf Bars",
    category: "rock-slider",
    weightLbs: 25,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B003QSE7Z2?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Doubles as step and rocker protection",
  },

  // ── Roof Rack (4) ────────────────────────────────────────────────────
  {
    id: "superatv-cargo-roof-rack",
    brand: "SuperATV",
    model: "Cargo Roof Rack",
    category: "roof-rack",
    weightLbs: 30,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0CNS4D5P9?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Steel construction, 100+ lb capacity",
  },
  {
    id: "razorback-roof-rack",
    brand: "Razorback",
    model: "Roof Rack",
    category: "roof-rack",
    weightLbs: 25,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0D7QW2S4Y?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "pro-armor-roof-rack",
    brand: "Pro Armor",
    model: "Roof Rack",
    category: "roof-rack",
    weightLbs: 28,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
  },
  {
    id: "polaris-lock-ride-cargo-rack",
    brand: "Polaris",
    model: "Lock & Ride Cargo Rack",
    category: "roof-rack",
    weightLbs: 22,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp"],
    notes: "Polaris Lock & Ride tool-less mount",
  },

  // ── Cargo Rack (3) ───────────────────────────────────────────────────
  {
    id: "superatv-rear-cargo-rack",
    brand: "SuperATV",
    model: "Rear Cargo Rack",
    category: "cargo-rack",
    weightLbs: 18,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B08P51J88S?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "kolpin-rear-cargo-rack",
    brand: "Kolpin",
    model: "Rear Cargo Rack",
    category: "cargo-rack",
    weightLbs: 15,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B09G697TG6?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "tusk-rear-cargo-box",
    brand: "Tusk",
    model: "Rear Cargo Box",
    category: "cargo-rack",
    weightLbs: 25,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07FKRK2K7?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Lockable, weatherproof storage",
  },

  // ── Light Bar (5) ────────────────────────────────────────────────────
  {
    id: "rigid-industries-30-led-bar",
    brand: "Rigid Industries",
    model: '30" LED Bar',
    category: "light-bar",
    weightLbs: 8,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00GQGWLQ8?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "E-Series, combo spot/flood beam",
  },
  {
    id: "baja-designs-onx6-30",
    brand: "Baja Designs",
    model: 'OnX6+ 30"',
    category: "light-bar",
    weightLbs: 7,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00Q5F9DR0?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "High-output laser hybrid, driving/combo",
  },
  {
    id: "kc-hilites-c-series-30",
    brand: "KC HiLites",
    model: 'C-Series 30"',
    category: "light-bar",
    weightLbs: 9,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B000630CCC?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Combo beam, IP68 rated",
  },
  {
    id: "rigid-radiance-plus-40",
    brand: "Rigid",
    model: 'Radiance+ 40"',
    category: "light-bar",
    weightLbs: 10,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0C2FLCW1K?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Multi-color backlight, broad scene light",
  },
  {
    id: "nilight-32-combo-beam",
    brand: "Nilight",
    model: '32" Combo Beam',
    category: "light-bar",
    weightLbs: 5,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01DNYCJQW?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Budget-friendly, spot/flood combo",
  },

  // ── Sound System (3) — all cosmetic ──────────────────────────────────
  {
    id: "ssv-works-5-speaker-kit",
    brand: "SSV Works",
    model: "5-Speaker Kit",
    category: "sound-system",
    weightLbs: 15,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B07KTDD6MS?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Includes head unit, 4 speakers, sub",
  },
  {
    id: "rockford-fosgate-stage-3-kit",
    brand: "Rockford Fosgate",
    model: "Stage 3 Kit",
    category: "sound-system",
    weightLbs: 22,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B079R818CT?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "PMX head unit, 4 speakers, amp, sub",
  },
  {
    id: "mb-quart-tuned-audio-kit",
    brand: "MB Quart",
    model: "Tuned Audio Kit",
    category: "sound-system",
    weightLbs: 18,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B07V9PFBWX?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Stage 5 tuned for UTV cab",
  },

  // ── Mirrors (3) ──────────────────────────────────────────────────────
  {
    id: "seizmik-pursuit-side-mirrors",
    brand: "Seizmik",
    model: "Pursuit Side Mirrors",
    category: "mirrors",
    weightLbs: 3,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00T6JDIVY?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Clamp-on, fits 1.75-2 inch cage",
  },
  {
    id: "assault-industries-bomber-mirrors",
    brand: "Assault Industries",
    model: "Bomber Side Mirrors",
    category: "mirrors",
    weightLbs: 4,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B079T89MVC?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Convex glass, breakaway design",
  },
  {
    id: "superatv-side-mirrors",
    brand: "SuperATV",
    model: "Side Mirrors",
    category: "mirrors",
    weightLbs: 3,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B016AQ6OIO?tag=prepperevo-20",
    compatibleMachines: "all",
  },

  // ── Fridge Mount (8) ─────────────────────────────────────────────────
  {
    id: "expedition-essentials-fridge-slide",
    brand: "Expedition Essentials",
    model: "Fridge Slide",
    category: "fridge-mount",
    weightLbs: 20,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Locking slide-out, fits 40-60L fridges",
  },
  {
    id: "front-runner-utv-fridge-mount",
    brand: "Front Runner",
    model: "UTV Fridge Mount",
    category: "fridge-mount",
    weightLbs: 18,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0114QO9VE?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Strapped tie-down plate with vibration damping",
  },
  {
    id: "dfg-fridge-slide-cfx95dz",
    brand: "DFG Offroad",
    model: "Fridge Slide Sideways — CFX 95DZ",
    category: "fridge-mount",
    weightLbs: 35,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.dfgoffroad.com/",
    compatibleMachines: "all",
    notes: "Sideways slide-out for Dometic CFX5 95DZ. 38.75\"L x 23.75\"W x 3\"H, tray 37\"x21.75\", 1\" tray height above base, 36\" extension, lock in/out, 350 lb rated capacity. $459.99.",
  },
  {
    id: "dfg-fridge-slide-cfx3-35-45",
    brand: "DFG Offroad",
    model: "Fridge Slide — CFX3 35-45",
    category: "fridge-mount",
    weightLbs: 25,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.dfgoffroad.com/",
    compatibleMachines: "all",
    notes: "Fits Dometic CFX3 35 and CFX3 45. Steel construction. $299.99.",
  },
  {
    id: "dfg-fridge-slide-cfx3-55im",
    brand: "DFG Offroad",
    model: "Fridge Slide Sideways — CFX3 55IM",
    category: "fridge-mount",
    weightLbs: 30,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.dfgoffroad.com/",
    compatibleMachines: "all",
    notes: "Sideways slide-out for Dometic CFX3 55IM. Steel. $309.99.",
  },
  {
    id: "dfg-fridge-slide-cfx5-25",
    brand: "DFG Offroad",
    model: "Fridge Slide — CFX5 25",
    category: "fridge-mount",
    weightLbs: 20,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.dfgoffroad.com/",
    compatibleMachines: "all",
    notes: "Fits Dometic CFX5 25. Compact steel slide. $259.99.",
  },
  {
    id: "dfg-fridge-slide-arb-zero-47",
    brand: "DFG Offroad",
    model: "Fridge Slide — ARB Zero 47Qt",
    category: "fridge-mount",
    weightLbs: 28,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.dfgoffroad.com/",
    compatibleMachines: "all",
    notes: "Fits ARB Zero 47 Qt. Steel. $314.99.",
  },
  {
    id: "dfg-fridge-slide-arb-63-82",
    brand: "DFG Offroad",
    model: "Fridge Slide — ARB 63-82Qt",
    category: "fridge-mount",
    weightLbs: 35,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.dfgoffroad.com/",
    compatibleMachines: "all",
    notes: "Fits ARB 63-82 Qt fridges. Steel. $389.99.",
  },

  // ── Dual Battery (2) ─────────────────────────────────────────────────
  {
    id: "odyssey-dual-battery-kit",
    brand: "Odyssey",
    model: "Dual Battery Kit",
    category: "dual-battery",
    weightLbs: 35,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "AGM batteries with isolator relay",
  },
  {
    id: "xs-power-dual-battery",
    brand: "XS Power",
    model: "Dual Battery Kit",
    category: "dual-battery",
    weightLbs: 30,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Lithium, lighter weight for same capacity",
  },

  // ── Solar Panel (2) ──────────────────────────────────────────────────
  {
    id: "renogy-100w-flex-panel",
    brand: "Renogy",
    model: "100W Flex Panel",
    category: "solar-panel",
    weightLbs: 5,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B09W21FRBC?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Flexible monocrystalline, mounts to roof with adhesive or bolts",
  },
  {
    id: "goal-zero-boulder-50",
    brand: "Goal Zero",
    model: "Boulder 50",
    category: "solar-panel",
    weightLbs: 12,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B06Y3XMQTK?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Rigid panel, tempered glass, high durability",
  },

  // ── RTT Mount (2) ────────────────────────────────────────────────────
  {
    id: "cbi-offroad-utv-tent-mount",
    brand: "CBI Offroad",
    model: "UTV Tent Mount",
    category: "rtt-mount",
    weightLbs: 40,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Rated for 2-person RTT, requires roof or cage mount",
  },
  {
    id: "diy-universal-tent-mount-frame",
    brand: "DIY",
    model: "Universal Tent Mount Frame",
    category: "rtt-mount",
    weightLbs: 35,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Weld-on or bolt-on universal frame, check cage rating",
  },

  // ── Spare Tire Carrier (2) ───────────────────────────────────────────
  {
    id: "superatv-spare-tire-carrier",
    brand: "SuperATV",
    model: "Spare Tire Carrier",
    category: "spare-tire-carrier",
    weightLbs: 20,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B06Y344JNV?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Bed-mount, fits up to 32-inch tires",
  },
  {
    id: "assault-industries-spare-tire-carrier",
    brand: "Assault Industries",
    model: "Spare Tire Carrier",
    category: "spare-tire-carrier",
    weightLbs: 22,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B077P7L36J?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Rear cage mount, quick-release",
  },

  // ── Fuel Can Rack (2) ────────────────────────────────────────────────
  {
    id: "rotopax-2gal-mount-kit",
    brand: "Rotopax",
    model: "2-Gal Mount Kit (with 2 Cans)",
    category: "fuel-can-rack",
    weightLbs: 15,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B003YBMDRU?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "2x 2-gallon cans + LOX pack mount",
  },
  {
    id: "rotopax-4gal-mount-kit",
    brand: "Rotopax",
    model: "4-Gal Mount Kit (with 2 Cans)",
    category: "fuel-can-rack",
    weightLbs: 22,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07GD2DRS3?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "2x 4-gallon cans + LOX pack mount, extends range significantly",
  },

  // ── LED Whip (3) — all cosmetic ─────────────────────────────────────
  {
    id: "gorilla-whips-4ft-led-pair",
    brand: "Gorilla Whips",
    model: "4ft LED Whip (Pair)",
    category: "led-whip",
    weightLbs: 4,
    mountPosition: "rear",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B072VMR58F?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "RGB, Bluetooth app controlled",
  },
  {
    id: "5150-whips-4ft-led-pair",
    brand: "5150 Whips",
    model: "4ft LED Whip (Pair)",
    category: "led-whip",
    weightLbs: 4,
    mountPosition: "rear",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B07DKY4TVR?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Multicolor, quick-release base",
  },
  {
    id: "tribal-whips-3ft-led-pair",
    brand: "Tribal Whips",
    model: "3ft LED Whip (Pair)",
    category: "led-whip",
    weightLbs: 3,
    mountPosition: "rear",
    isCosmetic: true,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Budget-friendly, multiple color modes",
  },

  // ── Underglow (2) — all cosmetic ────────────────────────────────────
  {
    id: "oracle-underbody-led-kit",
    brand: "Oracle",
    model: "Underbody LED Kit",
    category: "underglow",
    weightLbs: 3,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B06XPCFRNK?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "IP67, Bluetooth color control",
  },
  {
    id: "opt7-aura-pro-underglow",
    brand: "OPT7",
    model: "Aura Pro Underglow",
    category: "underglow",
    weightLbs: 2,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B09XWCTJMW?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Flexible strip, music-sync mode",
  },

  // ── Sound Bar (2) — all cosmetic ────────────────────────────────────
  {
    id: "boss-audio-brt18a",
    brand: "Boss Audio",
    model: "BRT18A Sound Bar",
    category: "sound-bar",
    weightLbs: 8,
    mountPosition: "roof",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B08F9NTB2G?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "18-inch, Bluetooth, built-in amp",
  },
  {
    id: "kicker-utv-sound-bar",
    brand: "Kicker",
    model: "UTV Sound Bar",
    category: "sound-bar",
    weightLbs: 10,
    mountPosition: "roof",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B09DYW5VY1?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "All-weather, cage clamp mount",
  },

  // ── Fuel Cells (5) ──────────────────────────────────────────────────────
  {
    id: "fuel-safe-10gal",
    brand: "Fuel Safe",
    model: "10-Gallon UTV Fuel Cell",
    category: "fuel-cell",
    weightLbs: 25,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07BNKH8WY?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 10,
    notes: "25 lbs dry, 88 lbs full. Aircraft-grade aluminum.",
  },
  {
    id: "fuel-safe-15gal",
    brand: "Fuel Safe",
    model: "15-Gallon UTV Fuel Cell",
    category: "fuel-cell",
    weightLbs: 30,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07BNKH8WY?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 15,
    notes: "30 lbs dry, 124 lbs full. Aircraft-grade aluminum.",
  },
  {
    id: "jaz-10gal",
    brand: "Jaz Products",
    model: "10-Gallon Pro Sport Cell",
    category: "fuel-cell",
    weightLbs: 22,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B004P2QQJ2?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 10,
    notes: "22 lbs dry, 85 lbs full. Polyethylene with foam baffles.",
  },
  {
    id: "rci-12gal",
    brand: "RCI",
    model: "12-Gallon Fuel Cell",
    category: "fuel-cell",
    weightLbs: 28,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B001O4ARRY?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 12,
    notes: "28 lbs dry, 103 lbs full. Steel container.",
  },
  {
    id: "rjs-8gal",
    brand: "RJS Racing",
    model: "8-Gallon Drag Cell",
    category: "fuel-cell",
    weightLbs: 20,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B001LF3R1S?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 8,
    notes: "20 lbs dry, 70 lbs full. Compact design for smaller beds.",
  },

  // ── Light Pods (10) ────────────────────────────────────────────────────
  {
    id: "roadshock-6in-flood",
    brand: "Roadshock",
    model: "6\" LED Floodlight",
    category: "light-pod",
    weightLbs: 1.4,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Harbor Freight budget flood. Item #57190.",
  },
  {
    id: "roadshock-3in-sidelight-pair",
    brand: "Roadshock",
    model: "3\" LED Flood w/ Sidelight (Pair)",
    category: "light-pod",
    weightLbs: 3.5,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Harbor Freight. Item #57539. Price of a fast food meal.",
  },
  {
    id: "nilight-18w-pods-pair",
    brand: "Nilight",
    model: "4\" 18W Flood/Spot Pods (Pair)",
    category: "light-pod",
    weightLbs: 2,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Budget king. 1,260 lumens per pod. IP67.",
  },
  {
    id: "nilight-60w-pods-pair",
    brand: "Nilight",
    model: "4\" 60W Triple Row Pods (Pair)",
    category: "light-pod",
    weightLbs: 2.4,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "6,000 lumens per pod. Triple row LED.",
  },
  {
    id: "rigid-d-series-pro-pair",
    brand: "Rigid Industries",
    model: "D-Series PRO Pods (Pair)",
    category: "light-pod",
    weightLbs: 2.3,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Classic 3\" cube light. Industry standard.",
  },
  {
    id: "rigid-srm-pro",
    brand: "Rigid Industries",
    model: "SR-M Series PRO Pod",
    category: "light-pod",
    weightLbs: 0.6,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Tiny but powerful. Surface or flush mount.",
  },
  {
    id: "kc-flex-era-1",
    brand: "KC HiLiTES",
    model: "FLEX ERA 1 Pod",
    category: "light-pod",
    weightLbs: 4,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Premium. Interchangeable optics system.",
  },
  {
    id: "kc-flex-era-3",
    brand: "KC HiLiTES",
    model: "FLEX ERA 3 Pod",
    category: "light-pod",
    weightLbs: 3.75,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Premium. SAE fog option available.",
  },
  {
    id: "kc-flex-era-4",
    brand: "KC HiLiTES",
    model: "FLEX ERA 4 Pod",
    category: "light-pod",
    weightLbs: 3.4,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Premium. Largest Flex Era pod.",
  },
  {
    id: "aurora-10in-bar",
    brand: "Aurora",
    model: "10\" Single Row Bar (75W)",
    category: "light-pod",
    weightLbs: 2.4,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "IP69K rated. 6063 aluminum + Lexan lens.",
  },

  // ── Harnesses (8) ─────────────────────────────────────────────────────
  {
    id: "click6-6pt-harness",
    brand: "Click-6",
    model: "6-Point Racing Harness",
    category: "harness",
    weightLbs: 5.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "IMMI 6-point retractable. Quick-release cam buckle.",
  },
  {
    id: "prp-42-harness",
    brand: "PRP Seats",
    model: "4.2 Harness (4-Point, 2\" Straps)",
    category: "harness",
    weightLbs: 6,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Auto-style latch, sewn-in pads. Sold per seat.",
  },
  {
    id: "dragonfire-4pt-harness",
    brand: "DragonFire Racing",
    model: "H-Style 4-Point EZ-Adjust Harness",
    category: "harness",
    weightLbs: 6,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Memory foam pads, sternum clip. 2\" and 3\" options.",
  },
  {
    id: "pro-armor-4pt-harness",
    brand: "Pro Armor",
    model: "4-Point Harness 3\"",
    category: "harness",
    weightLbs: 5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "3\" straps with sewn-in pads. Phone pocket built in.",
  },
  {
    id: "beard-4pt-harness",
    brand: "Beard Seats",
    model: "4-Point Safety Harness (2\" Auto Buckle)",
    category: "harness",
    weightLbs: 4,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "2\" lap + shoulder straps, sternum strap, auto buckle.",
  },
  {
    id: "prp-gt-se-seat",
    brand: "PRP Seats",
    model: "GT/S.E. Suspension Seat",
    category: "harness",
    weightLbs: 20,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Premium suspension seat. Extra wide. Made in USA. Per seat.",
  },
  {
    id: "utvma-bump-seat-front",
    brand: "UTVMA",
    model: "Bump Seat (Center/Front)",
    category: "harness",
    weightLbs: 8,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Center jump seat for kids up to 60 lbs. 4-point harness included.",
  },
  {
    id: "utvma-bump-seat-rear",
    brand: "UTVMA",
    model: "Bump Seat (Rear)",
    category: "harness",
    weightLbs: 8,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Rear-mount jump seat for KRX4 and other 4-seaters.",
  },

  // ── Storage (10) ──────────────────────────────────────────────────────
  {
    id: "milwaukee-packout-22-rolling",
    brand: "Milwaukee",
    model: "Packout 22\" Rolling Tool Box",
    category: "storage",
    weightLbs: 23.4,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Empty weight. Heavy but bomb-proof. IP65 sealed.",
  },
  {
    id: "milwaukee-packout-slim",
    brand: "Milwaukee",
    model: "Packout Low-Profile Organizer",
    category: "storage",
    weightLbs: 4.6,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Slim box. Great for bolts, fuses, small parts.",
  },
  {
    id: "prosteel-packout-plate-triple",
    brand: "ProSteel",
    model: "Heavy Duty Packout Locking Plate (Triple)",
    category: "storage",
    weightLbs: 9.6,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "10ga steel mounting plate. Locks Packout boxes to cage/bed.",
  },
  {
    id: "kemimoto-door-bags-pair",
    brand: "Kemimoto",
    model: "UTV Door Storage Bags (Pair)",
    category: "storage",
    weightLbs: 2,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "1680D nylon, water repellent. Various fitments.",
  },
  {
    id: "prp-door-bags-pair",
    brand: "PRP Seats",
    model: "KRX Door Bags (Pair)",
    category: "storage",
    weightLbs: 3.5,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Marine-grade fabric, zippers, mounting hardware.",
  },
  {
    id: "superatv-door-bags-pair",
    brand: "SuperATV",
    model: "Universal UTV Door Bags (Pair)",
    category: "storage",
    weightLbs: 2,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Water-resistant. Snap + velcro mounting.",
  },
  {
    id: "tusk-utv-cargo-box",
    brand: "Tusk",
    model: "UTV Cargo Box",
    category: "storage",
    weightLbs: 85,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Aluminum (0.1\" thick). Dual gasket seal, gas struts, lockable. HEAVY.",
  },
  {
    id: "kolpin-saddle-storage",
    brand: "Kolpin",
    model: "UTV Saddle Storage Box",
    category: "storage",
    weightLbs: 12,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Roto-molded, ~10 gallon. Mounts inside bed rails. Lockable.",
  },
  {
    id: "kemimoto-center-console-bag",
    brand: "Kemimoto",
    model: "UTV Center Console Bag",
    category: "storage",
    weightLbs: 1.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "4.4L capacity. Water resistant. Universal fitment.",
  },
  {
    id: "kemimoto-under-seat-bag",
    brand: "Kemimoto",
    model: "UTV Under-Seat Storage Bag",
    category: "storage",
    weightLbs: 1.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Hidden storage under bench or bucket seats.",
  },

  // ── Switch Panels (8) ─────────────────────────────────────────────────
  {
    id: "auxbeam-ba80",
    brand: "Auxbeam",
    model: "BA80 8-Gang LED Switch Panel",
    category: "switch-panel",
    weightLbs: 6.6,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Blue backlight. On/off. One-sided outlet. The classic.",
  },
  {
    id: "auxbeam-bc60",
    brand: "Auxbeam",
    model: "BC60 6-Gang LED Switch Panel",
    category: "switch-panel",
    weightLbs: 4,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "6 circuits. Blue backlight.",
  },
  {
    id: "auxbeam-ar800",
    brand: "Auxbeam",
    model: "AR-800 8-Gang RGB Switch Panel (App)",
    category: "switch-panel",
    weightLbs: 5.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "RGB with Bluetooth app. Toggle/momentary/pulsed modes.",
  },
  {
    id: "auxbeam-ar600",
    brand: "Auxbeam",
    model: "AR-600 6-Gang RGB Switch Panel (App)",
    category: "switch-panel",
    weightLbs: 2.4,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Lightest 6-gang. RGB + Bluetooth app control.",
  },
  {
    id: "auxbeam-ac800",
    brand: "Auxbeam",
    model: "AC-800 8-Gang RGB (App + Remote)",
    category: "switch-panel",
    weightLbs: 8.8,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Premium. RGB + app + wireless remote.",
  },
  {
    id: "auxbeam-ac1200",
    brand: "Auxbeam",
    model: "AC-1200 12-Gang RGB (App + Remote)",
    category: "switch-panel",
    weightLbs: 9.3,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "12-gang flagship. Heaviest panel. Full RGB + app + remote.",
  },
  {
    id: "xtc-power-6-switch",
    brand: "XTC Power",
    model: "6-Switch Power Control System",
    category: "switch-panel",
    weightLbs: 2.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Plug-and-play. 1x30A, 3x20A relayed, 2x10A direct.",
  },
  {
    id: "brute-perf-fuse-block",
    brand: "Brute Performance",
    model: "KRX Fuse Block (9 Circuit)",
    category: "switch-panel",
    weightLbs: 1.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "5 hot-all-time + 4 keyed circuits. Waterproof. 100A total.",
  },

  // ── Cameras (3) ───────────────────────────────────────────────────────
  {
    id: "utv-front-rear-camera-system",
    brand: "Generic",
    model: "UTV Front + Rear Camera System (7\" Monitor)",
    category: "camera",
    weightLbs: 4,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "2 IP67 cameras + 7\" monitor + wiring. Great for trails.",
  },
  {
    id: "brandmotion-summitview",
    brand: "Brandmotion",
    model: "SummitView UTV Camera System",
    category: "camera",
    weightLbs: 5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Premium UTV-specific front + rear cameras. Weatherproof.",
  },
  {
    id: "utv-single-rear-camera",
    brand: "Generic",
    model: "UTV Rear Camera w/ Mirror Monitor",
    category: "camera",
    weightLbs: 2,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Single rear camera with rearview mirror display.",
  },

  // ── Fender Flares (4) ─────────────────────────────────────────────────
  {
    id: "spike-fender-flares-set",
    brand: "Spike",
    model: "Fender Flares (Set of 4)",
    category: "fender-flare",
    weightLbs: 7,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "HMW polyethylene. 0.125\" thick. Front + rear.",
  },
  {
    id: "superatv-fender-flares-front",
    brand: "SuperATV",
    model: "Fender Flare Extensions (Front Pair)",
    category: "fender-flare",
    weightLbs: 4,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Bolt-on, no drilling. Keeps mud off the cab.",
  },
  {
    id: "superatv-fender-flares-rear",
    brand: "SuperATV",
    model: "Fender Flare Extensions (Rear Pair)",
    category: "fender-flare",
    weightLbs: 4,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Bolt-on rear fender extensions.",
  },
  {
    id: "mudbusters-fender-flares-set",
    brand: "MudBusters",
    model: "Fender Flares (Full Set)",
    category: "fender-flare",
    weightLbs: 8,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Extra-wide coverage. HDPE construction.",
  },

  // ── Brace / Guard Kits (8) ────────────────────────────────────────────
  {
    id: "emp-front-shock-braces",
    brand: "EMP",
    model: "Front Shock Mount Braces",
    category: "brace-kit",
    weightLbs: 2,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Bolt-on reinforcement for front shock mounts.",
  },
  {
    id: "fullaccessutv-a-arm-brace",
    brand: "Full Access UTV",
    model: "A-Arm Tab Support Kit (Ultimate)",
    category: "brace-kit",
    weightLbs: 3,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Uppers + lowers. 1,361g. Must-have for KRX.",
  },
  {
    id: "fullaccessutv-rear-braces",
    brand: "Full Access UTV",
    model: "Rear Shock Mount Braces",
    category: "brace-kit",
    weightLbs: 1.5,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "680g. Prevents rear shock mount cracking.",
  },
  {
    id: "brute-perf-shock-tower-guard",
    brand: "Brute Performance",
    model: "Shock Tower Guard/Brace (3/16\" Steel)",
    category: "brace-kit",
    weightLbs: 4,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "3/16\" steel. Protects shock tower from rock strikes.",
  },
  {
    id: "sss-uhmw-a-arm-guards",
    brand: "SSS Offroad",
    model: "UHMW Front A-Arm Guards",
    category: "brace-kit",
    weightLbs: 8,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "3/8\" thick UHMW. Confirmed weight.",
  },
  {
    id: "trail-armor-impact-guards",
    brand: "Trail Armor",
    model: "iMpact Front A-Arm Guards",
    category: "brace-kit",
    weightLbs: 10,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "1/2\" super-tough polymer. 3-sided CV boot protection.",
  },
  {
    id: "utvconnect-trans-skid",
    brand: "UTV Connect",
    model: "Transmission Skid Plate (1/8\" Steel)",
    category: "brace-kit",
    weightLbs: 9,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Press-formed 1/8\" steel. Drain holes included.",
  },
  {
    id: "frogskin-intake-guards",
    brand: "Frog Skin",
    model: "Intake Guards (Pair)",
    category: "brace-kit",
    weightLbs: 1.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Keeps debris out of intake vents. Various materials.",
  },

  // ── Interior (8) ──────────────────────────────────────────────────────
  {
    id: "prp-knee-pads-pair",
    brand: "PRP Seats",
    model: "Knee Guard Pads (Pair)",
    category: "interior",
    weightLbs: 1.2,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Foam padding with vinyl upholstery.",
  },
  {
    id: "ram-tablet-mount",
    brand: "RAM Mount",
    model: "X-Grip UTV Tablet Holder (9-11\")",
    category: "interior",
    weightLbs: 2.2,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Full assembly with arm and clamp.",
  },
  {
    id: "emp-shift-gate",
    brand: "EMP",
    model: "Speed/Gated Shifter Gate",
    category: "interior",
    weightLbs: 0.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Simple bolt-on shift gate plate. Budget-friendly.",
  },
  {
    id: "viper-billet-shift-gate",
    brand: "Viper Machine",
    model: "Complete Billet Gated Shift System (6 pcs)",
    category: "interior",
    weightLbs: 2,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "6061-T6 aluminum. Replaces stock plastic. Premium.",
  },
  {
    id: "billet-fuel-rail",
    brand: "ZRP / S&S",
    model: "Billet Aluminum Fuel Rail",
    category: "interior",
    weightLbs: 0.75,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "6061 billet aluminum. Replaces OEM plastic fuel rail.",
  },
  {
    id: "jbl-rallybar-xl",
    brand: "JBL",
    model: "Rally Bar XL",
    category: "sound-system",
    weightLbs: 21,
    mountPosition: "roof",
    isCosmetic: true,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "20.83 lbs soundbar + mounts. IP66 rated. 300W.",
  },
  {
    id: "mob-armor-phone-mount",
    brand: "Mob Armor",
    model: "Switch Magnetic Phone Mount",
    category: "interior",
    weightLbs: 0.5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Magnetic mount for phones. Clamps to cage/dash.",
  },
  {
    id: "assault-industries-steering-wheel",
    brand: "Assault Industries",
    model: "Navigator Suede Steering Wheel + Quick Release",
    category: "interior",
    weightLbs: 3,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Suede grip, quick-release hub. Replaces stock wheel.",
  },

  // ── Recovery Gear (10) ────────────────────────────────────────────────
  {
    id: "bubba-rope-78-20ft",
    brand: "Bubba Rope",
    model: "7/8\" x 20' Kinetic Recovery Rope",
    category: "recovery",
    weightLbs: 8,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "28,600 lb breaking strength. Double-braided nylon. Made in USA.",
  },
  {
    id: "bubba-rope-78-30ft",
    brand: "Bubba Rope",
    model: "7/8\" x 30' Kinetic Recovery Rope",
    category: "recovery",
    weightLbs: 12,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "28,600 lb breaking strength. Longer version.",
  },
  {
    id: "yankum-78-30ft",
    brand: "Yankum Ropes",
    model: "7/8\" x 30' Kinetic Rope",
    category: "recovery",
    weightLbs: 11,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Made in USA. HMPE fiber.",
  },
  {
    id: "yankum-soft-shackle-half",
    brand: "Yankum Ropes",
    model: "1/2\" Soft Shackle",
    category: "recovery",
    weightLbs: 0.25,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "38,000 lb breaking strength. HMPE fiber.",
  },
  {
    id: "hilift-hl484",
    brand: "Hi-Lift",
    model: "HL-484 48\" Cast/Steel Jack",
    category: "recovery",
    weightLbs: 30,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "4,660 lb rated / 7,000 lb tested. The OG recovery jack.",
  },
  {
    id: "hilift-xt605",
    brand: "Hi-Lift",
    model: "XT-605 60\" X-TREME Jack",
    category: "recovery",
    weightLbs: 28,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Lighter X-Treme series. Taller lift range.",
  },
  {
    id: "maxtrax-xtreme-pair",
    brand: "MAXTRAX",
    model: "XTREME Recovery Boards (Pair)",
    category: "recovery",
    weightLbs: 20,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "10 lbs each. 88 replaceable alloy teeth. Engineering-grade nylon.",
  },
  {
    id: "arb-hydraulic-jack-48",
    brand: "ARB",
    model: "48\" Hydraulic Recovery Jack",
    category: "recovery",
    weightLbs: 25,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "4,400 lb capacity. 6061 T6 aluminum. ~5 lbs lighter than Hi-Lift.",
  },
  {
    id: "vevor-kinetic-rope-78-30ft",
    brand: "VEVOR",
    model: "7/8\" x 30' Kinetic Recovery Rope",
    category: "recovery",
    weightLbs: 10,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "30,580 lb strength. 30% elasticity. Budget option.",
  },
  {
    id: "tre-tree-saver",
    brand: "TRE",
    model: "Tree Saver Soft Shackle",
    category: "recovery",
    weightLbs: 0.2,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "40,000 lb breaking strength. Quick release.",
  },

  // ── Cooling (5) ───────────────────────────────────────────────────────
  {
    id: "hess-radiator-relocate",
    brand: "Hess Motorsports",
    model: "Radiator Relocation Kit",
    category: "cooling",
    weightLbs: 20,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "CBR radiator, hoses, clamps, fan wire, hardware. ~$1,250.",
  },
  {
    id: "brute-perf-spal-fan",
    brand: "Brute Performance",
    model: "High Output SPAL Radiator Fan",
    category: "cooling",
    weightLbs: 7,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "14\" SPAL fan. 1800+ CFM (3x factory). Plug-and-play.",
  },
  {
    id: "fullaccessutv-spal-fan",
    brand: "Full Access UTV",
    model: "SPAL Radiator Fan Kit",
    category: "cooling",
    weightLbs: 6,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "1,300 CFM (2x factory). Aluminum shroud. Sealed SPAL motor.",
  },
  {
    id: "class1-oil-cooler",
    brand: "Class 1 Motorsports",
    model: "Oil Cooler Kit",
    category: "cooling",
    weightLbs: 9,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Derale cooler + dual fans + new oil pressure relief valve.",
  },
  {
    id: "antigravity-atx20-battery",
    brand: "Antigravity",
    model: "ATX20-HD Lithium Battery",
    category: "dual-battery",
    weightLbs: 5.2,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "900 CCA, 30Ah LiFePO4. SAVES ~8 lbs vs stock lead-acid.",
  },

  // ── Exhaust (4) ───────────────────────────────────────────────────────
  {
    id: "hmf-titan-xl-slip-on",
    brand: "HMF",
    model: "Titan XL Slip-On Exhaust",
    category: "exhaust",
    weightLbs: 8,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Stainless steel. Saves ~5 lbs over stock. Better flow.",
  },
  {
    id: "trinity-stage5-slip-on",
    brand: "Trinity Racing",
    model: "Stage 5 Slip-On Exhaust",
    category: "exhaust",
    weightLbs: 7,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Aluminum can. Saves ~6 lbs over stock.",
  },
  {
    id: "big-gun-evo-utility",
    brand: "Big Gun",
    model: "EVO Utility Slip-On",
    category: "exhaust",
    weightLbs: 9,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Stainless steel. USFS-approved spark arrestor.",
  },
  {
    id: "rjwc-slip-on",
    brand: "RJWC",
    model: "APX Slip-On Exhaust",
    category: "exhaust",
    weightLbs: 6,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Titanium option available (~4 lbs). Canadian-made.",
  },

  // ── Axles (5) ─────────────────────────────────────────────────────────
  {
    id: "superatv-rhino2-front-axle",
    brand: "SuperATV",
    model: "Rhino 2.0 HD Front Axle",
    category: "axle",
    weightLbs: 13,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "4340 chromoly. 4mm larger shaft. Per axle.",
  },
  {
    id: "superatv-rhino2-rear-axle",
    brand: "SuperATV",
    model: "Rhino 2.0 HD Rear Axle",
    category: "axle",
    weightLbs: 15,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "4340 chromoly. Slightly longer/heavier than front. Per axle.",
  },
  {
    id: "demon-hd-axle",
    brand: "Demon Powersports",
    model: "HD Axle",
    category: "axle",
    weightLbs: 13.2,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "15-20% larger diameter than stock. Per axle.",
  },
  {
    id: "allballs-6ball-axle",
    brand: "All Balls Racing",
    model: "6-Ball HD Axle",
    category: "axle",
    weightLbs: 5,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "30% stronger than competitors. Lighter duty. Per axle.",
  },
  {
    id: "allballs-8ball-extreme-axle",
    brand: "All Balls Racing",
    model: "8-Ball Extreme Duty Axle",
    category: "axle",
    weightLbs: 9,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "4340 chromoly bar. 35% larger CV joints. Per axle.",
  },

  // ── Heaters (3) ───────────────────────────────────────────────────────
  {
    id: "superatv-cab-heater",
    brand: "SuperATV",
    model: "UTV Cab Heater",
    category: "heater",
    weightLbs: 20,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "14,600 BTU, 135 CFM. Adjustable temp + fan speed.",
  },
  {
    id: "ice-crusher-compact-heater",
    brand: "Ice Crusher",
    model: "Compact Cab Heater (Universal)",
    category: "heater",
    weightLbs: 10,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "14,600 BTU, 180 CFM, 6 vents. Defrost option.",
  },
  {
    id: "ice-crusher-full-heater-kit",
    brand: "Ice Crusher",
    model: "Vehicle-Specific Full Heater Kit",
    category: "heater",
    weightLbs: 14,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Full kit with all hoses, fittings, vents for specific models.",
  },

  // ── Additional Windshield ─────────────────────────────────────────────
  {
    id: "tusk-folding-glass-windshield",
    brand: "Tusk",
    model: "Folding Glass Windshield w/ Wiper",
    category: "windshield",
    weightLbs: 40,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Laminated glass. Includes wiper motor. Heavy but premium.",
  },

  // ── Additional Roof ───────────────────────────────────────────────────
  {
    id: "tusk-profile-aluminum-roof",
    brand: "Tusk",
    model: "Profile Aluminum Roof",
    category: "roof",
    weightLbs: 20,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Laser-cut 0.10\" aluminum. Powder coated.",
  },

  // ── Additional Roof Rack ──────────────────────────────────────────────
  {
    id: "tusk-adventure-roof-rack",
    brand: "Tusk",
    model: "Adventure Roof Rack",
    category: "roof-rack",
    weightLbs: 18,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "1/8\" powder-coated aluminum. 38.5\" x 34.5\".",
  },

  // ── Additional Winch ──────────────────────────────────────────────────
  {
    id: "badlands-apex-5500",
    brand: "Badlands",
    model: "Apex 5500 lb Winch + Plate",
    category: "winch",
    weightLbs: 38,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Harbor Freight. 30.5 lbs winch + ~7.5 lbs mounting plate. Synthetic rope.",
  },

  // ── Additional Skid Plate ─────────────────────────────────────────────
  {
    id: "tusk-quiet-glide-uhmw-skid",
    brand: "Tusk",
    model: "Quiet-Glide 3/8\" UHMW Full Skid Plate",
    category: "skid-plate",
    weightLbs: 22,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "3/8\" UHMW full-coverage. Lighter than steel/aluminum.",
  },

  // ── Additional Rock Sliders ───────────────────────────────────────────
  {
    id: "tusk-rock-sliders",
    brand: "Tusk",
    model: "Rock Sliders / Nerf Bars",
    category: "rock-slider",
    weightLbs: 28,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "All-steel construction. Powder coated. Per pair.",
  },

  // ── Additional Light Bar ──────────────────────────────────────────────
  {
    id: "roadshock-32in-combo",
    brand: "Roadshock",
    model: "32\" Spot/Flood Combo LED Light Bar",
    category: "light-bar",
    weightLbs: 7.4,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Harbor Freight. Item #57052. Budget king.",
  },

  // ── Additional Spare Tire Carrier ─────────────────────────────────────
  {
    id: "generic-spare-tire-carrier-w-tire",
    brand: "Generic",
    model: "Spare Tire Carrier + Mounted Spare",
    category: "spare-tire-carrier",
    weightLbs: 55,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "~15 lbs carrier + ~40 lbs spare tire (31\" tire). Adjust for your tire size.",
  },
];

// ── Helper Functions ──────────────────────────────────────────────────────

/**
 * Returns available accessory categories.
 * When instagramMode is true, includes cosmetic categories (sound, lights, underglow).
 */
export function getAccessoryCategories(instagramMode: boolean): AccessoryCategory[] {
  const all: AccessoryCategory[] = [
    "windshield", "doors", "roof", "bumper-front", "bumper-rear",
    "winch", "skid-plate", "rock-slider", "roof-rack", "cargo-rack",
    "light-bar", "light-pod", "mirrors", "fridge-mount", "dual-battery",
    "solar-panel", "rtt-mount", "spare-tire-carrier", "fuel-can-rack", "fuel-cell",
    "harness", "storage", "switch-panel", "camera",
    "fender-flare", "brace-kit", "interior", "recovery",
    "cooling", "exhaust", "axle", "heater",
  ];
  const cosmetic: AccessoryCategory[] = ["sound-system", "led-whip", "underglow", "sound-bar"];
  return instagramMode ? [...all, ...cosmetic] : all;
}

/**
 * Returns all accessories in a given category.
 */
export function getAccessoriesByCategory(category: AccessoryCategory): UTVAccessory[] {
  return accessories.filter((a) => a.category === category);
}

/**
 * Returns accessories compatible with a specific machine, optionally filtered by category.
 */
export function getCompatibleAccessories(machineId: string, category?: AccessoryCategory): UTVAccessory[] {
  return accessories.filter((a) => {
    const compatible = a.compatibleMachines === "all" || a.compatibleMachines.includes(machineId);
    return compatible && (!category || a.category === category);
  });
}

/**
 * Human-readable labels for each accessory category.
 */
export const CATEGORY_LABELS: Record<AccessoryCategory, string> = {
  windshield: "Windshield",
  doors: "Doors",
  roof: "Roof",
  "bumper-front": "Front Bumper",
  "bumper-rear": "Rear Bumper",
  winch: "Winch",
  "skid-plate": "Skid Plates",
  "rock-slider": "Rock Sliders",
  "roof-rack": "Roof Rack",
  "cargo-rack": "Cargo Rack",
  "light-bar": "Light Bar",
  "light-pod": "Light Pods",
  "sound-system": "Sound System",
  mirrors: "Mirrors",
  "fridge-mount": "Fridge Mount",
  "dual-battery": "Dual Battery",
  "solar-panel": "Solar Panel",
  "rtt-mount": "RTT Mount",
  "spare-tire-carrier": "Spare Tire Carrier",
  "fuel-can-rack": "Fuel Can Rack",
  "fuel-cell": "Fuel Cell",
  "led-whip": "LED Whip",
  underglow: "Underglow",
  "sound-bar": "Sound Bar",
  harness: "Harness / Seats",
  storage: "Storage",
  "switch-panel": "Switch Panel",
  camera: "Camera",
  "fender-flare": "Fender Flares",
  "brace-kit": "Brace / Guard Kit",
  interior: "Interior",
  recovery: "Recovery Gear",
  cooling: "Cooling",
  exhaust: "Exhaust",
  axle: "Axles",
  heater: "Heater",
};
