// RigRated UTV Accessories Database
// ~80 accessories across 22 categories with realistic weights and brands

export type AccessoryCategory =
  | "windshield" | "doors" | "roof" | "bumper-front" | "bumper-rear"
  | "winch" | "skid-plate" | "rock-slider" | "roof-rack" | "cargo-rack"
  | "light-bar" | "sound-system" | "mirrors" | "fridge-mount" | "dual-battery"
  | "solar-panel" | "rtt-mount" | "spare-tire-carrier" | "fuel-can-rack"
  | "fuel-cell"
  | "led-whip" | "underglow" | "sound-bar";

export type AccessoryMountPosition = "front" | "rear" | "roof" | "bed" | "sides" | "distributed";

export interface UTVAccessory {
  id: string;
  brand: string;
  model: string;
  category: AccessoryCategory;
  weightLbs: number;
  mountPosition: AccessoryMountPosition;
  isCosmetic: boolean;
  affiliateUrl: string;
  compatibleMachines: string[] | "all";
  fuelCapacityGal?: number; // For fuel cells — dry weight in weightLbs, full = weightLbs + (fuelCapacityGal * 6.3)
  notes?: string;
}

export const accessories: UTVAccessory[] = [
  // ── Windshields (6) ──────────────────────────────────────────────────
  {
    id: "superatv-full-windshield-glass",
    brand: "SuperATV",
    model: "Full Windshield (Glass)",
    category: "windshield",
    weightLbs: 25,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B08J7L52QT?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Laminated safety glass, scratch-resistant",
  },
  {
    id: "superatv-half-windshield",
    brand: "SuperATV",
    model: "Half Windshield",
    category: "windshield",
    weightLbs: 12,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07HBDGYP9?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Polycarbonate, good airflow compromise",
  },
  {
    id: "seizmik-vented-windshield",
    brand: "Seizmik",
    model: "Vented Windshield",
    category: "windshield",
    weightLbs: 18,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01JSG1JRO?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Adjustable vents for airflow control",
  },
  {
    id: "kolpin-half-fold-windshield",
    brand: "Kolpin",
    model: "Half-Fold Windshield",
    category: "windshield",
    weightLbs: 14,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00DQ6SIGI?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Folds down for open-air riding",
  },
  {
    id: "cfmoto-oem-full-windshield",
    brand: "CFMOTO",
    model: "OEM Full Windshield",
    category: "windshield",
    weightLbs: 20,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["cfmoto-zforce-950", "cfmoto-zforce-800", "cfmoto-uforce-1000"],
    notes: "CFMOTO factory fitment only",
  },
  {
    id: "polaris-poly-full-windshield",
    brand: "Polaris",
    model: "Poly Full Windshield",
    category: "windshield",
    weightLbs: 15,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp", "polaris-rzr-200"],
    notes: "Polaris Lock & Ride compatible",
  },

  // ── Doors (5) ────────────────────────────────────────────────────────
  {
    id: "superatv-half-doors",
    brand: "SuperATV",
    model: "Half Doors (Pair)",
    category: "doors",
    weightLbs: 35,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07M6V6VST?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Aluminum frame, keeps debris out of cab",
  },
  {
    id: "pro-armor-suicide-doors",
    brand: "Pro Armor",
    model: "Suicide Doors (Pair)",
    category: "doors",
    weightLbs: 40,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B005G05F36?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Rear-hinged for easy entry/exit",
  },
  {
    id: "seizmik-full-doors",
    brand: "Seizmik",
    model: "Full Doors (Pair)",
    category: "doors",
    weightLbs: 55,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B009XIWOEA?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Full enclosure with upper window cutout",
  },
  {
    id: "polaris-lock-ride-pro-fit-doors",
    brand: "Polaris",
    model: "Lock & Ride Pro-Fit Doors",
    category: "doors",
    weightLbs: 50,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp"],
    notes: "Polaris OEM tool-less install",
  },
  {
    id: "dragonfire-hiboy-doors",
    brand: "Dragonfire",
    model: "HiBoy Doors (Pair)",
    category: "doors",
    weightLbs: 30,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00UI00PYI?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Lightweight aluminum, lower profile",
  },

  // ── Roof (5) ─────────────────────────────────────────────────────────
  {
    id: "superatv-aluminum-roof",
    brand: "SuperATV",
    model: "Aluminum Roof",
    category: "roof",
    weightLbs: 28,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07QSWKV6P?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Powder-coated aluminum, rattle-free",
  },
  {
    id: "polaris-poly-sport-roof",
    brand: "Polaris",
    model: "Poly Sport Roof",
    category: "roof",
    weightLbs: 20,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp", "polaris-rzr-200"],
    notes: "Polaris OEM poly roof",
  },
  {
    id: "pro-armor-aluminum-sport-roof",
    brand: "Pro Armor",
    model: "Aluminum Sport Roof",
    category: "roof",
    weightLbs: 25,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B071XWFX7F?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "razorback-soft-top",
    brand: "Razorback",
    model: "Soft Top",
    category: "roof",
    weightLbs: 8,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Lightweight fabric, easy on/off",
  },
  {
    id: "dragonfire-aluminum-roof",
    brand: "Dragonfire",
    model: "Aluminum Roof",
    category: "roof",
    weightLbs: 24,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07HF682GQ?tag=prepperevo-20",
    compatibleMachines: "all",
  },

  // ── Front Bumper (5) ─────────────────────────────────────────────────
  {
    id: "superatv-front-bumper",
    brand: "SuperATV",
    model: "Front Bumper",
    category: "bumper-front",
    weightLbs: 35,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0821QR74V?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Heavy-duty steel with winch mount",
  },
  {
    id: "hmf-front-bumper",
    brand: "HMF",
    model: "Front Bumper",
    category: "bumper-front",
    weightLbs: 40,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07QYBNZ3T?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Steel tube construction",
  },
  {
    id: "assault-industries-apache-front-bumper",
    brand: "Assault Industries",
    model: "Apache Front Bumper",
    category: "bumper-front",
    weightLbs: 45,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07NF4NN9F?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Integrated winch plate and D-ring mounts",
  },
  {
    id: "pro-armor-front-bumper",
    brand: "Pro Armor",
    model: "Front Bumper",
    category: "bumper-front",
    weightLbs: 38,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07PGQDK8F?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "can-am-oem-front-bumper",
    brand: "Can-Am",
    model: "OEM Front Bumper",
    category: "bumper-front",
    weightLbs: 30,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["can-am-maverick-x3", "can-am-maverick-sport", "can-am-defender"],
    notes: "Can-Am factory accessory",
  },

  // ── Rear Bumper (5) ──────────────────────────────────────────────────
  {
    id: "superatv-rear-bumper",
    brand: "SuperATV",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 30,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07PVZMW17?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "hmf-rear-bumper",
    brand: "HMF",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 35,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01MXTPQDO?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "assault-industries-rear-bumper",
    brand: "Assault Industries",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 40,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B072KGKKWJ?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "pro-armor-rear-bumper",
    brand: "Pro Armor",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 32,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00NPUZCH8?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "tusk-rear-bumper",
    brand: "Tusk",
    model: "Rear Bumper",
    category: "bumper-rear",
    weightLbs: 28,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00I48HZ3K?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Budget-friendly steel construction",
  },

  // ── Winch (5) ────────────────────────────────────────────────────────
  {
    id: "warn-vrx-45s",
    brand: "WARN",
    model: "VRX 45-S",
    category: "winch",
    weightLbs: 25,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B091XX4TZP?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, synthetic rope",
  },
  {
    id: "superatv-4500-black-ops",
    brand: "SuperATV",
    model: "4500 lb Black Ops Winch",
    category: "winch",
    weightLbs: 22,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07TNLH72L?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, synthetic rope",
  },
  {
    id: "kfi-se45-r2",
    brand: "KFI",
    model: "SE45-R2",
    category: "winch",
    weightLbs: 20,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01N6VN6I0?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, stealth series",
  },
  {
    id: "warn-provantage-4500s",
    brand: "WARN",
    model: "ProVantage 4500-S",
    category: "winch",
    weightLbs: 27,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B008BYQBUA?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, corrosion-resistant",
  },
  {
    id: "kolpin-4500-winch",
    brand: "Kolpin",
    model: "4500 lb Winch",
    category: "winch",
    weightLbs: 23,
    mountPosition: "front",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B075FSBP38?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "4,500 lb capacity, steel cable",
  },

  // ── Skid Plates (5) ──────────────────────────────────────────────────
  {
    id: "superatv-full-skid-plate-kit",
    brand: "SuperATV",
    model: "Full Skid Plate Kit",
    category: "skid-plate",
    weightLbs: 45,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01MZ2LDKX?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "HDPE, covers front to rear",
  },
  {
    id: "factory-utv-uhmw-skid-plate",
    brand: "Factory UTV",
    model: "UHMW Skid Plate",
    category: "skid-plate",
    weightLbs: 35,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01CXOUCP8?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "3/8-inch UHMW polyethylene, self-healing",
  },
  {
    id: "sss-off-road-skid-plates",
    brand: "SSS Off Road",
    model: "Skid Plates",
    category: "skid-plate",
    weightLbs: 50,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00M94UJ1A?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Aluminum, full coverage belly pan",
  },
  {
    id: "trail-armor-skid-plate-set",
    brand: "Trail Armor",
    model: "Skid Plate Set",
    category: "skid-plate",
    weightLbs: 40,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
  },
  {
    id: "polaris-oem-skid-plate",
    brand: "Polaris",
    model: "OEM Skid Plate",
    category: "skid-plate",
    weightLbs: 30,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp"],
    notes: "Polaris factory skid plate kit",
  },

  // ── Rock Sliders (4) ─────────────────────────────────────────────────
  {
    id: "superatv-rock-sliders",
    brand: "SuperATV",
    model: "Rock Sliders",
    category: "rock-slider",
    weightLbs: 35,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07KMLDR2J?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Heavy-duty steel tree kickers",
  },
  {
    id: "s3-power-sports-rock-sliders",
    brand: "S3 Power Sports",
    model: "Rock Sliders",
    category: "rock-slider",
    weightLbs: 40,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07JJ5VKV3?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "pro-armor-rock-sliders",
    brand: "Pro Armor",
    model: "Rock Sliders",
    category: "rock-slider",
    weightLbs: 38,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0CBS91DR8?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "tusk-nerf-bars",
    brand: "Tusk",
    model: "Nerf Bars",
    category: "rock-slider",
    weightLbs: 25,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B003QSE7Z2?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Doubles as step and rocker protection",
  },

  // ── Roof Rack (4) ────────────────────────────────────────────────────
  {
    id: "superatv-cargo-roof-rack",
    brand: "SuperATV",
    model: "Cargo Roof Rack",
    category: "roof-rack",
    weightLbs: 30,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0CNS4D5P9?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Steel construction, 100+ lb capacity",
  },
  {
    id: "razorback-roof-rack",
    brand: "Razorback",
    model: "Roof Rack",
    category: "roof-rack",
    weightLbs: 25,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0D7QW2S4Y?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "pro-armor-roof-rack",
    brand: "Pro Armor",
    model: "Roof Rack",
    category: "roof-rack",
    weightLbs: 28,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
  },
  {
    id: "polaris-lock-ride-cargo-rack",
    brand: "Polaris",
    model: "Lock & Ride Cargo Rack",
    category: "roof-rack",
    weightLbs: 22,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: ["polaris-rzr-xp-1000", "polaris-rzr-turbo", "polaris-rzr-pro-xp"],
    notes: "Polaris Lock & Ride tool-less mount",
  },

  // ── Cargo Rack (3) ───────────────────────────────────────────────────
  {
    id: "superatv-rear-cargo-rack",
    brand: "SuperATV",
    model: "Rear Cargo Rack",
    category: "cargo-rack",
    weightLbs: 18,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B08P51J88S?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "kolpin-rear-cargo-rack",
    brand: "Kolpin",
    model: "Rear Cargo Rack",
    category: "cargo-rack",
    weightLbs: 15,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B09G697TG6?tag=prepperevo-20",
    compatibleMachines: "all",
  },
  {
    id: "tusk-rear-cargo-box",
    brand: "Tusk",
    model: "Rear Cargo Box",
    category: "cargo-rack",
    weightLbs: 25,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07FKRK2K7?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Lockable, weatherproof storage",
  },

  // ── Light Bar (5) ────────────────────────────────────────────────────
  {
    id: "rigid-industries-30-led-bar",
    brand: "Rigid Industries",
    model: '30" LED Bar',
    category: "light-bar",
    weightLbs: 8,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00GQGWLQ8?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "E-Series, combo spot/flood beam",
  },
  {
    id: "baja-designs-onx6-30",
    brand: "Baja Designs",
    model: 'OnX6+ 30"',
    category: "light-bar",
    weightLbs: 7,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00Q5F9DR0?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "High-output laser hybrid, driving/combo",
  },
  {
    id: "kc-hilites-c-series-30",
    brand: "KC HiLites",
    model: 'C-Series 30"',
    category: "light-bar",
    weightLbs: 9,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B000630CCC?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Combo beam, IP68 rated",
  },
  {
    id: "rigid-radiance-plus-40",
    brand: "Rigid",
    model: 'Radiance+ 40"',
    category: "light-bar",
    weightLbs: 10,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0C2FLCW1K?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Multi-color backlight, broad scene light",
  },
  {
    id: "nilight-32-combo-beam",
    brand: "Nilight",
    model: '32" Combo Beam',
    category: "light-bar",
    weightLbs: 5,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B01DNYCJQW?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Budget-friendly, spot/flood combo",
  },

  // ── Sound System (3) — all cosmetic ──────────────────────────────────
  {
    id: "ssv-works-5-speaker-kit",
    brand: "SSV Works",
    model: "5-Speaker Kit",
    category: "sound-system",
    weightLbs: 15,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B07KTDD6MS?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Includes head unit, 4 speakers, sub",
  },
  {
    id: "rockford-fosgate-stage-3-kit",
    brand: "Rockford Fosgate",
    model: "Stage 3 Kit",
    category: "sound-system",
    weightLbs: 22,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B079R818CT?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "PMX head unit, 4 speakers, amp, sub",
  },
  {
    id: "mb-quart-tuned-audio-kit",
    brand: "MB Quart",
    model: "Tuned Audio Kit",
    category: "sound-system",
    weightLbs: 18,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B07V9PFBWX?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Stage 5 tuned for UTV cab",
  },

  // ── Mirrors (3) ──────────────────────────────────────────────────────
  {
    id: "seizmik-pursuit-side-mirrors",
    brand: "Seizmik",
    model: "Pursuit Side Mirrors",
    category: "mirrors",
    weightLbs: 3,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B00T6JDIVY?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Clamp-on, fits 1.75-2 inch cage",
  },
  {
    id: "assault-industries-bomber-mirrors",
    brand: "Assault Industries",
    model: "Bomber Side Mirrors",
    category: "mirrors",
    weightLbs: 4,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B079T89MVC?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Convex glass, breakaway design",
  },
  {
    id: "superatv-side-mirrors",
    brand: "SuperATV",
    model: "Side Mirrors",
    category: "mirrors",
    weightLbs: 3,
    mountPosition: "sides",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B016AQ6OIO?tag=prepperevo-20",
    compatibleMachines: "all",
  },

  // ── Fridge Mount (2) ─────────────────────────────────────────────────
  {
    id: "expedition-essentials-fridge-slide",
    brand: "Expedition Essentials",
    model: "Fridge Slide",
    category: "fridge-mount",
    weightLbs: 20,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Locking slide-out, fits 40-60L fridges",
  },
  {
    id: "front-runner-utv-fridge-mount",
    brand: "Front Runner",
    model: "UTV Fridge Mount",
    category: "fridge-mount",
    weightLbs: 18,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B0114QO9VE?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Strapped tie-down plate with vibration damping",
  },

  // ── Dual Battery (2) ─────────────────────────────────────────────────
  {
    id: "odyssey-dual-battery-kit",
    brand: "Odyssey",
    model: "Dual Battery Kit",
    category: "dual-battery",
    weightLbs: 35,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "AGM batteries with isolator relay",
  },
  {
    id: "xs-power-dual-battery",
    brand: "XS Power",
    model: "Dual Battery Kit",
    category: "dual-battery",
    weightLbs: 30,
    mountPosition: "distributed",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Lithium, lighter weight for same capacity",
  },

  // ── Solar Panel (2) ──────────────────────────────────────────────────
  {
    id: "renogy-100w-flex-panel",
    brand: "Renogy",
    model: "100W Flex Panel",
    category: "solar-panel",
    weightLbs: 5,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B09W21FRBC?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Flexible monocrystalline, mounts to roof with adhesive or bolts",
  },
  {
    id: "goal-zero-boulder-50",
    brand: "Goal Zero",
    model: "Boulder 50",
    category: "solar-panel",
    weightLbs: 12,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B06Y3XMQTK?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Rigid panel, tempered glass, high durability",
  },

  // ── RTT Mount (2) ────────────────────────────────────────────────────
  {
    id: "cbi-offroad-utv-tent-mount",
    brand: "CBI Offroad",
    model: "UTV Tent Mount",
    category: "rtt-mount",
    weightLbs: 40,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Rated for 2-person RTT, requires roof or cage mount",
  },
  {
    id: "diy-universal-tent-mount-frame",
    brand: "DIY",
    model: "Universal Tent Mount Frame",
    category: "rtt-mount",
    weightLbs: 35,
    mountPosition: "roof",
    isCosmetic: false,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Weld-on or bolt-on universal frame, check cage rating",
  },

  // ── Spare Tire Carrier (2) ───────────────────────────────────────────
  {
    id: "superatv-spare-tire-carrier",
    brand: "SuperATV",
    model: "Spare Tire Carrier",
    category: "spare-tire-carrier",
    weightLbs: 20,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B06Y344JNV?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Bed-mount, fits up to 32-inch tires",
  },
  {
    id: "assault-industries-spare-tire-carrier",
    brand: "Assault Industries",
    model: "Spare Tire Carrier",
    category: "spare-tire-carrier",
    weightLbs: 22,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B077P7L36J?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Rear cage mount, quick-release",
  },

  // ── Fuel Can Rack (2) ────────────────────────────────────────────────
  {
    id: "rotopax-2gal-mount-kit",
    brand: "Rotopax",
    model: "2-Gal Mount Kit (with 2 Cans)",
    category: "fuel-can-rack",
    weightLbs: 15,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B003YBMDRU?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "2x 2-gallon cans + LOX pack mount",
  },
  {
    id: "rotopax-4gal-mount-kit",
    brand: "Rotopax",
    model: "4-Gal Mount Kit (with 2 Cans)",
    category: "fuel-can-rack",
    weightLbs: 22,
    mountPosition: "rear",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07GD2DRS3?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "2x 4-gallon cans + LOX pack mount, extends range significantly",
  },

  // ── LED Whip (3) — all cosmetic ─────────────────────────────────────
  {
    id: "gorilla-whips-4ft-led-pair",
    brand: "Gorilla Whips",
    model: "4ft LED Whip (Pair)",
    category: "led-whip",
    weightLbs: 4,
    mountPosition: "rear",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B072VMR58F?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "RGB, Bluetooth app controlled",
  },
  {
    id: "5150-whips-4ft-led-pair",
    brand: "5150 Whips",
    model: "4ft LED Whip (Pair)",
    category: "led-whip",
    weightLbs: 4,
    mountPosition: "rear",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B07DKY4TVR?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Multicolor, quick-release base",
  },
  {
    id: "tribal-whips-3ft-led-pair",
    brand: "Tribal Whips",
    model: "3ft LED Whip (Pair)",
    category: "led-whip",
    weightLbs: 3,
    mountPosition: "rear",
    isCosmetic: true,
    affiliateUrl: "#",
    compatibleMachines: "all",
    notes: "Budget-friendly, multiple color modes",
  },

  // ── Underglow (2) — all cosmetic ────────────────────────────────────
  {
    id: "oracle-underbody-led-kit",
    brand: "Oracle",
    model: "Underbody LED Kit",
    category: "underglow",
    weightLbs: 3,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B06XPCFRNK?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "IP67, Bluetooth color control",
  },
  {
    id: "opt7-aura-pro-underglow",
    brand: "OPT7",
    model: "Aura Pro Underglow",
    category: "underglow",
    weightLbs: 2,
    mountPosition: "distributed",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B09XWCTJMW?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "Flexible strip, music-sync mode",
  },

  // ── Sound Bar (2) — all cosmetic ────────────────────────────────────
  {
    id: "boss-audio-brt18a",
    brand: "Boss Audio",
    model: "BRT18A Sound Bar",
    category: "sound-bar",
    weightLbs: 8,
    mountPosition: "roof",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B08F9NTB2G?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "18-inch, Bluetooth, built-in amp",
  },
  {
    id: "kicker-utv-sound-bar",
    brand: "Kicker",
    model: "UTV Sound Bar",
    category: "sound-bar",
    weightLbs: 10,
    mountPosition: "roof",
    isCosmetic: true,
    affiliateUrl: "https://www.amazon.com/dp/B09DYW5VY1?tag=prepperevo-20",
    compatibleMachines: "all",
    notes: "All-weather, cage clamp mount",
  },

  // ── Fuel Cells (5) ──────────────────────────────────────────────────────
  {
    id: "fuel-safe-10gal",
    brand: "Fuel Safe",
    model: "10-Gallon UTV Fuel Cell",
    category: "fuel-cell",
    weightLbs: 25,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07BNKH8WY?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 10,
    notes: "25 lbs dry, 88 lbs full. Aircraft-grade aluminum.",
  },
  {
    id: "fuel-safe-15gal",
    brand: "Fuel Safe",
    model: "15-Gallon UTV Fuel Cell",
    category: "fuel-cell",
    weightLbs: 30,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B07BNKH8WY?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 15,
    notes: "30 lbs dry, 124 lbs full. Aircraft-grade aluminum.",
  },
  {
    id: "jaz-10gal",
    brand: "Jaz Products",
    model: "10-Gallon Pro Sport Cell",
    category: "fuel-cell",
    weightLbs: 22,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B004P2QQJ2?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 10,
    notes: "22 lbs dry, 85 lbs full. Polyethylene with foam baffles.",
  },
  {
    id: "rci-12gal",
    brand: "RCI",
    model: "12-Gallon Fuel Cell",
    category: "fuel-cell",
    weightLbs: 28,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B001O4ARRY?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 12,
    notes: "28 lbs dry, 103 lbs full. Steel container.",
  },
  {
    id: "rjs-8gal",
    brand: "RJS Racing",
    model: "8-Gallon Drag Cell",
    category: "fuel-cell",
    weightLbs: 20,
    mountPosition: "bed",
    isCosmetic: false,
    affiliateUrl: "https://www.amazon.com/dp/B001LF3R1S?tag=prepperevo-20",
    compatibleMachines: "all",
    fuelCapacityGal: 8,
    notes: "20 lbs dry, 70 lbs full. Compact design for smaller beds.",
  },
];

// ── Helper Functions ──────────────────────────────────────────────────────

/**
 * Returns available accessory categories.
 * When instagramMode is true, includes cosmetic categories (sound, lights, underglow).
 */
export function getAccessoryCategories(instagramMode: boolean): AccessoryCategory[] {
  const all: AccessoryCategory[] = [
    "windshield", "doors", "roof", "bumper-front", "bumper-rear",
    "winch", "skid-plate", "rock-slider", "roof-rack", "cargo-rack",
    "light-bar", "mirrors", "fridge-mount", "dual-battery",
    "solar-panel", "rtt-mount", "spare-tire-carrier", "fuel-can-rack", "fuel-cell",
  ];
  const cosmetic: AccessoryCategory[] = ["sound-system", "led-whip", "underglow", "sound-bar"];
  return instagramMode ? [...all, ...cosmetic] : all;
}

/**
 * Returns all accessories in a given category.
 */
export function getAccessoriesByCategory(category: AccessoryCategory): UTVAccessory[] {
  return accessories.filter((a) => a.category === category);
}

/**
 * Returns accessories compatible with a specific machine, optionally filtered by category.
 */
export function getCompatibleAccessories(machineId: string, category?: AccessoryCategory): UTVAccessory[] {
  return accessories.filter((a) => {
    const compatible = a.compatibleMachines === "all" || a.compatibleMachines.includes(machineId);
    return compatible && (!category || a.category === category);
  });
}

/**
 * Human-readable labels for each accessory category.
 */
export const CATEGORY_LABELS: Record<AccessoryCategory, string> = {
  windshield: "Windshield",
  doors: "Doors",
  roof: "Roof",
  "bumper-front": "Front Bumper",
  "bumper-rear": "Rear Bumper",
  winch: "Winch",
  "skid-plate": "Skid Plates",
  "rock-slider": "Rock Sliders",
  "roof-rack": "Roof Rack",
  "cargo-rack": "Cargo Rack",
  "light-bar": "Light Bar",
  "sound-system": "Sound System",
  mirrors: "Mirrors",
  "fridge-mount": "Fridge Mount",
  "dual-battery": "Dual Battery",
  "solar-panel": "Solar Panel",
  "rtt-mount": "RTT Mount",
  "spare-tire-carrier": "Spare Tire Carrier",
  "fuel-can-rack": "Fuel Can Rack",
  "fuel-cell": "Fuel Cell",
  "led-whip": "LED Whip",
  underglow: "Underglow",
  "sound-bar": "Sound Bar",
};
