// RigRated Legal — 50-state OHV rules
// Last bulk update: 2025-12

export type LegalView = "unregistered" | "plated" | "non-resident";

export interface StateLegalInfo {
  stateCode: string;
  stateName: string;
  registrationRequired: boolean;
  nonResidentPermit: boolean;
  permitCost: string;
  highwayLegal: boolean;
  maxSpeedMph: number | null;
  helmetRequired: "always" | "under-18" | "never";
  ageRestrictions: string;
  soundLimitsDb: number | null;
  blmAccess: "open" | "restricted" | "closed";
  nationalForestRules: string;
  notes: string;
  officialUrl: string;
  lastVerified: string;
}

export const stateLegalData: StateLegalInfo[] = [
  // ── AL ──────────────────────────────────────────────
  {
    stateCode: "AL",
    stateName: "Alabama",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 16 must be supervised by adult",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Designated trails only in Talladega NF; stay on marked routes",
    notes: "OHV use limited to private land, designated state trails, and national forest trails. No road-legal pathway.",
    officialUrl: "https://www.alapark.com/parks/ohv-trails",
    lastVerified: "2025-12",
  },
  // ── AK ──────────────────────────────────────────────
  {
    stateCode: "AK",
    stateName: "Alaska",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "never",
    ageRestrictions: "Under 14 must be supervised; under 16 cannot cross highways",
    soundLimitsDb: null,
    blmAccess: "open",
    nationalForestRules: "Tongass and Chugach NF have designated routes; many remote areas open",
    notes: "Very permissive. ATVs allowed on most roads and shoulders outside municipalities. Huge BLM acreage with open access.",
    officialUrl: "https://dnr.alaska.gov/parks/ohv",
    lastVerified: "2025-12",
  },
  // ── AZ ──────────────────────────────────────────────
  {
    stateCode: "AZ",
    stateName: "Arizona",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$25",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 18 must complete safety course; under 16 supervised",
    soundLimitsDb: 96,
    blmAccess: "open",
    nationalForestRules: "Designated routes only; motorized travel maps required in Tonto, Coconino, Kaibab NFs",
    notes: "OHV decal required ($25). Highway legal on roads posted 35 mph or less. Massive BLM riding areas in southern AZ.",
    officialUrl: "https://azstateparks.com/ohv",
    lastVerified: "2025-12",
  },
  // ── AR ──────────────────────────────────────────────
  {
    stateCode: "AR",
    stateName: "Arkansas",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 must ride with adult; under 16 supervised on public land",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Ozark-St. Francis NF: designated trails only, seasonal closures",
    notes: "No state registration required. OHV use on private land and designated trails only. Not road-legal.",
    officialUrl: "https://www.arkansasstateparks.com/activities/atv-off-road",
    lastVerified: "2025-12",
  },
  // ── CA ──────────────────────────────────────────────
  {
    stateCode: "CA",
    stateName: "California",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$25",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 14 cannot operate on public land; 14-17 must have safety certificate",
    soundLimitsDb: 96,
    blmAccess: "open",
    nationalForestRules: "Forest-specific MVUMs required; many areas closed. Sequoia, Angeles, San Bernardino NFs have designated routes",
    notes: "Green or red sticker required. Red sticker vehicles restricted seasonally. 96 dB sound limit strictly enforced. Johnson Valley, Ocotillo Wells, Glamis are major riding areas.",
    officialUrl: "https://ohv.parks.ca.gov",
    lastVerified: "2025-12",
  },
  // ── CO ──────────────────────────────────────────────
  {
    stateCode: "CO",
    stateName: "Colorado",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$25",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 10 cannot operate OHV on public land; 10-15 supervised",
    soundLimitsDb: 96,
    blmAccess: "open",
    nationalForestRules: "Stay the Trail program; motorized travel maps required. White River, Grand Mesa, Uncompahgre NFs popular",
    notes: "OHV permit required ($25.25). Counties can authorize highway use on roads 35 mph or less. Massive trail system on BLM and USFS land.",
    officialUrl: "https://cpw.state.co.us/ohv",
    lastVerified: "2025-12",
  },
  // ── CT ──────────────────────────────────────────────
  {
    stateCode: "CT",
    stateName: "Connecticut",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 16 cannot operate ATV; 16-17 must have safety certificate",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No national forests in CT",
    notes: "Very restrictive. Registration required. No road use. Limited to private land and a few designated areas.",
    officialUrl: "https://portal.ct.gov/deep/outdoor-recreation/atv",
    lastVerified: "2025-12",
  },
  // ── DE ──────────────────────────────────────────────
  {
    stateCode: "DE",
    stateName: "Delaware",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 16 cannot operate on public land; must ride supervised",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No national forests in DE",
    notes: "Very limited OHV opportunities. Essentially private land only. No designated public trails for OHV.",
    officialUrl: "https://dnrec.delaware.gov/parks/",
    lastVerified: "2025-12",
  },
  // ── FL ──────────────────────────────────────────────
  {
    stateCode: "FL",
    stateName: "Florida",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 16 must complete safety course; under 16 cannot cross public roads",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Ocala NF has designated OHV trails; permit required. Apalachicola NF limited access",
    notes: "No registration for off-road-only use. Several state OHV parks. Cannot ride on public roads. Croom, Hard Rock, and Ocala are popular riding areas.",
    officialUrl: "https://www.floridastateparks.org/activities/off-road-vehicle",
    lastVerified: "2025-12",
  },
  // ── GA ──────────────────────────────────────────────
  {
    stateCode: "GA",
    stateName: "Georgia",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 must ride with adult; 12-15 must have safety certificate",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Chattahoochee-Oconee NF: very limited OHV; mostly closed to motorized use",
    notes: "No state OHV registration. Riding on private land and designated areas. Durhamtown and River Rock are popular private parks.",
    officialUrl: "https://gastateparks.org/",
    lastVerified: "2025-12",
  },
  // ── HI ──────────────────────────────────────────────
  {
    stateCode: "HI",
    stateName: "Hawaii",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 15 cannot operate; 15-17 must have safety certificate",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No national forest OHV areas",
    notes: "Extremely limited OHV access. Private land and guided tours only in most areas. No public OHV trail system.",
    officialUrl: "https://dlnr.hawaii.gov/dsp/",
    lastVerified: "2025-12",
  },
  // ── ID ──────────────────────────────────────────────
  {
    stateCode: "ID",
    stateName: "Idaho",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$20",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 10 cannot operate on public land; 10-15 supervised by adult",
    soundLimitsDb: null,
    blmAccess: "open",
    nationalForestRules: "Extensive trail systems in Boise, Payette, Sawtooth NFs. Motorized travel maps required",
    notes: "OHV sticker required ($20 non-resident). Highway legal on roads 35 mph or less where counties allow. Massive BLM and USFS riding. One of the most OHV-friendly states.",
    officialUrl: "https://parksandrecreation.idaho.gov/activities/ohv/",
    lastVerified: "2025-12",
  },
  // ── IL ──────────────────────────────────────────────
  {
    stateCode: "IL",
    stateName: "Illinois",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 must ride with adult; 12-15 supervised on public land",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Shawnee NF: very limited OHV access, mostly non-motorized",
    notes: "No state OHV registration. Private land and a handful of state OHV areas. Not road-legal.",
    officialUrl: "https://dnr.illinois.gov/recreation/ohv.html",
    lastVerified: "2025-12",
  },
  // ── IN ──────────────────────────────────────────────
  {
    stateCode: "IN",
    stateName: "Indiana",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 14 must ride with adult on public land; under 18 needs safety course for unsupervised use",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Hoosier NF: limited designated routes, mostly non-motorized",
    notes: "OHV riding on private land and designated areas. Redbird SRA and Interlake SRA are main public riding areas.",
    officialUrl: "https://www.in.gov/dnr/outdoor-recreation/off-road-vehicles/",
    lastVerified: "2025-12",
  },
  // ── IA ──────────────────────────────────────────────
  {
    stateCode: "IA",
    stateName: "Iowa",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate on public land without adult; 12-17 need safety certificate",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No significant national forest OHV areas",
    notes: "Registration required. ATVs may travel on designated county roads at 35 mph or less. Counties must opt in. No BLM land.",
    officialUrl: "https://www.iowadnr.gov/things-to-do/atv-riding",
    lastVerified: "2025-12",
  },
  // ── KS ──────────────────────────────────────────────
  {
    stateCode: "KS",
    stateName: "Kansas",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: true,
    maxSpeedMph: 30,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate on public roads; 12-15 supervised",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Cimarron National Grassland: limited OHV access on designated roads",
    notes: "Counties can allow ATV use on county roads. No state registration for off-road use. Limited public OHV riding areas.",
    officialUrl: "https://ksoutdoors.com/KDWP-Info/KDWP-Programs/ATV-Safety",
    lastVerified: "2025-12",
  },
  // ── KY ──────────────────────────────────────────────
  {
    stateCode: "KY",
    stateName: "Kentucky",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate without adult supervision; safety certificate recommended under 16",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Daniel Boone NF: designated trails only, permit required for some areas",
    notes: "Private land and designated state areas. Mine Made trails and private parks popular. Not road-legal statewide.",
    officialUrl: "https://fw.ky.gov/Education/Pages/ATV-Safety.aspx",
    lastVerified: "2025-12",
  },
  // ── LA ──────────────────────────────────────────────
  {
    stateCode: "LA",
    stateName: "Louisiana",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 16 must be supervised by adult; safety certification required for minors",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Kisatchie NF: limited designated OHV areas",
    notes: "Helmet required for all riders. No road use. Private land and private parks are primary riding areas.",
    officialUrl: "https://www.louisianasportsman.com/",
    lastVerified: "2025-12",
  },
  // ── ME ──────────────────────────────────────────────
  {
    stateCode: "ME",
    stateName: "Maine",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$45",
    highwayLegal: true,
    maxSpeedMph: 25,
    helmetRequired: "under-18",
    ageRestrictions: "Under 10 cannot operate; 10-15 must complete safety course; under 16 supervised",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No designated OHV areas in national forests",
    notes: "Registration required. Non-resident registration available. ATVs allowed on designated roads and extensive club trail networks. Strong ATV club system.",
    officialUrl: "https://www.maine.gov/ifw/atv-snowmobile/atv/index.html",
    lastVerified: "2025-12",
  },
  // ── MD ──────────────────────────────────────────────
  {
    stateCode: "MD",
    stateName: "Maryland",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 16 cannot operate on public land; must be supervised by adult",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No significant national forest OHV areas in MD",
    notes: "Very limited OHV access. Private land only for most riding. No public trail system. Stoney Ridge is one of few options.",
    officialUrl: "https://dnr.maryland.gov/publiclands/Pages/off-road-vehicles.aspx",
    lastVerified: "2025-12",
  },
  // ── MA ──────────────────────────────────────────────
  {
    stateCode: "MA",
    stateName: "Massachusetts",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 14 cannot operate; 14-17 must have safety certificate and parental consent",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No significant national forest OHV areas",
    notes: "Registration required. Helmet required for all. Very limited public riding areas. Mostly private land and designated state forest areas.",
    officialUrl: "https://www.mass.gov/guides/atv-recreation",
    lastVerified: "2025-12",
  },
  // ── MI ──────────────────────────────────────────────
  {
    stateCode: "MI",
    stateName: "Michigan",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$26",
    highwayLegal: true,
    maxSpeedMph: 25,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate on public land; 12-15 must have safety certificate",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Huron-Manistee NF: designated trails and routes; seasonal closures",
    notes: "ORV permit required. Extensive state ORV trail system (3,600+ miles). Designated county road riding allowed. Non-resident permits available.",
    officialUrl: "https://www.michigan.gov/dnr/things-to-do/orv",
    lastVerified: "2025-12",
  },
  // ── MN ──────────────────────────────────────────────
  {
    stateCode: "MN",
    stateName: "Minnesota",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$30",
    highwayLegal: true,
    maxSpeedMph: 30,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot cross public roads; 12-15 must have safety certificate",
    soundLimitsDb: 99,
    blmAccess: "closed",
    nationalForestRules: "Superior and Chippewa NFs: designated trails only, seasonal restrictions",
    notes: "Registration required. 1,300+ miles of state OHV trails. ATVs allowed on designated roads where counties permit. Strong trail grant program.",
    officialUrl: "https://www.dnr.state.mn.us/ohv/index.html",
    lastVerified: "2025-12",
  },
  // ── MS ──────────────────────────────────────────────
  {
    stateCode: "MS",
    stateName: "Mississippi",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 16 must be supervised by adult",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Bienville, De Soto NFs: limited OHV access, designated areas only",
    notes: "No state registration for off-road use. Limited public OHV areas. Mostly private land riding.",
    officialUrl: "https://www.mdwfp.com/",
    lastVerified: "2025-12",
  },
  // ── MO ──────────────────────────────────────────────
  {
    stateCode: "MO",
    stateName: "Missouri",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate without adult supervision; 12-15 need safety certificate",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Mark Twain NF: designated OHV trails available; seasonal closures apply",
    notes: "No state registration. Riding on private land and designated areas. Chadwick and Sutton Bluff are popular trail systems.",
    officialUrl: "https://mostateparks.com/activity/atv-riding",
    lastVerified: "2025-12",
  },
  // ── MT ──────────────────────────────────────────────
  {
    stateCode: "MT",
    stateName: "Montana",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$20",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 must be supervised; under 16 cannot cross state highways",
    soundLimitsDb: null,
    blmAccess: "open",
    nationalForestRules: "Extensive USFS trail systems in Flathead, Helena-Lewis & Clark, Lolo NFs; motorized travel maps required",
    notes: "OHV decal required. Counties can authorize road use at 35 mph or less. Huge BLM and USFS access. Very OHV-friendly state.",
    officialUrl: "https://fwp.mt.gov/recreation/ohv",
    lastVerified: "2025-12",
  },
  // ── NE ──────────────────────────────────────────────
  {
    stateCode: "NE",
    stateName: "Nebraska",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: true,
    maxSpeedMph: 30,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate on public roads; 12-17 need safety certificate",
    soundLimitsDb: null,
    blmAccess: "restricted",
    nationalForestRules: "Nebraska NF / Oglala National Grassland: limited designated routes",
    notes: "Counties can authorize ATV use on county roads. No registration for off-road use. Limited public riding areas in the Sandhills region.",
    officialUrl: "https://outdoornebraska.gov/atvutv/",
    lastVerified: "2025-12",
  },
  // ── NV ──────────────────────────────────────────────
  {
    stateCode: "NV",
    stateName: "Nevada",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$20",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 16 cannot operate on highways; must complete safety course",
    soundLimitsDb: 96,
    blmAccess: "open",
    nationalForestRules: "Humboldt-Toiyabe NF: designated routes; motorized travel maps required",
    notes: "OHV registration required. Highway legal on roads 35 mph or less. Nevada is ~85% BLM land — massive open riding. Logandale, Jean, Nellis dunes popular.",
    officialUrl: "https://ohv.nv.gov",
    lastVerified: "2025-12",
  },
  // ── NH ──────────────────────────────────────────────
  {
    stateCode: "NH",
    stateName: "New Hampshire",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$35",
    highwayLegal: true,
    maxSpeedMph: 25,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 must ride with licensed adult; 12-17 need safety education certificate",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "White Mountain NF: very limited OHV access, mostly non-motorized",
    notes: "OHRV registration required. Extensive club trail network (1,000+ miles). Designated road crossings and corridors. Non-resident registration available.",
    officialUrl: "https://www.nhstateparks.org/activities/atv-ohrvs",
    lastVerified: "2025-12",
  },
  // ── NJ ──────────────────────────────────────────────
  {
    stateCode: "NJ",
    stateName: "New Jersey",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 14 cannot operate; 14-17 must have safety certificate",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No national forests with OHV access in NJ",
    notes: "Registration required. Helmet required for all. Very limited public riding. Wharton State Forest has some designated areas. Pine Barrens riding restricted.",
    officialUrl: "https://www.nj.gov/dep/parksandforests/",
    lastVerified: "2025-12",
  },
  // ── NM ──────────────────────────────────────────────
  {
    stateCode: "NM",
    stateName: "New Mexico",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$18",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 10 cannot operate on public land; 10-17 supervised or safety certified",
    soundLimitsDb: 96,
    blmAccess: "open",
    nationalForestRules: "Santa Fe, Carson, Gila NFs: extensive designated trail systems; MVUMs required",
    notes: "OHV permit required. Road legal on designated roads 35 mph or less. Large BLM areas open. Popular areas include Rio Puerco, Jemez, and southern desert.",
    officialUrl: "https://www.emnrd.nm.gov/spd/find-a-park/ohv-areas/",
    lastVerified: "2025-12",
  },
  // ── NY ──────────────────────────────────────────────
  {
    stateCode: "NY",
    stateName: "New York",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 10 cannot operate; 10-15 must have safety certificate and ride supervised",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No significant national forest OHV access in NY",
    notes: "Registration required. Helmet required for all. Limited to private land, designated trails, and state forest trails. Adirondack Park mostly non-motorized.",
    officialUrl: "https://www.dec.ny.gov/outdoor/93485.html",
    lastVerified: "2025-12",
  },
  // ── NC ──────────────────────────────────────────────
  {
    stateCode: "NC",
    stateName: "North Carolina",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 8 cannot operate; 8-15 must be supervised by adult",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Nantahala, Pisgah NFs: designated trails only, Brown Mountain, Uwharrie popular",
    notes: "Helmet required for all riders. No road use. Popular trails at Uwharrie NF and Brown Mountain OHV area. Private parks also available.",
    officialUrl: "https://www.ncparks.gov/things-do/off-highway-vehicles",
    lastVerified: "2025-12",
  },
  // ── ND ──────────────────────────────────────────────
  {
    stateCode: "ND",
    stateName: "North Dakota",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: true,
    maxSpeedMph: 30,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate on public roads; 12-15 need safety certificate",
    soundLimitsDb: null,
    blmAccess: "restricted",
    nationalForestRules: "Dakota Prairie Grasslands: limited designated routes",
    notes: "Counties can authorize ATV road use. No state registration for off-road. Limited BLM land but some access in western ND Badlands area.",
    officialUrl: "https://gf.nd.gov/recreation/atv",
    lastVerified: "2025-12",
  },
  // ── OH ──────────────────────────────────────────────
  {
    stateCode: "OH",
    stateName: "Ohio",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 16 cannot operate without adult supervision on public land",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Wayne NF: limited designated OHV areas; Monday Creek and Pine Creek trails",
    notes: "Registration required for public land use. Not road-legal. Wayne NF has good designated trails. ATV parks at Sunday Creek and others.",
    officialUrl: "https://ohiodnr.gov/wps/portal/gov/odnr/go-and-do/plan-a-visit/find-a-property/atv-areas",
    lastVerified: "2025-12",
  },
  // ── OK ──────────────────────────────────────────────
  {
    stateCode: "OK",
    stateName: "Oklahoma",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: true,
    maxSpeedMph: 25,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate on public roads; 12-15 supervised",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Ouachita NF: limited designated trails",
    notes: "Counties can allow ATV use on county roads. No registration for off-road. Little Sahara State Park is a major riding area.",
    officialUrl: "https://www.travelok.com/state-parks/little-sahara-state-park",
    lastVerified: "2025-12",
  },
  // ── OR ──────────────────────────────────────────────
  {
    stateCode: "OR",
    stateName: "Oregon",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$25",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 must ride with adult; 12-15 need safety certificate",
    soundLimitsDb: 99,
    blmAccess: "open",
    nationalForestRules: "Deschutes, Willamette, Umpqua NFs have extensive OHV trails; MVUM required",
    notes: "ATV permit required ($25). Road legal on some county roads at 35 mph or less. Oregon Dunes NRA is world-class riding. Massive BLM access in eastern OR.",
    officialUrl: "https://www.oregon.gov/oprd/atv",
    lastVerified: "2025-12",
  },
  // ── PA ──────────────────────────────────────────────
  {
    stateCode: "PA",
    stateName: "Pennsylvania",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$40",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 10 cannot operate; 10-15 must have safety certificate and ride supervised",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Allegheny NF: designated OHV trails; seasonal closures; permit required",
    notes: "Registration required. Helmet required for all. No road use. State forests have extensive ATV trail system. Popular areas: Anthracite, Michaux, Bald Eagle.",
    officialUrl: "https://www.dcnr.pa.gov/Recreation/WhatToDo/ATVRiding/Pages/default.aspx",
    lastVerified: "2025-12",
  },
  // ── RI ──────────────────────────────────────────────
  {
    stateCode: "RI",
    stateName: "Rhode Island",
    registrationRequired: true,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 16 cannot operate on any public land",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "No national forests in RI",
    notes: "Extremely limited OHV opportunities. Registration required. No public trail system. Private land only.",
    officialUrl: "https://dem.ri.gov/natural-resources-bureau/parks-recreation",
    lastVerified: "2025-12",
  },
  // ── SC ──────────────────────────────────────────────
  {
    stateCode: "SC",
    stateName: "South Carolina",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 6 cannot operate; 6-15 must be supervised by adult",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Francis Marion, Sumter NFs: very limited OHV access",
    notes: "No state registration. Not road-legal. Private parks and private land primary riding areas. Gulches OHV Park is popular.",
    officialUrl: "https://www.scstateparks.com/",
    lastVerified: "2025-12",
  },
  // ── SD ──────────────────────────────────────────────
  {
    stateCode: "SD",
    stateName: "South Dakota",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$20",
    highwayLegal: true,
    maxSpeedMph: 30,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate on public roads; 12-15 need safety certificate",
    soundLimitsDb: null,
    blmAccess: "restricted",
    nationalForestRules: "Black Hills NF: extensive designated trail system; motorized travel maps required",
    notes: "Registration required. Road legal on designated roads. Black Hills has outstanding OHV trail system. Some BLM access in western SD.",
    officialUrl: "https://gfp.sd.gov/ohv/",
    lastVerified: "2025-12",
  },
  // ── TN ──────────────────────────────────────────────
  {
    stateCode: "TN",
    stateName: "Tennessee",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 must be supervised by adult; under 16 cannot operate on public roads",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Cherokee NF: very limited OHV access; mostly non-motorized",
    notes: "No state registration. Not road-legal. Royal Blue WMA, North Cumberland WMA, and private parks are popular. Windrock is world-class private OHV park.",
    officialUrl: "https://www.tn.gov/twra/outdoor-recreation/atv-safety.html",
    lastVerified: "2025-12",
  },
  // ── TX ──────────────────────────────────────────────
  {
    stateCode: "TX",
    stateName: "Texas",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 14 cannot operate on public land without adult; under 16 needs safety course",
    soundLimitsDb: null,
    blmAccess: "restricted",
    nationalForestRules: "Sam Houston, Angelina NFs: very limited OHV access",
    notes: "No state registration. Counties can allow ATV use on county roads. Barnwell Mountain, Hidden Falls, and Bridgeport popular. Mostly private land riding.",
    officialUrl: "https://tpwd.texas.gov/outdoor-learning/hunter-education/atv-safety",
    lastVerified: "2025-12",
  },
  // ── UT ──────────────────────────────────────────────
  {
    stateCode: "UT",
    stateName: "Utah",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$30",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 8 cannot operate on public land; 8-15 must have safety certificate",
    soundLimitsDb: 96,
    blmAccess: "open",
    nationalForestRules: "Extensive trail systems in Fishlake, Manti-La Sal, Uinta-Wasatch NFs; MVUMs required",
    notes: "OHV registration required ($30). Road legal on designated roads 35 mph or less. Utah has 80,000+ miles of OHV trails. Moab, Sand Hollow, Little Sahara, Paiute Trail world-class.",
    officialUrl: "https://stateparks.utah.gov/ohv",
    lastVerified: "2025-12",
  },
  // ── VT ──────────────────────────────────────────────
  {
    stateCode: "VT",
    stateName: "Vermont",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$35",
    highwayLegal: true,
    maxSpeedMph: 25,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 must ride with licensed adult; 12-15 need safety education",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Green Mountain NF: very limited OHV access, mostly non-motorized",
    notes: "Registration required. Non-resident registration available. VAST trail network connects to road corridors. Club-maintained trails. Limited road use where posted.",
    officialUrl: "https://fpr.vermont.gov/recreation/atv",
    lastVerified: "2025-12",
  },
  // ── VA ──────────────────────────────────────────────
  {
    stateCode: "VA",
    stateName: "Virginia",
    registrationRequired: false,
    nonResidentPermit: false,
    permitCost: "$0",
    highwayLegal: false,
    maxSpeedMph: null,
    helmetRequired: "always",
    ageRestrictions: "Under 16 cannot operate on public land without adult supervision",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "George Washington & Jefferson NF: limited designated OHV areas; Peters Mill Run, Taskers Gap",
    notes: "Helmet required for all. Not road-legal. Private land and designated USFS trails. Popular areas: Coeburn, South Pedlar, and private parks.",
    officialUrl: "https://www.dcr.virginia.gov/recreational-planning/atv",
    lastVerified: "2025-12",
  },
  // ── WA ──────────────────────────────────────────────
  {
    stateCode: "WA",
    stateName: "Washington",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$25",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 13 cannot operate on public land without adult; 13-17 need safety certificate",
    soundLimitsDb: null,
    blmAccess: "open",
    nationalForestRules: "Okanogan-Wenatchee, Gifford Pinchot NFs: designated trails; MVUMs required",
    notes: "ORV tag required. Non-resident permits available. Road legal on designated roads. Good BLM access in eastern WA. Popular areas: Reiter, Elbe Hills, Naches.",
    officialUrl: "https://www.parks.wa.gov/orv",
    lastVerified: "2025-12",
  },
  // ── WV ──────────────────────────────────────────────
  {
    stateCode: "WV",
    stateName: "West Virginia",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$25",
    highwayLegal: true,
    maxSpeedMph: 25,
    helmetRequired: "always",
    ageRestrictions: "Under 18 must have safety certificate; under 16 supervised by adult",
    soundLimitsDb: null,
    blmAccess: "closed",
    nationalForestRules: "Monongahela NF: very limited OHV access",
    notes: "Registration required. Helmet required for all. Hatfield-McCoy trail system is 700+ miles and nationally renowned. Non-resident permits available. Road connections on designated routes.",
    officialUrl: "https://www.wvdnr.gov/ohv/",
    lastVerified: "2025-12",
  },
  // ── WI ──────────────────────────────────────────────
  {
    stateCode: "WI",
    stateName: "Wisconsin",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$30",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 12 cannot operate without adult; 12-15 must have safety certificate",
    soundLimitsDb: 96,
    blmAccess: "closed",
    nationalForestRules: "Chequamegon-Nicolet NF: designated ATV trails; seasonal restrictions",
    notes: "Registration required. Non-resident trail pass available. Extensive ATV trail system (3,000+ miles). Counties can authorize road use. Northern WI very ATV-friendly.",
    officialUrl: "https://dnr.wisconsin.gov/topic/parks/recreation/atv",
    lastVerified: "2025-12",
  },
  // ── WY ──────────────────────────────────────────────
  {
    stateCode: "WY",
    stateName: "Wyoming",
    registrationRequired: true,
    nonResidentPermit: true,
    permitCost: "$15",
    highwayLegal: true,
    maxSpeedMph: 35,
    helmetRequired: "under-18",
    ageRestrictions: "Under 16 cannot operate on public roads; under 12 supervised on public land",
    soundLimitsDb: null,
    blmAccess: "open",
    nationalForestRules: "Bridger-Teton, Shoshone, Bighorn NFs: designated routes; MVUMs required",
    notes: "OHV permit required. Road legal on designated roads. Large BLM acreage open to OHV. Continental Divide trail system, Red Desert, and Killpecker Dunes popular.",
    officialUrl: "https://wyoparks.wyo.gov/index.php/programs/ohv",
    lastVerified: "2025-12",
  },
];

// ── Helpers ───────────────────────────────────────────

export function getLegalStatus(
  state: StateLegalInfo,
  view: LegalView,
): "green" | "yellow" | "red" {
  if (view === "unregistered") {
    // Unregistered: can you ride without any registration?
    if (!state.registrationRequired && state.blmAccess === "open") return "green";
    if (state.blmAccess === "open" || !state.registrationRequired) return "yellow";
    return "red";
  }
  if (view === "plated") {
    // Plated/registered: full legal access?
    if (state.highwayLegal && state.blmAccess === "open") return "green";
    if (state.highwayLegal || state.blmAccess === "open") return "yellow";
    return "red";
  }
  // Non-resident
  if (state.nonResidentPermit && state.blmAccess === "open") return "green";
  if (state.nonResidentPermit || state.blmAccess !== "closed") return "yellow";
  return "red";
}

export function getStateByCode(code: string): StateLegalInfo | undefined {
  return stateLegalData.find((s) => s.stateCode === code);
}
