// ─── RigSafe Rooftop Tent Database ──────────────────────────────────
// Real manufacturer specs for rooftop tents (RTTs).
//
// Sources:
//   Weight, dimensions, capacity: Manufacturer spec sheets & product pages
//   Realistic sleeping: Calculated from floor dimensions
//     (24" per adult + 6" gap, 20" per teen, 16" per child)

export interface TentEntry {
  id: string;
  brand: string;
  model: string;
  type: "hardshell-wedge" | "hardshell-clamshell" | "hardshell-cantilever" | "softshell-foldout";
  openSide: "driver" | "passenger" | "either";  // which side the tent opens / entry point
  closedWeightLbs: number;
  closedHeightIn: number;
  closedLengthIn: number;
  closedWidthIn: number;
  openLengthIn: number;
  openWidthIn: number;
  openHeadroomIn: number;
  mattressThicknessIn: number;
  sleepsMarketing: number;       // what they claim
  sleepsRealistic: number;       // what fits comfortably
  staticRatingLbs: number;       // tent's own weight rating for occupants
  hasAnnex: boolean;
  annexName?: string;
  annexWeightLbs?: number;
  annexSleeps?: number;
  annexAffiliateUrl?: string;
  affiliateUrl: string;
  notes?: string;
}

export const tentDatabase: TentEntry[] = [
  // ─── iKAMPER ────────────────────────────────────────────────────────

  {
    id: "ikamper-skycamp-3",
    brand: "iKamper",
    model: "Skycamp 3.0",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 165,
    closedHeightIn: 13,
    closedLengthIn: 86,
    closedWidthIn: 56,
    openLengthIn: 86,
    openWidthIn: 101,
    openHeadroomIn: 48,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "iKamper Skycamp 3.0 Annex",
    annexWeightLbs: 18,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B0BN3CGFQJ?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B0BN3BN7YK?tag=prepperevo-20",
    notes: "King-size mattress. Hard shell with poly-cotton canopy. Premium build quality.",
  },
  {
    id: "ikamper-bdv",
    brand: "iKamper",
    model: "BDV Duo",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 175,
    closedHeightIn: 6.75,
    closedLengthIn: 90,
    closedWidthIn: 56,
    openLengthIn: 90,
    openWidthIn: 56,
    openHeadroomIn: 53,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "iKamper BDV Annex",
    annexWeightLbs: 22,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B0C94KZXHT?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B0C94L3BGY?tag=prepperevo-20",
    notes: "Wedge hardshell with 6.75\" closed profile. Dual-expanding design. 600 lb max load.",
  },
  {
    id: "ikamper-xcover-2",
    brand: "iKamper",
    model: "X-Cover 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 150,
    closedHeightIn: 13,
    closedLengthIn: 56,
    closedWidthIn: 48,
    openLengthIn: 96,
    openWidthIn: 56,
    openHeadroomIn: 46,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "iKamper X-Cover 2.0 Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B09LQWXR7M?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B09LQXCTR4?tag=prepperevo-20",
    notes: "Soft-shell fold-out. Lighter weight, lower profile when closed.",
  },

  // ─── ROOFNEST ───────────────────────────────────────────────────────

  {
    id: "roofnest-falcon-2",
    brand: "Roofnest",
    model: "Falcon 2",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 140,
    closedHeightIn: 6.5,
    closedLengthIn: 88,
    closedWidthIn: 50,
    openLengthIn: 86,
    openWidthIn: 48,
    openHeadroomIn: 60,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 650,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B08T6JYC1D?tag=prepperevo-20",
    notes: "Slim wedge profile. 6.5\" closed height is extremely garage-friendly.",
  },
  {
    id: "roofnest-condor-xl",
    brand: "Roofnest",
    model: "Condor XL",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 180,
    closedHeightIn: 13,
    closedLengthIn: 74,
    closedWidthIn: 55,
    openLengthIn: 93,
    openWidthIn: 74,
    openHeadroomIn: 50,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B09NRGXY7T?tag=prepperevo-20",
    notes: "Extra-long platform. Great for tall people. Premium finish.",
  },
  {
    id: "roofnest-sparrow-eye",
    brand: "Roofnest",
    model: "Sparrow EYE",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 11.5,
    closedLengthIn: 85,
    closedWidthIn: 50,
    openLengthIn: 83,
    openWidthIn: 49,
    openHeadroomIn: 44,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 650,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0BZK7N8WR?tag=prepperevo-20",
    notes: "Most compact hardshell wedge. Panoramic skylight window.",
  },

  {
    id: "roofnest-condor-2-xxl-air",
    brand: "Roofnest",
    model: "Condor 2 XXL Air",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 205,
    closedHeightIn: 15,
    closedLengthIn: 88,
    closedWidthIn: 60,
    openLengthIn: 102,
    openWidthIn: 80,
    openHeadroomIn: 50,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/condor-2-xxl-air",
    notes: "World's largest hardshell RTT. PC-ABS shell with LINE-X coating. Inflatable foamcore mattress. 95x80 sleeping area.",
  },

  // ─── 23ZERO ─────────────────────────────────────────────────────────
  // Full 2.0 generation lineup. Breezeway + original Walkabout discontinued.
  // Walkabout 2.0 specs verified from 23zero.com product pages.
  // Kabul (wedge hardshell) + Armadillo (premium hardshell) pending spec verification.
  // Smaller models (Walkabout 36 2.0, 42 2.0) pending spec verification.
  // Winter liner available for all Walkabout 2.0 sizes: 8 lbs.

  {
    id: "23zero-walkabout-56",
    brand: "23Zero",
    model: "Walkabout 56 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 14,
    closedLengthIn: 57,
    closedWidthIn: 48,
    openLengthIn: 122,
    openWidthIn: 57,
    openHeadroomIn: 52,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 880,
    hasAnnex: true,
    affiliateUrl: "#",
    notes: "Full-size bed. 56\"×96\" sleeping area. 3\" rebound mattress with cotton top and waterproof base. 4-season. Heater/cooler port option available. Winter liner sold separately (8 lbs).",
  },
  {
    id: "23zero-walkabout-62",
    brand: "23Zero",
    model: "Walkabout 62 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 152,
    closedHeightIn: 14,
    closedLengthIn: 63,
    closedWidthIn: 48,
    openLengthIn: 122,
    openWidthIn: 63,
    openHeadroomIn: 52,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 880,
    hasAnnex: true,
    affiliateUrl: "#",
    notes: "Queen-size bed. 62\"×96\" sleeping area. 3\" rebound mattress with cotton top and waterproof base. 4-season. Winter liner sold separately (8 lbs).",
  },
  {
    id: "23zero-walkabout-72",
    brand: "23Zero",
    model: "Walkabout 72 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 165,
    closedHeightIn: 14,
    closedLengthIn: 48,
    closedWidthIn: 73,
    openLengthIn: 122,
    openWidthIn: 73,
    openHeadroomIn: 52,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 880,
    hasAnnex: true,
    affiliateUrl: "#",
    notes: "King-size bed. 72\"×96\" sleeping area. 3\" rebound mattress. 4-season. Heater/cooler port option available. Packs wider across vehicle (73\") — verify roof rack width. Winter liner sold separately (8 lbs).",
  },
  {
    id: "23zero-walkabout-87",
    brand: "23Zero",
    model: "Walkabout 87 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 198,
    closedHeightIn: 14,
    closedLengthIn: 88,
    closedWidthIn: 48,
    openLengthIn: 122,
    openWidthIn: 88,
    openHeadroomIn: 52,
    mattressThicknessIn: 3,
    sleepsMarketing: 6,
    sleepsRealistic: 3,
    staticRatingLbs: 1320,
    hasAnnex: true,
    affiliateUrl: "#",
    notes: "Largest 23Zero softshell. 87\"×96\" sleeping area — fits 3 adults. 3\" rebound mattress with cotton top and waterproof base. 4-season. Heater/cooler port option available. 1320 lb total load rating. 88\" closed footprint — verify rack length. Winter liner sold separately (8 lbs).",
  },

  // ─── OVS (Overland Vehicle Systems) ─────────────────────────────────

  {
    id: "ovs-nomadic-2",
    brand: "OVS",
    model: "Nomadic 2",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 150,
    closedHeightIn: 14,
    closedLengthIn: 47,
    closedWidthIn: 54,
    openLengthIn: 95,
    openWidthIn: 54,
    openHeadroomIn: 51,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 750,
    hasAnnex: true,
    annexName: "OVS Nomadic 2 Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B07R1V8RKQ?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B07R1V7TN6?tag=prepperevo-20",
    notes: "Best-selling budget soft-shell. Great entry-level RTT.",
  },
  {
    id: "ovs-nomadic-3",
    brand: "OVS",
    model: "Nomadic 3",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 174,
    closedHeightIn: 9.4,
    closedLengthIn: 64,
    closedWidthIn: 48,
    openLengthIn: 96,
    openWidthIn: 64,
    openHeadroomIn: 49,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 850,
    hasAnnex: true,
    annexName: "OVS Nomadic 3 Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B07R1VH3TG?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B07R1VGT9N?tag=prepperevo-20",
    notes: "Mid-size OVS. Popular upgrade from Nomadic 2.",
  },
  {
    id: "ovs-nomadic-4",
    brand: "OVS",
    model: "Nomadic 4",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 165,
    closedHeightIn: 16,
    closedLengthIn: 72,
    closedWidthIn: 62,
    openLengthIn: 112,
    openWidthIn: 72,
    openHeadroomIn: 50,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 750,
    hasAnnex: true,
    annexName: "OVS Nomadic 4 Annex",
    annexWeightLbs: 18,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B09D3GNVR8?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B09D3GN3S4?tag=prepperevo-20",
    notes: "Largest OVS soft-shell. Extended model for families.",
  },

  {
    id: "ovs-bushveld",
    brand: "OVS",
    model: "Bushveld",
    type: "hardshell-clamshell",
    openSide: "passenger",
    closedWeightLbs: 208,
    closedHeightIn: 12,
    closedLengthIn: 85,
    closedWidthIn: 49,
    openLengthIn: 85,
    openWidthIn: 88,
    openHeadroomIn: 45,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B094TM3HXS?tag=prepperevo-20",
    notes: "Cantilever hard shell. Single-piece polymer top. Marine-grade 304 stainless hardware. 1-minute setup.",
  },
  {
    id: "ovs-hd-bushveld-2p",
    brand: "OVS",
    model: "HD Bushveld 2 Person",
    type: "hardshell-clamshell",
    openSide: "passenger",
    closedWeightLbs: 178.2,
    closedHeightIn: 12,
    closedLengthIn: 65,
    closedWidthIn: 49,
    openLengthIn: 65,
    openWidthIn: 88,
    openHeadroomIn: 45,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B094TM3HXS?tag=prepperevo-20",
    notes: "HD Bushveld 2-person hardshell. 280G ripstop body, 420D oxford rainfly, insulated base. Same 49\" width and 45\" open headroom as 4-person — shorter 65\" footprint. Opens passenger-side only. 1-minute setup.",
  },
  {
    id: "ovs-hd-bushveld",
    brand: "OVS",
    model: "HD Bushveld 4 Person",
    type: "hardshell-clamshell",
    openSide: "passenger",
    closedWeightLbs: 207.9,
    closedHeightIn: 12,
    closedLengthIn: 85,
    closedWidthIn: 49,
    openLengthIn: 85,
    openWidthIn: 88,
    openHeadroomIn: 45,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS HD Bushveld Annex",
    annexWeightLbs: 15,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B096GCM4MK?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B094TM3HXS?tag=prepperevo-20",
    notes: "HD upgrade: double 280G ripstop body, 420D oxford rainfly, insulated base with anti-condensation layer. Grey body & tan rainfly. Cantilever design, 1-minute setup. 96in aluminum ladder. Opens passenger-side only — entry is always from the passenger side of the vehicle.",
  },
  {
    id: "ovs-nomadic-4-extended",
    brand: "OVS",
    model: "Nomadic 4 Extended",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 172,
    closedHeightIn: 9.4,
    closedLengthIn: 76,
    closedWidthIn: 48,
    openLengthIn: 76,
    openWidthIn: 95,
    openHeadroomIn: 49,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 950,
    hasAnnex: true,
    annexName: "OVS Nomadic 4 Extended Annex",
    annexWeightLbs: 18,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B09D3GNVR8?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B0C9KXLXHJ?tag=prepperevo-20",
    notes: "Largest OVS soft-shell. 75 x 94.5 sleeping area. 280G poly-cotton ripstop. Extended overhang.",
  },
  {
    id: "ovs-hd-nomadic-2-extended",
    brand: "OVS",
    model: "HD Nomadic 2 Extended",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 147,
    closedHeightIn: 14,
    closedLengthIn: 47,
    closedWidthIn: 54,
    openLengthIn: 95,
    openWidthIn: 54,
    openHeadroomIn: 51,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 750,
    hasAnnex: true,
    annexName: "OVS HD Nomadic 2 Extended Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    affiliateUrl: "#",
    notes: "HD upgrade: double 280G ripstop, 420D oxford rainfly, insulated base. Extended overhang model.",
  },
  {
    id: "ovs-hd-nomadic-3-extended",
    brand: "OVS",
    model: "HD Nomadic 3 Extended",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 156,
    closedHeightIn: 9.4,
    closedLengthIn: 64,
    closedWidthIn: 48,
    openLengthIn: 96,
    openWidthIn: 64,
    openHeadroomIn: 49,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 850,
    hasAnnex: true,
    annexName: "OVS HD Nomadic 3 Extended Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    affiliateUrl: "#",
    notes: "HD upgrade: double 280G ripstop, 420D oxford rainfly, insulated base. Mid-size extended overhang model.",
  },
  {
    id: "ovs-hd-nomadic-4-extended",
    brand: "OVS",
    model: "HD Nomadic 4 Extended",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 172,
    closedHeightIn: 9.4,
    closedLengthIn: 76,
    closedWidthIn: 48,
    openLengthIn: 76,
    openWidthIn: 95,
    openHeadroomIn: 49,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 950,
    hasAnnex: true,
    annexName: "OVS HD Nomadic 4 Extended Annex",
    annexWeightLbs: 18,
    annexSleeps: 2,
    affiliateUrl: "#",
    notes: "HD upgrade: double 280G ripstop, 420D oxford rainfly, insulated base. Largest OVS soft-shell. 75 x 94.5 sleeping area.",
  },

  // ─── OVS HARDSHELL LINEUP (VERIFIED FROM OVS PRODUCT PAGES) ─────────

  {
    id: "ovs-ld-tmon-2p",
    brand: "OVS",
    model: "LD TMON 2 Person",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 150,
    closedHeightIn: 6,
    closedLengthIn: 82.7,
    closedWidthIn: 50,
    openLengthIn: 82.7,
    openWidthIn: 50,
    openHeadroomIn: 65,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 750,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "LD (entry) tier. A-frame wedge shape when open — 65\" peak height is the tallest in the OVS lineup. Very flat 6\" closed profile. 3500 PU. Tan body & green rainfly.",
  },
  {
    id: "ovs-hd-mamba",
    brand: "OVS",
    model: "HD Mamba 3 Person",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 220,
    closedHeightIn: 6.5,
    closedLengthIn: 90.5,
    closedWidthIn: 55,
    openLengthIn: 90.5,
    openWidthIn: 55,
    openHeadroomIn: 59,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Largest OVS clamshell — 90.5\" footprint, verify rack length before ordering. Honeycomb aluminum shell. No skylight, no lighting, no annex. 3500 PU. Storage rack 45 lbs open / 100 lbs closed. Grey body & grey rainfly.",
  },
  {
    id: "ovs-hd-sidewinder",
    brand: "OVS",
    model: "HD Sidewinder 3 Person",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 220,
    closedHeightIn: 6.5,
    closedLengthIn: 90.5,
    closedWidthIn: 55,
    openLengthIn: 90.5,
    openWidthIn: 55,
    openHeadroomIn: 48,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Side-load variant of the HD Mamba — same base shell but opens to the side rather than straight up. Lower headroom (48\") due to side-load mechanism. Can be configured driver or passenger side. No skylight, no lighting. 3500 PU.",
  },
  {
    id: "ovs-hd-bundu-2p",
    brand: "OVS",
    model: "HD Bundu 2 Person",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 156,
    closedHeightIn: 11,
    closedLengthIn: 63,
    closedWidthIn: 43,
    openLengthIn: 63,
    openWidthIn: 82.5,
    openHeadroomIn: 47,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS HD Bundu Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Compact cantilever. ABS plastic shell. 2 nitrogen gas struts. Skylight and interior lighting included. Anti-condensation mat included. Annex optional. 3500 PU. 81\" telescoping ladder. 4-year warranty.",
  },
  {
    id: "ovs-hd-bundu-4p",
    brand: "OVS",
    model: "HD Bundu 4 Person",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 190,
    closedHeightIn: 12,
    closedLengthIn: 86.5,
    closedWidthIn: 51,
    openLengthIn: 86.5,
    openWidthIn: 88.5,
    openHeadroomIn: 45,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS HD Bundu Annex",
    annexWeightLbs: 15,
    annexSleeps: 2,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Large cantilever — 86.5\" footprint, verify rack length. ABS plastic shell. Skylight and interior lighting. Anti-condensation mat. Annex optional. 3500 PU. 81\" telescoping ladder. 4-year warranty.",
  },
  {
    id: "ovs-xd-atlas",
    brand: "OVS",
    model: "XD Atlas",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 180,
    closedHeightIn: 13,
    closedLengthIn: 60,
    closedWidthIn: 52,
    openLengthIn: 60,
    openWidthIn: 87,
    openHeadroomIn: 53,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS XD Atlas Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "XD-tier cantilever. ABS shell over aluminum honeycomb base. Only OVS tent with AC/heater port. Skylight, interior lighting, blackout coating. 5000 PU. Annex + awning extension optional. Storage rack 45/100 lbs. 6-year fabric / lifetime structural warranty. 81\" ladder.",
  },
  {
    id: "ovs-xd-lhotse",
    brand: "OVS",
    model: "XD Lhotse 2 Person",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 230,
    closedHeightIn: 8,
    closedLengthIn: 84,
    closedWidthIn: 52,
    openLengthIn: 84,
    openWidthIn: 52,
    openHeadroomIn: 57,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Premium XD clamshell. Full honeycomb aluminum shell. Built-in storage rack (45 lbs open / 100 lbs closed) — can run solar on top while packed. Blackout interior, 5000 PU, military-spec seals. 6-year / lifetime structural warranty. Blue body & black shell.",
  },
  {
    id: "ovs-xd-k2",
    brand: "OVS",
    model: "XD K2 2 Person",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 220,
    closedHeightIn: 10,
    closedLengthIn: 84.5,
    closedWidthIn: 57,
    openLengthIn: 95,
    openWidthIn: 57,
    openHeadroomIn: 51,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Pop-up clamshell — platform extends to 95\" when open. Rainfly expands to 107\"×78\" when fully deployed. Ladder mounts on all 4 sides (3 entry points). Honeycomb aluminum shell. 5000 PU, blackout, storage rack 45/100 lbs. AC/heater port. 6-year / lifetime structural warranty.",
  },
  {
    id: "ovs-xd-everest-2p",
    brand: "OVS",
    model: "XD Everest 2 Person",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 250,
    closedHeightIn: 13,
    closedLengthIn: 68,
    closedWidthIn: 52.75,
    openLengthIn: 68,
    openWidthIn: 85.8,
    openHeadroomIn: 54,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS XD Everest Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Premium XD cantilever. Full honeycomb aluminum shell and base. AC/heater port, skylight, interior lighting, blackout. 5000 PU. Storage rack 45/100 lbs. Annex + awning optional. 6-year / lifetime structural warranty. 81\" ladder.",
  },
  {
    id: "ovs-xd-everest-4p",
    brand: "OVS",
    model: "XD Everest 4 Person",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 302,
    closedHeightIn: 13,
    closedLengthIn: 74.8,
    closedWidthIn: 52.36,
    openLengthIn: 74.8,
    openWidthIn: 85.8,
    openHeadroomIn: 54,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS XD Everest Annex",
    annexWeightLbs: 15,
    annexSleeps: 2,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Heaviest tent in the OVS lineup at 302 lbs — verify vehicle dynamic roof rating AND rack rating before ordering. Full honeycomb aluminum shell and base. AC/heater port, skylight, interior lighting, blackout. 5000 PU. Storage rack 45/100 lbs. 6-year / lifetime structural warranty.",
  },

  // ─── SMITTYBILT ─────────────────────────────────────────────────────

  {
    id: "smittybilt-overlander-gen2-xl",
    brand: "Smittybilt",
    model: "Overlander Gen2 XL",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 139,
    closedHeightIn: 11,
    closedLengthIn: 76,
    closedWidthIn: 47,
    openLengthIn: 76,
    openWidthIn: 122,
    openHeadroomIn: 51,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 770,
    hasAnnex: true,
    annexName: "Smittybilt Overlander Gen2 Annex",
    annexWeightLbs: 14,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B08JQDP7FX?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B08JQDR9RR?tag=prepperevo-20",
    notes: "Budget-friendly. Most affordable RTT with decent build quality.",
  },

  // ─── ARB ────────────────────────────────────────────────────────────

  {
    id: "arb-simpson-iii",
    brand: "ARB",
    model: "Simpson III",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 154,
    closedHeightIn: 12,
    closedLengthIn: 47,
    closedWidthIn: 55,
    openLengthIn: 95,
    openWidthIn: 55,
    openHeadroomIn: 51,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 550,
    hasAnnex: true,
    annexName: "ARB Simpson III Annex",
    annexWeightLbs: 15,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B001CWKLZ4?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B001CWKLZE?tag=prepperevo-20",
    notes: "Australian legend. Known for durability and build quality.",
  },

  // ─── TOPOAK ─────────────────────────────────────────────────────────

  {
    id: "topoak-galaxy-pro",
    brand: "TOPOAK",
    model: "Galaxy Pro",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 176,
    closedHeightIn: 8,
    closedLengthIn: 83,
    closedWidthIn: 56,
    openLengthIn: 83,
    openWidthIn: 56,
    openHeadroomIn: 53,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 500,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0B9SQT31Y?tag=prepperevo-20",
    notes: "Budget hardshell wedge. Low profile. Light weight for the class.",
  },

  // ─── BODY ARMOR ─────────────────────────────────────────────────────

  {
    id: "bodyarmor-pike-2p",
    brand: "Body Armor",
    model: "Sky Ridge Pike 2-Person",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 108,
    closedHeightIn: 12,
    closedLengthIn: 43,
    closedWidthIn: 48,
    openLengthIn: 110,
    openWidthIn: 55,
    openHeadroomIn: 50,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 460,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0B4N7BJXT?tag=prepperevo-20",
    notes: "Mid-range hardshell. Good value for the weight class.",
  },
  {
    id: "bodyarmor-pike-3p",
    brand: "Body Armor",
    model: "Sky Ridge Pike 3-Person",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 172,
    closedHeightIn: 14,
    closedLengthIn: 47,
    closedWidthIn: 75,
    openLengthIn: 122,
    openWidthIn: 74,
    openHeadroomIn: 51,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 770,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0B4N8J97G?tag=prepperevo-20",
    notes: "Clamshell version. Full standing room for 6-foot person.",
  },

  // ─── TUFF STUFF ─────────────────────────────────────────────────────

  {
    id: "tuffstuff-alpha",
    brand: "Tuff Stuff",
    model: "Alpha",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 176,
    closedHeightIn: 15,
    closedLengthIn: 75,
    closedWidthIn: 55,
    openLengthIn: 87,
    openWidthIn: 71,
    openHeadroomIn: 52,
    mattressThicknessIn: 2.75,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 1100,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B07YQJHGGN?tag=prepperevo-20",
    notes: "Side-opening ABS hard shell. Aluminum honeycomb floor. 1100 lb static rating. 2-minute setup.",
  },
  {
    id: "tuffstuff-alpha-ii",
    brand: "Tuff Stuff",
    model: "Alpha II",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 141,
    closedHeightIn: 14,
    closedLengthIn: 60,
    closedWidthIn: 50,
    openLengthIn: 79,
    openWidthIn: 60,
    openHeadroomIn: 46,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B07YQJHGGN?tag=prepperevo-20",
    notes: "Gas strut assisted. Budget clamshell option.",
  },
  {
    id: "tuffstuff-ranger-3",
    brand: "Tuff Stuff",
    model: "Ranger 3",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 164,
    closedHeightIn: 15,
    closedLengthIn: 65,
    closedWidthIn: 48,
    openLengthIn: 96,
    openWidthIn: 65,
    openHeadroomIn: 52,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: true,
    annexName: "Tuff Stuff Ranger 3 Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B07BZQRP4K?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B07BZQRN6K?tag=prepperevo-20",
    notes: "Affordable entry-level soft-shell with annex.",
  },

  // ─── THULE ──────────────────────────────────────────────────────────

  {
    id: "thule-tepui-autana",
    brand: "Thule",
    model: "Tepui Explorer Autana",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 12,
    closedLengthIn: 48,
    closedWidthIn: 56,
    openLengthIn: 96,
    openWidthIn: 56,
    openHeadroomIn: 52,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "Thule Tepui Autana Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B076H5K8RN?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B076H5JGRM?tag=prepperevo-20",
    notes: "Thule quality. Integrated annex room option. Good ventilation.",
  },

  // ─── ALU-CAB ────────────────────────────────────────────────────────

  {
    id: "alucab-gen3-expedition",
    brand: "Alu-Cab",
    model: "Gen 3.1 Expedition",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 192,
    closedHeightIn: 11,
    closedLengthIn: 90,
    closedWidthIn: 55,
    openLengthIn: 83,
    openWidthIn: 51,
    openHeadroomIn: 63,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "Alu-Cab Gen 3.1 Annex",
    annexWeightLbs: 30,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B0CWV4R2QX?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B0CWV4PYQQ?tag=prepperevo-20",
    notes: "South African engineering. All-aluminum construction. Premium expedition-grade.",
  },

  // ─── ROOF SPACE ─────────────────────────────────────────────────────

  {
    id: "roofspace-2",
    brand: "Roof Space",
    model: "Roof Space 2",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 147,
    closedHeightIn: 9.4,
    closedLengthIn: 61.5,
    closedWidthIn: 53.5,
    openLengthIn: 98,
    openWidthIn: 59,
    openHeadroomIn: 51,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "Light Base Annex",
    annexWeightLbs: 15,
    annexSleeps: 0,
    affiliateUrl: "https://roofspace.com/products/roof-space-2",
    notes: "German-engineered hybrid hardshell. 270-degree terrace/awning. Queen mattress. 9.4\" low profile.",
  },
  {
    id: "roofspace-4",
    brand: "Roof Space",
    model: "Roof Space 4",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 196,
    closedHeightIn: 9.4,
    closedLengthIn: 87,
    closedWidthIn: 53.5,
    openLengthIn: 98.4,
    openWidthIn: 82.7,
    openHeadroomIn: 51.2,
    mattressThicknessIn: 2,
    sleepsMarketing: 6,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://roofspace.com/products/roof-space-4",
    notes: "Largest hardshell-style RTT on market. Cal King mattress. Double terrace. 30-second gas strut setup.",
  },

  // ─── GO FAST CAMPERS (GFC) ─────────────────────────────────────────

  {
    id: "gfc-v2-pro",
    brand: "GFC",
    model: "V2 Pro RTT",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 135,
    closedHeightIn: 6,
    closedLengthIn: 97,
    closedWidthIn: 53,
    openLengthIn: 90,
    openWidthIn: 50,
    openHeadroomIn: 55,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 500,
    hasAnnex: false,
    affiliateUrl: "https://gofastcampers.com/products/v2-pro-rtt",
    notes: "Made in Bozeman, MT. Aluminum honeycomb panels. Industry-thinnest 6\" closed profile.",
  },
  {
    id: "gfc-v2-pro-xl",
    brand: "GFC",
    model: "V2 Pro RTT XL",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 157,
    closedHeightIn: 6,
    closedLengthIn: 97,
    closedWidthIn: 59,
    openLengthIn: 90,
    openWidthIn: 56,
    openHeadroomIn: 55,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 500,
    hasAnnex: false,
    affiliateUrl: "https://gofastcampers.com/products/v2-pro-rtt-xl",
    notes: "6\" wider sleeping platform than standard V2. Comfortably fits two adults.",
  },
  {
    id: "gfc-superlite",
    brand: "GFC",
    model: "SuperLite",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 80,
    closedHeightIn: 5,
    closedLengthIn: 90,
    closedWidthIn: 50,
    openLengthIn: 90,
    openWidthIn: 50,
    openHeadroomIn: 50,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 1,
    staticRatingLbs: 500,
    hasAnnex: false,
    affiliateUrl: "https://gofastcampers.com/products/superlite",
    notes: "Lightest hardshell RTT on market at 80 lbs. 5\" closed profile. Mattress optional add-on.",
  },

  // ─── FRONT RUNNER ──────────────────────────────────────────────────

  {
    id: "frontrunner-rtt",
    brand: "Front Runner",
    model: "Roof Top Tent",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 93,
    closedHeightIn: 13,
    closedLengthIn: 52,
    closedWidthIn: 49,
    openLengthIn: 96,
    openWidthIn: 51,
    openHeadroomIn: 46,
    mattressThicknessIn: 2.4,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "Front Runner RTT Annex",
    annexWeightLbs: 12,
    annexSleeps: 0,
    affiliateUrl: "https://www.amazon.com/dp/B00S1Q89SU?tag=prepperevo-20",
    notes: "Only 95 lbs. Lowest-profile softshell at 13\". South African made. 260g poly-cotton ripstop.",
  },

  // ─── EEZI-AWN ─────────────────────────────────────────────────────

  {
    id: "eeziawn-series3-1400",
    brand: "Eezi-Awn",
    model: "Series 3 1400",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 11,
    closedLengthIn: 48,
    closedWidthIn: 55,
    openLengthIn: 96,
    openWidthIn: 55,
    openHeadroomIn: 51,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "Series 3 Shower Skirt",
    annexWeightLbs: 10,
    annexSleeps: 0,
    affiliateUrl: "https://eezi-awn.com/us/product/series-3/",
    notes: "Gold standard softshell since the 1980s. South African. 360GSM heavy-duty ripstop canvas. 4-season.",
  },
  {
    id: "eeziawn-blade-40th",
    brand: "Eezi-Awn",
    model: "Blade 40th Edition",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 181,
    closedHeightIn: 13,
    closedLengthIn: 87,
    closedWidthIn: 57,
    openLengthIn: 84,
    openWidthIn: 52,
    openHeadroomIn: 56,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://eezi-awn.com/us/product/blade/",
    notes: "All-aluminum. Insulated roof and floor. K9 rack on top for solar/bikes. Rear-hinge design.",
  },

  // ─── CVT (CASCADIA VEHICLE TENTS) ─────────────────────────────────

  {
    id: "cvt-mt-hood-56",
    brand: "CVT",
    model: "Mt Hood 2 (56\")",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 205,
    closedHeightIn: 8.25,
    closedLengthIn: 85,
    closedWidthIn: 56,
    openLengthIn: 81,
    openWidthIn: 53,
    openHeadroomIn: 56,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://cascadiatents.com/products/mt-hood-2-hardshell-tent",
    notes: "CNC-machined aluminum. T-channel perimeter for accessories. Portland, OR based. 8.25\" closed profile.",
  },

  // ─── GUANA EQUIPMENT ──────────────────────────────────────────────

  {
    id: "guana-wanaka-55",
    brand: "Guana Equipment",
    model: "Wanaka 55",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 125,
    closedHeightIn: 14,
    closedLengthIn: 55,
    closedWidthIn: 50,
    openLengthIn: 96,
    openWidthIn: 55,
    openHeadroomIn: 48,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "Guana Wanaka XL Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B08R7GY8V3?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B08R7H4QHV?tag=prepperevo-20",
    notes: "600D waterproof ripstop polyester oxford. Diamond plate aluminum base. 1\" thick aluminum poles. XL annex included.",
  },

  // ─── iKAMPER MINI ─────────────────────────────────────────────────

  {
    id: "ikamper-skycamp-mini",
    brand: "iKamper",
    model: "Skycamp Mini",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 105,
    closedHeightIn: 9.5,
    closedLengthIn: 74,
    closedWidthIn: 44,
    openLengthIn: 74,
    openWidthIn: 88,
    openHeadroomIn: 44,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 1,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0BN3HPFQ4?tag=prepperevo-20",
    notes: "Designed specifically for compact vehicles and crossovers. Lightest iKamper hardshell at 105 lbs. 9.5\" closed profile. Best-fit RTT for crossovers with 165 lb roof ratings when paired with Thule/Yakima crossbars (~22 lbs).",
  },

  // ─── TRUSTMADE ────────────────────────────────────────────────────

  {
    id: "trustmade-nomad",
    brand: "Trustmade",
    model: "Nomad",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 207,
    closedHeightIn: 11,
    closedLengthIn: 83,
    closedWidthIn: 49,
    openLengthIn: 83,
    openWidthIn: 49,
    openHeadroomIn: 35,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 1,
    staticRatingLbs: 700,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B09JKG6D2Z?tag=prepperevo-20",
    notes: "Budget-friendly hardshell. Stainless steel frame. Only 35\" headroom. Good entry-level RTT.",
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────

export function getTentBrands(): string[] {
  return [...new Set(tentDatabase.map((t) => t.brand))].sort();
}

export function getTentModels(brand: string): TentEntry[] {
  return tentDatabase.filter((t) => t.brand === brand).sort((a, b) => a.model.localeCompare(b.model));
}

export function findTent(id: string): TentEntry | undefined {
  return tentDatabase.find((t) => t.id === id);
}

/**
 * Calculate realistic sleeping capacity from floor dimensions.
 * 24" per adult (shoulder width) + 6" gap between each person.
 */
export function calcRealisticSleeping(widthIn: number): { adults: number; tight: number } {
  const adultWidth = 24;
  const gap = 6;
  const adults = Math.floor((widthIn + gap) / (adultWidth + gap));
  const tight = Math.floor(widthIn / adultWidth);
  return { adults: Math.max(1, adults), tight: Math.max(1, tight) };
}
