// ─── RigSafe Rooftop Tent Database ──────────────────────────────────
// Real manufacturer specs for rooftop tents (RTTs).
//
// Sources:
//   Weight, dimensions, capacity: Manufacturer spec sheets & product pages
//   Realistic sleeping: Calculated from floor dimensions
//     (24" per adult + 6" gap, 20" per teen, 16" per child)

export interface TentEntry {
  id: string;
  brand: string;
  model: string;
  type: "hardshell-wedge" | "hardshell-clamshell" | "hardshell-cantilever" | "softshell-foldout";
  openSide: "driver" | "passenger" | "either";  // which side the tent opens / entry point
  closedWeightLbs: number;
  closedHeightIn: number;
  closedLengthIn: number;
  closedWidthIn: number;
  openLengthIn: number;
  openWidthIn: number;
  openHeadroomIn: number;
  mattressThicknessIn: number;
  sleepsMarketing: number;       // what they claim
  sleepsRealistic: number;       // what fits comfortably
  staticRatingLbs: number;       // tent's own weight rating for occupants
  hasAnnex: boolean;
  annexName?: string;
  annexWeightLbs?: number;
  annexSleeps?: number;
  annexAffiliateUrl?: string;
  affiliateUrl: string;
  notes?: string;
}

export const tentDatabase: TentEntry[] = [
  // ─── iKAMPER ────────────────────────────────────────────────────────

  {
    id: "ikamper-skycamp-3",
    brand: "iKamper",
    model: "Skycamp 3.0",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 165,
    closedHeightIn: 13.5,
    closedLengthIn: 85.5,
    closedWidthIn: 54.75,
    openLengthIn: 85.5,
    openWidthIn: 77.25,
    openHeadroomIn: 48,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "iKamper Skycamp 3.0 Annex",
    annexWeightLbs: 22,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B0BN3CGFQJ?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B0BN3BN7YK?tag=prepperevo-20",
    notes: "82.75\"×77.25\" sleeping area (44.3 sq ft). Dual-layer FRP shell with 1\" air insulation. 9-zone 2.5\" polyfoam mattress. 300 gsm blackout poly-cotton canvas. Crossbar range 30\"–60\". 88.5\" HC Ladder included. Accessory weights: Annex Room +20–24 lbs, HC Steps +5 lbs.",
  },
  {
    id: "ikamper-skycamp-dlx",
    brand: "iKamper",
    model: "Skycamp DLX",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 190,
    closedHeightIn: 13.5,
    closedLengthIn: 85.5,
    closedWidthIn: 54.75,
    openLengthIn: 85.5,
    openWidthIn: 77.25,
    openHeadroomIn: 48,
    mattressThicknessIn: 4,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "iKamper Skycamp 3.0 Annex",
    annexWeightLbs: 22,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B0BN3CGFQJ?tag=prepperevo-20",
    affiliateUrl: "#",
    notes: "Premium DLX upgrade over Skycamp 3.0 — same shell/footprint but 4\" RTT Comfort air-and-foam mattress, cork layer on honeycomb aluminum floor, interior + exterior LED lighting (USB DC5V). 82.75\"×77.25\" sleeping area. 25 lbs heavier than standard 3.0. Accessory weights: Annex Room +20–24 lbs, HC Steps +5 lbs.",
  },
  {
    id: "ikamper-bdv",
    brand: "iKamper",
    model: "BDV Duo",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 175,
    closedHeightIn: 6.75,
    closedLengthIn: 90,
    closedWidthIn: 56,
    openLengthIn: 90,
    openWidthIn: 56,
    openHeadroomIn: 59,
    mattressThicknessIn: 2.75,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "iKamper BDV Annex",
    annexWeightLbs: 18.7,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B0C94KZXHT?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B0C94L3BGY?tag=prepperevo-20",
    notes: "Wedge hardshell. 83.75\"×53.75\" sleeping area (31.3 sq ft). 59\" peak headroom. 6.75\" closed profile — excellent garage clearance. FRP shell with blackout canvas. Crossbar range 32\"–48\". Ladder installs driver, passenger, or rear. Accessory weights: BDV Annex Plus +18.7 lbs, BDV Accessory Rack +11.7 lbs (Solo) / +14.3 lbs (Duo).",
  },
  {
    id: "ikamper-xcover-3",
    brand: "iKamper",
    model: "X-Cover 3.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 128,
    closedHeightIn: 11,
    closedLengthIn: 77.75,
    closedWidthIn: 48.5,
    openLengthIn: 90.5,
    openWidthIn: 74,
    openHeadroomIn: 48.75,
    mattressThicknessIn: 2.75,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 750,
    hasAnnex: true,
    annexName: "iKamper X-Cover 3.0 Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Hybrid design — honeycomb aluminum panel floor with canvas sides. 74\"×90.5\" open footprint (46.5 sq ft). 9-zone 2.75\" polyfoam mattress. 11\" closed profile. Crossbar range 30\"–60\".",
  },
  {
    id: "ikamper-xcover-2",
    brand: "iKamper",
    model: "X-Cover 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 150,
    closedHeightIn: 13,
    closedLengthIn: 56,
    closedWidthIn: 48,
    openLengthIn: 89,
    openWidthIn: 56,
    openHeadroomIn: 46,
    mattressThicknessIn: 2.75,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "iKamper X-Cover 2.0 Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B09LQWXR7M?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B09LQXCTR4?tag=prepperevo-20",
    notes: "Legacy model — no longer on iKamper's live product page but accessories/parts still supported. Hybrid hardshell-floor/canvas-sides design. 89\"×56\" sleeping area.",
  },

  // ─── ROOFNEST — CURRENT LINEUP ──────────────────────────────────────
  // All specs verified from roofnest.com product pages, March 2026.
  // "Fold-out hardshell" = sleeping area overhangs closed footprint when open.
  // Condor Overland uses stamped aluminum honeycomb shell vs PC/ABS on standard Condor.

  {
    id: "roofnest-condor-2-air",
    brand: "Roofnest",
    model: "Condor 2 Air",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 145,
    closedHeightIn: 14,
    closedLengthIn: 60,
    closedWidthIn: 49,
    openLengthIn: 81,
    openWidthIn: 53,
    openHeadroomIn: 40,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/condor-2-air",
    notes: "Fold-out hardshell. Compact 60\"×49\" closed footprint. 81\"×53\" sleeping area. Rest EZ 2\" self-inflating foamcore mattress. Min crossbar spread 28\". LED lights, gear grid, window awnings included. Awning accessory: +12.5 lbs.",
  },
  {
    id: "roofnest-condor-2-xl-air",
    brand: "Roofnest",
    model: "Condor 2 XL Air",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 170,
    closedHeightIn: 14.5,
    closedLengthIn: 75,
    closedWidthIn: 56,
    openLengthIn: 89,
    openWidthIn: 68,
    openHeadroomIn: 50,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/condor-2-xl-air",
    notes: "Fold-out hardshell. 89\"×68\" sleeping area. Rest EZ 2\" self-inflating foamcore mattress. Min crossbar spread 30\". LED lights, gear grid, window awnings included. Awning accessory: +12.5 lbs regular / +13 lbs XL.",
  },
  {
    id: "roofnest-condor-2-xxl-air",
    brand: "Roofnest",
    model: "Condor 2 XXL Air",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 205,
    closedHeightIn: 15,
    closedLengthIn: 88,
    closedWidthIn: 60,
    openLengthIn: 95,
    openWidthIn: 80,
    openHeadroomIn: 50,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/condor-2-xxl-air",
    notes: "Largest fold-out Roofnest tent. PC/ABS shell with LINE-X coating. 95\"×80\" sleeping area. 2\" self-inflating Foamcore mattress. HVAC ports for fan/heater integration. Min crossbar spread 32\".",
  },
  {
    id: "roofnest-condor-overland-2-air",
    brand: "Roofnest",
    model: "Condor Overland 2 Air",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 180,
    closedHeightIn: 12,
    closedLengthIn: 60,
    closedWidthIn: 48,
    openLengthIn: 81,
    openWidthIn: 53,
    openHeadroomIn: 40,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/condor-overland-2-air",
    notes: "Overland edition — stamped aluminum honeycomb shell vs PC/ABS on standard Condor 2. 12\" closed profile (2\" thinner). Same 81\"×53\" sleeping area. 35 lbs heavier due to aluminum shell. Sub-1-min setup. 280 GSM poly-cotton blackout canvas.",
  },
  {
    id: "roofnest-condor-overland-2-xl-air",
    brand: "Roofnest",
    model: "Condor Overland 2 XL Air",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 240,
    closedHeightIn: 12,
    closedLengthIn: 73,
    closedWidthIn: 55,
    openLengthIn: 89,
    openWidthIn: 68,
    openHeadroomIn: 50,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 1000,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/condor-overland-2-xl-air",
    notes: "Heaviest Roofnest tent at 240 lbs — stamped aluminum honeycomb shell. 12\" closed profile. 89\"×68\" sleeping area. Verify vehicle payload and rack static rating before ordering. 280 GSM poly-cotton blackout canvas. Sub-1-min setup.",
  },
  {
    id: "roofnest-falcon-3-evo-air",
    brand: "Roofnest",
    model: "Falcon 3 EVO Air",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 8,
    closedLengthIn: 83,
    closedWidthIn: 50,
    openLengthIn: 80,
    openWidthIn: 47,
    openHeadroomIn: 58,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/falcon-3-evo-air",
    notes: "Clamshell hardshell. 8\" closed profile — best in the Roofnest lineup for garage clearance. 58\" peak headroom. Rest EZ 2\" self-inflating foamcore mattress. Anti-condensation mat included. Min crossbar spread 30\". Awning accessory: +22 lbs.",
  },
  {
    id: "roofnest-falcon-3-evo-xl-air",
    brand: "Roofnest",
    model: "Falcon 3 EVO XL Air",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 160,
    closedHeightIn: 8,
    closedLengthIn: 88,
    closedWidthIn: 60,
    openLengthIn: 85,
    openWidthIn: 57,
    openHeadroomIn: 60,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/falcon-3-evo-xl-air",
    notes: "Clamshell hardshell. 8\" closed profile with 60\" peak headroom — near-standing height. 85\"×57\" sleeping area. Rest EZ 2\" self-inflating foamcore mattress. Anti-condensation mat included. Min crossbar spread 30\". Awning accessory: +22 lbs regular / +24 lbs XL.",
  },
  {
    id: "roofnest-meadowlark",
    brand: "Roofnest",
    model: "Meadowlark",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 90,
    closedHeightIn: 12,
    closedLengthIn: 47,
    closedWidthIn: 44,
    openLengthIn: 80,
    openWidthIn: 43,
    openHeadroomIn: 36,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: false,
    affiliateUrl: "https://roofnest.com/products/meadowlark",
    notes: "Roofnest's only current softshell tent. Lightest in the lineup at 90 lbs. Compact 47\"×44\" closed footprint. 2.5\" dual-density integrated foam mattress. 190 GSM poly-cotton canvas (2000 mm WR). 210D rainfly (3000 mm WR). USB LED strip.",
  },

  // ─── ROOFNEST — LEGACY ──────────────────────────────────────────────
  // Specs from Roofnest PDF manuals, EU legacy listings, and TREAD coverage.
  // Units remain widely in circulation so kept for accurate weight calculations.

  {
    id: "roofnest-falcon-2",
    brand: "Roofnest",
    model: "Falcon 2",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 160,
    closedHeightIn: 6.5,
    closedLengthIn: 83,
    closedWidthIn: 50,
    openLengthIn: 83,
    openWidthIn: 49,
    openHeadroomIn: 60,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 650,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B08T6JYC1D?tag=prepperevo-20",
    notes: "Legacy clamshell hardshell. 6.5\" closed profile — very garage-friendly. 2.5\" memory foam mattress. Aluminum shell with 75 lb accessory channel rating. Confirmed 160 lbs per Roofnest official Falcon 2 PDF manual.",
  },
  {
    id: "roofnest-falcon-2-xl",
    brand: "Roofnest",
    model: "Falcon 2 XL",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 175,
    closedHeightIn: 6.5,
    closedLengthIn: 90,
    closedWidthIn: 60,
    openLengthIn: 88,
    openWidthIn: 58,
    openHeadroomIn: 60,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 650,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B08T6JYC1D?tag=prepperevo-20",
    notes: "Legacy XL clamshell hardshell. 6.5\" closed profile. 88\"×58\" sleeping area. Min crossbar distance 30\". 8.5' ladder, padded ceiling, dual pockets, LED. Confirmed 175 lbs per Roofnest official Falcon 2 PDF manual.",
  },
  {
    id: "roofnest-condor-xl",
    brand: "Roofnest",
    model: "Condor XL",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 160,
    closedHeightIn: 13,
    closedLengthIn: 74,
    closedWidthIn: 55,
    openLengthIn: 93,
    openWidthIn: 74,
    openHeadroomIn: 50,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B09NRGXY7T?tag=prepperevo-20",
    notes: "Legacy fold-out hardshell. ASA/ABS plastic shell. 93\"×74\" sleeping area — wide platform, great for tall sleepers. 8.5' ladder, privacy tent, ground mat, LED. Confirmed 160 lbs from legacy retailer listings.",
  },
  {
    id: "roofnest-sparrow-eye",
    brand: "Roofnest",
    model: "Sparrow EYE",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 11.5,
    closedLengthIn: 85,
    closedWidthIn: 50,
    openLengthIn: 83,
    openWidthIn: 49,
    openHeadroomIn: 44,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 650,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0BZK7N8WR?tag=prepperevo-20",
    notes: "Legacy clamshell hardshell with panoramic skylight window (the \"EYE\"). 83\"×49\" sleeping area. Min crossbar distance 28\". Mounting rail spacing 21.5\". 8.5' ladder, privacy tent, ground mat, LED. ~130–135 lbs per Roofnest Sparrow PDF manual.",
  },
  {
    id: "roofnest-sparrow",
    brand: "Roofnest",
    model: "Sparrow",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 11,
    closedLengthIn: 85,
    closedWidthIn: 50,
    openLengthIn: 83,
    openWidthIn: 49,
    openHeadroomIn: 40,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 650,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Legacy clamshell hardshell. Same footprint as Sparrow EYE but no skylight — 0.5\" less closed height, 4\" less headroom. Min crossbar distance 28\". Mounting rail spacing 21.5\". ~130–135 lbs per Roofnest Sparrow PDF manual.",
  },
  {
    id: "roofnest-eagle",
    brand: "Roofnest",
    model: "Eagle",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 141,
    closedHeightIn: 11.8,
    closedLengthIn: 82.7,
    closedWidthIn: 55.1,
    openLengthIn: 82.7,
    openWidthIn: 55.1,
    openHeadroomIn: 33.5,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 650,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Legacy model. Best-effort specs from third-party sources — Roofnest's official page no longer live. Approx: 141 lbs, 83\"×55\" footprint, 33.5\" headroom. Treat as reference only; verify before purchase.",
  },

  // ─── THULE ──────────────────────────────────────────────────────────
  // All specs from thule.com live product pages, March 2026.
  // Approach 2 = current gen (recycled fabric); Approach = older gen, still live at lower MSRP.
  // Foothill 2 = current gen; Foothill = older gen, still live on clearance.
  // Basin / Basin Wedge = unique hardshell cargo-box-hybrid tent.
  // Tepui is Thule's softshell sub-brand (formerly Tepui Tents, acquired by Thule).

  {
    id: "thule-approach-2-s",
    brand: "Thule",
    model: "Approach 2 S",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 110,
    closedHeightIn: 11,
    closedLengthIn: 43,
    closedWidthIn: 48,
    openLengthIn: 82,
    openWidthIn: 43,
    openHeadroomIn: 35,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/approach-2-s",
    notes: "Current-gen softshell. 82\"×43\" sleeping footprint. Welded aluminum tube base with insulation and aluminum cap sheet. 100% recycled 600D polyester ripstop canopy. All-season rated. Min crossbar spread 28\". Accessory weights: Approach Annex S +16.31 lbs (same footprint fits), Awning 2 S/M +10.8 lbs, Anti-condensation Mat S +5.3 lbs.",
  },
  {
    id: "thule-approach-2-m",
    brand: "Thule",
    model: "Approach 2 M",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 128,
    closedHeightIn: 11,
    closedLengthIn: 49,
    closedWidthIn: 56,
    openLengthIn: 95,
    openWidthIn: 51,
    openHeadroomIn: 40,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/approach-2-m",
    notes: "Current-gen softshell. 95\"×51\" sleeping footprint. Welded aluminum tube base with insulation and aluminum cap sheet. 100% recycled 600D polyester ripstop canopy. All-season rated. Min crossbar spread 31\". Accessory weights: Approach Annex M +17.85 lbs (same footprint fits), Awning 2 S/M +10.8 lbs, Anti-condensation Mat M +6 lbs.",
  },
  {
    id: "thule-approach-2-l",
    brand: "Thule",
    model: "Approach 2 L",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 150,
    closedHeightIn: 11,
    closedLengthIn: 49,
    closedWidthIn: 72,
    openLengthIn: 95,
    openWidthIn: 67,
    openHeadroomIn: 40,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/approach-2-l",
    notes: "Current-gen softshell. 95\"×67\" sleeping footprint — widest in the Approach line. Welded aluminum tube base with insulation and aluminum cap sheet. 100% recycled 600D polyester ripstop canopy. Min crossbar spread 31\". Accessory weights: Approach Annex L +20.17 lbs (same footprint fits), Awning 2 L +12.1 lbs, Anti-condensation Mat L +7.5 lbs.",
  },
  {
    id: "thule-foothill-2",
    brand: "Thule",
    model: "Foothill 2",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 122,
    closedHeightIn: 11,
    closedLengthIn: 84,
    closedWidthIn: 25,
    openLengthIn: 80,
    openWidthIn: 45,
    openHeadroomIn: 37,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/foothill-2",
    notes: "Current-gen softshell. Folds out sideways along the long axis — 84\" long but only 25\" wide closed. 80\"×45\" sleeping footprint. 37\" headroom.",
  },
  {
    id: "thule-basin",
    brand: "Thule",
    model: "Basin",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 176,
    closedHeightIn: 12.75,
    closedLengthIn: 84,
    closedWidthIn: 55,
    openLengthIn: 81,
    openWidthIn: 51,
    openHeadroomIn: 36,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/basin",
    notes: "Hardshell clamshell that doubles as a cargo carrier when closed (81\"×52\"×9\" cargo space). 81\"×51\" sleeping footprint, 36\" headroom. Unique dual-use design — haul gear on the road, sleep in it at camp. Min crossbar spread 32\". Accessory weights: Anti-condensation Mat S +5.3 lbs, Mounting Brackets +4.5 lbs.",
  },
  {
    id: "thule-basin-wedge",
    brand: "Thule",
    model: "Basin Wedge",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 156,
    closedHeightIn: 12.8,
    closedLengthIn: 84,
    closedWidthIn: 55,
    openLengthIn: 79,
    openWidthIn: 51,
    openHeadroomIn: 46,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/basin-wedge",
    notes: "Wedge hardshell that doubles as a cargo carrier when closed (78\"×52\"×6.6\" cargo space). 79\"×51\" sleeping footprint, 46\" peak headroom. 5 mm ABS upper shell + welded aluminum/honeycomb PP lower. 260g cotton/poly canvas (1500 mm WR). Min crossbar spread 32\". Accessory weights: Anti-condensation Mat S +5.3 lbs, Mounting Brackets +4.5 lbs.",
  },
  {
    id: "thule-tepui-kukenam",
    brand: "Thule",
    model: "Tepui Explorer Kukenam",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 119,
    closedHeightIn: 12,
    closedLengthIn: 48,
    closedWidthIn: 56,
    openLengthIn: 96,
    openWidthIn: 56,
    openHeadroomIn: 52,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: false,
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/tepui-explorer-kukenam",
    notes: "Thule Tepui sub-brand softshell. 52\" peak headroom — tallest softshell in the Thule lineup. 96\"×56\" sleeping footprint. Min crossbar spread 33.5\". Good headroom-to-weight ratio at 119 lbs. Accessory weights: Anti-condensation Mat M +6 lbs, Mounting Brackets +4.5 lbs, Organizer +1.25 lbs.",
  },

  // ─── THULE — PREVIOUS GEN (still live at lower MSRP) ────────────────

  {
    id: "thule-approach-s",
    brand: "Thule",
    model: "Approach S",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 110,
    closedHeightIn: 11,
    closedLengthIn: 43,
    closedWidthIn: 48,
    openLengthIn: 82,
    openWidthIn: 43,
    openHeadroomIn: 35,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: true,
    annexName: "Thule Approach Annex S",
    annexWeightLbs: 16.31,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.thule.com/us/rooftop-tent-accessories/approach-annex-s",
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/approach-s",
    notes: "Previous-gen softshell — same specs as Approach 2 S but non-recycled fabric. Still live on thule.com at $200 less. 82\"×43\" sleeping footprint. Min crossbar spread 28\". Accessory weights: Annex S +16.31 lbs, Awning S/M +8.8 lbs (or Awning 2 S/M +10.8 lbs), Anti-condensation Mat S +5.3 lbs.",
  },
  {
    id: "thule-approach-m",
    brand: "Thule",
    model: "Approach M",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 128,
    closedHeightIn: 11,
    closedLengthIn: 49,
    closedWidthIn: 56,
    openLengthIn: 95,
    openWidthIn: 51,
    openHeadroomIn: 40,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: true,
    annexName: "Thule Approach Annex M",
    annexWeightLbs: 17.85,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.thule.com/us/rooftop-tent-accessories/approach-annex-m",
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/approach-m",
    notes: "Previous-gen softshell — same specs as Approach 2 M but non-recycled fabric. Still live on thule.com at $300 less. 95\"×51\" sleeping footprint. Min crossbar spread 31\". Accessory weights: Annex M +17.85 lbs, Awning S/M +8.8 lbs (or Awning 2 S/M +10.8 lbs), Anti-condensation Mat M +6 lbs.",
  },
  {
    id: "thule-approach-l",
    brand: "Thule",
    model: "Approach L",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 150,
    closedHeightIn: 11,
    closedLengthIn: 49,
    closedWidthIn: 72,
    openLengthIn: 95,
    openWidthIn: 67,
    openHeadroomIn: 40,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 660,
    hasAnnex: true,
    annexName: "Thule Approach Annex L",
    annexWeightLbs: 20.17,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.thule.com/us/rooftop-tent-accessories/approach-annex-l",
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/approach-l",
    notes: "Previous-gen softshell — same specs as Approach 2 L but non-recycled fabric. Still live on thule.com at $400 less. 95\"×67\" sleeping footprint. Min crossbar spread 31\". Accessory weights: Annex L +20.17 lbs, Awning L +9 lbs (or Awning 2 L +12.1 lbs), Anti-condensation Mat L +7.5 lbs.",
  },
  {
    id: "thule-foothill",
    brand: "Thule",
    model: "Foothill",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 122,
    closedHeightIn: 9.5,
    closedLengthIn: 83,
    closedWidthIn: 24,
    openLengthIn: 84,
    openWidthIn: 47,
    openHeadroomIn: 37,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: false,
    affiliateUrl: "https://www.thule.com/us/rooftop-tents/foothill",
    notes: "Previous-gen softshell — on clearance. 9.5\" closed profile (thinner than Foothill 2 at 11\"). 84\"×47\" sleeping footprint, 37\" headroom. Accessory weights: Anti-condensation Mat S +5.3 lbs, Foothill Mounting Rails +7.85 lbs.",
  },

  // ─── 23ZERO ─────────────────────────────────────────────────────────
  // Full 2.0 generation lineup. Breezeway + original Walkabout discontinued.
  // All specs verified from 23zero.com product pages.
  // Winter liner available for all Walkabout 2.0 sizes: 8 lbs.

  {
    id: "23zero-kabari-z",
    brand: "23Zero",
    model: "Kabari Z Aluminum Z-Lift",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 204,
    closedHeightIn: 9.5,
    closedLengthIn: 86.625,
    closedWidthIn: 55.25,
    openLengthIn: 86.625,
    openWidthIn: 55.25,
    openHeadroomIn: 58,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Z-lift clamshell mechanism — dual-stage lift opens the shell and raises the tent body. 48\"×79.5\" sleeping area, 58\" peak headroom. Very flat 9.5\" closed profile. Currently out of stock.",
  },
  {
    id: "23zero-kabari-xl",
    brand: "23Zero",
    model: "Kabari XL Wedge",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 202,
    closedHeightIn: 8.5,
    closedLengthIn: 84.5,
    closedWidthIn: 55,
    openLengthIn: 84.5,
    openWidthIn: 55,
    openHeadroomIn: 53,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Wedge hardshell. 49.5\"×79\" sleeping area. 53\" peak headroom, 13\" at foot (A-frame taper). 8.5\" closed profile.",
  },
  {
    id: "23zero-kabari-superfly",
    brand: "23Zero",
    model: "Kabari SuperFly Hybrid",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 105,
    closedHeightIn: 7.75,
    closedLengthIn: 86.5,
    closedWidthIn: 50.25,
    openLengthIn: 86.5,
    openWidthIn: 50.25,
    openHeadroomIn: 56,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 750,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Lightest 23Zero hardshell at 105 lbs — hybrid construction (aluminum frame, lightweight composite panels). 46.5\"×79.5\" sleeping area. 56\" peak headroom. 7.75\" closed height including rails (6.25\" without). Crossbars included.",
  },
  {
    id: "23zero-armadillo-horizon-2",
    brand: "23Zero",
    model: "Armadillo Horizon 2",
    type: "hardshell-clamshell",
    openSide: "driver",
    closedWeightLbs: 205,
    closedHeightIn: 13.25,
    closedLengthIn: 62,
    closedWidthIn: 52.5,
    openLengthIn: 80,
    openWidthIn: 62,
    openHeadroomIn: 49,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Premium Armadillo hardshell — 2-person. 51\"×78\" sleeping area, 43\" headroom at sleeping level. Opens left/driver side. 4-season.",
  },
  {
    id: "23zero-armadillo-ax3",
    brand: "23Zero",
    model: "Armadillo AX3",
    type: "hardshell-clamshell",
    openSide: "driver",
    closedWeightLbs: 213,
    closedHeightIn: 12.5,
    closedLengthIn: 75.25,
    closedWidthIn: 50.5,
    openLengthIn: 85,
    openWidthIn: 75.25,
    openHeadroomIn: 54,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Aluminum Armadillo — 3-person rating. 68\"×80\" sleeping area, 46\" headroom at sleeping level, 54\" peak. Only 2 left in stock. 4-season.",
  },
  {
    id: "23zero-armadillo-horizon-3",
    brand: "23Zero",
    model: "Armadillo Horizon 3",
    type: "hardshell-clamshell",
    openSide: "driver",
    closedWeightLbs: 246,
    closedHeightIn: 13.25,
    closedLengthIn: 75.25,
    closedWidthIn: 55.5,
    openLengthIn: 89,
    openWidthIn: 75.25,
    openHeadroomIn: 50.5,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Premium Armadillo — 3-person, heaviest 23Zero tent at 246 lbs (includes mounting rails and ladder). 68\"×83\" sleeping area, 46\" headroom at sleeping level, 50.5\" peak. Opens left/driver side. 4-season.",
  },

  {
    id: "23zero-walkabout-56",
    brand: "23Zero",
    model: "Walkabout 56 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 14,
    closedLengthIn: 57,
    closedWidthIn: 48,
    openLengthIn: 122,
    openWidthIn: 57,
    openHeadroomIn: 52,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 880,
    hasAnnex: true,
    affiliateUrl: "#",
    notes: "Full-size bed. 56\"×96\" sleeping area. 3\" rebound mattress with cotton top and waterproof base. 4-season. Heater/cooler port option available. Winter liner sold separately (8 lbs).",
  },
  {
    id: "23zero-walkabout-62",
    brand: "23Zero",
    model: "Walkabout 62 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 152,
    closedHeightIn: 14,
    closedLengthIn: 63,
    closedWidthIn: 48,
    openLengthIn: 122,
    openWidthIn: 63,
    openHeadroomIn: 52,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 880,
    hasAnnex: true,
    affiliateUrl: "#",
    notes: "Queen-size bed. 62\"×96\" sleeping area. 3\" rebound mattress with cotton top and waterproof base. 4-season. Winter liner sold separately (8 lbs).",
  },
  {
    id: "23zero-walkabout-72",
    brand: "23Zero",
    model: "Walkabout 72 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 165,
    closedHeightIn: 14,
    closedLengthIn: 48,
    closedWidthIn: 73,
    openLengthIn: 122,
    openWidthIn: 73,
    openHeadroomIn: 52,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 880,
    hasAnnex: true,
    affiliateUrl: "#",
    notes: "King-size bed. 72\"×96\" sleeping area. 3\" rebound mattress. 4-season. Heater/cooler port option available. Packs wider across vehicle (73\") — verify roof rack width. Winter liner sold separately (8 lbs).",
  },
  {
    id: "23zero-walkabout-87",
    brand: "23Zero",
    model: "Walkabout 87 2.0",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 198,
    closedHeightIn: 14,
    closedLengthIn: 88,
    closedWidthIn: 48,
    openLengthIn: 122,
    openWidthIn: 88,
    openHeadroomIn: 52,
    mattressThicknessIn: 3,
    sleepsMarketing: 6,
    sleepsRealistic: 3,
    staticRatingLbs: 1320,
    hasAnnex: true,
    affiliateUrl: "#",
    notes: "Largest 23Zero softshell. 87\"×96\" sleeping area — fits 3 adults. 3\" rebound mattress with cotton top and waterproof base. 4-season. Heater/cooler port option available. 1320 lb total load rating. 88\" closed footprint — verify rack length. Winter liner sold separately (8 lbs).",
  },

  // ─── OVS (Overland Vehicle Systems) ─────────────────────────────────

  {
    id: "ovs-nomadic-2",
    brand: "OVS",
    model: "Nomadic 2",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 150,
    closedHeightIn: 14,
    closedLengthIn: 47,
    closedWidthIn: 54,
    openLengthIn: 95,
    openWidthIn: 54,
    openHeadroomIn: 51,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 750,
    hasAnnex: true,
    annexName: "OVS Nomadic 2 Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B07R1V8RKQ?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B07R1V7TN6?tag=prepperevo-20",
    notes: "Best-selling budget soft-shell. Great entry-level RTT.",
  },
  {
    id: "ovs-nomadic-3",
    brand: "OVS",
    model: "Nomadic 3",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 174,
    closedHeightIn: 9.4,
    closedLengthIn: 64,
    closedWidthIn: 48,
    openLengthIn: 96,
    openWidthIn: 64,
    openHeadroomIn: 49,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 850,
    hasAnnex: true,
    annexName: "OVS Nomadic 3 Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B07R1VH3TG?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B07R1VGT9N?tag=prepperevo-20",
    notes: "Mid-size OVS. Popular upgrade from Nomadic 2.",
  },
  {
    id: "ovs-nomadic-4",
    brand: "OVS",
    model: "Nomadic 4",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 165,
    closedHeightIn: 16,
    closedLengthIn: 72,
    closedWidthIn: 62,
    openLengthIn: 112,
    openWidthIn: 72,
    openHeadroomIn: 50,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 750,
    hasAnnex: true,
    annexName: "OVS Nomadic 4 Annex",
    annexWeightLbs: 18,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B09D3GNVR8?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B09D3GN3S4?tag=prepperevo-20",
    notes: "Largest OVS soft-shell. Extended model for families.",
  },

  {
    id: "ovs-bushveld",
    brand: "OVS",
    model: "Bushveld",
    type: "hardshell-clamshell",
    openSide: "passenger",
    closedWeightLbs: 208,
    closedHeightIn: 12,
    closedLengthIn: 85,
    closedWidthIn: 49,
    openLengthIn: 85,
    openWidthIn: 88,
    openHeadroomIn: 45,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B094TM3HXS?tag=prepperevo-20",
    notes: "Cantilever hard shell. Single-piece polymer top. Marine-grade 304 stainless hardware. 1-minute setup.",
  },
  {
    id: "ovs-hd-bushveld-2p",
    brand: "OVS",
    model: "HD Bushveld 2 Person",
    type: "hardshell-clamshell",
    openSide: "passenger",
    closedWeightLbs: 178.2,
    closedHeightIn: 12,
    closedLengthIn: 65,
    closedWidthIn: 49,
    openLengthIn: 65,
    openWidthIn: 88,
    openHeadroomIn: 45,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B094TM3HXS?tag=prepperevo-20",
    notes: "HD Bushveld 2-person hardshell. 280G ripstop body, 420D oxford rainfly, insulated base. Same 49\" width and 45\" open headroom as 4-person — shorter 65\" footprint. Opens passenger-side only. 1-minute setup.",
  },
  {
    id: "ovs-hd-bushveld",
    brand: "OVS",
    model: "HD Bushveld 4 Person",
    type: "hardshell-clamshell",
    openSide: "passenger",
    closedWeightLbs: 207.9,
    closedHeightIn: 12,
    closedLengthIn: 85,
    closedWidthIn: 49,
    openLengthIn: 85,
    openWidthIn: 88,
    openHeadroomIn: 45,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS HD Bushveld Annex",
    annexWeightLbs: 15,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B096GCM4MK?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B094TM3HXS?tag=prepperevo-20",
    notes: "HD upgrade: double 280G ripstop body, 420D oxford rainfly, insulated base with anti-condensation layer. Grey body & tan rainfly. Cantilever design, 1-minute setup. 96in aluminum ladder. Opens passenger-side only — entry is always from the passenger side of the vehicle.",
  },
  {
    id: "ovs-nomadic-4-extended",
    brand: "OVS",
    model: "Nomadic 4 Extended",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 172,
    closedHeightIn: 9.4,
    closedLengthIn: 76,
    closedWidthIn: 48,
    openLengthIn: 76,
    openWidthIn: 95,
    openHeadroomIn: 49,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 950,
    hasAnnex: true,
    annexName: "OVS Nomadic 4 Extended Annex",
    annexWeightLbs: 18,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B09D3GNVR8?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B0C9KXLXHJ?tag=prepperevo-20",
    notes: "Largest OVS soft-shell. 75 x 94.5 sleeping area. 280G poly-cotton ripstop. Extended overhang.",
  },
  {
    id: "ovs-hd-nomadic-2-extended",
    brand: "OVS",
    model: "HD Nomadic 2 Extended",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 147,
    closedHeightIn: 14,
    closedLengthIn: 47,
    closedWidthIn: 54,
    openLengthIn: 95,
    openWidthIn: 54,
    openHeadroomIn: 51,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 750,
    hasAnnex: true,
    annexName: "OVS HD Nomadic 2 Extended Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    affiliateUrl: "#",
    notes: "HD upgrade: double 280G ripstop, 420D oxford rainfly, insulated base. Extended overhang model.",
  },
  {
    id: "ovs-hd-nomadic-3-extended",
    brand: "OVS",
    model: "HD Nomadic 3 Extended",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 156,
    closedHeightIn: 9.4,
    closedLengthIn: 64,
    closedWidthIn: 48,
    openLengthIn: 96,
    openWidthIn: 64,
    openHeadroomIn: 49,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 850,
    hasAnnex: true,
    annexName: "OVS HD Nomadic 3 Extended Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    affiliateUrl: "#",
    notes: "HD upgrade: double 280G ripstop, 420D oxford rainfly, insulated base. Mid-size extended overhang model.",
  },
  {
    id: "ovs-hd-nomadic-4-extended",
    brand: "OVS",
    model: "HD Nomadic 4 Extended",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 172,
    closedHeightIn: 9.4,
    closedLengthIn: 76,
    closedWidthIn: 48,
    openLengthIn: 76,
    openWidthIn: 95,
    openHeadroomIn: 49,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 950,
    hasAnnex: true,
    annexName: "OVS HD Nomadic 4 Extended Annex",
    annexWeightLbs: 18,
    annexSleeps: 2,
    affiliateUrl: "#",
    notes: "HD upgrade: double 280G ripstop, 420D oxford rainfly, insulated base. Largest OVS soft-shell. 75 x 94.5 sleeping area.",
  },

  // ─── OVS HARDSHELL LINEUP (VERIFIED FROM OVS PRODUCT PAGES) ─────────

  {
    id: "ovs-ld-tmon-2p",
    brand: "OVS",
    model: "LD TMON 2 Person",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 150,
    closedHeightIn: 6,
    closedLengthIn: 82.7,
    closedWidthIn: 50,
    openLengthIn: 82.7,
    openWidthIn: 50,
    openHeadroomIn: 65,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 750,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "LD (entry) tier. A-frame wedge shape when open — 65\" peak height is the tallest in the OVS lineup. Very flat 6\" closed profile. 3500 PU. Tan body & green rainfly.",
  },
  {
    id: "ovs-hd-mamba",
    brand: "OVS",
    model: "HD Mamba 3 Person",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 220,
    closedHeightIn: 6.5,
    closedLengthIn: 90.5,
    closedWidthIn: 55,
    openLengthIn: 90.5,
    openWidthIn: 55,
    openHeadroomIn: 59,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Largest OVS clamshell — 90.5\" footprint, verify rack length before ordering. Honeycomb aluminum shell. No skylight, no lighting, no annex. 3500 PU. Storage rack 45 lbs open / 100 lbs closed. Grey body & grey rainfly.",
  },
  {
    id: "ovs-hd-sidewinder",
    brand: "OVS",
    model: "HD Sidewinder 3 Person",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 220,
    closedHeightIn: 6.5,
    closedLengthIn: 90.5,
    closedWidthIn: 55,
    openLengthIn: 90.5,
    openWidthIn: 55,
    openHeadroomIn: 48,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Side-load variant of the HD Mamba — same base shell but opens to the side rather than straight up. Lower headroom (48\") due to side-load mechanism. Can be configured driver or passenger side. No skylight, no lighting. 3500 PU.",
  },
  {
    id: "ovs-hd-bundu-2p",
    brand: "OVS",
    model: "HD Bundu 2 Person",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 156,
    closedHeightIn: 11,
    closedLengthIn: 63,
    closedWidthIn: 43,
    openLengthIn: 63,
    openWidthIn: 82.5,
    openHeadroomIn: 47,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS HD Bundu Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Compact cantilever. ABS plastic shell. 2 nitrogen gas struts. Skylight and interior lighting included. Anti-condensation mat included. Annex optional. 3500 PU. 81\" telescoping ladder. 4-year warranty.",
  },
  {
    id: "ovs-hd-bundu-4p",
    brand: "OVS",
    model: "HD Bundu 4 Person",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 190,
    closedHeightIn: 12,
    closedLengthIn: 86.5,
    closedWidthIn: 51,
    openLengthIn: 86.5,
    openWidthIn: 88.5,
    openHeadroomIn: 45,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS HD Bundu Annex",
    annexWeightLbs: 15,
    annexSleeps: 2,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Large cantilever — 86.5\" footprint, verify rack length. ABS plastic shell. Skylight and interior lighting. Anti-condensation mat. Annex optional. 3500 PU. 81\" telescoping ladder. 4-year warranty.",
  },
  {
    id: "ovs-xd-atlas",
    brand: "OVS",
    model: "XD Atlas",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 180,
    closedHeightIn: 13,
    closedLengthIn: 60,
    closedWidthIn: 52,
    openLengthIn: 60,
    openWidthIn: 87,
    openHeadroomIn: 53,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS XD Atlas Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "XD-tier cantilever. ABS shell over aluminum honeycomb base. Only OVS tent with AC/heater port. Skylight, interior lighting, blackout coating. 5000 PU. Annex + awning extension optional. Storage rack 45/100 lbs. 6-year fabric / lifetime structural warranty. 81\" ladder.",
  },
  {
    id: "ovs-xd-lhotse",
    brand: "OVS",
    model: "XD Lhotse 2 Person",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 230,
    closedHeightIn: 8,
    closedLengthIn: 84,
    closedWidthIn: 52,
    openLengthIn: 84,
    openWidthIn: 52,
    openHeadroomIn: 57,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Premium XD clamshell. Full honeycomb aluminum shell. Built-in storage rack (45 lbs open / 100 lbs closed) — can run solar on top while packed. Blackout interior, 5000 PU, military-spec seals. 6-year / lifetime structural warranty. Blue body & black shell.",
  },
  {
    id: "ovs-xd-k2",
    brand: "OVS",
    model: "XD K2 2 Person",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 220,
    closedHeightIn: 10,
    closedLengthIn: 84.5,
    closedWidthIn: 57,
    openLengthIn: 95,
    openWidthIn: 57,
    openHeadroomIn: 51,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Pop-up clamshell — platform extends to 95\" when open. Rainfly expands to 107\"×78\" when fully deployed. Ladder mounts on all 4 sides (3 entry points). Honeycomb aluminum shell. 5000 PU, blackout, storage rack 45/100 lbs. AC/heater port. 6-year / lifetime structural warranty.",
  },
  {
    id: "ovs-xd-everest-2p",
    brand: "OVS",
    model: "XD Everest 2 Person",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 250,
    closedHeightIn: 13,
    closedLengthIn: 68,
    closedWidthIn: 52.75,
    openLengthIn: 68,
    openWidthIn: 85.8,
    openHeadroomIn: 54,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS XD Everest Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Premium XD cantilever. Full honeycomb aluminum shell and base. AC/heater port, skylight, interior lighting, blackout. 5000 PU. Storage rack 45/100 lbs. Annex + awning optional. 6-year / lifetime structural warranty. 81\" ladder.",
  },
  {
    id: "ovs-xd-everest-4p",
    brand: "OVS",
    model: "XD Everest 4 Person",
    type: "hardshell-cantilever",
    openSide: "passenger",
    closedWeightLbs: 302,
    closedHeightIn: 13,
    closedLengthIn: 74.8,
    closedWidthIn: 52.36,
    openLengthIn: 74.8,
    openWidthIn: 85.8,
    openHeadroomIn: 54,
    mattressThicknessIn: 2,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "OVS XD Everest Annex",
    annexWeightLbs: 15,
    annexSleeps: 2,
    annexAffiliateUrl: "#",
    affiliateUrl: "#",
    notes: "Heaviest tent in the OVS lineup at 302 lbs — verify vehicle dynamic roof rating AND rack rating before ordering. Full honeycomb aluminum shell and base. AC/heater port, skylight, interior lighting, blackout. 5000 PU. Storage rack 45/100 lbs. 6-year / lifetime structural warranty.",
  },

  // ─── SMITTYBILT ─────────────────────────────────────────────────────

  {
    id: "smittybilt-overlander-gen2-xl",
    brand: "Smittybilt",
    model: "Overlander Gen2 XL",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 139,
    closedHeightIn: 11,
    closedLengthIn: 76,
    closedWidthIn: 47,
    openLengthIn: 76,
    openWidthIn: 122,
    openHeadroomIn: 51,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 770,
    hasAnnex: true,
    annexName: "Smittybilt Overlander Gen2 Annex",
    annexWeightLbs: 14,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B08JQDP7FX?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B08JQDR9RR?tag=prepperevo-20",
    notes: "Budget-friendly. Most affordable RTT with decent build quality.",
  },

  // ─── ARB ────────────────────────────────────────────────────────────

  {
    id: "arb-simpson-iii",
    brand: "ARB",
    model: "Simpson III",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 154,
    closedHeightIn: 12,
    closedLengthIn: 47,
    closedWidthIn: 55,
    openLengthIn: 95,
    openWidthIn: 55,
    openHeadroomIn: 51,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 550,
    hasAnnex: true,
    annexName: "ARB Simpson III Annex",
    annexWeightLbs: 15,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B001CWKLZ4?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B001CWKLZE?tag=prepperevo-20",
    notes: "Australian legend. Known for durability and build quality.",
  },

  // ─── TOPOAK ─────────────────────────────────────────────────────────

  {
    id: "topoak-galaxy-pro",
    brand: "TOPOAK",
    model: "Galaxy Pro",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 176,
    closedHeightIn: 8,
    closedLengthIn: 83,
    closedWidthIn: 56,
    openLengthIn: 83,
    openWidthIn: 56,
    openHeadroomIn: 53,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 500,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0B9SQT31Y?tag=prepperevo-20",
    notes: "Budget hardshell wedge. Low profile. Light weight for the class.",
  },

  // ─── BODY ARMOR ─────────────────────────────────────────────────────

  {
    id: "bodyarmor-pike-2p",
    brand: "Body Armor",
    model: "Sky Ridge Pike 2-Person",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 108,
    closedHeightIn: 12,
    closedLengthIn: 43,
    closedWidthIn: 48,
    openLengthIn: 110,
    openWidthIn: 55,
    openHeadroomIn: 50,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 460,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0B4N7BJXT?tag=prepperevo-20",
    notes: "Mid-range hardshell. Good value for the weight class.",
  },
  {
    id: "bodyarmor-pike-3p",
    brand: "Body Armor",
    model: "Sky Ridge Pike 3-Person",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 172,
    closedHeightIn: 14,
    closedLengthIn: 47,
    closedWidthIn: 75,
    openLengthIn: 122,
    openWidthIn: 74,
    openHeadroomIn: 51,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 770,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0B4N8J97G?tag=prepperevo-20",
    notes: "Clamshell version. Full standing room for 6-foot person.",
  },

  // ─── TUFF STUFF ─────────────────────────────────────────────────────

  {
    id: "tuffstuff-alpha",
    brand: "Tuff Stuff",
    model: "Alpha",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 176,
    closedHeightIn: 15,
    closedLengthIn: 75,
    closedWidthIn: 55,
    openLengthIn: 87,
    openWidthIn: 71,
    openHeadroomIn: 52,
    mattressThicknessIn: 2.75,
    sleepsMarketing: 4,
    sleepsRealistic: 2,
    staticRatingLbs: 1100,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B07YQJHGGN?tag=prepperevo-20",
    notes: "Side-opening ABS hard shell. Aluminum honeycomb floor. 1100 lb static rating. 2-minute setup.",
  },
  {
    id: "tuffstuff-alpha-ii",
    brand: "Tuff Stuff",
    model: "Alpha II",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 141,
    closedHeightIn: 14,
    closedLengthIn: 60,
    closedWidthIn: 50,
    openLengthIn: 79,
    openWidthIn: 60,
    openHeadroomIn: 46,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B07YQJHGGN?tag=prepperevo-20",
    notes: "Gas strut assisted. Budget clamshell option.",
  },
  {
    id: "tuffstuff-ranger-3",
    brand: "Tuff Stuff",
    model: "Ranger 3",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 164,
    closedHeightIn: 15,
    closedLengthIn: 65,
    closedWidthIn: 48,
    openLengthIn: 96,
    openWidthIn: 65,
    openHeadroomIn: 52,
    mattressThicknessIn: 2,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 800,
    hasAnnex: true,
    annexName: "Tuff Stuff Ranger 3 Annex",
    annexWeightLbs: 12,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B07BZQRP4K?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B07BZQRN6K?tag=prepperevo-20",
    notes: "Affordable entry-level soft-shell with annex.",
  },

  // ─── ALU-CAB ────────────────────────────────────────────────────────

  {
    id: "alucab-gen3-expedition",
    brand: "Alu-Cab",
    model: "Gen 3.1 Expedition",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 192,
    closedHeightIn: 11,
    closedLengthIn: 90,
    closedWidthIn: 55,
    openLengthIn: 83,
    openWidthIn: 51,
    openHeadroomIn: 63,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "Alu-Cab Gen 3.1 Annex",
    annexWeightLbs: 30,
    annexSleeps: 2,
    annexAffiliateUrl: "https://www.amazon.com/dp/B0CWV4R2QX?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B0CWV4PYQQ?tag=prepperevo-20",
    notes: "South African engineering. All-aluminum construction. Premium expedition-grade.",
  },

  // ─── ROOF SPACE ─────────────────────────────────────────────────────

  {
    id: "roofspace-2",
    brand: "Roof Space",
    model: "Roof Space 2",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 147,
    closedHeightIn: 9.4,
    closedLengthIn: 61.5,
    closedWidthIn: 53.5,
    openLengthIn: 98,
    openWidthIn: 59,
    openHeadroomIn: 51,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "Light Base Annex",
    annexWeightLbs: 15,
    annexSleeps: 0,
    affiliateUrl: "https://roofspace.com/products/roof-space-2",
    notes: "German-engineered hybrid hardshell. 270-degree terrace/awning. Queen mattress. 9.4\" low profile.",
  },
  {
    id: "roofspace-4",
    brand: "Roof Space",
    model: "Roof Space 4",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 196,
    closedHeightIn: 9.4,
    closedLengthIn: 87,
    closedWidthIn: 53.5,
    openLengthIn: 98.4,
    openWidthIn: 82.7,
    openHeadroomIn: 51.2,
    mattressThicknessIn: 2,
    sleepsMarketing: 6,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://roofspace.com/products/roof-space-4",
    notes: "Largest hardshell-style RTT on market. Cal King mattress. Double terrace. 30-second gas strut setup.",
  },

  // ─── GO FAST CAMPERS (GFC) ─────────────────────────────────────────

  {
    id: "gfc-v2-pro",
    brand: "GFC",
    model: "V2 Pro RTT",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 135,
    closedHeightIn: 6,
    closedLengthIn: 97,
    closedWidthIn: 53,
    openLengthIn: 90,
    openWidthIn: 50,
    openHeadroomIn: 55,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 500,
    hasAnnex: false,
    affiliateUrl: "https://gofastcampers.com/products/v2-pro-rtt",
    notes: "Made in Bozeman, MT. Aluminum honeycomb panels. Industry-thinnest 6\" closed profile.",
  },
  {
    id: "gfc-v2-pro-xl",
    brand: "GFC",
    model: "V2 Pro RTT XL",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 157,
    closedHeightIn: 6,
    closedLengthIn: 97,
    closedWidthIn: 59,
    openLengthIn: 90,
    openWidthIn: 56,
    openHeadroomIn: 55,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 500,
    hasAnnex: false,
    affiliateUrl: "https://gofastcampers.com/products/v2-pro-rtt-xl",
    notes: "6\" wider sleeping platform than standard V2. Comfortably fits two adults.",
  },
  {
    id: "gfc-superlite",
    brand: "GFC",
    model: "SuperLite",
    type: "hardshell-wedge",
    openSide: "either",
    closedWeightLbs: 80,
    closedHeightIn: 5,
    closedLengthIn: 90,
    closedWidthIn: 50,
    openLengthIn: 90,
    openWidthIn: 50,
    openHeadroomIn: 50,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 1,
    staticRatingLbs: 500,
    hasAnnex: false,
    affiliateUrl: "https://gofastcampers.com/products/superlite",
    notes: "Lightest hardshell RTT on market at 80 lbs. 5\" closed profile. Mattress optional add-on.",
  },

  // ─── FRONT RUNNER ──────────────────────────────────────────────────

  {
    id: "frontrunner-rtt",
    brand: "Front Runner",
    model: "Roof Top Tent",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 93,
    closedHeightIn: 13,
    closedLengthIn: 52,
    closedWidthIn: 49,
    openLengthIn: 96,
    openWidthIn: 51,
    openHeadroomIn: 46,
    mattressThicknessIn: 2.4,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "Front Runner RTT Annex",
    annexWeightLbs: 12,
    annexSleeps: 0,
    affiliateUrl: "https://www.amazon.com/dp/B00S1Q89SU?tag=prepperevo-20",
    notes: "Only 95 lbs. Lowest-profile softshell at 13\". South African made. 260g poly-cotton ripstop.",
  },

  // ─── EEZI-AWN ─────────────────────────────────────────────────────

  {
    id: "eeziawn-series3-1400",
    brand: "Eezi-Awn",
    model: "Series 3 1400",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 130,
    closedHeightIn: 11,
    closedLengthIn: 48,
    closedWidthIn: 55,
    openLengthIn: 96,
    openWidthIn: 55,
    openHeadroomIn: 51,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "Series 3 Shower Skirt",
    annexWeightLbs: 10,
    annexSleeps: 0,
    affiliateUrl: "https://eezi-awn.com/us/product/series-3/",
    notes: "Gold standard softshell since the 1980s. South African. 360GSM heavy-duty ripstop canvas. 4-season.",
  },
  {
    id: "eeziawn-blade-40th",
    brand: "Eezi-Awn",
    model: "Blade 40th Edition",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 181,
    closedHeightIn: 13,
    closedLengthIn: 87,
    closedWidthIn: 57,
    openLengthIn: 84,
    openWidthIn: 52,
    openHeadroomIn: 56,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://eezi-awn.com/us/product/blade/",
    notes: "All-aluminum. Insulated roof and floor. K9 rack on top for solar/bikes. Rear-hinge design.",
  },

  // ─── CVT (CASCADIA VEHICLE TENTS) ─────────────────────────────────
  // All specs verified from cascadiatents.com product pages, March 2026.
  // Portland, OR based. CNC-machined / extruded aluminum construction.
  // Wasatch = fold-out hardshell (sleeping area overhangs closed shell).
  // Mt. Hood 2 / La Sal = clamshell hardshell. Pioneer 2 = softshell fold-out.
  // Pioneer 2 closed dims estimated — CVT does not publish closed rack dimensions.

  {
    id: "cvt-wasatch-m",
    brand: "CVT",
    model: "Wasatch Hardshell — Medium",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 213,
    closedHeightIn: 12,
    closedLengthIn: 61.5,
    closedWidthIn: 50,
    openLengthIn: 79,
    openWidthIn: 58,
    openHeadroomIn: 45,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "CVT Wasatch Annex — Medium",
    annexWeightLbs: 22,
    annexSleeps: 2,
    annexAffiliateUrl: "https://cascadiatents.com/collections/accessories",
    affiliateUrl: "https://cascadiatents.com/products/wasatch-hardshell-tent",
    notes: "Fold-out hardshell — sleeping area (79\"×58\") overhangs the 61.5\"×50\" closed shell. Extruded aluminum shell. 3\" dual-layer foam/blue-gel mattress. Mounting rail spacing 32\". Setup 5–8 min. Annex (+22 lbs, 102\"×90\").",
  },
  {
    id: "cvt-wasatch-l",
    brand: "CVT",
    model: "Wasatch Hardshell — Large",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 240,
    closedHeightIn: 12,
    closedLengthIn: 76,
    closedWidthIn: 57,
    openLengthIn: 97,
    openWidthIn: 72.5,
    openHeadroomIn: 50,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "CVT Wasatch Annex — Large",
    annexWeightLbs: 25,
    annexSleeps: 2,
    annexAffiliateUrl: "https://cascadiatents.com/collections/accessories",
    affiliateUrl: "https://cascadiatents.com/products/wasatch-hardshell-tent",
    notes: "Fold-out hardshell — sleeping area (97\"×72.5\") overhangs the 76\"×57\" closed shell. Extruded aluminum shell. 3\" dual-layer foam/blue-gel mattress. Mounting rail spacing 32\". Setup 5–8 min. Heaviest CVT tent at 240 lbs. Annex (+25 lbs, 112\"×102\").",
  },
  {
    id: "cvt-pioneer2-48",
    brand: "CVT",
    model: "Pioneer 2 Softshell — 48\" Mt. Bachelor",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 152,
    closedHeightIn: 13,
    closedLengthIn: 94,
    closedWidthIn: 48,
    openLengthIn: 94.5,
    openWidthIn: 47,
    openHeadroomIn: 47,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 700,
    hasAnnex: false,
    affiliateUrl: "https://cascadiatents.com/products/pioneer-2-softshell-tent",
    notes: "Entry-size softshell. 94.5\"×47\" sleeping area, 47\" headroom. 320G canvas/ripstop fabric, 1000D PVC cover. 3\" mattress. Closed dims estimated (CVT does not publish rack footprint). No annex available for this size.",
  },
  {
    id: "cvt-pioneer2-56",
    brand: "CVT",
    model: "Pioneer 2 Softshell — 56\" Mt. Shasta",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 176,
    closedHeightIn: 13,
    closedLengthIn: 94,
    closedWidthIn: 56,
    openLengthIn: 94,
    openWidthIn: 55,
    openHeadroomIn: 47,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 700,
    hasAnnex: true,
    annexName: "CVT Pioneer Annex — 56\" Mt. Shasta",
    annexWeightLbs: 10,
    annexSleeps: 1,
    annexAffiliateUrl: "https://cascadiatents.com/collections/accessories",
    affiliateUrl: "https://cascadiatents.com/products/pioneer-2-softshell-tent",
    notes: "Mid-size softshell. 94\"×55\" sleeping area, 47\" headroom. 320G canvas/ripstop, 1000D PVC cover. 3\" mattress. Closed dims estimated. Annex (+10 lbs, 55\"×79\"×79\"). Pioneer Awning accessory: 55\" Small +10 lbs / 79\" Med +12 lbs / 99\" Large +15 lbs.",
  },
  {
    id: "cvt-pioneer2-72",
    brand: "CVT",
    model: "Pioneer 2 Softshell — 72\" Mt. Rainier",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 198,
    closedHeightIn: 13,
    closedLengthIn: 94,
    closedWidthIn: 72,
    openLengthIn: 94,
    openWidthIn: 71,
    openHeadroomIn: 47,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 700,
    hasAnnex: true,
    annexName: "CVT Pioneer Annex — 72\" Mt. Rainier",
    annexWeightLbs: 11.2,
    annexSleeps: 1,
    annexAffiliateUrl: "https://cascadiatents.com/collections/accessories",
    affiliateUrl: "https://cascadiatents.com/products/pioneer-2-softshell-tent",
    notes: "Wide 3-person softshell. 94\"×71\" sleeping area, 47\" headroom. 320G canvas/ripstop, 1000D PVC cover. 3\" mattress. Closed dims estimated. Annex (+11.2 lbs, 71\"×79\"×79\"). 72\" wide — verify rack and vehicle width before ordering.",
  },
  {
    id: "cvt-pioneer2-87",
    brand: "CVT",
    model: "Pioneer 2 Softshell — 87\" Mt. Denali",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 262,
    closedHeightIn: 13,
    closedLengthIn: 94,
    closedWidthIn: 87,
    openLengthIn: 94,
    openWidthIn: 86,
    openHeadroomIn: 47,
    mattressThicknessIn: 3,
    sleepsMarketing: 4,
    sleepsRealistic: 3,
    staticRatingLbs: 700,
    hasAnnex: true,
    annexName: "CVT Pioneer Annex — 87\" Mt. Denali",
    annexWeightLbs: 12.5,
    annexSleeps: 2,
    annexAffiliateUrl: "https://cascadiatents.com/collections/accessories",
    affiliateUrl: "https://cascadiatents.com/products/pioneer-2-softshell-tent",
    notes: "Largest Pioneer 2. 94\"×86\" sleeping area, 47\" headroom. 262 lbs — heaviest CVT tent. 320G canvas/ripstop, 1000D PVC cover. 3\" mattress. Closed dims estimated. Annex (+12.5 lbs, 86\"×79\"×79\"). 87\" width overhangs most full-size truck beds by ~12\" per side.",
  },
  {
    id: "cvt-mt-hood2-50",
    brand: "CVT",
    model: "Mt. Hood 2 Hardshell — 50\" Small",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 215,
    closedHeightIn: 8.5,
    closedLengthIn: 85,
    closedWidthIn: 50,
    openLengthIn: 82,
    openWidthIn: 48,
    openHeadroomIn: 53.5,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "CVT Mt. Hood Annex — 50\" Small",
    annexWeightLbs: 18,
    annexSleeps: 1,
    annexAffiliateUrl: "https://cascadiatents.com/collections/accessories",
    affiliateUrl: "https://cascadiatents.com/products/mt-hood-2-hardshell-tent",
    notes: "Clamshell hardshell. 8.5\" closed profile. 82\"×48\" sleeping area, 53.5\" headroom. Aluminum shell, 280 GSM polyester fabric, LED light strip. T-channel perimeter for accessories. Setup 2–4 min. Annex (+18 lbs, 83\"×47\"×87\").",
  },
  {
    id: "cvt-mt-hood2-56",
    brand: "CVT",
    model: "Mt. Hood 2 Hardshell — 56\" Medium",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 222,
    closedHeightIn: 8.5,
    closedLengthIn: 85,
    closedWidthIn: 56,
    openLengthIn: 82,
    openWidthIn: 53,
    openHeadroomIn: 53.5,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "CVT Mt. Hood Annex — 56\" Medium",
    annexWeightLbs: 20,
    annexSleeps: 2,
    annexAffiliateUrl: "https://cascadiatents.com/collections/accessories",
    affiliateUrl: "https://cascadiatents.com/products/mt-hood-2-hardshell-tent",
    notes: "Clamshell hardshell. 8.5\" closed profile. 82\"×53\" sleeping area, 53.5\" headroom. Aluminum shell, 280 GSM polyester fabric, LED light strip. T-channel perimeter for accessories. Setup 2–4 min. Annex (+20 lbs, 83\"×53\"×87\").",
  },
  {
    id: "cvt-mt-hood2-60",
    brand: "CVT",
    model: "Mt. Hood 2 Hardshell — 60\" Large",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 231,
    closedHeightIn: 8.5,
    closedLengthIn: 85,
    closedWidthIn: 60,
    openLengthIn: 82,
    openWidthIn: 57,
    openHeadroomIn: 53.5,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: true,
    annexName: "CVT Mt. Hood Annex — 60\" Large",
    annexWeightLbs: 22,
    annexSleeps: 2,
    annexAffiliateUrl: "https://cascadiatents.com/collections/accessories",
    affiliateUrl: "https://cascadiatents.com/products/mt-hood-2-hardshell-tent",
    notes: "Clamshell hardshell. 8.5\" closed profile. 82\"×57\" sleeping area, 53.5\" headroom. Aluminum shell, 280 GSM polyester fabric, LED light strip. T-channel perimeter for accessories. Setup 2–4 min. Annex (+22 lbs, 83\"×57\"×87\").",
  },
  {
    id: "cvt-la-sal-50",
    brand: "CVT",
    model: "La Sal Hardshell — 50\" Small",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 220,
    closedHeightIn: 8.5,
    closedLengthIn: 85,
    closedWidthIn: 50,
    openLengthIn: 82,
    openWidthIn: 48,
    openHeadroomIn: 47,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://cascadiatents.com/products/la-sal-hardshell-tent",
    notes: "All-season clamshell hardshell. Same closed profile as Mt. Hood 2 (85\"×50\"×8.5\") but 6.5\" less headroom (47\" vs 53.5\"). 3\" jersey-cotton-wrapped mattress. 280 GSM polyester blackout fabric. Anti-condensation mats, carpeted roof, and climate ports included. Setup 2–4 min.",
  },
  {
    id: "cvt-la-sal-56",
    brand: "CVT",
    model: "La Sal Hardshell — 56\" Medium",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 230,
    closedHeightIn: 8.5,
    closedLengthIn: 85,
    closedWidthIn: 56,
    openLengthIn: 82,
    openWidthIn: 54,
    openHeadroomIn: 47,
    mattressThicknessIn: 3,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 900,
    hasAnnex: false,
    affiliateUrl: "https://cascadiatents.com/products/la-sal-hardshell-tent",
    notes: "All-season clamshell hardshell. Same closed profile as Mt. Hood 2 56\" (85\"×56\"×8.5\"). 3\" jersey-cotton-wrapped mattress. 280 GSM polyester blackout fabric. Anti-condensation mats, carpeted roof, and climate ports included. Setup 2–4 min.",
  },

  // ─── GUANA EQUIPMENT ──────────────────────────────────────────────

  {
    id: "guana-wanaka-55",
    brand: "Guana Equipment",
    model: "Wanaka 55",
    type: "softshell-foldout",
    openSide: "either",
    closedWeightLbs: 125,
    closedHeightIn: 14,
    closedLengthIn: 55,
    closedWidthIn: 50,
    openLengthIn: 96,
    openWidthIn: 55,
    openHeadroomIn: 48,
    mattressThicknessIn: 3,
    sleepsMarketing: 3,
    sleepsRealistic: 2,
    staticRatingLbs: 600,
    hasAnnex: true,
    annexName: "Guana Wanaka XL Annex",
    annexWeightLbs: 15,
    annexSleeps: 1,
    annexAffiliateUrl: "https://www.amazon.com/dp/B08R7GY8V3?tag=prepperevo-20",
    affiliateUrl: "https://www.amazon.com/dp/B08R7H4QHV?tag=prepperevo-20",
    notes: "600D waterproof ripstop polyester oxford. Diamond plate aluminum base. 1\" thick aluminum poles. XL annex included.",
  },

  // ─── iKAMPER MINI ─────────────────────────────────────────────────

  {
    id: "ikamper-skycamp-mini",
    brand: "iKamper",
    model: "Skycamp 3.0 Mini",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 125,
    closedHeightIn: 13.5,
    closedLengthIn: 57.5,
    closedWidthIn: 54.75,
    openLengthIn: 57.5,
    openWidthIn: 51.25,
    openHeadroomIn: 48,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B0BN3HPFQ4?tag=prepperevo-20",
    notes: "Compact hardshell designed for crossovers and smaller vehicles. 57.5\"×54.75\" footprint fits short racks. 9-zone 2.5\" polyfoam mattress. 13.5\" closed profile. 125 lbs — usable on most crossovers with aftermarket rack. Crossbar range 26\"–48\".",
  },
  {
    id: "ikamper-skycamp-dlx-mini",
    brand: "iKamper",
    model: "Skycamp DLX Mini",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 140,
    closedHeightIn: 13.5,
    closedLengthIn: 57.5,
    closedWidthIn: 54.75,
    openLengthIn: 57.5,
    openWidthIn: 51.25,
    openHeadroomIn: 48,
    mattressThicknessIn: 4,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Premium DLX version of the Skycamp 3.0 Mini — same compact footprint but upgraded 4\" RTT Comfort air-and-foam mattress, cork layer on honeycomb aluminum floor, interior + exterior LED lighting. 15 lbs heavier than standard 3.0 Mini. Crossbar range 26\"–48\".",
  },
  {
    id: "ikamper-rivian-skycamp-mini",
    brand: "iKamper",
    model: "Rivian × iKamper Skycamp Mini",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 137,
    closedHeightIn: 13.5,
    closedLengthIn: 57.5,
    closedWidthIn: 54.75,
    openLengthIn: 57.5,
    openWidthIn: 51.25,
    openHeadroomIn: 48,
    mattressThicknessIn: 2.5,
    sleepsMarketing: 2,
    sleepsRealistic: 2,
    staticRatingLbs: 660,
    hasAnnex: false,
    affiliateUrl: "#",
    notes: "Limited collab edition co-designed with Rivian. Same footprint as Skycamp 3.0 Mini. Rivian-branded colorway and interior accents. Engineered to fit Rivian R1T/R1S Crossbars. 137 lbs.",
  },

  // ─── TRUSTMADE ────────────────────────────────────────────────────

  {
    id: "trustmade-nomad",
    brand: "Trustmade",
    model: "Nomad",
    type: "hardshell-clamshell",
    openSide: "either",
    closedWeightLbs: 207,
    closedHeightIn: 11,
    closedLengthIn: 83,
    closedWidthIn: 49,
    openLengthIn: 83,
    openWidthIn: 49,
    openHeadroomIn: 35,
    mattressThicknessIn: 2,
    sleepsMarketing: 2,
    sleepsRealistic: 1,
    staticRatingLbs: 700,
    hasAnnex: false,
    affiliateUrl: "https://www.amazon.com/dp/B09JKG6D2Z?tag=prepperevo-20",
    notes: "Budget-friendly hardshell. Stainless steel frame. Only 35\" headroom. Good entry-level RTT.",
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────

export function getTentBrands(): string[] {
  return [...new Set(tentDatabase.map((t) => t.brand))].sort();
}

export function getTentModels(brand: string): TentEntry[] {
  return tentDatabase.filter((t) => t.brand === brand).sort((a, b) => a.model.localeCompare(b.model));
}

export function findTent(id: string): TentEntry | undefined {
  return tentDatabase.find((t) => t.id === id);
}

/**
 * Calculate realistic sleeping capacity from floor dimensions.
 * 24" per adult (shoulder width) + 6" gap between each person.
 */
export function calcRealisticSleeping(widthIn: number): { adults: number; tight: number } {
  const adultWidth = 24;
  const gap = 6;
  const adults = Math.floor((widthIn + gap) / (adultWidth + gap));
  const tight = Math.floor(widthIn / adultWidth);
  return { adults: Math.max(1, adults), tight: Math.max(1, tight) };
}
