// ─── Backpacking Tent Finder — tent-data.ts ─────────────────────────────
// Comprehensive database of ultralight backpacking tents with real specs.
// Sources: manufacturer websites, REI, Outdoor Gear Lab, SectionHiker,
// CleverHiker, SwitchbackTravel, Amazon product listings.
// Last updated: March 2026

export interface BackpackingTent {
  id: string;
  brand: string;
  model: string;
  capacity: 1 | 2 | 3 | 4;
  weightOz: number; // trail weight in ounces
  packedWeightOz: number; // packed/minimum weight
  price: number; // MSRP in dollars
  setup: "freestanding" | "semi-freestanding" | "trekking-pole" | "non-freestanding";
  season: "3-season" | "3plus-season" | "4-season";
  wallType: "double" | "single" | "hybrid";
  windRating: "low" | "moderate" | "high" | "storm";
  floorArea: number; // square inches
  vestibuleArea: number; // square inches (total both sides)
  peakHeight: number; // inches
  packedSize: string; // e.g. "6 x 18 in"
  fabricFly: string;
  fabricFloor: string;
  poles: string;
  doors: 1 | 2;
  stakes: number;
  stakesIncluded: boolean;
  footprintIncluded: boolean;
  madeIn: string;
  url: string;
  affiliateUrl: string;
  imageUrl?: string;
  pros: string[];
  cons: string[];
  bestFor: string;
  notes?: string;
}

export const tents: BackpackingTent[] = [
  // ═══════════════════════════════════════════════════════════
  //  2-PERSON TENTS
  // ═══════════════════════════════════════════════════════════

  // ─── Mountain Hardwear Nimbus UL2 ──────────────────────────
  {
    id: "mhw-nimbus-ul2",
    brand: "Mountain Hardwear",
    model: "Nimbus UL 2",
    capacity: 2,
    weightOz: 31,
    packedWeightOz: 34.2,
    price: 420,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4046,
    vestibuleArea: 1152,
    peakHeight: 40,
    packedSize: "6 x 19.5 in",
    fabricFly: "20D sil/sil nylon ripstop (1200mm)",
    fabricFloor: "30D nylon ripstop (1500mm)",
    poles: "DAC Featherlite NFL",
    doors: 1,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.mountainhardwear.com/p/nimbus-ul-2-tent-2102631.html",
    affiliateUrl: "https://www.amazon.com/dp/B0BQ3YXKW4?tag=prepperevo-20",
    pros: [
      "Ultra-light at just over 2 lbs trail weight",
      "Pre-bent pole design maximizes headroom",
      "G-hook canopy attachment is fast to set up"
    ],
    cons: [
      "Single door limits entry options",
      "Small vestibule for gear storage",
      "Tight for two people"
    ],
    bestFor: "Solo hikers who want a roomy 1P or ultra-minimal 2P",
  },

  // ─── Big Agnes Fly Creek HV UL2 ───────────────────────────
  {
    id: "ba-fly-creek-ul2",
    brand: "Big Agnes",
    model: "Fly Creek HV UL2",
    capacity: 2,
    weightOz: 31,
    packedWeightOz: 36,
    price: 450,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4032,
    vestibuleArea: 1152,
    peakHeight: 40,
    packedSize: "6 x 19.5 in",
    fabricFly: "20D HyperBead ripstop nylon (1200mm)",
    fabricFloor: "20D HyperBead ripstop nylon (1500mm)",
    poles: "DAC Featherlite NFL",
    doors: 1,
    stakes: 7,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.bigagnes.com/products/fly-creek-ul-two",
    affiliateUrl: "https://www.amazon.com/dp/B08MWZXQLV?tag=prepperevo-20",
    pros: [
      "Extremely light for a double-wall tent",
      "HyperBead fabric is PFAS-free and durable",
      "Good wind performance for its weight class"
    ],
    cons: [
      "Single door is limiting for two occupants",
      "Floor tapers significantly at the foot",
      "Vestibule is small"
    ],
    bestFor: "Weight-obsessed backpackers who want a proven ultralight",
  },

  // ─── MSR Freelite 2 ───────────────────────────────────────
  {
    id: "msr-freelite-2",
    brand: "MSR",
    model: "FreeLite 2",
    capacity: 2,
    weightOz: 32,
    packedWeightOz: 37,
    price: 450,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4176,
    vestibuleArea: 1440,
    peakHeight: 39,
    packedSize: "6 x 18 in",
    fabricFly: "15D ripstop nylon DuraShield (1200mm)",
    fabricFloor: "15D ripstop nylon DuraShield (1200mm)",
    poles: "DAC NFL aluminum",
    doors: 2,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://cascadedesigns.com/products/freelite-2-person-ultralight-backpacking-tent",
    affiliateUrl: "https://www.amazon.com/dp/B0D936TY67?tag=prepperevo-20",
    pros: [
      "True rectangular floor with no taper",
      "Two doors and two vestibules",
      "39 in peak height gives good headroom",
      "Micromesh body for stargazing"
    ],
    cons: [
      "Semi-freestanding requires staking the foot end",
      "DuraShield coating less proven long-term than sil/sil",
      "Slightly heavier than the lightest competitors"
    ],
    bestFor: "Backpackers who want a spacious rectangular floor at low weight",
  },

  // ─── Big Agnes Tiger Wall UL2 ─────────────────────────────
  {
    id: "ba-tiger-wall-ul2",
    brand: "Big Agnes",
    model: "Tiger Wall UL2",
    capacity: 2,
    weightOz: 40,
    packedWeightOz: 44,
    price: 500,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4032,
    vestibuleArea: 1440,
    peakHeight: 39,
    packedSize: "6 x 19.5 in",
    fabricFly: "15D HyperBead ripstop nylon",
    fabricFloor: "20D HyperBead ripstop nylon (1500mm)",
    poles: "DAC Featherlite NFL hubbed",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.bigagnes.com/products/tiger-wall-ul-two",
    affiliateUrl: "https://www.amazon.com/dp/B08MWZXQLV?tag=prepperevo-20",
    pros: [
      "Two doors and two vestibules",
      "HyperBead fabric is 25% more waterproof",
      "Good balance of weight and livability"
    ],
    cons: [
      "Semi-freestanding needs stakes at foot",
      "Floor tapers at the foot end",
      "Pricey for the weight"
    ],
    bestFor: "Couples who want two doors without a huge weight penalty",
  },

  // ─── NEMO Hornet Osmo 2P ──────────────────────────────────
  {
    id: "nemo-hornet-osmo-2p",
    brand: "NEMO",
    model: "Hornet Osmo 2P",
    capacity: 2,
    weightOz: 33,
    packedWeightOz: 40.7,
    price: 480,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 3931,
    vestibuleArea: 1296,
    peakHeight: 37,
    packedSize: "12.5 x 7.5 in",
    fabricFly: "15D Osmo ripstop poly-nylon",
    fabricFloor: "20D Osmo ripstop nylon (1200mm)",
    poles: "DAC Featherlite NFL",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.nemoequipment.com/products/hornet-osmo",
    affiliateUrl: "https://www.amazon.com/dp/B0BMT99T4S?tag=prepperevo-20",
    pros: [
      "Osmo fabric has 4x longer water repellency",
      "Osmo stretches 3x less when wet vs nylon",
      "Two doors and vestibules",
      "Nightlight pocket and Gatekeeper tiebacks"
    ],
    cons: [
      "37 in peak height is on the low side",
      "Tight floor width at foot end (42 in)",
      "Semi-freestanding needs staking"
    ],
    bestFor: "Backpackers who camp in wet conditions and want minimal sag",
  },

  // ─── NEMO Hornet Elite Osmo 2P ────────────────────────────
  {
    id: "nemo-hornet-elite-osmo-2p",
    brand: "NEMO",
    model: "Hornet Elite Osmo 2P",
    capacity: 2,
    weightOz: 27,
    packedWeightOz: 33,
    price: 650,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 3931,
    vestibuleArea: 1296,
    peakHeight: 37,
    packedSize: "12 x 7 in",
    fabricFly: "10D Osmo ripstop poly-nylon",
    fabricFloor: "15D Osmo ripstop nylon (1200mm)",
    poles: "DAC Featherlite NSL",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.nemoequipment.com/products/hornet-elite-osmo",
    affiliateUrl: "https://www.amazon.com/dp/B09WJN611K?tag=prepperevo-20",
    pros: [
      "Sub-2 lb trail weight in a double-wall tent",
      "Osmo fabric resists wet sag",
      "Flybar clip increases headroom"
    ],
    cons: [
      "Expensive at $650",
      "Thinner fabrics are less durable",
      "Tight for actual two-person use"
    ],
    bestFor: "Gram-counting thru-hikers who want the lightest double-wall",
  },

  // ─── Tarptent Double Rainbow ──────────────────────────────
  {
    id: "tarptent-double-rainbow",
    brand: "Tarptent",
    model: "Double Rainbow",
    capacity: 2,
    weightOz: 38,
    packedWeightOz: 41.8,
    price: 349,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "high",
    floorArea: 4400,
    vestibuleArea: 2160,
    peakHeight: 44,
    packedSize: "5 x 18 in",
    fabricFly: "20D silicone-coated high tenacity polyester",
    fabricFloor: "30D nylon 66 (3000mm)",
    poles: "Trekking poles or optional crossing pole",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://www.tarptent.com/product/double-rainbow/",
    affiliateUrl: "https://www.tarptent.com/product/double-rainbow/",
    pros: [
      "Made in the USA",
      "Generous 88 in length fits tall hikers",
      "Two huge 7.5 sq ft vestibules",
      "Can add crossing pole for freestanding pitch",
      "Excellent value at $349"
    ],
    cons: [
      "Single-wall means more condensation risk",
      "Trekking pole setup has a learning curve",
      "Not available on Amazon"
    ],
    bestFor: "Value-conscious hikers who want a spacious, USA-made trekking pole tent",
  },

  // ─── Big Agnes Copper Spur HV UL2 ────────────────────────
  {
    id: "ba-copper-spur-ul2",
    brand: "Big Agnes",
    model: "Copper Spur HV UL2",
    capacity: 2,
    weightOz: 44,
    packedWeightOz: 48,
    price: 550,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 4176,
    vestibuleArea: 1728,
    peakHeight: 40,
    packedSize: "6 x 20 in",
    fabricFly: "15D HyperBead ripstop nylon (1200mm)",
    fabricFloor: "20D HyperBead ripstop nylon (1500mm)",
    poles: "DAC Featherlite NFL + NSL pressfit",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.bigagnes.com/products/copper-spur-ul-two",
    affiliateUrl: "https://www.amazon.com/dp/B08175B2TN?tag=prepperevo-20",
    pros: [
      "True freestanding — pitch anywhere",
      "HyperBead waterproofing is PFAS-free",
      "Excellent livability for the weight",
      "Two doors, two vestibules"
    ],
    cons: [
      "Heavier than semi-freestanding competitors",
      "Premium price at $550",
      "Thin fabrics need care around sharp rocks"
    ],
    bestFor: "The gold standard freestanding UL tent — comfort, weather, versatility",
  },

  // ─── Durston X-Mid 2 ──────────────────────────────────────
  {
    id: "durston-xmid-2",
    brand: "Durston",
    model: "X-Mid 2",
    capacity: 2,
    weightOz: 38,
    packedWeightOz: 42,
    price: 280,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 4400,
    vestibuleArea: 1728,
    peakHeight: 43,
    packedSize: "5 x 15 in",
    fabricFly: "15D high tenacity silpoly",
    fabricFloor: "20D nylon (3000mm)",
    poles: "2 trekking poles (not included)",
    doors: 2,
    stakes: 4,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "China",
    url: "https://durstongear.com/products/x-mid-2-tent-ultralight-backpacking",
    affiliateUrl: "https://durstongear.com/products/x-mid-2-tent-ultralight-backpacking",
    pros: [
      "Incredible value at $280",
      "Only 4 stakes required — simple pitch",
      "Double-wall with great condensation management",
      "Generous floor area and 43 in peak height",
      "Storm-worthy X-Mid geometry"
    ],
    cons: [
      "Often out of stock due to demand",
      "Requires trekking poles",
      "Not available on Amazon — direct sale only"
    ],
    bestFor: "Best-value trekking pole tent — hard to beat at this price",
  },

  // ─── Durston X-Mid 2 Pro ──────────────────────────────────
  {
    id: "durston-xmid-2-pro",
    brand: "Durston",
    model: "X-Mid Pro 2",
    capacity: 2,
    weightOz: 20.4,
    packedWeightOz: 23,
    price: 639,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "high",
    floorArea: 4400,
    vestibuleArea: 1728,
    peakHeight: 43,
    packedSize: "4 x 12 in",
    fabricFly: "DCF 0.55 oz/sqyd",
    fabricFloor: "15D woven DCF floor",
    poles: "2 trekking poles (not included)",
    doors: 2,
    stakes: 4,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://durstongear.com/products/x-mid-pro-2-tent-ultralight-thruhiking",
    affiliateUrl: "https://durstongear.com/products/x-mid-pro-2-tent-ultralight-thruhiking",
    pros: [
      "Sub-1.5 lb in DCF — absurdly light",
      "Same X-Mid geometry as the standard model",
      "Woven DCF floor is more durable than laminate",
      "Only 4 stakes to pitch"
    ],
    cons: [
      "Single-wall design means condensation risk",
      "Expensive at $639",
      "DCF is less packable than nylon"
    ],
    bestFor: "Thru-hikers who want the lightest stormworthy 2P shelter money can buy",
  },

  // ─── Durston X-Dome 2 ─────────────────────────────────────
  {
    id: "durston-xdome-2",
    brand: "Durston",
    model: "X-Dome 2",
    capacity: 2,
    weightOz: 43.2,
    packedWeightOz: 48,
    price: 469,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 4608,
    vestibuleArea: 1296,
    peakHeight: 43,
    packedSize: "6 x 19 in",
    fabricFly: "15D high tenacity silpoly",
    fabricFloor: "20D nylon ripstop (3000mm)",
    poles: "Easton carbon poles (double-Y structure)",
    doors: 2,
    stakes: 4,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "China",
    url: "https://durstongear.com/products/x-dome-2-ultralight-tent",
    affiliateUrl: "https://durstongear.com/products/x-dome-2-ultralight-tent",
    pros: [
      "True freestanding with carbon poles",
      "Massive 32 sq ft floor area",
      "43 in peak height",
      "Magnetic door toggles",
      "Only 4 stakes needed for vestibules"
    ],
    cons: [
      "Carbon poles are expensive to replace",
      "Heavier than trekking pole options",
      "Direct sale only — can sell out"
    ],
    bestFor: "Freestanding tent seekers who want maximum floor space on a carbon pole frame",
  },

  // ─── Exped Cassira 2 ──────────────────────────────────────
  {
    id: "exped-cassira-2",
    brand: "Exped",
    model: "Cassira 2",
    capacity: 2,
    weightOz: 40.5,
    packedWeightOz: 46,
    price: 530,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4032,
    vestibuleArea: 1440,
    peakHeight: 41,
    packedSize: "6 x 17 in",
    fabricFly: "20D ripstop nylon sil/PU (1500mm)",
    fabricFloor: "30D ripstop nylon PU (3000mm)",
    poles: "DAC Featherlite NFL",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.expedusa.com/products/cassira",
    affiliateUrl: "https://www.amazon.com/dp/B0BZ2HVBKX?tag=prepperevo-20",
    pros: [
      "Inner tent works as standalone mosquito net",
      "Clip-and-pole setup is fast",
      "Good ventilation design"
    ],
    cons: [
      "Less widely reviewed than competitors",
      "Semi-freestanding needs staking",
      "Price is above average"
    ],
    bestFor: "Backpackers who value a convertible inner tent for warm-weather camping",
  },

  // ─── Slingfin 2Lite ───────────────────────────────────────
  {
    id: "slingfin-2lite",
    brand: "Slingfin",
    model: "2Lite",
    capacity: 2,
    weightOz: 42,
    packedWeightOz: 44,
    price: 505,
    setup: "non-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 4032,
    vestibuleArea: 1728,
    peakHeight: 41,
    packedSize: "12 x 6 in",
    fabricFly: "20D sil/sil nylon ripstop",
    fabricFloor: "20D sil/PU nylon ripstop",
    poles: "DAC Featherlite NFL (12 in segments)",
    doors: 2,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://www.slingfin.com/products/2lite",
    affiliateUrl: "https://www.slingfin.com/products/2lite",
    pros: [
      "Made in the USA",
      "Short pole segments ideal for bikepacking",
      "89 in length fits tall hikers",
      "Ergonomic footprint shape adds elbow room"
    ],
    cons: [
      "Non-freestanding requires staking",
      "Higher price point",
      "Tunnel design unfamiliar to some"
    ],
    bestFor: "Bikepackers and tall hikers who want a USA-made tunnel tent",
  },

  // ─── Slingfin Portal 2 ────────────────────────────────────
  {
    id: "slingfin-portal-2",
    brand: "Slingfin",
    model: "Portal 2",
    capacity: 2,
    weightOz: 46,
    packedWeightOz: 50,
    price: 510,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 3960,
    vestibuleArea: 1440,
    peakHeight: 44,
    packedSize: "6 x 18 in",
    fabricFly: "20D sil/sil polyester",
    fabricFloor: "20D sil/PE floor",
    poles: "2x DAC Featherlite NFL + 1x 9mm NFL",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://www.slingfin.com/products/portal-2",
    affiliateUrl: "https://www.slingfin.com/products/portal-2",
    pros: [
      "True freestanding at under 3 lbs",
      "44 in peak height — tallest in class",
      "Internal guylines for wind stability",
      "Sil/PE floor resists hydrolysis"
    ],
    cons: [
      "Price is premium at $510",
      "Slightly heavier than semi-free competitors",
      "Floor width tapers at foot end"
    ],
    bestFor: "The lightest freestanding tent with serious wind stability",
  },

  // ─── Marmot Limelight Ultralight 2P ───────────────────────
  {
    id: "marmot-limelight-ul-2p",
    brand: "Marmot",
    model: "Limelight UL 2P",
    capacity: 2,
    weightOz: 46,
    packedWeightOz: 50,
    price: 399,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4464,
    vestibuleArea: 1584,
    peakHeight: 43,
    packedSize: "7 x 20 in",
    fabricFly: "20D ripstop polyester",
    fabricFloor: "30D ripstop nylon (2000mm)",
    poles: "DAC Featherlite NFL aluminum",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.marmot.com/p/limelight-ul-2-person-tent/SP_2948360/AFS_195115225100.html",
    affiliateUrl: "https://www.amazon.com/dp/B0CPVZ78TX?tag=prepperevo-20",
    pros: [
      "31+ sq ft of floor space — very roomy",
      "True freestanding design",
      "Gear cubbies by each door",
      "Good value for a freestanding tent"
    ],
    cons: [
      "Heavier than UL competitors at ~3 lbs",
      "Bulkier packed size",
      "Polyester fly holds up but less tear-resistant"
    ],
    bestFor: "Backpackers who prioritize interior space and freestanding convenience",
  },

  // ─── Mountain Hardwear Aspect 2 ───────────────────────────
  {
    id: "mhw-aspect-2",
    brand: "Mountain Hardwear",
    model: "Aspect 2",
    capacity: 2,
    weightOz: 46.7,
    packedWeightOz: 54,
    price: 496,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4219,
    vestibuleArea: 1440,
    peakHeight: 41,
    packedSize: "6 x 20.5 in",
    fabricFly: "20D sil/sil nylon ripstop (1200mm)",
    fabricFloor: "40D nylon ripstop (1500mm)",
    poles: "DAC Featherlite poles",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.mountainhardwear.com/p/aspect-2-tent-1830101.html",
    affiliateUrl: "https://www.amazon.com/dp/B0BQ3Z1VYG?tag=prepperevo-20",
    pros: [
      "40D floor is bomber durable",
      "True freestanding with pre-bent poles",
      "Star-gazing mesh canopy",
      "Dual doors and vestibules"
    ],
    cons: [
      "Heavier at 3 lbs 6 oz packed",
      "Fly is only 1200mm HH",
      "Not the lightest option available"
    ],
    bestFor: "Durability-focused backpackers who want a burly freestanding tent",
  },

  // ─── REI Flash 2 ──────────────────────────────────────────
  {
    id: "rei-flash-2",
    brand: "REI Co-op",
    model: "Flash 2",
    capacity: 2,
    weightOz: 45.2,
    packedWeightOz: 49,
    price: 349,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4132,
    vestibuleArea: 1872,
    peakHeight: 40,
    packedSize: "6 x 18.5 in",
    fabricFly: "20D ripstop nylon sil/PU",
    fabricFloor: "30D ripstop nylon PU (3000mm)",
    poles: "DAC Featherlite NFL (3 poles)",
    doors: 2,
    stakes: 10,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.rei.com/product/216316/rei-co-op-flash-2-tent",
    affiliateUrl: "https://www.rei.com/product/216316/rei-co-op-flash-2-tent",
    pros: [
      "True freestanding at a great price",
      "88 in length fits tall hikers",
      "Scooped fly design sheds rain well",
      "REI member dividend applies"
    ],
    cons: [
      "Heavier than semi-free competitors",
      "Three poles to manage",
      "Smaller vestibules than some"
    ],
    bestFor: "REI members who want a solid freestanding tent at a fair price",
  },

  // ─── Sea to Summit Alto TR2 Plus ──────────────────────────
  {
    id: "sts-alto-tr2-plus",
    brand: "Sea to Summit",
    model: "Alto TR2 Plus",
    capacity: 2,
    weightOz: 51,
    packedWeightOz: 57,
    price: 449,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 4176,
    vestibuleArea: 1584,
    peakHeight: 43,
    packedSize: "6 x 17 in",
    fabricFly: "15D ripstop nylon sil/PU (1200mm)",
    fabricFloor: "20D ripstop nylon PU (2500mm)",
    poles: "DAC Featherlite NFL + Tension Ridge",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.rei.com/product/191711/sea-to-summit-alto-tr-2-plus-tent",
    affiliateUrl: "https://www.amazon.com/dp/B095H5T73G?tag=prepperevo-20",
    pros: [
      "Tension Ridge creates near-vertical walls",
      "Full-fabric inner for cold/wet conditions",
      "FairShare 3-sack system splits load evenly",
      "Excellent headroom for the weight"
    ],
    cons: [
      "Heavier than most UL 2P tents",
      "Semi-freestanding needs staking",
      "Tension Ridge adds complexity"
    ],
    bestFor: "Cold/wet weather backpackers who want maximum headroom and a full-fabric inner",
  },

  // ─── Sea to Summit Telos TR2 ──────────────────────────────
  {
    id: "sts-telos-tr2",
    brand: "Sea to Summit",
    model: "Telos TR2",
    capacity: 2,
    weightOz: 52.3,
    packedWeightOz: 59,
    price: 499,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4032,
    vestibuleArea: 1584,
    peakHeight: 43,
    packedSize: "6 x 17 in",
    fabricFly: "15D ripstop nylon sil/PU (1200mm)",
    fabricFloor: "20D ripstop nylon PU (2000mm)",
    poles: "DAC Featherlite NFL + Tension Ridge",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.rei.com/product/189385/sea-to-summit-telos-tr2-tent",
    affiliateUrl: "https://www.amazon.com/dp/B095H4HSVR?tag=prepperevo-20",
    pros: [
      "Three pitch modes: tent, tarp, shade canopy",
      "Tension Ridge maximizes headroom",
      "FairShare 3-sack system",
      "Mesh inner for ventilation"
    ],
    cons: [
      "Heavier than dedicated UL tents",
      "Complex setup compared to simple dome",
      "Mesh inner is cold in winter"
    ],
    bestFor: "Versatile 3-mode tent for backpackers who want options",
  },

  // ─── NEMO Dragonfly Osmo 2P ───────────────────────────────
  {
    id: "nemo-dragonfly-osmo-2p",
    brand: "NEMO",
    model: "Dragonfly Osmo 2P",
    capacity: 2,
    weightOz: 42,
    packedWeightOz: 50,
    price: 500,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4176,
    vestibuleArea: 1584,
    peakHeight: 41,
    packedSize: "19.5 x 5.5 in",
    fabricFly: "15D Osmo ripstop poly-nylon",
    fabricFloor: "20D Osmo ripstop nylon (1200mm)",
    poles: "DAC Featherlite NFL recycled aluminum",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.nemoequipment.com/products/dragonfly-osmo",
    affiliateUrl: "https://www.amazon.com/dp/B0BMT8X9JK?tag=prepperevo-20",
    pros: [
      "More spacious than the Hornet line",
      "Osmo fabric stays taut when wet",
      "41 in peak height for comfortable sitting",
      "Solution-dyed, PFAS-free fabrics"
    ],
    cons: [
      "Heavier than Hornet at 2 lbs 10 oz",
      "Semi-freestanding needs staking",
      "Premium price"
    ],
    bestFor: "Backpackers who want more livability than the Hornet with Osmo benefits",
  },

  // ─── NEMO Mayfly Osmo 2P ──────────────────────────────────
  {
    id: "nemo-mayfly-osmo-2p",
    brand: "NEMO",
    model: "Mayfly Osmo 2P",
    capacity: 2,
    weightOz: 48,
    packedWeightOz: 56,
    price: 400,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4017,
    vestibuleArea: 1022,
    peakHeight: 40,
    packedSize: "18 x 6 in",
    fabricFly: "20D Osmo ripstop poly-nylon",
    fabricFloor: "68D PU ripstop nylon",
    poles: "DAC Featherlite NFL",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.nemoequipment.com/products/mayfly-osmo",
    affiliateUrl: "https://www.amazon.com/dp/B0D5RYK7LQ?tag=prepperevo-20",
    pros: [
      "68D floor is extremely durable — no footprint needed",
      "Osmo fabric stays taut in rain",
      "Good value at $400",
      "Great for dog owners and rough ground"
    ],
    cons: [
      "Heavier at 3 lbs trail weight",
      "Smaller vestibules than competitors",
      "Not truly ultralight"
    ],
    bestFor: "Hikers with dogs or rough terrain who want a bomber floor without a footprint",
  },

  // ─── Kuiu Mountain Star 2 ─────────────────────────────────
  {
    id: "kuiu-mountain-star-2",
    brand: "Kuiu",
    model: "Mountain Star 2",
    capacity: 2,
    weightOz: 51.3,
    packedWeightOz: 56,
    price: 459,
    setup: "freestanding",
    season: "3plus-season",
    wallType: "single",
    windRating: "storm",
    floorArea: 4032,
    vestibuleArea: 1728,
    peakHeight: 42,
    packedSize: "6 x 18 in",
    fabricFly: "20D ripstop nylon sil/sil",
    fabricFloor: "40D ripstop nylon PU (5000mm)",
    poles: "Easton carbon fiber (or aluminum)",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.kuiu.com/products/mountainstar-2-person-tent-gunmetal-camel",
    affiliateUrl: "https://www.kuiu.com/products/mountainstar-2-person-tent-gunmetal-camel",
    pros: [
      "Storm-worthy with double pole intersections",
      "5000mm floor is extremely waterproof",
      "Carbon poles option saves 2.2 oz",
      "Two large vestibules for gear"
    ],
    cons: [
      "Heavier than dedicated UL tents",
      "Single-wall design means condensation risk",
      "Hunting brand — not widely reviewed by hikers"
    ],
    bestFor: "Mountain hunters and exposed-ridge campers who need storm protection",
  },

  // ─── Marmot Tungsten UL 2P ────────────────────────────────
  {
    id: "marmot-tungsten-ul-2p",
    brand: "Marmot",
    model: "Tungsten UL 2P",
    capacity: 2,
    weightOz: 46.9,
    packedWeightOz: 52,
    price: 379,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4608,
    vestibuleArea: 2160,
    peakHeight: 42,
    packedSize: "7 x 20 in",
    fabricFly: "20D ripstop polyester (1500mm)",
    fabricFloor: "30D ripstop nylon (2000mm)",
    poles: "DAC Pressfit aluminum (pre-bent knees)",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.rei.com/product/186996/marmot-tungsten-ul-2p-tent",
    affiliateUrl: "https://www.amazon.com/dp/B08CMR5HJZ?tag=prepperevo-20",
    pros: [
      "32 sq ft floor — among the roomiest UL tents",
      "Pre-bent pole knees maximize interior volume",
      "Good value at $379",
      "15 sq ft total vestibule area"
    ],
    cons: [
      "Not truly ultralight at ~3 lbs",
      "Polyester fly less tear-resistant than nylon",
      "Bulkier packed size"
    ],
    bestFor: "Budget-conscious backpackers who want a roomy freestanding tent",
  },

  // ─── Sierra Designs Clip Flashlight 2P ────────────────────
  {
    id: "sd-clip-flashlight-2",
    brand: "Sierra Designs",
    model: "Clip Flashlight 2",
    capacity: 2,
    weightOz: 62,
    packedWeightOz: 66,
    price: 200,
    setup: "non-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4320,
    vestibuleArea: 1440,
    peakHeight: 42,
    packedSize: "6 x 20 in",
    fabricFly: "40D ripstop polyester PU (1500mm)",
    fabricFloor: "40D ripstop nylon PU (3000mm)",
    poles: "DAC Pressfit aluminum",
    doors: 1,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "China",
    url: "https://sierradesigns.com/clip-flashlight-2/",
    affiliateUrl: "https://www.amazon.com/dp/B09F3G8XHG?tag=prepperevo-20",
    pros: [
      "Very affordable at ~$200",
      "30 sq ft interior is spacious",
      "Night Glow lantern accessory included",
      "Full vestibule with porch awning"
    ],
    cons: [
      "Heavy at 3 lbs 14 oz",
      "Non-freestanding design",
      "Single door limits access",
      "Not an ultralight — more of a budget lightweight"
    ],
    bestFor: "Budget backpackers who want a proven design at a low price",
  },

  // ─── Zpacks Duplex ────────────────────────────────────────
  {
    id: "zpacks-duplex",
    brand: "Zpacks",
    model: "Duplex",
    capacity: 2,
    weightOz: 19.4,
    packedWeightOz: 21,
    price: 699,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 3744,
    vestibuleArea: 1152,
    peakHeight: 48,
    packedSize: "5 x 9 in",
    fabricFly: "DCF 0.75 oz/sqyd",
    fabricFloor: "DCF 1.0 oz/sqyd",
    poles: "2x 48 in trekking poles (not included)",
    doors: 2,
    stakes: 8,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://zpacks.com/products/duplex-tent",
    affiliateUrl: "https://zpacks.com/products/duplex-tent",
    pros: [
      "Under 1.25 lbs — iconic ultralight shelter",
      "Made in the USA with DCF",
      "48 in peak height for sitting comfort",
      "Two side entry doors"
    ],
    cons: [
      "Single-wall — condensation in humid conditions",
      "Narrow 40 in floor width",
      "Expensive at $699",
      "DCF shows wear over time"
    ],
    bestFor: "Thru-hikers who count every gram and accept single-wall trade-offs",
  },

  // ─── Zpacks Pivot Duo ─────────────────────────────────────
  {
    id: "zpacks-pivot-duo",
    brand: "Zpacks",
    model: "Pivot Duo",
    capacity: 2,
    weightOz: 18.6,
    packedWeightOz: 21,
    price: 850,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 3888,
    vestibuleArea: 1152,
    peakHeight: 46,
    packedSize: "5 x 10 in",
    fabricFly: "DCF 0.55 oz/sqyd",
    fabricFloor: "DCF 0.75 oz/sqyd",
    poles: "2x 52 in trekking poles + 32 in end pole (included)",
    doors: 2,
    stakes: 8,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://zpacks.com/products/pivot-duo-tent",
    affiliateUrl: "https://zpacks.com/products/pivot-duo-tent",
    pros: [
      "Under 1.2 lbs — among the lightest 2P tents",
      "Symmetrical floor — sleep either direction",
      "Mirrored doors for wind flexibility",
      "Made in the USA"
    ],
    cons: [
      "Very expensive at $850",
      "Single-wall condensation issues",
      "Narrow for two wide pads",
      "Stakes not included"
    ],
    bestFor: "Ultralight purists who want the lightest enclosed 2P tent",
  },

  // ─── Zpacks Free Zip 2P ──────────────────────────────────
  {
    id: "zpacks-free-zip-2p",
    brand: "Zpacks",
    model: "Free Zip 2P",
    capacity: 2,
    weightOz: 33.7,
    packedWeightOz: 35.4,
    price: 899,
    setup: "freestanding",
    season: "3-season",
    wallType: "single",
    windRating: "high",
    floorArea: 3784,
    vestibuleArea: 0,
    peakHeight: 42,
    packedSize: "6 x 12 in",
    fabricFly: "DCF 0.75 oz/sqyd",
    fabricFloor: "DCF 1.0 oz/sqyd",
    poles: "4x Easton Carbon 6.3 poles (included)",
    doors: 2,
    stakes: 0,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://zpacks.com/products/free-zip-2p-tent",
    affiliateUrl: "https://zpacks.com/products/free-zip-2p-tent",
    pros: [
      "Freestanding — no stakes needed for pitch",
      "Sub-2.5 lb DCF freestanding tent",
      "Double-X pole design is stable",
      "Made in the USA"
    ],
    cons: [
      "Very expensive at $899",
      "No vestibules for gear storage",
      "Single-wall condensation",
      "5 in bathtub floor can splash in heavy rain"
    ],
    bestFor: "Desert/slickrock campers who need freestanding DCF without stakes",
  },

  // ─── HMG CrossPeak 2 ──────────────────────────────────────
  {
    id: "hmg-crosspeak-2",
    brand: "Hyperlite Mountain Gear",
    model: "CrossPeak 2",
    capacity: 2,
    weightOz: 34,
    packedWeightOz: 37,
    price: 950,
    setup: "freestanding",
    season: "3-season",
    wallType: "single",
    windRating: "high",
    floorArea: 3888,
    vestibuleArea: 1152,
    peakHeight: 42,
    packedSize: "6 x 18 in",
    fabricFly: "DCF (100% waterproof Dyneema)",
    fabricFloor: "DCF (100% waterproof Dyneema)",
    poles: "DAC Featherlite NFL 8.7mm aluminum",
    doors: 2,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Mexico",
    url: "https://hyperlitemountaingear.com/products/crosspeak-2",
    affiliateUrl: "https://hyperlitemountaingear.com/products/crosspeak-2",
    pros: [
      "Freestanding DCF at just over 2 lbs",
      "Near-vertical walls maximize space",
      "Internal guylines for extra wind stability",
      "High-quality DCF construction"
    ],
    cons: [
      "Very expensive at $950",
      "Single-wall condensation management",
      "Tight for two with wider pads",
      "Vestibules are modest"
    ],
    bestFor: "The lightest freestanding DCF tent for exposed alpine camping",
  },

  // ─── HMG UltaMid 2 ────────────────────────────────────────
  {
    id: "hmg-ultamid-2",
    brand: "Hyperlite Mountain Gear",
    model: "UltaMid 2",
    capacity: 2,
    weightOz: 19,
    packedWeightOz: 21,
    price: 699,
    setup: "trekking-pole",
    season: "4-season",
    wallType: "single",
    windRating: "storm",
    floorArea: 9072,
    vestibuleArea: 0,
    peakHeight: 56,
    packedSize: "5 x 10 in",
    fabricFly: "DCF (100% waterproof Dyneema)",
    fabricFloor: "None (pyramid shelter — floor sold separately)",
    poles: "2 trekking poles or carbon pole (not included)",
    doors: 1,
    stakes: 8,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "Mexico",
    url: "https://hyperlitemountaingear.com/products/ultamid-2-ultralight-pyramid-tent",
    affiliateUrl: "https://hyperlitemountaingear.com/products/ultamid-2-ultralight-pyramid-tent",
    pros: [
      "63 sq ft interior — enormous for the weight",
      "4-season capable pyramid design",
      "Storm-worthy in extreme conditions",
      "Under 1.2 lbs for the shelter alone"
    ],
    cons: [
      "No floor included — need separate insert or ground sheet",
      "Pyramid shape wastes some space at edges",
      "Requires 8 stakes — cannot pitch on rock",
      "Insert adds significant weight and cost"
    ],
    bestFor: "Winter mountaineers and alpine campers who need a bombproof 4-season shelter",
    notes: "Shelter only — full mesh insert ($325) or solid insert ($395) sold separately"
  },

  // ─── Gossamer Gear The Two ────────────────────────────────
  {
    id: "gg-the-two",
    brand: "Gossamer Gear",
    model: "The Two",
    capacity: 2,
    weightOz: 24,
    packedWeightOz: 26,
    price: 375,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 3888,
    vestibuleArea: 1440,
    peakHeight: 43,
    packedSize: "5 x 12 in",
    fabricFly: "10D seam-taped sil/PU nylon ripstop",
    fabricFloor: "10D seam-taped sil/PU nylon ripstop",
    poles: "2 adjustable trekking poles at 125cm",
    doors: 2,
    stakes: 6,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.gossamergear.com/products/the-two",
    affiliateUrl: "https://www.gossamergear.com/products/the-two",
    pros: [
      "Only 1.5 lbs — incredible for a 2P tent",
      "43 in peak height for sitting comfort",
      "Dual side entry doors and vestibules",
      "Factory seam-taped"
    ],
    cons: [
      "Single-wall means condensation risk",
      "10D fabric requires careful handling",
      "Trekking poles required (not included)",
      "Narrow at foot end (42 in)"
    ],
    bestFor: "Budget-conscious ultralight hikers who want sub-1.5 lb at a reasonable price",
  },

  // ─── MSR Hubba Hubba 2 ────────────────────────────────────
  {
    id: "msr-hubba-hubba-2",
    brand: "MSR",
    model: "Hubba Hubba 2",
    capacity: 2,
    weightOz: 46,
    packedWeightOz: 55,
    price: 550,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 4176,
    vestibuleArea: 1728,
    peakHeight: 39,
    packedSize: "6 x 18 in",
    fabricFly: "20D ripstop nylon DuraShield (1200mm)",
    fabricFloor: "30D ripstop nylon DuraShield (1500mm)",
    poles: "Easton Syclone aluminum",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://cascadedesigns.com/products/hubba-hubba-lt-2-person-tent",
    affiliateUrl: "https://www.amazon.com/dp/B09LNZLDJ7?tag=prepperevo-20",
    pros: [
      "Legendary durability and reliability",
      "True freestanding with Syclone poles",
      "Symmetrical design for easy setup",
      "Non-tapered floor for maximum space"
    ],
    cons: [
      "Heavier at 2 lbs 14 oz trail weight",
      "Price has crept up to $550",
      "39 in peak is lower than some competitors"
    ],
    bestFor: "The benchmark freestanding tent — proven on millions of miles of trail",
  },

  // ─── Hilleberg Anjan 2 ────────────────────────────────────
  {
    id: "hilleberg-anjan-2",
    brand: "Hilleberg",
    model: "Anjan 2",
    capacity: 2,
    weightOz: 60,
    packedWeightOz: 64,
    price: 745,
    setup: "non-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "storm",
    floorArea: 4334,
    vestibuleArea: 1728,
    peakHeight: 39,
    packedSize: "6 x 18 in",
    fabricFly: "Kerlon 1000 (20D triple-coated ripstop nylon)",
    fabricFloor: "70D nylon taffeta (8000mm)",
    poles: "9mm DAC poles",
    doors: 2,
    stakes: 4,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Estonia",
    url: "https://hilleberg.com/eng/products/tent/Anjan",
    affiliateUrl: "https://www.amazon.com/dp/B00BN9WMN0?tag=prepperevo-20",
    pros: [
      "Kerlon fabric is legendarily durable",
      "8000mm floor is nearly indestructible",
      "Made in Estonia — world-class quality",
      "Only 4 pegs for a proper pitch",
      "Handles extreme weather"
    ],
    cons: [
      "Heavy at 3 lbs 12 oz",
      "Very expensive at $745",
      "Tunnel design not for everyone",
      "Overkill for fair-weather 3-season"
    ],
    bestFor: "Hilleberg quality seekers who want a tent that will outlast everything else",
  },

  // ─── Big Agnes Sarvis VST 2 ───────────────────────────────
  {
    id: "ba-sarvis-vst-2",
    brand: "Big Agnes",
    model: "Sarvis VST 2",
    capacity: 2,
    weightOz: 40,
    packedWeightOz: 44,
    price: 749,
    setup: "freestanding",
    season: "3-season",
    wallType: "hybrid",
    windRating: "high",
    floorArea: 4320,
    vestibuleArea: 1584,
    peakHeight: 40,
    packedSize: "18 x 4.5 in",
    fabricFly: "20D recycled HyperBead nylon (4000mm)",
    fabricFloor: "20D HyperBead nylon (4000mm)",
    poles: "DAC Featherlite NFL",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.bigagnes.com/products/sarvis-vst-2",
    affiliateUrl: "https://www.amazon.com/dp/B0GFY1GVPJ?tag=prepperevo-20",
    pros: [
      "4000mm HyperBead — most waterproof BA tent",
      "Hybrid single/double wall with built-in vents",
      "Freestanding at only 2.5 lbs",
      "Recycled fabrics"
    ],
    cons: [
      "Very expensive at $749",
      "New design — limited long-term reviews",
      "Hybrid wall may condense in humid conditions"
    ],
    bestFor: "Big Agnes fans who want the latest tech with maximum waterproofing",
    notes: "2026 release — Big Agnes 25th anniversary VST collection"
  },

  // ─── Naturehike Cloud Up 2 ────────────────────────────────
  {
    id: "naturehike-cloud-up-2",
    brand: "Naturehike",
    model: "Cloud Up 2",
    capacity: 2,
    weightOz: 48.6,
    packedWeightOz: 63.5,
    price: 130,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "low",
    floorArea: 4032,
    vestibuleArea: 864,
    peakHeight: 41,
    packedSize: "4.7 x 17.7 in",
    fabricFly: "20D silicone-coated nylon (4000mm)",
    fabricFloor: "210T polyester PU (3000mm)",
    poles: "7001 aluminum alloy",
    doors: 1,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: true,
    madeIn: "China",
    url: "https://www.naturehike.com/products/cloud-up-2-person-ultralight-backpacking-tent",
    affiliateUrl: "https://www.amazon.com/dp/B0CPLJ6VGS?tag=prepperevo-20",
    pros: [
      "Incredibly affordable at ~$130",
      "Footprint included",
      "Freestanding design",
      "Silicone-coated fly is waterproof"
    ],
    cons: [
      "Heavier than premium options",
      "Single door only",
      "Budget poles flex in wind",
      "Fabrics less durable long-term"
    ],
    bestFor: "Budget backpackers or first-time tent buyers who want freestanding at the lowest price",
  },

  // ─── 3F UL Gear Lanshan 2 Pro ─────────────────────────────
  {
    id: "3ful-lanshan-2-pro",
    brand: "3F UL Gear",
    model: "Lanshan 2 Pro",
    capacity: 2,
    weightOz: 32.3,
    packedWeightOz: 36,
    price: 150,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "double",
    windRating: "low",
    floorArea: 3888,
    vestibuleArea: 1008,
    peakHeight: 49,
    packedSize: "5.9 x 13.8 in",
    fabricFly: "15D silnylon ripstop (5000mm)",
    fabricFloor: "20D nylon PU (5000mm)",
    poles: "2 trekking poles (not included)",
    doors: 2,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "China",
    url: "https://3fulgear.com/product/ultralight-tent/lanshan-2-pro/",
    affiliateUrl: "https://www.amazon.com/dp/B08LNKGB9R?tag=prepperevo-20",
    pros: [
      "Absurd value at $150 for a double-wall tent",
      "Under 2 lbs trail weight",
      "15D silnylon is reasonably durable",
      "Double-wall for condensation management"
    ],
    cons: [
      "Build quality not as refined as premium brands",
      "Seams need additional seam sealing",
      "Trekking pole setup less stable than premium tents",
      "Limited customer support"
    ],
    bestFor: "Budget ultralight hikers who want cottage tent performance at import prices",
  },

  // ─── Paria Outdoor Products Bryce 2P ──────────────────────
  {
    id: "paria-bryce-2p",
    brand: "Paria Outdoor Products",
    model: "Bryce 2P",
    capacity: 2,
    weightOz: 42,
    packedWeightOz: 55,
    price: 170,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 4505,
    vestibuleArea: 1152,
    peakHeight: 36,
    packedSize: "6 x 17 in",
    fabricFly: "20D sil/PU nylon ripstop (5000mm)",
    fabricFloor: "20D sil/PU nylon ripstop (5000mm)",
    poles: "DAC Pressfit aluminum",
    doors: 1,
    stakes: 12,
    stakesIncluded: true,
    footprintIncluded: true,
    madeIn: "China",
    url: "https://www.pariaoutdoorproducts.com/products/backpacking-tent-bryce",
    affiliateUrl: "https://www.amazon.com/dp/B07HGHZNNJ?tag=prepperevo-20",
    pros: [
      "Insane value at $170 with footprint included",
      "Freestanding with DAC poles",
      "5000mm waterproof rating",
      "Dyneema guy lines and 12 Y-stakes included"
    ],
    cons: [
      "Heavier than premium UL tents",
      "Single door only",
      "36 in peak height is cramped",
      "Small brand with limited reviews"
    ],
    bestFor: "Best-value freestanding tent — DAC poles and footprint at $170",
  },

  // ─── Six Moon Designs Lunar Duo Explorer ──────────────────
  {
    id: "smd-lunar-duo",
    brand: "Six Moon Designs",
    model: "Lunar Duo Explorer",
    capacity: 2,
    weightOz: 45,
    packedWeightOz: 48,
    price: 395,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 4860,
    vestibuleArea: 1728,
    peakHeight: 45,
    packedSize: "5 x 15 in",
    fabricFly: "20D silicone-coated nylon (3000mm)",
    fabricFloor: "40D silicone-coated polyester",
    poles: "2 trekking poles (not included)",
    doors: 2,
    stakes: 8,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://www.sixmoondesigns.com/products/lunar-duo-backpacking-tent",
    affiliateUrl: "https://www.sixmoondesigns.com/products/lunar-duo-backpacking-tent",
    pros: [
      "34 sq ft floor — extremely spacious",
      "45 in peak height for comfortable sitting",
      "Dual side entry with large vestibules",
      "Made in the USA"
    ],
    cons: [
      "Single-wall means condensation potential",
      "Requires staking — not freestanding",
      "Heavier than some trekking pole tents",
      "Stakes not included"
    ],
    bestFor: "Tall or wide hikers who want maximum interior space in a trekking pole tent",
  },

  // ═══════════════════════════════════════════════════════════
  //  1-PERSON TENTS
  // ═══════════════════════════════════════════════════════════

  // ─── Durston X-Mid 1 ──────────────────────────────────────
  {
    id: "durston-xmid-1",
    brand: "Durston",
    model: "X-Mid 1",
    capacity: 1,
    weightOz: 25,
    packedWeightOz: 28,
    price: 240,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 2880,
    vestibuleArea: 1152,
    peakHeight: 43,
    packedSize: "5 x 13 in",
    fabricFly: "15D high tenacity silpoly",
    fabricFloor: "20D nylon (3000mm)",
    poles: "2 trekking poles (not included)",
    doors: 2,
    stakes: 4,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "China",
    url: "https://durstongear.com/products/x-mid-1-tent-ultralight-backpacking",
    affiliateUrl: "https://durstongear.com/products/x-mid-1-tent-ultralight-backpacking",
    pros: [
      "Best value 1P trekking pole tent at $240",
      "Only 4 stakes — simplest pitch in class",
      "Double-wall eliminates condensation issues",
      "Gen 3 is wider, taller, and lighter"
    ],
    cons: [
      "Sells out fast",
      "Requires trekking poles",
      "Direct sale only"
    ],
    bestFor: "Solo hikers who want the best-value double-wall trekking pole tent",
  },

  // ─── Zpacks Plex Solo ─────────────────────────────────────
  {
    id: "zpacks-plex-solo",
    brand: "Zpacks",
    model: "Plex Solo",
    capacity: 1,
    weightOz: 13.9,
    packedWeightOz: 15,
    price: 599,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 2966,
    vestibuleArea: 720,
    peakHeight: 52,
    packedSize: "5 x 11 in",
    fabricFly: "DCF 0.75 oz/sqyd",
    fabricFloor: "DCF 1.0 oz/sqyd",
    poles: "1x 52 in trekking pole (not included)",
    doors: 1,
    stakes: 8,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://zpacks.com/products/plex-solo-tent",
    affiliateUrl: "https://zpacks.com/products/plex-solo-tent",
    pros: [
      "Sub-1 lb — among the lightest 1P tents ever made",
      "52 in peak height — can almost stand",
      "Made in the USA with DCF",
      "Roomy for a solo tent"
    ],
    cons: [
      "Single-wall condensation",
      "Expensive at $599",
      "Single entry door",
      "Stakes not included"
    ],
    bestFor: "Gram-counting solo thru-hikers who accept single-wall DCF trade-offs",
  },

  // ─── Big Agnes Fly Creek HV UL1 ───────────────────────────
  {
    id: "ba-fly-creek-ul1",
    brand: "Big Agnes",
    model: "Fly Creek HV UL1",
    capacity: 1,
    weightOz: 27,
    packedWeightOz: 33,
    price: 400,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 2736,
    vestibuleArea: 864,
    peakHeight: 38,
    packedSize: "4 x 18.5 in",
    fabricFly: "20D HyperBead ripstop nylon (1200mm)",
    fabricFloor: "20D HyperBead ripstop nylon (1500mm)",
    poles: "DAC Featherlite NFL",
    doors: 1,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.bigagnes.com/products/fly-creek-ul-one",
    affiliateUrl: "https://www.amazon.com/dp/B08MX1KJCQ?tag=prepperevo-20",
    pros: [
      "Under 1.7 lbs trail weight",
      "HyperBead fabric is proven and PFAS-free",
      "Double-wall prevents condensation",
      "Compact packed size"
    ],
    cons: [
      "Single door limits access",
      "Narrow floor tapers at foot",
      "Head-entry design takes getting used to"
    ],
    bestFor: "Solo backpackers who want a proven double-wall ultralight 1P",
  },

  // ─── NEMO Hornet Osmo 1P ──────────────────────────────────
  {
    id: "nemo-hornet-osmo-1p",
    brand: "NEMO",
    model: "Hornet Osmo 1P",
    capacity: 1,
    weightOz: 26,
    packedWeightOz: 29,
    price: 400,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 2966,
    vestibuleArea: 720,
    peakHeight: 36,
    packedSize: "11 x 5 in",
    fabricFly: "15D Osmo ripstop poly-nylon",
    fabricFloor: "20D Osmo ripstop nylon (1200mm)",
    poles: "DAC Featherlite NFL",
    doors: 1,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.nemoequipment.com/products/hornet-osmo",
    affiliateUrl: "https://www.amazon.com/dp/B0BMT8KBZZ?tag=prepperevo-20",
    pros: [
      "Osmo fabric repels water 4x longer",
      "Won't sag when wet like pure nylon",
      "Nightlight pocket for ambient light",
      "Compact packed size"
    ],
    cons: [
      "36 in peak height is low",
      "Single door only",
      "Semi-freestanding needs staking"
    ],
    bestFor: "Solo hikers who camp in wet areas and want minimal sag",
  },

  // ─── Gossamer Gear The One ────────────────────────────────
  {
    id: "gg-the-one",
    brand: "Gossamer Gear",
    model: "The One",
    capacity: 1,
    weightOz: 18,
    packedWeightOz: 20,
    price: 299,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 2268,
    vestibuleArea: 576,
    peakHeight: 45,
    packedSize: "4.5 x 11 in",
    fabricFly: "10D sil/PU nylon ripstop (1800mm)",
    fabricFloor: "10D sil/PU nylon ripstop (1800mm)",
    poles: "2 adjustable trekking poles at 125cm",
    doors: 1,
    stakes: 6,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.gossamergear.com/products/the-one",
    affiliateUrl: "https://www.gossamergear.com/products/the-one",
    pros: [
      "Just over 1 lb — incredible weight",
      "45 in peak height for sitting comfort",
      "Factory seam-taped",
      "Affordable at $299 for a UL tent"
    ],
    cons: [
      "Single-wall condensation",
      "10D fabric is delicate",
      "Narrow floor at 33 in head / 21 in foot",
      "Stakes not included"
    ],
    bestFor: "Budget-minded ultralight solo hikers who want sub-1.5 lb shelter",
  },

  // ─── Tarptent Protrail ────────────────────────────────────
  {
    id: "tarptent-protrail",
    brand: "Tarptent",
    model: "ProTrail",
    capacity: 1,
    weightOz: 26,
    packedWeightOz: 28,
    price: 239,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 2880,
    vestibuleArea: 720,
    peakHeight: 44,
    packedSize: "5 x 14 in",
    fabricFly: "20D SilPoly",
    fabricFloor: "30D nylon PU (3000mm)",
    poles: "2 trekking poles (not included)",
    doors: 1,
    stakes: 4,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://www.tarptent.com/product/protrail/",
    affiliateUrl: "https://www.tarptent.com/product/protrail/",
    pros: [
      "Made in the USA",
      "Fits users up to 6 ft 6 in",
      "Fast 4-stake pitch",
      "Excellent value at $239"
    ],
    cons: [
      "Single-wall condensation",
      "Front-entry design is less convenient",
      "Learning curve for first-time setup"
    ],
    bestFor: "Thru-hikers who want a USA-made solo shelter at an honest price",
  },

  // ─── Six Moon Designs Lunar Solo ──────────────────────────
  {
    id: "smd-lunar-solo",
    brand: "Six Moon Designs",
    model: "Lunar Solo",
    capacity: 1,
    weightOz: 26,
    packedWeightOz: 28,
    price: 260,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 3780,
    vestibuleArea: 1224,
    peakHeight: 48,
    packedSize: "4.5 x 11 in",
    fabricFly: "20D silicone-coated nylon (3000mm)",
    fabricFloor: "40D silicone-coated polyester",
    poles: "1x 49 in trekking pole or tent pole (not included)",
    doors: 1,
    stakes: 6,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://www.sixmoondesigns.com/products/lunar-solo-tent",
    affiliateUrl: "https://www.amazon.com/dp/B0DYMV6QH6?tag=prepperevo-20",
    pros: [
      "26.25 sq ft floor — palatial for a 1P",
      "48 in peak height — can sit up easily",
      "8.5 sq ft vestibule for gear",
      "Made in the USA"
    ],
    cons: [
      "Single-wall condensation risk",
      "Needs seam sealing (or pay extra for it)",
      "Single pole can feel less stable",
      "Stakes not included"
    ],
    bestFor: "Solo hikers who want huge interior space in a lightweight tent",
  },

  // ─── Tarptent Double Rainbow DW ───────────────────────────
  {
    id: "tarptent-double-rainbow-dw",
    brand: "Tarptent",
    model: "Double Rainbow DW",
    capacity: 2,
    weightOz: 44,
    packedWeightOz: 48,
    price: 439,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 4400,
    vestibuleArea: 2160,
    peakHeight: 44,
    packedSize: "5 x 18 in",
    fabricFly: "20D silicone-coated high tenacity polyester",
    fabricFloor: "30D nylon 66 (3000mm)",
    poles: "Trekking poles + DAC NFL 9.3 arch poles",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://www.tarptent.com/product/double-rainbow-dw-sp/",
    affiliateUrl: "https://www.tarptent.com/product/double-rainbow-dw-sp/",
    pros: [
      "Double-wall version of the legendary Double Rainbow",
      "Interior-only pitching and stargazing mode",
      "88 in length fits tall hikers",
      "Made in the USA"
    ],
    cons: [
      "Heavier than the single-wall version",
      "Trekking pole setup has a learning curve",
      "Not available on Amazon"
    ],
    bestFor: "Double Rainbow fans who want condensation separation and stargazing",
  },

  // ─── Durston X-Mid Pro 1 ──────────────────────────────────
  {
    id: "durston-xmid-pro-1",
    brand: "Durston",
    model: "X-Mid Pro 1",
    capacity: 1,
    weightOz: 15.5,
    packedWeightOz: 18,
    price: 449,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "high",
    floorArea: 2880,
    vestibuleArea: 1152,
    peakHeight: 45,
    packedSize: "4 x 10 in",
    fabricFly: "DCF 0.55 oz/sqyd",
    fabricFloor: "15D silnylon (or DCF option)",
    poles: "2 trekking poles (not included)",
    doors: 2,
    stakes: 4,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://durstongear.com/products/x-mid-pro-1-tent-ultralight-thruhiking",
    affiliateUrl: "https://durstongear.com/products/x-mid-pro-1-tent-ultralight-thruhiking",
    pros: [
      "Sub-1 lb with DCF — remarkably light",
      "50% more volume than closest rivals",
      "90 in length fits hikers up to 6 ft 8 in",
      "Only 4 stakes required"
    ],
    cons: [
      "Single-wall condensation risk",
      "Sells out immediately on drops",
      "DCF packs bulkier than nylon"
    ],
    bestFor: "Solo thru-hikers who want the lightest stormworthy 1P shelter",
  },

  // ─── Big Agnes Copper Spur HV UL1 ────────────────────────
  {
    id: "ba-copper-spur-ul1",
    brand: "Big Agnes",
    model: "Copper Spur HV UL1",
    capacity: 1,
    weightOz: 35,
    packedWeightOz: 38,
    price: 450,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 2736,
    vestibuleArea: 1008,
    peakHeight: 38,
    packedSize: "5 x 19 in",
    fabricFly: "15D HyperBead ripstop nylon (1200mm)",
    fabricFloor: "20D HyperBead ripstop nylon (1500mm)",
    poles: "DAC Featherlite NFL + NSL pressfit",
    doors: 1,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.bigagnes.com/products/copper-spur-ul-one",
    affiliateUrl: "https://www.amazon.com/dp/B08176VV9Z?tag=prepperevo-20",
    pros: [
      "True freestanding in a 1P tent",
      "HyperBead waterproofing is PFAS-free",
      "Cross pole keeps walls near-vertical",
      "Generous vestibule for solo use"
    ],
    cons: [
      "Heavier than trekking pole 1P tents",
      "Single door only",
      "Premium price at $450"
    ],
    bestFor: "Solo backpackers who want a freestanding 1P with no compromises",
  },

  // ─── MSR Hubba Hubba LT 2 ────────────────────────────────
  {
    id: "msr-hubba-hubba-lt-2",
    brand: "MSR",
    model: "Hubba Hubba LT 2",
    capacity: 2,
    weightOz: 34,
    packedWeightOz: 40,
    price: 600,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 4176,
    vestibuleArea: 1728,
    peakHeight: 39,
    packedSize: "6 x 16 in",
    fabricFly: "10D ripstop nylon DuraShield (1200mm)",
    fabricFloor: "15D ripstop nylon DuraShield (1200mm)",
    poles: "Easton Syclone aluminum",
    doors: 2,
    stakes: 8,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://cascadedesigns.com/products/hubba-hubba-lt-2-person-tent",
    affiliateUrl: "https://www.amazon.com/dp/B0DN3QGTPD?tag=prepperevo-20",
    pros: [
      "Lightest Hubba Hubba ever at 2 lbs 2 oz",
      "Freestanding with Syclone poles",
      "Same proven Hubba geometry",
      "10D fabrics cut significant weight"
    ],
    cons: [
      "Premium price at $600",
      "10D fabrics are delicate",
      "Lighter but more fragile than the standard"
    ],
    bestFor: "MSR loyalists who want the lightest freestanding Hubba Hubba",
  },

  // ─── Nemo Hornet Elite Osmo 1P ────────────────────────────
  {
    id: "nemo-hornet-elite-osmo-1p",
    brand: "NEMO",
    model: "Hornet Elite Osmo 1P",
    capacity: 1,
    weightOz: 21,
    packedWeightOz: 25,
    price: 550,
    setup: "semi-freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "moderate",
    floorArea: 2448,
    vestibuleArea: 576,
    peakHeight: 36,
    packedSize: "10 x 5 in",
    fabricFly: "10D Osmo ripstop poly-nylon",
    fabricFloor: "15D Osmo ripstop nylon (1200mm)",
    poles: "DAC Featherlite NSL",
    doors: 1,
    stakes: 6,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "Vietnam",
    url: "https://www.nemoequipment.com/products/hornet-elite-osmo",
    affiliateUrl: "https://www.amazon.com/dp/B09WJN4F9L?tag=prepperevo-20",
    pros: [
      "Under 1.5 lbs trail weight — remarkably light",
      "Osmo fabric resists wet sag",
      "Double-wall eliminates condensation worry"
    ],
    cons: [
      "Expensive at $550",
      "36 in peak height is very low",
      "10D fabrics need careful handling"
    ],
    bestFor: "Gram-counting solo thru-hikers who want the lightest double-wall 1P",
  },

  // ─── Zpacks Pivot Solo ────────────────────────────────────
  {
    id: "zpacks-pivot-solo",
    brand: "Zpacks",
    model: "Pivot Solo",
    capacity: 1,
    weightOz: 12.5,
    packedWeightOz: 14,
    price: 649,
    setup: "trekking-pole",
    season: "3-season",
    wallType: "single",
    windRating: "moderate",
    floorArea: 2592,
    vestibuleArea: 576,
    peakHeight: 46,
    packedSize: "4 x 9 in",
    fabricFly: "DCF 0.55 oz/sqyd",
    fabricFloor: "DCF 0.75 oz/sqyd",
    poles: "1x 52 in trekking pole + 32 in end pole (included)",
    doors: 1,
    stakes: 6,
    stakesIncluded: false,
    footprintIncluded: false,
    madeIn: "USA",
    url: "https://zpacks.com/products/pivot-solo-tent",
    affiliateUrl: "https://zpacks.com/products/pivot-solo-tent",
    pros: [
      "Sub-13 oz — among the lightest shelters made",
      "Included end pole adds structure",
      "Made in the USA with DCF",
      "46 in peak height for a solo tent"
    ],
    cons: [
      "Single-wall condensation",
      "Expensive at $649",
      "Stakes not included"
    ],
    bestFor: "Absolute weight minimalists who accept single-wall DCF",
  },

  // ─── Durston X-Dome 1+ ───────────────────────────────────
  {
    id: "durston-xdome-1-plus",
    brand: "Durston",
    model: "X-Dome 1+",
    capacity: 1,
    weightOz: 33,
    packedWeightOz: 37,
    price: 369,
    setup: "freestanding",
    season: "3-season",
    wallType: "double",
    windRating: "high",
    floorArea: 3024,
    vestibuleArea: 864,
    peakHeight: 41,
    packedSize: "6 x 17 in",
    fabricFly: "15D high tenacity silpoly",
    fabricFloor: "20D nylon ripstop (3000mm)",
    poles: "Easton carbon poles (Y-shaped)",
    doors: 2,
    stakes: 2,
    stakesIncluded: true,
    footprintIncluded: false,
    madeIn: "China",
    url: "https://durstongear.com/products/x-dome-1-plus-ultralight-backpacking-tent",
    affiliateUrl: "https://durstongear.com/products/x-dome-1-plus-ultralight-backpacking-tent",
    pros: [
      "True freestanding with carbon poles at 2 lbs",
      "21 sq ft floor — spacious for a 1P",
      "Only 2 stakes needed for vestibules",
      "Excellent value at $369"
    ],
    cons: [
      "Carbon poles are expensive to replace",
      "Heavier than trekking pole options",
      "Direct sale only"
    ],
    bestFor: "Solo hikers who want a freestanding tent with carbon poles at a fair price",
  },
];

// ─── Helper: compute weight in lbs and oz display ────────────────────────
export function formatWeight(oz: number): string {
  const lbs = Math.floor(oz / 16);
  const remainOz = +(oz % 16).toFixed(1);
  if (lbs === 0) return `${remainOz} oz`;
  return `${lbs} lb ${remainOz} oz`;
}

// ─── Helper: compute floor area in sq ft ─────────────────────────────────
export function sqInToSqFt(sqIn: number): string {
  return (sqIn / 144).toFixed(1);
}

// ─── Setup type labels ───────────────────────────────────────────────────
export const setupLabels: Record<BackpackingTent["setup"], string> = {
  freestanding: "Freestanding",
  "semi-freestanding": "Semi-Freestanding",
  "trekking-pole": "Trekking Pole",
  "non-freestanding": "Non-Freestanding",
};

// ─── Season labels ───────────────────────────────────────────────────────
export const seasonLabels: Record<BackpackingTent["season"], string> = {
  "3-season": "3-Season",
  "3plus-season": "3+ Season",
  "4-season": "4-Season",
};

// ─── Wind rating labels + colors ─────────────────────────────────────────
export const windLabels: Record<BackpackingTent["windRating"], string> = {
  low: "Low",
  moderate: "Moderate",
  high: "High",
  storm: "Storm",
};

export const windColors: Record<BackpackingTent["windRating"], string> = {
  low: "bg-green-500/20 text-green-400 border-green-500/30",
  moderate: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  high: "bg-orange-500/20 text-orange-400 border-orange-500/30",
  storm: "bg-red-500/20 text-red-400 border-red-500/30",
};
