export interface AffiliateLink {
  network: "amazon" | "avantlink" | "shareasale" | "awin" | "direct";
  label: string;
  url: string;
  commission?: string;
}

export interface Product {
  slug: string;
  name: string;
  category: string;
  price: string;
  rating: number;
  reviewCount: number;
  image: string;
  description: string;
  features: string[];
  affiliateUrl: string;
  affiliateLinks?: AffiliateLink[];
  pros?: string[];
  cons?: string[];
  bestFor?: string;
  badge?: string;
  featured?: boolean;
  articleSlug?: string;
}

// ─── Product → Article mapping ───
// Maps product slugs to WordPress article slugs so product cards link to real reviews
export const productArticleMap: Record<string, string> = {
  // ─── products.ts slugs ───
  "sawyer-squeeze-water-filter": "sawyer-squeeze-water-filter-review",
  "waterdrop-king-tank": "waterdrop-king-tank-gravity-water-filter-review-2026",
  "molle-ii-rucksack": "molle-ii-rucksack-review-military-surplus-72hr-pack",
  "511-tactical-rush72": "5-11-rush-72-bug-out-bag-review",
  "morakniv-companion-knife": "mora-companion-hd-review-best-budget-survival-knife-17",
  "baofeng-uv5r-radio": "baofeng-uv-5r-review-26-ham-radio-for-emergency-comms",
  "garmin-inreach-mini-2": "garmin-inreach-mini-2-review-satellite-sos-messaging",
  "ikamper-skycamp-3-rooftop-tent": "ikamper-skycamp-3-review",
  "maxtrax-mkii-recovery-boards": "maxtrax-vs-actiontrax-recovery-boards",
  "dometic-cfx3-55im-portable-fridge": "dometic-cfx3-55im-review",
  "dometic-cfx3-35": "best-overlanding-fridges-compared-dometic-vs-arb-2026",
  "arb-elements-60l": "arb-classic-series-ii-fridge-review",
  "jackery-explorer-1000-v2": "jackery-explorer-1000-v2-review",
  "ecoflow-delta-2-max": "best-portable-power-stations-2026",
  "ecoflow-delta-3-ultra": "best-portable-power-stations-2026",
  "ecoflow-delta-3-max-plus": "best-portable-power-stations-2026",
  "ecoflow-wave-3": "best-portable-power-stations-2026",
  "bigblue-28w-solar-charger": "renogy-200w-solar-panel-review",
  "leatherman-wave-plus": "best-survival-knives-compared-budget-to-premium-2026",
  "cat-tourniquet-gen7": "first-aid-essentials-survival",
  "ifak-trauma-kit": "first-aid-essentials-survival",
  "mountain-house-14-day-emergency-food": "long-term-food-storage-guide",
  "mylar-bags-oxygen-absorbers": "long-term-food-storage-guide",
  "sol-emergency-bivvy": "building-your-first-bug-out-bag",
  "aquamira-water-purification-tablets": "water-purification-methods",
  "dakota-alert-murs-sensor": "home-security-budget",
  "511-tactical-rush24": "best-bug-out-bags-2026",
  "mystery-ranch-3-day-assault": "best-bug-out-bags-2026",
  "vertx-gamut-2": "best-bug-out-bags-2026",
  "goruck-gr2-40l": "best-bug-out-bags-2026",
  "maxpedition-falcon-ii": "best-bug-out-bags-2026",
  "helikon-tex-raccoon-mk2": "best-bug-out-bags-2026",
  "iceco-vl60-pros": "best-12v-fridges-overlanding",
  "bougerv-cr45": "best-12v-fridges-overlanding",
  "alpicool-c20": "best-12v-fridges-overlanding",
  "setpower-pt45": "best-12v-fridges-overlanding",
  "petzl-actik-core-headlamp": "best-portable-lighting-camping-2026",
  "katadyn-befree-water-filter": "best-water-filters-preppers-2026",
  "jetboil-flash-cooking-system": "best-camp-stoves-cooking-gear-compared-2026",
  "gsi-pinnacle-camper-cookset": "best-camp-stoves-cooking-gear-compared-2026",
  "big-agnes-copper-spur-hv-ul2": "ultralight-backpacking-gear-guide",
  "thermarest-neoair-xlite-nxt": "ultralight-backpacking-gear-guide",
  "enlightened-equipment-enigma-quilt": "ultralight-backpacking-gear-guide",
  "osprey-atmos-ag-65-backpack": "ultralight-backpacking-gear-guide",
  // ─── Replit DB slugs (different from products.ts) ───
  "lifestraw-personal-water-filter": "lifestraw-personal-water-filter-review",
  "berkey-water-filter": "best-water-filters-preppers-2026",
  "jackery-explorer-1000-plus": "jackery-explorer-1000-v2-review",
  "bluetti-ac200pl": "bluetti-ac200max-review",
  "ikamper-skycamp-3-0": "ikamper-skycamp-3-review",
  "roofnest-falcon-2": "roofnest-falcon-2-review-clamshell-hardshell-for-3495",
  "arb-simpson-iii": "arb-simpson-iii-review-budget-soft-shell-rtt-for-1795",
  "baofeng-uv-5r": "baofeng-uv-5r-review-26-ham-radio-for-emergency-comms",
  "midland-gxt1000vp4": "midland-gxt1000vp4-review-36-mile-gmrs-radio-pair",
  "solo-stove-ranger-2": "solo-stove-ranger-2-0-review-smokeless-fire-pit",
  "camp-chef-explorer-2x": "camp-chef-explorer-2x-review",
  "biolite-campstove-2": "biolite-campstove-2-review",
  "dometic-cfx3-55im": "dometic-cfx3-55im-review",
  "arb-classic-series-ii-50qt": "arb-classic-series-ii-fridge-review",
  "mora-companion-hd": "mora-companion-hd-review-best-budget-survival-knife-17",
  "esee-4": "esee-4-survival-knife-review",
  "benchmade-bugout-535": "benchmade-bugout-535-review",
  "renogy-200w-solar-panel": "renogy-200w-solar-panel-review",
  "goal-zero-yeti-1000-core": "goal-zero-yeti-1000-core-review",
  // ─── Overlanding accessories (no dedicated reviews, link to overlanding gear guide) ───
  "warn-vr-evo-10s-winch": "best-overlanding-gear-emergency-preparedness",
  "arb-twin-air-compressor": "best-overlanding-gear-emergency-preparedness",
  "front-runner-slimline-ii-roof-rack": "best-overlanding-gear-emergency-preparedness",
  "baja-designs-squadron-sport-led": "best-overlanding-gear-emergency-preparedness",
  "goose-gear-campervan-plate-system": "best-overlanding-gear-emergency-preparedness",
};

const products: Product[] = [
  // WATER
  {
    slug: "sawyer-squeeze-water-filter",
    name: "Sawyer Squeeze Water Filter System",
    category: "water",
    price: "$37",
    rating: 4.8,
    reviewCount: 28400,
    image: "https://cdn.prod.website-files.com/61549f9352f3558157a226ea/6776e9804a8c2ee279d54f97_sawyer-squeeze-water-filteration.png",
    description:
      "The gold standard for portable water filtration. Filters up to 100,000 gallons, removes 99.99999% of bacteria and 99.9999% of protozoa. Weighs just 3 oz.",
    features: [
      "0.1 micron absolute hollow fiber membrane",
      "Filters 100,000 gallons",
      "Weighs 3 oz — ultralight",
      "Includes 32oz squeeze pouches",
      "Backflush syringe for cleaning",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B00B1OSU4W?tag=prepperevo-20",
    pros: [
      "100,000 gallon filter lifespan",
      "Only 3 oz — ultralight for any pack",
      "Under $40 — best value in water filtration",
      "Backflushable for field maintenance",
    ],
    cons: [
      "Does not remove viruses",
      "Can crack if frozen with water inside",
      "Squeeze pouches wear out over time",
    ],
    bestFor: "Bug out bags, backpacking, and portable emergency filtration",
    badge: "Editor's Pick",
    featured: true,
  },
  {
    slug: "waterdrop-king-tank",
    name: "Waterdrop King Tank Gravity Water Filter System",
    category: "water",
    price: "$190",
    rating: 4.6,
    reviewCount: 3200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Waterdrop_King_Tank_Gravity_Water_Filter_System.jpeg",
    description:
      "The gravity-fed water filter that replaced the discontinued Berkey. NSF 42 and 372 certified, reduces chlorine, lead, mercury, PFAS, and 20+ contaminants. 2.25-gallon stainless steel tank with dual filter elements — no electricity or plumbing required.",
    features: [
      "NSF 42 & 372 certified filtration",
      "Reduces chlorine, lead, mercury, PFAS, and 20+ contaminants",
      "No electricity or plumbing required",
      "2.25-gallon stainless steel tank",
      "Dual filter elements — 8,000 gallon combined lifespan",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0BLNSYNW3?tag=prepperevo-20",
    pros: [
      "NSF certified — independently tested and verified",
      "No electricity or plumbing needed",
      "$190 — significantly cheaper than the old Berkey",
      "Stainless steel construction — built to last",
    ],
    cons: [
      "Does not remove viruses (pair with chemical treatment)",
      "Gravity-fed — slower than pressurized filters",
      "Filter elements need replacement every 8,000 gallons",
    ],
    bestFor: "Home preparedness, base camp, and family emergency water supply",
    featured: true,
  },
  {
    slug: "aquamira-water-treatment-drops",
    name: "Aquamira Water Treatment Drops (1 oz)",
    category: "water",
    price: "$16",
    rating: 4.6,
    reviewCount: 6200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Aquamira_Water_Purification_Drops.jpeg",
    description:
      "Two-part chlorine dioxide water treatment drops. Mix Part A and Part B, wait 5 minutes, add to water. Treats up to 30 gallons (112 liters). Iodine-free, chlorine-free, no weird taste.",
    features: [
      "Chlorine dioxide — kills bacteria, viruses, Giardia, and Crypto",
      "Treats up to 30 gallons (112 liters) per set",
      "Two-part liquid drops — no tablets to dissolve",
      "Iodine-free and chlorine-free",
      "5-year shelf life",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0078SA5SE?tag=prepperevo-20",
    pros: [
      "Best taste of any chemical treatment — no iodine or chlorine flavor",
      "112 liters per set — way more than tablets",
      "Ultralight at 3 oz total",
      "Works on viruses, bacteria, and cysts",
    ],
    cons: [
      "Two-part mixing required before adding to water",
      "15-minute wait for bacteria, 4 hours for Crypto",
      "Liquid bottles can leak if not sealed tight",
    ],
    bestFor: "Lightweight backup water treatment for hiking, camping, and emergency kits",
  },

  // FOOD
  {
    slug: "mountain-house-14-day-emergency-food",
    name: "Mountain House 14-Day Emergency Food Supply",
    category: "food",
    price: "$249",
    rating: 4.7,
    reviewCount: 8900,
    image: "https://mountainhouse.com/cdn/shop/files/0089600-14-day-emergency-food-supply-kit-pouches-box.jpg?v=1756031630",
    description:
      "14 days of freeze-dried meals with a 30-year shelf life. Just add water. Includes breakfast, lunch, and dinner varieties.",
    features: [
      "30-year shelf life guaranteed",
      "Just add water — ready in minutes",
      "Includes 20 pouches / 74 servings",
      "Average 1,800 calories per day",
      "No refrigeration needed",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0BPVMJKV2?tag=prepperevo-20",
    pros: [
      "30-year shelf life — set it and forget it",
      "Just add water — no cooking skills needed",
      "74 servings across breakfast, lunch, and dinner",
      "Lightweight pouches — portable for bug out situations",
    ],
    cons: [
      "$249 upfront — roughly $3.36 per serving",
      "High sodium content in most meals",
      "Requires water to prepare — plan accordingly",
    ],
    bestFor: "Set-and-forget emergency food stockpile for families and bug out kits",
    badge: "Best Seller",
    featured: true,
  },
  {
    slug: "mylar-bags-oxygen-absorbers",
    name: "Mylar Bags with Oxygen Absorbers (100-pack)",
    category: "food",
    price: "$32",
    rating: 4.6,
    reviewCount: 4200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Mylar_Bags_with_Oxygen_Absorbers.jpeg",
    description:
      "1-gallon Mylar bags (7mil) with 300cc oxygen absorbers for DIY long-term food storage. Seal with a flat iron for 20+ year shelf life.",
    features: [
      "7 mil thick — puncture resistant",
      "100 bags + 100 oxygen absorbers",
      "Seal with household iron or impulse sealer",
      "Creates 20-25 year food storage",
      "FDA food-safe material",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0CZ7VVJZ6?tag=prepperevo-20",
    pros: [
      "100 bags + absorbers — enough for a full pantry conversion",
      "$32 — incredibly affordable long-term storage",
      "Creates 20-25 year shelf life on dry goods",
      "Seal with a household iron — no special equipment",
    ],
    cons: [
      "Requires time and effort to fill and seal each bag",
      "Oxygen absorbers activate on exposure — work quickly",
      "Not suitable for high-moisture foods",
    ],
    bestFor: "DIY long-term food storage for rice, beans, oats, and dry goods",
  },

  // FIRST AID
  {
    slug: "cat-tourniquet-gen7",
    name: "CAT Tourniquet Gen 7 (Combat Application Tourniquet)",
    category: "firstaid",
    price: "$30",
    rating: 4.9,
    reviewCount: 15600,
    image: "https://cdn11.bigcommerce.com/s-mc2ixn/images/stencil/1280x1280/products/705/3127/Combat-Application-Tourniquet-Black-Front__54269.1695270106.png?c=2",
    description:
      "The standard-issue tourniquet used by the US Military, law enforcement, and EMS. Proven to stop life-threatening extremity bleeding in seconds.",
    features: [
      "Official US Military issue (NSN listed)",
      "Single-hand application capable",
      "Windlass locking mechanism",
      "Time strap for recording application time",
      "Compact, lightweight design",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0DVZR1XHP?tag=prepperevo-20",
    badge: "Essential",
    featured: true,
  },
  {
    slug: "ifak-trauma-kit",
    name: "Compact IFAK Trauma Kit",
    category: "firstaid",
    price: "$65",
    rating: 4.7,
    reviewCount: 3400,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Compact_IFAK_Trauma_Kit.jpeg",
    description:
      "Individual First Aid Kit with tourniquet, Israeli bandage, chest seal, wound packing gauze, and trauma shears. MOLLE-compatible pouch.",
    features: [
      "CAT tourniquet included",
      "Israeli emergency bandage",
      "HyFin chest seal (twin pack)",
      "QuikClot hemostatic gauze",
      "MOLLE-compatible pouch",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0FYF2S1HM?tag=prepperevo-20",
    pros: [
      "Complete trauma kit — tourniquet, bandage, chest seal, gauze",
      "MOLLE pouch attaches to any tactical bag or vest",
      "$65 — cheaper than buying components separately",
      "Everything you need for penetrating trauma and hemorrhage",
    ],
    cons: [
      "Requires training to use effectively — take a Stop the Bleed class",
      "Components have expiration dates — check annually",
      "Generic brands on some components",
    ],
    bestFor: "Every bug out bag, vehicle kit, and range bag needs an IFAK",
  },

  // COMMUNICATION
  {
    slug: "baofeng-uv5r-radio",
    name: "Baofeng UV-5R Dual Band HAM Radio",
    category: "communication",
    price: "$25",
    rating: 4.4,
    reviewCount: 42000,
    image: "https://www.baofengradio.com/cdn/shop/files/UV-5R-5W-Dual-Band-Radio-Baofeng-2690_grande.jpg?v=1696418635",
    description:
      "The most popular budget HAM radio. Dual-band (VHF/UHF), programmable, and incredibly affordable. Requires a Technician HAM license to transmit.",
    features: [
      "Dual-band VHF (136-174MHz) / UHF (400-520MHz)",
      "128 programmable memory channels",
      "Built-in FM radio and flashlight",
      "1800mAh battery — long battery life",
      "Includes antenna, charger, and earpiece",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B007H4VT7A?tag=prepperevo-20",
    pros: [
      "$25 — cheapest way into HAM radio",
      "Dual-band VHF/UHF covers the most useful frequencies",
      "128 channels — highly programmable with CHIRP software",
      "Built-in FM radio and LED flashlight",
    ],
    cons: [
      "Requires HAM Technician license to legally transmit",
      "Clunky menu system — steep learning curve",
      "Stock antenna is mediocre — plan to upgrade",
    ],
    bestFor: "Budget HAM radio for emergency comms and new ham operators",
  },
  {
    slug: "garmin-inreach-mini-2",
    name: "Garmin inReach Mini 2 Satellite Communicator",
    category: "communication",
    price: "$350",
    rating: 4.6,
    reviewCount: 6700,
    image: "https://res.garmin.com/en/products/010-02602-00/v/cf-lg-751bd56a-08aa-4b4f-a932-0e2d8ac71de7.jpg",
    description:
      "Two-way satellite messaging, SOS, and GPS tracking — works anywhere on Earth with zero cell coverage. Pairs with your phone for easy messaging.",
    features: [
      "Two-way satellite text messaging",
      "Interactive SOS with 24/7 GEOS rescue center",
      "GPS tracking and sharing",
      "Weighs 3.5 oz",
      "100-hour battery in tracking mode",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0G4RST8LV?tag=prepperevo-20",
    badge: "Premium Pick",
    featured: true,
  },

  // SHELTER
  {
    slug: "sol-emergency-bivvy",
    name: "SOL Emergency Bivvy with Rescue Whistle",
    category: "shelter",
    price: "$18",
    rating: 4.5,
    reviewCount: 9800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/SOL_Emergency_Bivvy_with_Rescue_Whistle.jpeg",
    description:
      "Reflects 90% of body heat, windproof and waterproof. Weighs 3.8 oz — small enough for any bug out bag, glove box, or daypack.",
    features: [
      "Reflects 90% of radiated body heat",
      "Windproof and waterproof",
      "Built-in rescue whistle",
      "Weighs 3.8 oz",
      "Reusable — not single-use like space blankets",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B08KWQVBT7?tag=prepperevo-20",
    pros: [
      "Reflects 90% body heat — genuine lifesaver in cold",
      "3.8 oz — fits in any pocket or pack",
      "$18 — cheap insurance against hypothermia",
      "Reusable — not single-use like space blankets",
    ],
    cons: [
      "Condensation builds up inside during extended use",
      "Not a replacement for a real sleeping bag",
      "Crinkly and noisy — hard to sleep in",
    ],
    bestFor: "Emergency shelter backup in every bug out bag, car kit, and daypack",
  },

  // BUG OUT BAGS
  {
    slug: "molle-ii-rucksack",
    name: "Akmax MOLLE II Medium Rucksack (Military Style)",
    category: "gear",
    price: "$85",
    rating: 4.3,
    reviewCount: 3800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Akmax_MOLLE_II_Medium_Rucksack.jpeg",
    description:
      "The actual US Military-issue rucksack used in combat operations worldwide. 4,000 cubic inches of capacity with full MOLLE webbing, aluminum frame, and padded kidney belt. Surplus units are battle-tested and absurdly affordable for the quality you get.",
    features: [
      "4,000 cubic inch main compartment",
      "Full MOLLE webbing for pouch attachment",
      "Aluminum frame with padded kidney belt",
      "2 sustainment pouches included",
      "Cordura 1000D nylon — built for combat loads",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B09H71PN7H?tag=prepperevo-20",
    pros: [
      "Battle-proven US Military design",
      "Massive 4,000 cu in capacity for long-duration BOBs",
      "$85 surplus — fraction of comparable civilian packs",
      "Full MOLLE system — endlessly customizable with pouches",
    ],
    cons: [
      "Heavy — frame + pack = 7+ lbs empty",
      "Surplus condition varies — inspect before buying",
      "Less comfortable than modern civilian suspension systems",
      "Screams tactical — zero gray man appeal",
    ],
    bestFor: "Budget-conscious preppers who want maximum capacity and military durability",
    badge: "Best Budget",
  },
  {
    slug: "511-tactical-rush72",
    name: "5.11 Tactical RUSH72 2.0 Backpack (55L)",
    category: "gear",
    price: "$220",
    rating: 4.8,
    reviewCount: 8900,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/5.11_Tactical_RUSH72_2.0_Backpack_55L.jpeg",
    description:
      "The 72-hour bug out bag standard. 55L capacity with 21 compartments, MOLLE/SlickStick web platform, and a hidden CCW pocket. Water-resistant 1050D nylon with self-repairing YKK zippers. The pack most serious preppers choose for their primary bug out bag.",
    features: [
      "55L capacity — 21 compartments for organized loadout",
      "1050D nylon with water-resistant coating",
      "MOLLE/SlickStick web platform for attachments",
      "Fleece-lined eyewear and electronics pocket",
      "Hidden CCW compartment",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0D9R239MT?tag=prepperevo-20",
    pros: [
      "55L — perfectly sized for a 72-hour bug out loadout",
      "21 compartments keep every piece of gear organized",
      "1050D nylon with self-repairing YKK zippers",
      "CCW pocket and full MOLLE webbing",
    ],
    cons: [
      "$220 — premium price for a tactical pack",
      "4.5 lbs empty — heavier than ultralight options",
      "Tactical appearance — not gray man friendly",
    ],
    bestFor: "The definitive 72-hour bug out bag for serious preppers",
    badge: "Editor's Pick",
    featured: true,
  },
  {
    slug: "511-tactical-rush24",
    name: "5.11 Tactical RUSH24 2.0 Backpack (37L)",
    category: "gear",
    price: "$140",
    rating: 4.7,
    reviewCount: 12400,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/5.11_Tactical_RUSH24_2.0_Backpack_37L.jpeg",
    description:
      "The compact version of the legendary RUSH72. 37L capacity perfect for a 24-hour get-home bag or lightweight bug out bag. Same 1050D nylon construction, MOLLE webbing, and CCW pocket in a more maneuverable size.",
    features: [
      "37L capacity — 16 compartments",
      "1050D nylon with water-resistant coating",
      "MOLLE/SlickStick web platform",
      "Fleece-lined sunglass pocket",
      "Hidden CCW compartment",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0D9QZWBC1?tag=prepperevo-20",
    pros: [
      "37L — ideal size for get-home and 24-hour bags",
      "Same bombproof 1050D construction as the RUSH72",
      "$140 — more accessible price point",
      "Lighter and more maneuverable than full 72-hour packs",
    ],
    cons: [
      "37L may be too small for a full 72-hour loadout",
      "Still looks tactical — not gray man",
      "Hydration pocket but bladder not included",
    ],
    bestFor: "Get-home bags, EDC packs, and lightweight 24-hour bug out bags",
  },
  {
    slug: "mystery-ranch-3-day-assault",
    name: "Mystery Ranch 2 Day Backpack",
    category: "gear",
    price: "$249",
    rating: 4.9,
    reviewCount: 2100,
    image: "https://www.mysteryranch.com/Products/2%20Day%20Assault%20113383_shadow-10.jpg?resizeid=3&resizeh=800&resizew=800",
    description:
      "The pack carried by US Special Operations. Mystery Ranch's 3-zip design provides full main compartment access without digging. FUTURA yoke and frame sheet deliver all-day comfort under heavy loads. Made in the USA.",
    features: [
      "Patented 3-ZIP design — full panel access to main compartment",
      "FUTURA yoke and adjustable frame sheet",
      "500D Cordura with DWR coating",
      "Hydration compatible (3L reservoir)",
      "Made in the USA — Bozeman, Montana",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0DTB48FW4?tag=prepperevo-20",
    pros: [
      "3-ZIP design — best main compartment access in any tactical pack",
      "FUTURA yoke — genuinely comfortable under heavy loads",
      "Made in USA — highest build quality available",
      "Used by USSOCOM — proven in combat",
    ],
    cons: [
      "$349 — premium price (you get what you pay for)",
      "30L may require supplemental pouches for 72-hour loadout",
      "Limited MOLLE webbing compared to pure tactical packs",
    ],
    bestFor: "Operators, veterans, and preppers who demand the best suspension and access",
    badge: "Premium Pick",
  },
  {
    slug: "vertx-gamut-2",
    name: "Vertx Gamut 22L Sling Backpack",
    category: "gear",
    price: "$230",
    rating: 4.7,
    reviewCount: 4200,
    image: "https://vertx.com/cdn/shop/files/VTX5013_Gamut22L_Sling_BK_Front_grande.jpg?v=1762978444",
    description:
      "The ultimate gray man pack. Looks like a normal commuter backpack but hides a full CCW compartment, rapid-access admin panel, and laser-cut MOLLE under the flap. Designed by former Special Forces to blend in urban environments while carrying a full tactical loadout.",
    features: [
      "28L capacity in a low-profile commuter silhouette",
      "Full-size CCW compartment with loop lining",
      "Laser-cut MOLLE under front flap — hidden attachment points",
      "Rapid-access admin panel with organizer slots",
      "210D and 1680D ballistic nylon construction",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0G2MY4814?tag=prepperevo-20",
    pros: [
      "Looks like a normal backpack — perfect gray man profile",
      "Full CCW compartment with Velcro loop lining",
      "Hidden MOLLE under flap — tactical without looking tactical",
      "Built by former Special Forces operators",
    ],
    cons: [
      "28L — limited capacity for full 72-hour loadout",
      "$200 for a 28L pack is steep",
      "Gray man design means fewer external attachment points",
    ],
    bestFor: "Urban bug out bags where blending in matters more than capacity",
    badge: "Gray Man Pick",
  },
  {
    slug: "goruck-gr2-40l",
    name: "GORUCK Rucker 4.0 20L",
    category: "gear",
    price: "$255",
    rating: 4.9,
    reviewCount: 1800,
    image: "https://www.goruck.com/cdn/shop/files/25L_rucker_blackout_orange_cd1a7ded-e959-416f-805a-8b67ec0f74b3.jpg?v=1770096107",
    description:
      "Built in the USA with 1000D Cordura and designed by a former Green Beret. Two large clamshell compartments, laptop sleeve, and bombproof construction backed by a lifetime guarantee. Looks professional enough for an office but built to survive anything. The premium gray man standard.",
    features: [
      "40L capacity — two full clamshell compartments",
      "1000D Cordura nylon — lifetime SCARS guarantee",
      "Padded laptop compartment (fits up to 17 inch)",
      "Reinforced bottom panel and grab handles",
      "Made in USA — designed by former Green Beret",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0DDZPCXZD?tag=prepperevo-20",
    pros: [
      "40L clamshell — packs like a suitcase, carries like a ruck",
      "1000D Cordura with lifetime SCARS guarantee",
      "Professional look — gray man in any environment",
      "Made in USA by a veteran-owned company",
    ],
    cons: [
      "$395 — the most expensive pack on this list",
      "No frame or hip belt — load transfer is limited",
      "Minimal external attachment points",
    ],
    bestFor: "Premium gray man pack for urban and travel bug out scenarios",
  },
  {
    slug: "maxpedition-falcon-ii",
    name: "Maxpedition Falcon-II Backpack (23L)",
    category: "gear",
    price: "$167",
    rating: 4.6,
    reviewCount: 6200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Maxpedition_Falcon-II_Backpack_23L.jpeg",
    description:
      "Compact tactical pack built like a tank. 1050D ballistic nylon with Teflon coating for water and stain resistance. Full MOLLE front panel, CCW pocket, and hydration compatible. A proven mid-range choice for smaller bug out bags and get-home kits.",
    features: [
      "23L capacity — compact tactical profile",
      "1050D ballistic nylon with Teflon fabric protector",
      "Full MOLLE front panel for pouch attachment",
      "CCW-compatible back compartment",
      "Hydration compatible (2L bladder pocket)",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0013AXY54?tag=prepperevo-20",
    pros: [
      "1050D ballistic nylon with Teflon — incredibly durable",
      "Full MOLLE panel for maximum customization",
      "$149 — solid mid-range value",
      "Compact enough for daily carry or vehicle storage",
    ],
    cons: [
      "23L — too small for a full 72-hour loadout",
      "No frame — uncomfortable with heavy loads over 25 lbs",
      "Tactical appearance — not gray man",
    ],
    bestFor: "Get-home bags, vehicle packs, and compact tactical loadouts",
  },
  {
    slug: "helikon-tex-raccoon-mk2",
    name: "Helikon-Tex Raccoon Mk2 Backpack (20L)",
    category: "gear",
    price: "$86",
    rating: 4.5,
    reviewCount: 3400,
    image: "https://www.helikon-tex.us/media/catalog/product/cache/6/image/1800x/040ec09b1e35df139433887a97daa66f/p/l/pl-rc2-cd-plecak_raccoon_mk2_20l_-_cordura-8-1000_1.jpg",
    description:
      "Polish-made tactical pack trusted by NATO militaries across Europe. 20L capacity with Cordura 500D construction, full MOLLE webbing, and a laser-cut admin panel. The best budget tactical pack you can buy — half the price of comparable US brands with matching quality.",
    features: [
      "20L capacity — compact tactical design",
      "Cordura 500D with PU coating",
      "Full MOLLE/PALS webbing on three panels",
      "Laser-cut admin panel with organizer",
      "Hydration bladder compatible (3L)",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0D8HCRCYR?tag=prepperevo-20",
    pros: [
      "Cordura 500D — genuine military-spec material",
      "$90 — best value in tactical packs",
      "Trusted by NATO forces across Europe",
      "MOLLE on three panels — highly customizable",
    ],
    cons: [
      "20L — smallest pack on this list",
      "Shoulder straps could use more padding for heavy loads",
      "Harder to find in US retail stores",
    ],
    bestFor: "Budget-friendly tactical EDC, get-home bags, and lightweight bug out kits",
  },

  // TOOLS
  {
    slug: "morakniv-companion-knife",
    name: "Morakniv Companion Fixed-Blade Knife",
    category: "gear",
    price: "$16",
    rating: 4.8,
    reviewCount: 31000,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Morakniv_Companion_Fixed-Blade_Knife.jpeg",
    description:
      "Swedish stainless steel blade, razor-sharp out of the box. The most recommended budget survival knife in the prepper community.",
    features: [
      "Swedish stainless steel blade (4.1 inches)",
      "Rubber grip handle — excellent in wet conditions",
      "Friction-fit sheath with belt clip",
      "Lightweight at 4.1 oz",
      "Color-coded for easy identification",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B004TNWD40?tag=prepperevo-20",
    pros: [
      "Razor-sharp out of the box — ready to work immediately",
      "$16 — best knife value in the world",
      "Rubber grip excels in wet and cold conditions",
      "Swedish steel holds an edge well",
    ],
    cons: [
      "Friction-fit sheath has no positive locking retention",
      "Not full-tang — not ideal for heavy batoning",
      "Stainless version trades edge retention for rust resistance",
    ],
    bestFor: "Every prepper's first fixed-blade knife — and many veterans' favorite",
    badge: "Best Value",
  },
  {
    slug: "leatherman-wave-plus",
    name: "Leatherman Wave+ Multi-Tool",
    category: "gear",
    price: "$100",
    rating: 4.8,
    reviewCount: 22000,
    image: "https://www.leatherman.com/cdn/shop/files/akeneo_3_e_8_a_3e8a70d756780f19c4096300b48adbb660538c02_wave_plus_black_fanned_shopify.jpg?v=1771229276",
    description:
      "18 tools in one, including pliers, knife, saw, scissors, file, and multiple screwdrivers. 25-year warranty. The multi-tool preppers trust most.",
    features: [
      "18 tools including pliers, knives, saw, scissors",
      "Replaceable wire cutters",
      "All locking blades for safety",
      "One-hand accessible blades",
      "25-year warranty",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B07BK58NX2?tag=prepperevo-20",
    pros: [
      "18 tools — handles nearly any repair or task",
      "All blades lock — safe one-hand operation",
      "Replaceable wire cutters extend lifespan",
      "25-year warranty — Leatherman stands behind it",
    ],
    cons: [
      "$100 — significant investment for a multi-tool",
      "7 oz — noticeable pocket carry weight",
      "Scissors are small for extended cutting tasks",
    ],
    bestFor: "The one multi-tool every prepper should own — does everything well",
  },

  // POWER
  {
    slug: "bigblue-28w-solar-charger",
    name: "BigBlue 28W USB Solar Charger",
    category: "gear",
    price: "$66",
    rating: 4.5,
    reviewCount: 14200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/BigBlue_28W_USB_Solar_Charger.jpeg",
    description:
      "Foldable 28W solar panel with 3 USB ports including USB-C. SunPower monocrystalline cells deliver 23.5% efficiency — noticeably better than standard panels in partial shade. Charges phones, radios, GPS, headlamps, and power banks directly from sunlight.",
    features: [
      "28W solar output — 3 USB ports (including USB-C)",
      "SunPower monocrystalline cells — 23.5% efficiency",
      "Foldable and portable (11.1 x 6.3 inches folded)",
      "IPX4 waterproof for outdoor use",
      "Smart IC chip detects and optimizes charging speed",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B01EXWCPLC?tag=prepperevo-20",
    pros: [
      "28W output with 3 USB ports including USB-C",
      "SunPower cells — better performance in partial shade",
      "IPX4 waterproof — built for outdoor use",
      "$66 — best value in portable solar",
    ],
    cons: [
      "Won't charge large power stations directly",
      "Output drops in heavy overcast conditions",
      "No built-in battery — solar panels only",
    ],
    bestFor: "Bug out bags, day hikes, and keeping small electronics charged off-grid",
  },

  // SECURITY
  {
    slug: "dakota-alert-murs-sensor",
    name: "Dakota Alert MURS Wireless Motion Sensor",
    category: "security",
    price: "$130",
    rating: 4.4,
    reviewCount: 2800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Dakota_Alert_MURS_Wireless_Motion_Sensor.jpg",
    description:
      "Wireless perimeter alert system with up to 4-mile range. Detects movement and sends an alert to a base unit inside your home. No subscription fees.",
    features: [
      "Up to 4-mile range (line of sight)",
      "Passive infrared motion detection",
      "Weatherproof outdoor sensor",
      "MURS radio frequency — no license needed",
      "Expandable — add multiple sensors",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B07PFWL5Y1?tag=prepperevo-20",
    pros: [
      "4-mile range — covers large properties",
      "MURS frequency — no license required",
      "No subscription fees — one-time purchase",
      "Expandable with multiple sensors on different zones",
    ],
    cons: [
      "$130 per sensor — costs add up for full perimeter coverage",
      "False triggers from animals and wind-blown debris",
      "Range drops significantly in dense forest or hilly terrain",
    ],
    bestFor: "Rural property perimeter security and early warning systems",
  },

  // OVERLANDING
  {
    slug: "ikamper-skycamp-3-rooftop-tent",
    name: "Galaxy Pro Pop-Up Rooftop Tent",
    category: "overlanding",
    price: "$1,199",
    rating: 4.8,
    reviewCount: 1200,
    image: "https://bikerumor.com/wp-content/uploads/2025/09/Topoak-Overland-Galaxy-Pro-Review-Hero.jpeg",
    description:
      "Hard-shell rooftop tent that opens in 1 minute. Sleeps 4 with king-size mattress. Built-in skylights, insulated canopy, and all-season capability. The gold standard in overlanding shelter.",
    features: [
      "Hard-shell — sets up in under 60 seconds",
      "King-size memory foam mattress (sleeps 4)",
      "Built-in skylights and ventilation",
      "All-season insulated canopy",
      "Fits most roof racks (universal mount)",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0F1MWF1GL?tag=prepperevo-20",
    pros: [
      "Sets up in under 60 seconds",
      "King-size mattress sleeps 4",
      "All-season insulated canopy",
      "Built-in skylights for stargazing",
    ],
    cons: [
      "$4,699 is a serious investment",
      "Adds significant roof weight",
      "Requires robust roof rack system",
    ],
    bestFor: "Serious overlanders who want fast setup and all-season comfort",
    badge: "Premium Pick",
    featured: true,
  },
  {
    slug: "maxtrax-mkii-recovery-boards",
    name: "MAXTRAX MKII Recovery Boards",
    category: "overlanding",
    price: "$299",
    rating: 4.9,
    reviewCount: 4800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/MAXTRAX_MKII_Recovery_Boards.jpeg",
    description:
      "The #1 vehicle recovery board in the overlanding world. Engineered teeth grip tires in sand, mud, and snow. UV-stabilized nylon construction built for extreme conditions.",
    features: [
      "Engineered teeth for maximum tire grip",
      "UV-stabilized reinforced nylon",
      "17.6 lbs per pair — built-in handles",
      "Works in sand, mud, snow, and rock",
      "Integrated leash point for recovery",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B01ACMCUGM?tag=prepperevo-20",
    pros: [
      "Works in sand, mud, snow, and rock",
      "Zero installation — place and drive",
      "UV-stabilized nylon — nearly indestructible",
      "Industry standard — proven worldwide",
    ],
    cons: [
      "Need external mounting (roof rack or bumper)",
      "$299 for a pair of boards",
      "17.6 lbs adds up on the roof",
    ],
    bestFor: "Every overlanding rig — the #1 most essential recovery tool",
    badge: "Essential",
    featured: true,
  },
  {
    slug: "dometic-cfx3-55im-portable-fridge",
    name: "Dometic CFX3 55IM Powered Cooler with Ice Maker",
    category: "overlanding",
    price: "$1,299",
    rating: 4.7,
    reviewCount: 2100,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Dometic_CFX3_55IM_Fridge_Ice_Maker.jpeg",
    description:
      "53-liter 12V/120V portable fridge-freezer with built-in ice maker. Runs off your vehicle battery, solar, or shore power. The most trusted cooler brand in overlanding.",
    features: [
      "53L capacity — fridge and freezer zones",
      "Built-in ice maker (first in class)",
      "Runs on 12V DC, 24V DC, or 120V AC",
      "WiFi app monitoring and control",
      "Heavy-duty construction with ExoFrame",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B083G3NBNZ?tag=prepperevo-20",
    pros: [
      "Built-in ice maker — first in any portable fridge",
      "53L dual-zone — fridge and freezer simultaneously",
      "WiFi app monitoring from your phone",
      "ExoFrame construction handles off-road abuse",
    ],
    cons: [
      "$1,299 — the most expensive portable fridge",
      "Ice maker increases power consumption significantly",
      "Heavy at 55 lbs — needs a fridge slide",
    ],
    bestFor: "Overlanders who want the ultimate portable fridge with ice maker capability",
    badge: "Premium Pick",
    featured: true,
  },
  {
    slug: "dometic-cfx3-35",
    name: "Dometic CFX3 35 Portable Fridge (36L)",
    category: "overlanding",
    price: "$800",
    rating: 4.7,
    reviewCount: 3100,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Dometic_CFX3_35_Fridge_36L.jpeg",
    description:
      "The compact version of Dometic's legendary CFX3 line. 36-liter single-zone fridge-freezer that runs on 12V, 24V, or 120V. VMSO3 compressor is whisper-quiet and ultra-efficient. Perfect for smaller rigs, solo overlanders, or as a second fridge for drinks.",
    features: [
      "36L single-zone fridge or freezer",
      "VMSO3 compressor — efficient and near-silent",
      "Runs on 12V DC, 24V DC, or 120V AC",
      "WiFi app for temperature monitoring",
      "ExoFrame construction — impact resistant",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B085MM9B2D?tag=prepperevo-20",
    pros: [
      "Compact size fits tight vehicle builds",
      "VMSO3 compressor — class-leading efficiency",
      "Same premium build as larger CFX3 models",
      "WiFi app control for remote monitoring",
    ],
    cons: [
      "$899 for a 36L fridge is premium pricing",
      "Single zone — can't fridge and freeze simultaneously",
      "No ice maker (55IM exclusive feature)",
    ],
    bestFor: "Solo overlanders, compact rigs, and supplemental fridge setups",
  },
{
    slug: "arb-elements-60l",
    name: "ARB Fridge Freezer Series II 50QT",
    category: "overlanding",
    price: "$1,062",
    rating: 4.6,
    reviewCount: 1200,
    image: "https://cdn11.bigcommerce.com/s-wg9nennc1z/images/stencil/2000x2000/products/11999/13139286/arb-50-quart-classic-series-ii-fridge-freezer-10801472__39071.1752171001.jpg?c=1",
    description:
      "The world's first fully weatherproof portable fridge freezer. IPX4-rated stainless steel cabinet designed to live permanently in a truck bed, trailer, or open-air rig without a canopy. 60L dual-zone capacity with Danfoss compressor.",
    features: [
      "60L dual-zone — independent fridge and freezer",
      "IPX4 weatherproof stainless steel cabinet",
      "Danfoss/Secop compressor with battery protection",
      "Designed for open-air truck bed mounting",
      "Spring-loaded latches seal against dust and rain",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B07Q75PB68?tag=prepperevo-20",
    pros: [
      "IPX4 weatherproof — lives outside permanently",
      "60L dual-zone — fridge and freezer simultaneously",
      "Stainless steel — toughest fridge cabinet made",
      "Perfect for flatbed and open-air rig builds",
    ],
    cons: [
      "$1,400 — most expensive fridge on this list",
      "70 lbs — very heavy, needs permanent mounting",
      "Stainless exterior gets hot in direct sun",
    ],
    bestFor: "Open-air rigs, flatbeds, and trailers that need weatherproof cold storage",
  },
  {
    slug: "iceco-vl60-pros",
    name: "ICECO VL60 ProS Dual Zone Fridge Freezer (60L)",
    category: "overlanding",
    price: "$849",
    rating: 4.6,
    reviewCount: 4200,
    image: "https://icecofreezer.com/cdn/shop/files/VL60D_cd9a72da-a476-4075-8848-b76274236a34.jpg",
    description:
      "The best mid-range 12V fridge in overlanding. 60L dual-zone with independent temperature controls, Danfoss/Secop compressor, and a price that undercuts Dometic and ARB by hundreds. The fridge the overlanding community discovered through word of mouth.",
    features: [
      "60L dual-zone — independent fridge and freezer controls",
      "Danfoss/Secop compressor — same as ARB and Dometic",
      "3-stage battery protection system",
      "MAX mode for rapid cooling",
      "WiFi and Bluetooth app control",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B07TXG7G1Y?tag=prepperevo-20",
    pros: [
      "Same Danfoss compressor as $1,000+ brands",
      "$580 — half the price of comparable Dometic/ARB",
      "Dual zone with independent controls",
      "WiFi app for remote temperature monitoring",
    ],
    cons: [
      "Cabinet build quality a step below Dometic/ARB",
      "Customer support not as established as big brands",
      "55 lbs — still needs a slide for easy access",
    ],
    bestFor: "Budget-conscious overlanders who want Danfoss quality without the brand tax",
    badge: "Best Value",
    featured: true,
  },
  {
    slug: "bougerv-cr45",
    name: "BougeRV 12V Portable Refrigerator (30 Quart)",
    category: "overlanding",
    price: "$230",
    rating: 4.4,
    reviewCount: 5800,
    image: "https://rackupgo.com/cdn/shop/files/12V30Quart_28L_PortableRefrigeratorBlack_1800x1800_cc58b96c-3d29-493a-8512-725eb98809b0_grande.png?v=1728265475",
    description:
      "The budget king of 12V overlanding fridges. 45L capacity with a surprisingly capable compressor at a price that seems too good to be true. Won't match Dometic efficiency on deep-freeze duty, but for basic fridge temps it punches way above its weight class.",
    features: [
      "45L single-zone fridge/freezer (down to -4F)",
      "Efficient compressor with low-voltage protection",
      "Runs on 12V/24V DC or 120V AC",
      "ECO and MAX cooling modes",
      "Removable basket divider",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0BPM7C8RT?tag=prepperevo-20",
    pros: [
      "$310 — cheapest fridge that actually works for overlanding",
      "45L capacity — surprisingly spacious for the price",
      "Low-voltage battery protection included",
      "Can reach -4F in freezer mode",
    ],
    cons: [
      "Compressor is louder than Danfoss models",
      "Higher power draw than premium brands",
      "Single zone only — no simultaneous fridge + freezer",
    ],
    bestFor: "First-time overlanders and budget builds who want cold food without spending $1,000+",
    badge: "Budget Pick",
  },
  {
    slug: "alpicool-c20",
    name: "Alpicool C20 Portable Fridge (20L)",
    category: "overlanding",
    price: "$170",
    rating: 4.3,
    reviewCount: 8900,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Alpicool_C20_Fridge_20L.jpeg",
    description:
      "Ultra-compact 20L 12V fridge that fits in any vehicle. The entry-level choice for car camping, road trips, and overlanders who just need cold drinks and basic food storage. Powered by 12V cigarette lighter or 120V AC.",
    features: [
      "20L capacity — compact enough for any vehicle",
      "Cools to -4F in freezer mode",
      "12V DC (cigarette lighter) or 120V AC",
      "ECO and MAX modes for efficiency",
      "Built-in LED interior light",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B075R1LH8D?tag=prepperevo-20",
    pros: [
      "$160 — cheapest true-compressor fridge available",
      "Ultra-compact — fits center console, back seat, or trunk",
      "22 lbs — light enough to carry with one hand",
      "Great for road trips and car camping",
    ],
    cons: [
      "20L is very small — drinks and snacks only",
      "Compressor is audible in quiet environments",
      "Not built for harsh off-road abuse",
    ],
    bestFor: "Road trips, car camping, and anyone who wants a cheap entry into 12V fridges",
  },
  {
    slug: "setpower-pt45",
    name: "Setpower 12V Refrigerator with APP Control (48QT)",
    category: "overlanding",
    price: "$359",
    rating: 4.4,
    reviewCount: 3600,
    image: "https://m.media-amazon.com/images/I/410jmpAIzJL.jpg",
    description:
      "A budget-friendly 45L 12V fridge with LG compressor — a cut above the cheapest options. Dual-zone design lets you run fridge and freezer simultaneously. Bluetooth app control and a 3-year warranty make this the smart budget pick for overlanders.",
    features: [
      "45L dual-zone — fridge and freezer simultaneously",
      "LG compressor — reliable brand-name cooling",
      "Bluetooth app for temperature control",
      "12V/24V DC and 120V AC compatible",
      "3-year manufacturer warranty",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0DZHGD8B6?tag=prepperevo-20",
    pros: [
      "$280 for a dual-zone fridge — incredible value",
      "LG compressor — more reliable than generic brands",
      "Bluetooth app control at a budget price point",
      "3-year warranty shows manufacturer confidence",
    ],
    cons: [
      "Less power efficient than Danfoss/Secop compressors",
      "Cabinet not as robust as Dometic or ARB",
      "Bluetooth range can be inconsistent",
    ],
    bestFor: "Budget overlanders who want dual-zone capability without paying $1,000+",
  },
  {
    slug: "jackery-explorer-1000-v2",
    name: "Jackery Explorer 1000 V2 Portable Power Station",
    category: "overlanding",
    price: "$699",
    rating: 4.7,
    reviewCount: 5200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Jackery_Explorer_1000_V2_Power_Station.jpeg",
    description:
      "1070Wh LiFePO4 battery with 1500W output. The upgraded V2 model delivers faster solar charging, 4,000+ cycle lifespan, and smart app control. Powers fridges, CPAP machines, tools, and camp electronics for days off-grid.",
    features: [
      "1070Wh capacity, 1500W output (3000W surge)",
      "LiFePO4 battery — 4,000+ charge cycles (10-year life)",
      "Solar charging up to 800W input",
      "Charges 0-80% in 1.5 hours (wall)",
      "Smart app monitoring and control via Bluetooth",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0D7PPG25F?tag=prepperevo-20",
    pros: [
      "LiFePO4 — 4,000+ charge cycles (10-year life)",
      "800W solar input — fast off-grid charging",
      "Smart app control via Bluetooth",
      "$699 — excellent value for LiFePO4",
    ],
    cons: [
      "1500W output — won't run high-draw appliances",
      "24.2 lbs — manageable but not ultralight",
      "Not expandable with add-on batteries",
    ],
    bestFor: "Overlanders and preppers who want reliable LiFePO4 power at a fair price",
    badge: "Editor's Pick",
    featured: true,
  },
  {
    slug: "warn-vr-evo-10s-winch",
    name: "Warn VR EVO 10-S Winch",
    category: "overlanding",
    price: "$640",
    rating: 4.8,
    reviewCount: 3200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Warn_VR_EVO_10-S_Winch.jpeg",
    description:
      "10,000 lb capacity synthetic rope winch. The industry standard for self-recovery in the backcountry. Waterproof (IP68), lightweight synthetic rope, and one-piece tie plate.",
    features: [
      "10,000 lb pulling capacity",
      "90 ft synthetic rope (safer than steel cable)",
      "Waterproof IP68 sealed construction",
      "Series wound motor — reliable under load",
      "Includes wireless remote control",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B07SJHVQTJ?tag=prepperevo-20",
    pros: [
      "10,000 lb capacity handles any full-size rig",
      "Synthetic rope — safer than steel cable, won't spring back",
      "IP68 sealed — fully waterproof for river crossings",
      "Wireless remote — operate from a safe distance",
    ],
    cons: [
      "$640 — significant investment",
      "Synthetic rope degrades in UV — needs a cover",
      "Draws heavy amps — needs proper wiring and battery",
    ],
    bestFor: "Every overlanding rig that goes off-pavement needs a winch — this is the standard",
  },
  {
    slug: "arb-twin-air-compressor",
    name: "ARB CKMTA12 Twin Motor Air Compressor",
    category: "overlanding",
    price: "$575",
    rating: 4.8,
    reviewCount: 2400,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/ARB_Twin_Motor_Air_Compressor.jpeg",
    description:
      "High-output 12V portable air compressor for airing up tires, running air lockers, and inflating camp gear. Dust and moisture resistant for harsh environments.",
    features: [
      "Twin motor — 6.16 CFM @ 0 PSI free flow",
      "Hard-mount or portable installation",
      "Airs up 35-inch tire in under 3 minutes",
      "Dust and moisture resistant design",
      "Also powers ARB air lockers",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0050DI9YQ?tag=prepperevo-20",
    pros: [
      "6.16 CFM — airs up 35-inch tires in under 3 minutes",
      "Also powers ARB air lockers — dual purpose",
      "Hard-mount or portable — flexible installation",
      "Dust and moisture resistant for desert and mud",
    ],
    cons: [
      "$575 — expensive for a compressor",
      "Loud during operation",
      "Hard-mount requires dedicated wiring and space",
    ],
    bestFor: "Overlanders with 33-inch+ tires who air down frequently and need fast re-inflation",
  },
  {
    slug: "front-runner-slimline-ii-roof-rack",
    name: "Front Runner Slimline II Roof Rack",
    category: "overlanding",
    price: "$895",
    rating: 4.7,
    reviewCount: 3600,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Front_Runner_Slimline_II_Roof_Rack.jpeg",
    description:
      "Modular aluminum roof rack system that fits most vehicles. Low-profile, lightweight, and endlessly configurable with accessories for water, fuel, gear, and rooftop tents.",
    features: [
      "T6 aluminum construction — lightweight and strong",
      "Low-profile — reduces wind noise and drag",
      "Modular accessory system (50+ attachments)",
      "Vehicle-specific fit kits available",
      "Supports rooftop tents, awnings, and cargo",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B07MVF491C?tag=prepperevo-20",
    pros: [
      "Low-profile reduces wind noise and fuel consumption",
      "50+ modular accessories — infinitely configurable",
      "Vehicle-specific fit kits for perfect installation",
      "T6 aluminum — lightweight and corrosion resistant",
    ],
    cons: [
      "$895+ before accessories — adds up fast",
      "Installation can be complex for some vehicles",
      "Weight limit varies by vehicle roof strength",
    ],
    bestFor: "Overlanders who need a modular, low-drag platform for gear, tents, and accessories",
  },
  {
    slug: "baja-designs-squadron-sport-led",
    name: "Baja Designs Squadron Sport LED Pod Lights (Pair)",
    category: "overlanding",
    price: "$299",
    rating: 4.8,
    reviewCount: 5100,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Baja_Designs_Squadron_Sport_LED_Pods.jpeg",
    description:
      "Professional-grade LED auxiliary lights built for the trail. 3,150 lumens per light with combo beam pattern. Fully sealed, dust-proof, and backed by a lifetime warranty.",
    features: [
      "3,150 lumens per light (6,300 per pair)",
      "Combo beam — spot + flood pattern",
      "IP69K waterproof and dust-proof",
      "CopperDrive LED technology",
      "Lifetime limited warranty",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B073V6Q8DY?tag=prepperevo-20",
    pros: [
      "6,300 lumens per pair — turns night into day",
      "IP69K — the highest waterproof/dustproof rating possible",
      "Lifetime limited warranty — Baja Designs stands behind them",
      "Combo beam pattern — spot + flood in one light",
    ],
    cons: [
      "$299/pair — premium price for pod lights",
      "Require proper wiring harness and switch",
      "Can blind oncoming traffic — use responsibly",
    ],
    bestFor: "Trail lighting, camp illumination, and off-road auxiliary lights",
  },
  {
    slug: "ecoflow-delta-2-max",
    name: "EcoFlow DELTA 2 Max Portable Power Station",
    category: "overlanding",
    price: "$1,599",
    rating: 4.6,
    reviewCount: 3800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/EcoFlow_DELTA_2_Max_Power_Station.jpeg",
    description:
      "2048Wh LiFePO4 battery with 2400W output. Expandable to 6kWh. Powers an entire camp — fridges, lights, tools, medical devices. Smart app control and fast solar charging.",
    features: [
      "2048Wh LiFePO4 capacity, 2400W output",
      "Expandable to 6144Wh with extra batteries",
      "X-Stream fast charge — 0-80% in 43 min (AC)",
      "800W max solar input",
      "Smart home panel integration capable",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0C4DW17PD?tag=prepperevo-20",
    pros: [
      "2048Wh capacity — powers an entire camp",
      "800W solar input — fastest solar charging",
      "Smart app monitoring and control",
      "Expandable to 6kWh",
    ],
    cons: [
      "$1,599 — premium price",
      "50.7 lbs — very heavy",
      "App can be buggy on some devices",
    ],
    bestFor: "Van lifers and serious overlanders who need maximum power",
  },
  {
    slug: "ecoflow-delta-3-max-plus",
    name: "EcoFlow DELTA 3 Max Plus Portable Power Station",
    category: "overlanding",
    price: "$1,899",
    rating: 4.7,
    reviewCount: 1200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/EcoFlow_DELTA_3_Max_Plus_Power_Station.jpeg",
    description:
      "2048Wh LiFePO4 battery with 3000W output. Expandable to 10kWh. Powers an entire camp — fridges, lights, tools, medical devices. Smart app control and 0-80% recharge in 64 minutes.",
    features: [
      "2048Wh LiFePO4 capacity, 3000W output",
      "Expandable to 10kWh with extra batteries",
      "X-Stream fast charge — 0-80% in 64 min (AC)",
      "1000W max solar input",
      "UPS mode with 10ms switchover",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0FQV9Q9J2?tag=prepperevo-20",
    pros: [
      "2048Wh capacity — powers an entire camp",
      "3000W output handles heavy loads",
      "LFP battery — 4000+ cycle lifespan",
      "Expandable to 10kWh",
    ],
    cons: [
      "$1,899 — premium price",
      "Heavy — plan for permanent vehicle mount",
      "New product — fewer long-term reviews",
    ],
    bestFor: "Van lifers and serious overlanders who need maximum power",
  },
  {
    slug: "ecoflow-wave-3",
    name: "EcoFlow WAVE 3 Portable Air Conditioner with Heater",
    category: "overlanding",
    price: "$1,399",
    rating: 4.6,
    reviewCount: 800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/EcoFlow_WAVE_3_Portable_AC.jpeg",
    description:
      "Portable AC and heater with built-in 1024Wh LFP battery. 6100 BTU cooling and 6800 BTU heating. Runs 8 hours cordless, charges in 75 minutes, and fits in your RTT or tent. IPX4 water resistant.",
    features: [
      "6100 BTU cooling / 6800 BTU heating",
      "Built-in 1024Wh LFP battery — 8hr cordless runtime",
      "1000W fast charge — full in 75 min",
      "IPX4 water resistant for outdoor use",
      "44dB sleep mode — quieter than a conversation",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0F4D4Z18S?tag=prepperevo-20",
    pros: [
      "Built-in battery — no external power needed",
      "Both AC and heat in one unit",
      "IPX4 — handles rain and condensation",
      "Compact luggage-size form factor",
    ],
    cons: [
      "$1,399 — premium price for portable AC",
      "6100 BTU — best for tents/RTTs, not large spaces",
      "Heavy for backpacking, ideal for vehicle-based camping",
    ],
    bestFor: "RTT and tent campers who want climate control off-grid",
  },
  {
    slug: "ecoflow-wave-2",
    name: "EcoFlow WAVE 2 Portable Air Conditioner",
    category: "overlanding",
    price: "$1,099",
    rating: 4.4,
    reviewCount: 2400,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/EcoFlow_WAVE_2_Portable_AC.jpeg",
    description:
      "5100 BTU cooling and 6100 BTU heating in a portable package. Runs on AC, solar, car charger, or optional add-on battery. Proven previous-gen model with thousands of real-world reviews.",
    features: [
      "5100 BTU cooling / 6100 BTU heating",
      "~700W power draw — works with mid-size power stations",
      "Charges while running — no downtime",
      "Multiple power inputs: AC, solar, car, battery",
      "App control via Bluetooth",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0BZJ6S64B?tag=prepperevo-20",
    pros: [
      "Lower power draw than WAVE 3 — easier on batteries",
      "Both AC and heat",
      "Thousands of proven reviews",
      "Charges while running",
    ],
    cons: [
      "Battery sold separately ($599+)",
      "Less BTU than WAVE 3",
      "No built-in battery — needs external power",
    ],
    bestFor: "Overlanders who already have a power station and want tent/RTT cooling",
  },
  {
    slug: "zero-breeze-mark-3",
    name: "Zero Breeze Mark 3 Portable AC",
    category: "overlanding",
    price: "$1,299",
    rating: 4.5,
    reviewCount: 600,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Zero_Breeze_Mark_3_Portable_AC.jpeg",
    description:
      "5280 BTU cooling and 5800 BTU heating at just 22 lbs. Suitcase-style design built specifically for overlanding and tent camping. Battery sold separately with solar/AC/DC charging options.",
    features: [
      "5280 BTU cooling / 5800 BTU heating",
      "22 lbs — lightest in class for its BTU rating",
      "Suitcase-style portable design",
      "Battery supports solar, AC, DC, and car charging",
      "Built-in drainage pump — no manual water dumping",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0F8Q5JD7V?tag=prepperevo-20",
    pros: [
      "22 lbs — incredibly portable",
      "Both cooling and heating",
      "Purpose-built for camping and overlanding",
      "Auto drainage pump",
    ],
    cons: [
      "Battery sold separately",
      "New product — limited long-term data",
      "1550W draw — needs beefy power station",
    ],
    bestFor: "Weight-conscious overlanders who need portable AC for RTTs and tents",
  },
  {
    slug: "zero-breeze-mark-2",
    name: "Zero Breeze Mark 2 Portable AC",
    category: "overlanding",
    price: "$1,200",
    rating: 4.3,
    reviewCount: 1800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Zero_Breeze_Mark_2_Portable_AC.jpeg",
    description:
      "2300 BTU battery-powered portable AC that draws only 240W. The ultra-low power draw means even a small power station can run it all night. Cooling only — no heat mode. The original overlanding AC.",
    features: [
      "2300 BTU cooling capacity",
      "240W draw — runs on small power stations",
      "Battery powered with optional extra battery",
      "24V DC input — true off-grid operation",
      "Proven track record in the overlanding community",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B08Z3HNXH1?tag=prepperevo-20",
    pros: [
      "240W — ultra-low power draw",
      "Runs all night on a 1000Wh station",
      "Proven reliability — years of reviews",
      "Compact and portable",
    ],
    cons: [
      "2300 BTU — cooling only, no heat",
      "Struggles in extreme heat (95F+)",
      "Battery sold separately ($500+)",
    ],
    bestFor: "Budget-conscious overlanders who want tent cooling without a huge power station",
  },
  {
    slug: "goose-gear-campervan-plate-system",
    name: "Goose Gear CampKing Plate System",
    category: "overlanding",
    price: "$499",
    rating: 4.6,
    reviewCount: 890,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Goose_Gear_CampKing_Plate_System.jpeg",
    description:
      "Modular vehicle storage and sleeping platform. CNC-machined aluminum for truck beds, SUVs, and vans. Configure drawers, fridge slides, and sleeping platforms in any combination.",
    features: [
      "CNC-machined aluminum construction",
      "Modular — drawers, fridge slides, sleeping decks",
      "Vehicle-specific and universal fit options",
      "Integrated tie-down points",
      "Supports rooftop tent on top of cab",
    ],
    affiliateUrl: "https://www.amazon.com/s?k=Goose+Gear+vehicle+storage+system&tag=prepperevo-20",
    pros: [
      "CNC aluminum — precise fit and premium build quality",
      "Fully modular — reconfigure as your needs change",
      "Vehicle-specific options for perfect fit",
      "Supports rooftop tent weight on cab-height platforms",
    ],
    cons: [
      "$499+ — expensive before adding drawers and slides",
      "Heavy aluminum adds significant vehicle weight",
      "Long lead times on custom orders",
    ],
    bestFor: "Van lifers and overlanders building out a full vehicle sleeping and storage system",
  },

  // CAMPING & OUTDOORS
  {
    slug: "big-agnes-copper-spur-hv-ul2",
    name: "Big Agnes Copper Spur HV UL2 Tent",
    category: "camping",
    price: "$450",
    rating: 4.8,
    reviewCount: 4600,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Big_Agnes_Copper_Spur_HV_UL2_Tent.jpeg",
    description:
      "The gold standard ultralight 2-person backpacking tent. 2 lbs 12 oz packed weight with high-volume architecture that feels spacious despite the ultralight design. Three-season freestanding.",
    features: [
      "2 lbs 12 oz packed weight (trail weight)",
      "Freestanding with DAC Featherlite NFL poles",
      "Two doors and two vestibules",
      "High-volume hubbed pole design",
      "Fits inside most backpacking packs",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0817CJLHN?tag=prepperevo-20",
    pros: [
      "2 lbs 12 oz — ultralight without sacrificing livability",
      "Two doors and vestibules — easy entry from either side",
      "High-volume design feels spacious for its weight class",
      "Freestanding — pitches on rock, sand, or platforms",
    ],
    cons: [
      "$450 — premium ultralight pricing",
      "Three-season only — not built for heavy snow loads",
      "Thin fabrics require care with sharp objects",
    ],
    bestFor: "Backpackers and bug out planners who count every ounce",
    badge: "Ultralight Pick",
    featured: true,
  },
  {
    slug: "jetboil-flash-cooking-system",
    name: "Jetboil Flash Cooking System",
    category: "camping",
    price: "$115",
    rating: 4.7,
    reviewCount: 12800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Jetboil_Flash_Cooking_System.jpeg",
    description:
      "Boils 2 cups of water in 100 seconds. Integrated 1-liter cooking cup with insulating cozy, push-button igniter, and color-changing heat indicator. The fastest camp stove on the market.",
    features: [
      "Boils 2 cups in 100 seconds",
      "Integrated 1L FluxRing cooking cup",
      "Push-button piezo igniter",
      "Color-changing heat indicator",
      "Compact nesting design — fuel canister fits inside",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0DXQC9B14?tag=prepperevo-20",
    pros: [
      "Boils water in 100 seconds — fastest camp stove available",
      "Integrated design — everything nests inside the cup",
      "Push-button igniter — no matches or lighter needed",
      "Color-changing heat indicator prevents burns",
    ],
    cons: [
      "$115 — expensive for a camp stove system",
      "1L cup is small for cooking actual meals",
      "Proprietary fuel canisters (Jetpower or similar)",
    ],
    bestFor: "Fast water boiling for dehydrated meals, coffee, and emergency cooking",
    badge: "Best Seller",
  },
  {
    slug: "thermarest-neoair-xlite-nxt",
    name: "Therm-a-Rest NeoAir XLite NXT Sleeping Pad",
    category: "camping",
    price: "$210",
    rating: 4.7,
    reviewCount: 3900,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Therm-a-Rest_NeoAir_XLite_NXT_Sleeping_Pad.jpeg",
    description:
      "R-value 4.5 ultralight inflatable sleeping pad. Weighs just 12.5 oz for the regular size. WingLock valve inflates fast and won't accidentally open. The backpacker's choice for three seasons.",
    features: [
      "R-value 4.5 — warm through 3 seasons",
      "12.5 oz (regular) — ultralight",
      "WingLock valve for fast inflation",
      "Triangular Core Matrix baffles",
      "Packs to the size of a water bottle",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0CS4NHPVP?tag=prepperevo-20",
    pros: [
      "12.5 oz — lightest warm sleeping pad available",
      "R-value 4.5 — warm through three seasons",
      "WingLock valve inflates fast and won't open accidentally",
      "Packs to the size of a water bottle",
    ],
    cons: [
      "$210 — expensive for a sleeping pad",
      "Noisy crinkle sound when shifting at night",
      "Inflatable — puncture risk requires patch kit",
    ],
    bestFor: "Ultralight backpackers and weight-conscious preppers",
  },
  {
    slug: "enlightened-equipment-enigma-quilt",
    name: "Featherstone Moondance 25 Down Sleeping Bag (850 Fill)",
    category: "camping",
    price: "$200",
    rating: 4.9,
    reviewCount: 2100,
    image: "https://www.featherstoneoutdoor.com/cdn/shop/products/MOONTQ_3.png?v=1616723924",
    description:
      "Ultralight 850FP down quilt rated to 20°F. Ditches the zipper and hood for weight savings. The go-to choice for thru-hikers and ultralight backpackers who know that quilts beat sleeping bags.",
    features: [
      "850FP DownTek water-resistant down",
      "20°F comfort rating",
      "19 oz (regular/regular) — absurdly light",
      "Pad attachment system keeps drafts out",
      "Custom sizes and colors available",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0B17FCP29?tag=prepperevo-20",
    pros: [
      "19 oz — lighter than any sleeping bag at this temp rating",
      "850FP DownTek is water-resistant down — handles moisture",
      "Pad attachment system eliminates drafts",
      "Custom sizes and colors available",
    ],
    cons: [
      "$285 — premium price for a quilt",
      "Learning curve — quilts are different from sleeping bags",
      "Requires a good sleeping pad underneath (R-value 3+)",
    ],
    bestFor: "Thru-hikers, ultralight preppers, and anyone who wants the lightest sleep system",
  },
  {
    slug: "osprey-atmos-ag-65-backpack",
    name: "Osprey Atmos AG 65 Backpack",
    category: "camping",
    price: "$300",
    rating: 4.8,
    reviewCount: 7200,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Osprey_Atmos_AG_65_Backpack.jpeg",
    description:
      "Anti-Gravity suspension system distributes weight like no other pack. 65-liter capacity for multi-day trips. Fits like a second skin with the adjustable harness and hipbelt. The most comfortable backpacking pack made.",
    features: [
      "Anti-Gravity suspension — weight disappears",
      "65L capacity for 3-7 day trips",
      "Adjustable torso and hipbelt fit",
      "Integrated rain cover included",
      "Stow-on-the-Go trekking pole attachment",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B09JXQDZG5?tag=prepperevo-20",
    pros: [
      "Anti-Gravity suspension — most comfortable pack made",
      "65L capacity for multi-day trips and large bug out bags",
      "Integrated rain cover included",
      "Adjustable torso and hipbelt fit any body type",
    ],
    cons: [
      "$300 — high-end backpacking pack price",
      "4 lbs 11 oz — not ultralight",
      "Mesh back panel can snag on branches",
    ],
    bestFor: "Multi-day backpacking, large bug out bags, and anyone who prioritizes comfort",
    badge: "Editor's Pick",
    featured: true,
  },
  {
    slug: "gsi-pinnacle-camper-cookset",
    name: "GSI Outdoors Pinnacle Camper Cookset",
    category: "camping",
    price: "$130",
    rating: 4.6,
    reviewCount: 1800,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/GSI_Pinnacle_Camper_Cookset.jpeg",
    description:
      "Complete camp kitchen in a nesting package. Includes 2 pots, frypan, strainer lids, cutting board, and 4 insulated mugs/bowls/plates. Teflon-coated for easy cleanup. Feeds 4 comfortably.",
    features: [
      "Serves 4 — full nesting cookset",
      "Teflon-coated for stick-free cooking",
      "Includes cutting board and folding spatula",
      "Crushproof stuff sack packs it all",
      "Welded stuff sack doubles as wash basin",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0DJPSBDYN?tag=prepperevo-20",
    pros: [
      "Complete kitchen for 4 — pots, pan, plates, mugs, utensils",
      "Teflon-coated — easy cooking and cleanup",
      "Everything nests into one compact package",
      "Welded stuff sack doubles as a wash basin",
    ],
    cons: [
      "$130 — more than basic camp cookware",
      "Teflon coating wears over time with metal utensils",
      "Too heavy for backpacking — best for car camping",
    ],
    bestFor: "Car camping, overlanding, and family camp cooking",
  },
  {
    slug: "petzl-actik-core-headlamp",
    name: "Petzl Actik Core Rechargeable Headlamp",
    category: "camping",
    price: "$70",
    rating: 4.7,
    reviewCount: 8400,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Petzl_Actik_Core_Headlamp.jpeg",
    description:
      "450-lumen rechargeable headlamp with red light mode for preserving night vision. USB-C rechargeable core battery included, also accepts AAA batteries as backup. The camper's essential light.",
    features: [
      "450 lumens max output",
      "USB-C rechargeable CORE battery included",
      "Also accepts 3x AAA as backup",
      "Red light mode for night vision",
      "IPX4 weather resistant — 75g weight",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0FHKTNR6T?tag=prepperevo-20",
    pros: [
      "450 lumens — bright enough for any camp or trail task",
      "USB-C rechargeable + accepts AAA batteries as backup",
      "Red light mode preserves night vision",
      "75g — comfortable for hours of wear",
    ],
    cons: [
      "$70 — more expensive than basic headlamps",
      "CORE battery isn't standard — harder to find replacements",
      "IPX4 is splash-resistant, not submersible",
    ],
    bestFor: "The essential headlamp for camping, night hiking, and emergency kits",
  },
  {
    slug: "katadyn-befree-water-filter",
    name: "Katadyn BeFree 1.0L Water Filter",
    category: "camping",
    price: "$45",
    rating: 4.5,
    reviewCount: 5600,
    image: "https://wp.prepperevolution.com/wp-content/uploads/2026/03/Katadyn_BeFree_Water_Filter.jpeg",
    description:
      "Ultralight collapsible water filter. Squeeze or drink directly — 2 liters per minute flow rate. EZ-Clean membrane maintains flow with a simple shake. 2 oz when empty.",
    features: [
      "0.1 micron hollow fiber filter",
      "2 L/min flow rate — fast filtering",
      "Collapsible 1L soft flask — 2 oz empty",
      "EZ-Clean membrane — shake to clean",
      "42mm thread fits most water bottles",
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0BFQMMJVS?tag=prepperevo-20",
    pros: [
      "2 oz empty — lightest water filter you can carry",
      "2 L/min flow — fast drinking and filling",
      "EZ-Clean membrane — just shake to maintain flow",
      "Collapsible flask disappears when empty",
    ],
    cons: [
      "1L flask is small — refill frequently",
      "Soft flask wears out and needs replacement",
      "42mm thread limits bottle compatibility",
    ],
    bestFor: "Ultralight backpacking, trail running, and minimalist bug out water filtration",
  },
];

export default products;
